### ISSUE TITLE
Build components from the sources

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#1]
It works using `xenserver-build-env` and the right calls:

```
git clone git://github.com/xenserver/xenserver-build-env
cd xenserver-build-env
./build.sh
./run.py -p xapi --rm

# --- you are now inside the docker container ---

git clone https://github.com/xcp-ng/xen-api.git
cd xen-api
./configure
make
```

Same principle for another component, eg `xcp-networkd`:

```
./build.sh
./run.py -p xcp-networkd --rm

# --- you are now inside the docker container ---

git clone git@github.com:xcp-ng/xcp-networkd.git
cd xcp-networkd
make
```

**Comment by necouchman** [comment]
So, one of the challenges using the xenserver-build-env is that it relies on Citrix's "xs" repo to pull in several dependencies, with ocaml among those.  I tried going back and using the EPEL7 ocaml build, but it is not recent enough for some of the ocaml dependencies (jbuilder, for instance), so in order to be completely independent we're going to have to build up a more recent ocaml from source - just like Citrix did.

Probably the easiest way to do this is going to be to grab the SRPMS from the Citrix "xs" repo and then go from there - I think once we grab those SRPMs and build up on own that should be "independent enough" to build up our own RPM repo.

**Comment by olivierlambert** [comment]
We could use SRPM to add our own patches (you can add a `.patch` file in a SRPM to generate the RPM). This was, with the right XAPI patch, we could build the XAPI RPM that remove the licenses restrictions :)

**Comment by necouchman** [comment]
> We could use SRPM to add our own patches

Definitely.

> This was, with the right XAPI patch, we could build the XAPI RPM that remove the licenses restrictions :)

Yep, absolutely.  I think the ultimate goal would be to actually reverse this - if we get Citrix to "buy-in" to the project, hopefully the community drives development from the open source repositories and then they can apply license restrictions to their commercial offering.  But one step at a time, right? :-).

**Comment by olivierlambert** [comment]
Sure, that would be better in this order, but I think we start to have a path on how to achieve our objective now 👍

**Comment by nix67** [comment]
You can find a more recent oCaml compiler for Cenos 7 here: https://download.opensuse.org/repositories/home:/bayrepo/CentOS_7/x86_64/ocaml-4.02.3-4.3.x86_64.rpm
Do You think will be possible to port XAPI and XO to other linuxes (i.e. OpenSuSE/SLES) ?

**Comment by olivierlambert** [comment]
You mean XAPI and XS, right? XO is already open source and works on any Linux ;)

I can open an issue, but the first step would be to keep it simple. Obviously, everyone would be happy to have contributors for other distros :)

**Comment by stormi** [comment]
See https://github.com/xcp-ng/xcp-ng-build-env/ for an update on our build environment.

I don't think we will rebuild all packages for XCP-ng 7.5, but that could be an objective for 7.6.

**Comment by stormi** [comment]
So, this issue number one from XCP-ng is now complete. I've rebuilt all of XCP-ng 7.6 (except two packages that are a technical challenges to rebuild, but nothing core to XCP-ng) in Koji, which is our new build system. XCP-ng 8.0 should be the first version where all source RPMs will have been rebuilt (except those that come from CentOS or EPEL).

All source RPMs have been imported to https://github.com/xcp-ng-rpms/ and rebuilt as https://koji.xcp-ng.org/builds?tagID=22
