### ISSUE TITLE
PCI-Passthrough problem

### ISSUE THREAD

**Issue by vitotsg** [xcp-ng/xcp#101]
Hello,

I followed the guide https://xenserver.org/blog/entry/pci-pass-through-on-xenserver-7-0.html. 

Here is the info:
[root@xcp-ng ~]#lspci |grep 07:08.0
07:08.0 SCSI storage controller: LSI Logic / Symbios Logic 53c1030 PCI-X Fusion-MPT Dual Ultra320 SCSI (rev c1)

it did create the entries in grub:
[root@xcp-ng ~]#cat /boot/grub/grub.cfg |grep 07:08.0
        module2 /boot/vmlinuz-4.4-xen root=LABEL=root-gwhhoo ro nolvm hpet=disable xencons=hvc console=hvc0 console=tty0 quiet vga=785 splash plymouth.ignore-serial-consoles xen-pciback.hide=(07:08.0)
        module2 /boot/vmlinuz-4.4-xen root=LABEL=root-gwhhoo ro nolvm hpet=disable console=tty0 xencons=hvc console=hvc0 xen-pciback.hide=(07:08.0)

After reboot, I still see it in the host server and nothing appears in the vm (Windows 10).....
I am trying to expose a SCSI adapter to the Windows client. 
Any advise?

**Comment by borzel** [comment]
@vitotsg fresh created page just for you ;-) https://github.com/xcp-ng/xcp/wiki/PCI-Passtrough

**Comment by vitotsg** [comment]
Well that is exactly what I have in the host. Below is the full info in grub:
[root@xcp-ng ~]#cat /boot/grub/grub.cfg
serial --unit=0 --speed=115200
terminal_input serial console
terminal_output serial console
set default=0
set timeout=5
menuentry 'XCP-ng' {
        search --label --set root root-gwhhoo
        multiboot2 /boot/xen.gz dom0_mem=4096M,max:4096M watchdog ucode=scan dom0_max_vcpus=1-16 crashkernel=192M,below=4G console=vga vga=mode-0x0311
        module2 /boot/vmlinuz-4.4-xen root=LABEL=root-gwhhoo ro nolvm hpet=disable xencons=hvc console=hvc0 console=tty0 quiet vga=785 splash plymouth.ignore-serial-consoles xen-pciback.hide=(07:08.0)
        module2 /boot/initrd-4.4-xen.img
}
menuentry 'XCP-ng (Serial)' {
        search --label --set root root-gwhhoo
        multiboot2 /boot/xen.gz com1=115200,8n1 console=com1,vga dom0_mem=4096M,max:4096M watchdog ucode=scan dom0_max_vcpus=1-16 crashkernel=192M,below=4G
        module2 /boot/vmlinuz-4.4-xen root=LABEL=root-gwhhoo ro nolvm hpet=disable console=tty0 xencons=hvc console=hvc0 xen-pciback.hide=(07:08.0)
        module2 /boot/initrd-4.4-xen.img
}
menuentry 'XCP-ng in Safe Mode' {
        search --label --set root root-gwhhoo
        multiboot2 /boot/xen.gz nosmp noreboot noirqbalance no-mce no-bootscrub no-numa no-hap no-mmcfg iommu=off max_cstate=0 nmi=ignore allow_unsafe dom0_mem=4096M,max:4096M com1=115200,8n1 console=com1,vga
        module2 /boot/vmlinuz-4.4-xen earlyprintk=xen root=LABEL=root-gwhhoo ro nolvm hpet=disable console=tty0 xencons=hvc console=hvc0
        module2 /boot/initrd-4.4-xen.img
}
menuentry 'XCP-ng (Xen 4.7.6 / Linux 4.4.0+10)' {
        search --label --set root root-gwhhoo
        multiboot2 /boot/xen-fallback.gz dom0_mem=4096M,max:4096M watchdog ucode=scan dom0_max_vcpus=1-16 crashkernel=192M,below=4G
        module2 /boot/vmlinuz-fallback root=LABEL=root-gwhhoo ro nolvm hpet=disable xencons=hvc console=hvc0 console=tty0
        module2 /boot/initrd-fallback.img
}
menuentry 'XCP-ng (Serial, Xen 4.7.6 / Linux 4.4.0+10)' {
        search --label --set root root-gwhhoo
        multiboot2 /boot/xen-fallback.gz com1=115200,8n1 console=com1,vga dom0_mem=4096M,max:4096M watchdog ucode=scan dom0_max_vcpus=1-16 crashkernel=192M,below=4G
        module2 /boot/vmlinuz-fallback root=LABEL=root-gwhhoo ro nolvm hpet=disable console=tty0 xencons=hvc console=hvc0
        module2 /boot/initrd-fallback.img
}

Here is the output of the xl pci-assignable-list:

[root@xcp-ng ~]#xl pci-assignable-list
0000:07:08.0

Here is the list of VMs:
[root@xcp-ng ~]#xe vm-list
uuid ( RO)           : 93b7af14-48a5-4014-b2c4-a8dc76129360
     name-label ( RW): Control domain on host: xcp-ng
    power-state ( RO): running


uuid ( RO)           : 5ca64928-8247-4f2d-214f-f7eb6c165533
     name-label ( RW): Windows 10 (64-bit)
    power-state ( RO): running


[root@xcp-ng ~]# xe vm-param-set other-config:pci=0/0000:07:08.0 uuid=5ca64928-8247-4f2d-214f-f7eb6c165533
[root@xcp-ng ~]#

Still, I don't see the device in the guest VM and still I see it in the host. Several reboots were made to the host - still no luck...

**Comment by borzel** [comment]
@vitotsg Can you please boot some sort of linux in your windows VM and check with lspci?

For example boot a grml-ISO (https://grml.org/) or some sort of live CD.

**Comment by vitotsg** [comment]
Hi guys,

Sorry for the delay in answer. I've tried with two live distros - they don't see the scsi...

**Comment by desnudopenguino** [comment]
I'm dealing with the exact same issue. I found one interesting thing though. running lscpu on the host, I'm gettgin `virtualization type: none` even though I have svm/amd-v enabled in my bios. I also have IOMMU enabled. Is there a module that needs to be loaded? I'm running an AMD Opteron 6276 on an Asus KGPE-D16.

**Comment by oallart** [comment]
> `virtualization type: none`

That's normal, the host is not virtualized. If you run this inside a guest vm, you will likely get `Hypervisor vendor:     Xen`.

@vitotsg , am shamelessly pluggign in my own notes for PCI Passthrough: https://github.com/oallart/xcpng-ceph-hci/blob/master/pci-passthrough/README.md

Please have a look at the part with `xen-cmdline --set-dom0 "xen-pciback.hide=({PCI ID})` and `xl pci-assignable-list`. What does  `xl pci-assignable-list` return for you ?

**Comment by stormi** [comment]
Closing as PCI passthrough is now documented: https://xcp-ng.org/docs/compute.html#pci-passthrough
