### ISSUE TITLE
XCP-ng Center flagged for Razy virus

### ISSUE THREAD

**Issue by rwarford** [xcp-ng/xcp#106]
XCP-ng Center has been quarantined by my AV software for the **Razy virus**.  Can anyone confirm that this is a false alarm?

I originally installed from the MSI I downloaded on 10/3/2018.  I downloaded and re-installed today (12/3/2018) using the MSI installer (*XCP_ng_Center_Installer.msi*) from *https://github.com/xcp-ng/xenadmin/releases/download/v7.4.1-MSI/XCP_ng_Center_Installer.msi*.  XCP-ng center was immediately flagged again.

My software:
  * VIPRE Antivirus 2016
  * Windows 7 Home Premium, SP1

**Comment by rwarford** [comment]
Done.  Thank you.  [Issue 122](https://github.com/xcp-ng/xenadmin/issues/122).

**Comment by olivierlambert** [comment]
Thanks for your feedback!

**Comment by borzel** [comment]
False Alarm!

https://www.virustotal.com/#/file/23f9ccfbde90d2e895590a2061832e48d6aba8d55119c4daac149ec6a654b7d7/detection
