### ISSUE TITLE
Defining a specific MAC address during the XVA import wizard does not persist when VM starts up

### ISSUE THREAD

**Issue by De-Occultist** [xcp-ng/xcp#109]
XCP-ng version 7.6

1) Import XVA specify the MAC address as aa:bb:cc:11:22:33 in the wizard
2) Start the VM, check the Networking tab, the MAC address is a random MAC address.

**Comment by olivierlambert** [comment]
How do you import the XVA exactly? Because this will probably decide where to do the bug report.

**Comment by De-Occultist** [comment]
I experienced this problem in XCP-ng Center 7.6.0. 
How do I move this issue to https://github.com/xcp-ng/xenadmin?
Create a new issue there?

**Comment by olivierlambert** [comment]
Create the issue there yes. Also, before that, you could test if you experience the same problem with `xe` CLI (with `--preserve=true`)

**Comment by stormi** [comment]
Hi @De-Occultist. Have you had the opportunity to test with the `xe` CLI tool?

**Comment by De-Occultist** [comment]
I haven't had a chance to test with the xe command yet. Will get on it in the new year.

**Comment by De-Occultist** [comment]
I've tested import with 
`xe vm-import filename=xxx.xva preserve=true` and the MAC address is preserved.

But when exporting with XCP-ng Center 7.6.0, the import will begin immediately after the "Storage" selection in the"Import XVA" wizard. Changing the Network MAC address in the "Network" dialog will display the new MAC address but upon starting the VM it will revert back to the random MAC address it initially displayed in the "Import XVA" wizard.

**Comment by borzel** [comment]
It's resolved with https://github.com/xcp-ng/xenadmin/releases/tag/v8.0.1.26
