### ISSUE TITLE
Windows VM Management Agent 8.2.1 Beta1 Running but not Reporting

### ISSUE THREAD

**Issue by BTLOPER** [xcp-ng/xcp#112]
I installed Windows 10 via XCP-NG Center then started up the self built Xen Orchestra.  I installed subject management agent.  I can see in windows the service is running, but XO and XCP-NG center both say the tools are not installed and memory usage is not being reported.   I feel I have exhausted research options here and else where.  I don't see any similar issues with Citrix version documented; however I have not tried to install it.  I'm very new to virtualization, but I hope to help in any way I can.  Just let me know what information you need.  
Thanks in advance!

**Comment by borzel** [comment]
Did you check in device manager if the XCP-ng devices are there?

**Comment by borzel** [comment]
You did not install the XCP-ng drivers. Your devices use the XenServer drivers, I assume you got these from Windows Update.

XCP-ng Management Agent does not work with the XenServer drivers.

**Comment by BTLOPER** [comment]
Understood.  I'll give that a try and mark this closed.  Thanks so much!
