### ISSUE TITLE
Modify install process to use anaconda/kickstart rather than Answer File

### ISSUE THREAD

**Issue by bdonnahue** [xcp-ng/xcp#117]
I would like to execute a pre-install script to detect hardware and dynamically configure my installation parameters. For example, selecting a hard drive or nic to be used / configured based on serial number or other metadata.

This is commonly done with pre and post installation scripts using anaconda/kickstart.

As XenServer is based on CentOS I was hoping it would not be difficult to migrate to or add support for using anaconda/kickstart.

**Comment by stormi** [comment]
Unfortunately, as discussed briefly on IRC, we do not use anaconda but rather an installation that has been written for XenServer specifically.

Code available at https://github.com/xcp-ng/host-installer

**Comment by bdonnahue** [comment]
From the conversations in IRC, I thought switching installers was a long term goal?

**Comment by stormi** [comment]
Not necessarily. It would be if there was a significant gain to switch as compared to the extra maintenance work of maintaining our own installation scripts while still retaining the specific behaviours of the current installer, but at the moment it doesn't appear desirable to me.
