### ISSUE TITLE
Faster VHD coalesce

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#127]
Is it possible to have faster VHD coalescing? The code is in C, available here: https://github.com/xapi-project/blktap/blob/0bdf8daacec523ceda0d5b438654e79e1ca9d002/vhd/lib/vhd-util-coalesce.c

Ideas:

* extract the code, use a testable VHD chain and run benchmarks (local and NFS)
* try to improve the code if possible (eg: NFS case, network latency?)
* why not trying to use Rust? multithreading? multimerge?

**Comment by Wescoeur** [comment]
I don't see obvious bottleneck in this code. I have no ideal answer for the moment.
Potentially, we can investigate: multithreads, queue of blocks (Read Only), many fds, increasing block size...
