### ISSUE TITLE
Upgrade systemd/ Install docker on the XEN hypervisor

### ISSUE THREAD

**Issue by PinchenCui** [xcp-ng/xcp#129]
Hi guys,

I know we can run and manage docker containers inside of the CoreOS VMs. However, I'm trying to install docker on the hypervisor layer.

By default, the yum repos are disabled by the XEN. I have fixed that, but the docker cannot be installed via yum. It requires the libselinux >2.5.14, which cannot be installed with systemd version 219-19.

I have tried: 1) Install libselinux with the modified spec (require systemd > 219-20 to require > 219-19). 2) Upgrade the systemd version.

Now, I have libselinux 2.5 on my XEN. However, I can only install a duplicate systemd 219-62 (the system stops me from replacing/removing the old one, and it cannot be updated by yum update). 

I'm wondering that is there anyone could upgrade the systemd or install the docker on the hypervisor layer?

**Comment by olivierlambert** [comment]
We do **NOT** recommend to install Docker in the `dom0`, but in a non-privileged VM. This will trigger package issues, security issues and also performances issues.

**Comment by PinchenCui** [comment]
I know it is not a good idea to do this. But I'm just wondering whether I can run the container at the bottom instead of spawning a VM to contain it.

**Comment by stormi** [comment]
`dom0` is already a VM, technically, so I'm not sure there is any technical advantage in doing so, and as Olivier said, this raises a number of issues.

**Comment by PinchenCui** [comment]
Yeah, stormi you are right. I think there is no advantage here. Maybe this thread can be closed.
