### ISSUE TITLE
NFS 4.1 Support

### ISSUE THREAD

**Issue by MrMEEE** [xcp-ng/xcp#130]
Hi guys..

Thanks for some great work on this project..

I have gotten NFS4.1 to work with XCP, and would love to commit a pull request.. but I can't find the storage management files anywhere?? in which github repo is stuff like /opt/xensource/sm/nfs.py located???

**Comment by MrMEEE** [comment]
Ok.. thanks

Pull request is here:
https://github.com/xapi-project/sm/pull/424

**Comment by stormi** [comment]
:+1:

**Comment by stormi** [comment]
Hi. Why did you close the pull request? The response about it was positive and only required to adapt the tests.

**Comment by MrMEEE** [comment]
I'm not really good at git.. 

So I made a new one, with the tests..

https://github.com/xapi-project/sm/pull/427

**Comment by MrMEEE** [comment]
Well.. now it's merged :)

**Comment by olivierlambert** [comment]
Congrats @MrMEEE ! @stormi what should we do on our side?

**Comment by stormi** [comment]
Either we wait for next XS release, or we include the patch now (doesn't look like it could bring any regressions).

**Comment by olivierlambert** [comment]
I can't tell this patch would be even integrated in next XS release. I think we can start to patch it (no big rush) and put it in testing.

**Comment by stormi** [comment]
I have pushed updated packages with your patch to our `xcp-ng-updates_testing` repository.

See https://xcp-ng.org/forum/post/8353

Can you test it?

**Comment by MrMEEE** [comment]
Looks good from here.. installed the packages, change default to 4.1 and remounted.. seems good...

2 considerations:

1. We need to move the default version to a configuration file somewhere.. as any updates to the sm package will reset your default version

2. This would be really nice to implement in the gui :)

**Comment by stormi** [comment]
About 1. can you explain to me as if I knew nothing about it? (which is not far from being the case :))

**Comment by MrMEEE** [comment]
Sure:

As by design, the RPM package manager overwrites all files (removes and writes new) if a package with the same name (and different, preferably newer version) is installed. Files can be "protected" from changes by using the %config parameter when creating the RPM package. This means that the files tagged as config will only be replaced, if they have not changed since installation.

The problem here is that the nfs.py contains the "DEFAULT_NFSVERSION = '3'" which defines the version of NFS you want to use. This means that if the package is updated, the configuration change will be discarded

Using %config on nfs.py will only partly solve the issue, as the file then will see no updates at all, so my suggestion would be:
1. that the file /etc/sysconfig/xensm would be created and added as a config file to the sm package, containing the line "DEFAULT_NFSVERSION = '3'". (and probably more configuration in the future)
2. nfs.py should read configuration from this file, using something like https://docs.python.org/3.4/library/configparser.html should make it pretty easy

**Comment by stormi** [comment]
Ok, so the default value is actually hardcoded. When is it used exactly and why is it needed to modify it to use other versions of NFS? Also can you open a separate issue for this enhancement request?

From what I know this stack is supposed to be deprecated in a not so distant future, but don't hesitate to make those changes you described and submit them upstream for the code, and to https://github.com/xcp-ng-rpms/sm/ for the RPM packaging part (which I can do if necessary but you seem to be able to do it :)).

**Comment by olivierlambert** [comment]
Regarding .2 @MrMEEE can you [open an issue here](https://github.com/vatesfr/xen-orchestra/issues/new) so we can add it into Xen Orchestra?

**Comment by MrMEEE** [comment]
Sure, but I was thinking that maybe the correct (more complex) solution would be:

1. Modigt nfs.py so it tales the nfs version as an argument
2. Add an nfs version option to pbd objekt (defaulting to v. 3)

This will remove the need for the config file and allow multiple nfs storages with different nfs versions..

What do you think?

**Comment by MrMEEE** [comment]
Do you have any ideas where the code for the xen objects are located??

**Comment by johnelse** [comment]
@MrMEEE do you mean the objects PBD, SR, VDI etc. in XenAPI? If so, probably best to start here:

https://github.com/xapi-project/xen-api/blob/master/ocaml/xapi/xapi_pbd.ml
https://github.com/xapi-project/xen-api/blob/master/ocaml/xapi/xapi_sr.ml
https://github.com/xapi-project/xen-api/blob/master/ocaml/xapi/xapi_vdi.ml

If you have any specific questions let me know and I'll do my best to help; there's several layers of code between those files and the interaction with SM and it's not very easy to navigate!

**Comment by MrMEEE** [comment]
After re-reading nfs.py, I have come to the conclusion that the functionality is already available.. but seems undocumented...

xe pbd-params-set other-config:nfsversion=4.1 should work.. I will retest and confirm this..

XOA does this already to allow NFS4.. we just have to add functionality for NFS4.1 as well

**Comment by stormi** [comment]
I'm leaving this issue open for now since the update candidate for the `sm` package with NFS 4.1 support is still in the `updates_testing` repository.

**Comment by stormi** [comment]
Still an update candidate. Not enough feedback for me to push it to everyone for 7.6, but it's included already in upcoming 8.0. When 8.0 is released I'll stop considering pushing it to 7.6.

**Comment by stormi** [comment]
Tested it myself and pushed to 7.6.
