### ISSUE TITLE
Guest tool show "not installed" even after install on Windows

### ISSUE THREAD

**Issue by etlweather** [xcp-ng/xcp#132]
XCP-ng 7.6, all patches.

Installed Guest Tools on a Windows (extracted the ISO from the XenServer ISO download). Rebooted the VM. Both XOA and XCP-ng Center show as if the tools were not installed.

Hence how I concluded it's a problem in XCP, not XOA.

the tools are running per the windows process list. Linux VMs show the tools are installed (install taken from same ISO).

**Comment by borzel** [comment]
did you try the steps in the trouble shooting guide?
https://github.com/xcp-ng/xcp/wiki/Troubleshooting#windows-management-agent--windows-pv-tools

**Comment by stormi** [comment]
Hi. Did you solve your issue?

**Comment by etlweather** [comment]
Not really yet. I tried the uninstall/reinstall and it's hard to tell if it is having some issues or not. I do have a VM running Windows Server 2016 which I moved from a machine that had an earlier version of XCP (or XenServer) and it shows fine as having the tools running. But the Windows 2008R2 VM that I first moved is still showing has not having the XenTools running.

**Comment by borzel** [comment]
@etlweather did you use the troubleshooting guide? There is more than just reinstall...

**Comment by etlweather** [comment]
Yes, I did, but I still have to go through the troubleshooting guide a second time, making sure I'm not missing anything. Things don't show exactly as the guide explains - maybe due to a version difference.

**Comment by borzel** [comment]
Yes, this complete windows guest tools field is a huge mess... but I didn't find the right time and mood to dig deep into it...

**Comment by borzel** [comment]
Please try with the latest version: https://github.com/xcp-ng/win-pv-drivers/releases/tag/v8.2.2.200-RC1

Please reopen this ticket if needed.
