### ISSUE TITLE
XenServer shown rather than XCP-ng upon install

### ISSUE THREAD

**Issue by sammcj** [xcp-ng/xcp#133]
After booting from the ISO, before the installer shows up as per below screenshot:

![screen shot 2019-02-05 at 2 57 46 pm](https://user-images.githubusercontent.com/862951/52311549-6c2e1400-29fb-11e9-8093-c4e71cd9bab4.jpg)

**Comment by sammcj** [comment]
Also in xsconsole after first boot after an upgrade from XenServer 7.2 to XCP-ng 7.6:

![xcp-ng-xenserver-after-install](https://user-images.githubusercontent.com/862951/52313843-37728a80-2a04-11e9-96f2-545c0a17d867.jpg)

**Comment by stormi** [comment]
The part in in XSConsole is a known issue in XenServer. The top left version is refreshed only after some time.

**Comment by stormi** [comment]
About the "Xenserver" string in the installer, it comes from /etc/os-release, value "PRETTY_NAME".

I'll update the build scripts to fix it in next release.

**Comment by stormi** [comment]
Closing though there's no way for you to test at the moment, but it's fixed in the build scripts.
