### ISSUE TITLE
[wiki] experimental kernel root label

### ISSUE THREAD

**Issue by cocoon** [xcp-ng/xcp#136]
I just did follow this tutorial: https://github.com/xcp-ng/xcp/wiki/Alternate-kernel

and saw this "warning":
Pay special attention to root=LABEL=root-kbonvw to match it with your root label.

But the root label occurs two times, so maybe make it more obvious / bold / colored, that it exists two times in the grub entry:

menuentry 'XCP-ng 4.9' {
        search --label --set root **root-kbonvw**
        multiboot2 /boot/xen.gz dom0_mem=752M,max:752M watchdog ucode=scan dom0_max_vcpus=4 crashkernel=192M,below=4G console=vga vga=mode-0x0311
        module2 /boot/vmlinuz-4.9-xen root=LABEL=**root-kbonvw** ro nolvm hpet=disable xencons=hvc console=hvc0 console=tty0 quiet vga=785 splash plymouth.ignore-serial-consoles
        module2 /boot/initrd-4.9-xen.img
}

**Comment by olivierlambert** [comment]
Feel free to correct the wiki, it's open to edition by anyone :) When it's done, close this issue.

Thanks a lot!

**Comment by cocoon** [comment]
Just felt I should get a second opinion about it to be sure ^^
Done.
