### ISSUE TITLE
Upstream Xen patch related to libxenstat

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#140]
We can upstream `xentop-display-correct-stats.patch` to Xen directly. This should be relatively straight forward.

This will allow us to understand how to contribute to Xen directly. Here is the process: https://wiki.xenproject.org/wiki/Submitting_Xen_Project_Patches

**Comment by borzel** [comment]
I did this complicated procedure once to get our PCI-device range entry. Biggest issue was to correct formst the email. Till today I don't understand why they send emails with patchfiles to integrate code...on a maillinglist...

**Comment by olivierlambert** [comment]
@borzel that's the same way people contribute on Linux. Let's say it's the "historical" way :wink:  It's very different than the how it works today for a vast majority of project (ie with GitHub PR for example).

**Comment by Wescoeur** [comment]
Merged: https://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=91c3e3dc91d614d3385d69d03e2dbefbe8abced4
