### ISSUE TITLE
Improve migration speed (VM)

### ISSUE THREAD

**Issue by Wescoeur** [xcp-ng/xcp#145]
Slow performance has been observed with VM migration and particularly on 1G Network Interface Device.

Observations:
- Migrate with _unbuffered_ or _encryption_ does not change the result.
- With a bigger sync limit in https://github.com/xapi-project/vhd-tool/blob/1167cdf660a60f93d4aeef9c742e1a27aef7ec26/src/channels.ml#L76 the migration speed remains the same. Tested with 8MB, 16MB and 128MB.
- With 10G Network Interface Device, the migration speed is: ~120MB/s. This speed can be explained by disk limitation.

With 1G Network Interface Device, the speed is: ~60MB/s (mgmt/no mgmt). The disk limitation is not the problem.

For the moment this issue is blocked.

**Comment by nikade87** [comment]
Was this just migration of a VM within a pool with shared storage or was it vdi-migration?
