### ISSUE TITLE
No NIC anymore after guest tools installation

### ISSUE THREAD

**Issue by lafi08** [xcp-ng/xcp#153]
Just installed the guest tools on my Ubuntu Machine. After a reboot i could not ping my gateway anymore.
Ifconfig said that theres no more ethernet connected. 2nd error: I cant login in root anymore...
Any ideas ?

**Comment by olivierlambert** [comment]
Please post on [XCP-ng forum](https://xcp-ng.org/forum) if your issue is still vague like this. Please provide there: how did you installed the tools, what XCP-ng version used, are you up to date etc.

**Comment by stormi** [comment]
Closing, feel free to reopen with more information.
