### ISSUE TITLE
Guest tools not installing on SLE 15 with Linux installation script

### ISSUE THREAD

**Issue by boblmartens** [xcp-ng/xcp#159]
When I attempt to install the guest tools on a SLE 15 server (SUSE Linux Enterprise) I get the following error message:

`Fatal Error: Failed to determine Linux distribution and version.`

Just looking to get the script updated so that it will install successfully. Thanks!

**Comment by stormi** [comment]
It's been fixed upstream 2 months ago apparently: https://github.com/xenserver/xe-guest-utilities/commit/fedb8302d893b5535b2746b3d7b3c3b0def093a5

So this will be in next release of XCP-ng. 

Meanwhile, you can probably install them with `./install.sh -d sles -m 15` (untested)

**Comment by boblmartens** [comment]
I am able to get it installed with -m 12, but it looks like there are some bugs with getting XCP-ng to see that the tools are installed. I can be patient on this one.

**Comment by stormi** [comment]
I can see that in install.sh, looks like there are several versions of SLES missing in the script. I suppose there's a SLES 13 and a SLES 14 too?

**Comment by boblmartens** [comment]
Nope. SLE went from 12 to 15.

**Comment by stormi** [comment]
There aren't a lot of commits to https://github.com/xenserver/xe-guest-utilities so it's not guaranteed that your SLES with tools installed will get recognized as having tools installed in the next release. If you have a way to find what's happening, this would help ensure that it will work.

**Comment by boblmartens** [comment]
I'll do some more investigating to see what may or may not need to be done. I tried re-running the installation and it found the installed tools.

**Comment by boblmartens** [comment]
Thanks for your help. I think I am going to wait for the next release before doing too much more investigation into what is going on.

**Comment by stormi** [comment]
This should be fixed in XCP-ng 8.0 beta
