### ISSUE TITLE
ql2xx kernel panic happened during installed as well after installation completed.

### ISSUE THREAD

**Issue by mkaliyannan** [xcp-ng/xcp#162]
Did anyone resolved? I tried to upgrade xcp-7.6 on hp DL60. it's doesn't go through well, when reaches ql2xx card, kernel panic happened... tried several attemps no luck..

Finally I disable QLogic card from the bios, then restarted the upgrade, and this time went well and got upgraded to xcp-7.6,

So I decided to back to enable Qlogic card on Bios, after upgraded. . when reaches certain point restarted the server right away.. if I disabled it's let me go in...

Driers issue ??

Previous version of xenserver 7.2 worked..

**Comment by stormi** [comment]
Closing as probable duplicate for #57
