### ISSUE TITLE
Lilo as an alternative to GRUB

### ISSUE THREAD

**Issue by guidofaecke** [xcp-ng/xcp#167]
Would it be possible to add lilo as an option to the install process?  
In case you ask the "why"... I have a lenovo machine (with UEFI capabilies), which is perfect for xcp, unfortunately, it has issue with linux installing GRUB. In other words, it will not boot. Simple bootloaders like lilo have no problems on that box.  
If not, what is the recommend way of replacing grub with lilo?

**Comment by stormi** [comment]
Hello. There's no plan to add lilo support at the moment. It would require a lot of extra work for very limited use cases. I suggest you try the forum to see if anyone can help debugging your grub issue or install lilo. https://xcp-ng.org/forum/

**Comment by stormi** [comment]
Closing since there is no short or mid-term plan to support LILO.
