### ISSUE TITLE
Could not locate Fixup ISO

### ISSUE THREAD

**Issue by Zewwy** [xcp-ng/xcp#169]
When importing an OVA I exported from another hypervisor (ESXi), once I get up to the wizard step (OS Fixup Settings). I select the radio button to use Operating System Fixup. Then get an Error: Could not locate Fixup ISO:

![image](https://user-images.githubusercontent.com/3783231/55841372-84520a80-5af4-11e9-89d2-82e3218b52f4.png)

How do I get this ISO? and how can I use it? Everything else in the install was so easy and then this... like why is this so difficult? why is this not available by default?

**Comment by Zewwy** [comment]
So far I found importing a Windows 10 OVA export from ESXi works without issue. Ubuntu so far has not been so successful.

**Comment by stormi** [comment]
The fixup ISO is provided by Citrix. You can probably download it from their website or extract it from XenCenter.

**Comment by stormi** [comment]
@borzel Do you know if there's a github repository for that ISO and/or where to find it?

**Comment by borzel** [comment]
No, I dont

**Comment by Zewwy** [comment]
If this option is available there should be proper documentation on how to use it.

**Comment by olivierlambert** [comment]
This feature is a remainder of XenCenter, and made it "accidentally" in XCP-ng Center. This is NOT integrated in Xen Orchestra, which is the XCP-ng client with most support (because there is 6 devs working on it every day).

XCP-ng Center is only community maintained by few people, so that's why you should expect some rough edges like this @Zewwy

**Comment by Zewwy** [comment]
Hopefully can be "fixed" if not, even removed, if its non functional.

**Comment by olivierlambert** [comment]
All contributions welcome, feel free to create a PR in XCP-ng Center repo (or create an issue there at least). :)

Closing here.

**Comment by ddy86** [comment]
Can find the xenserver-linuxfixup-disk.iso in XenCenter installer path: C:\Program Files (x86)\Citrix\XenCenter\External Tools, 
and put it into the xcp-ng's iso library path.

So you can import vmdk image continue, but the progress bar is stopped.

**Comment by olivierlambert** [comment]
@ddy86 please use Xen Orchestra to make your VMDK import. Or create an issue on XCP-ng Center repo.
