### ISSUE TITLE
Feature: EXT4 Support for Thin Provisioning on Local SR

### ISSUE THREAD

**Issue by pflaugh** [xcp-ng/xcp#17]
I would love to see better Thin Prov support in XCP-ng. Citrix XenServer uses outdated EXT3 for Thin Provisioned local SRs. I have a 14TB Local SR so the 2TB Max file-system limitation of EXT3 is frustrating, since I use hardware raid.

I see that there is plans to have ZFS support in the future. Would this be able to support Thin-Provisioning our is EXT4 the only hope for Local SRs larger than 2TB?

Thanks for all you've done so far! I am excited to try out the first XCP-ng ISO on some spare equipment!

**Comment by olivierlambert** [comment]
Hi,

The 2TiB limit has nothing to do with ext3, but it's a VHD format limit. It should be replaced in the future by qcow2, but it's not trivial.

**Comment by pflaugh** [comment]
Interesting ok. Thanks for the info. I was aware of the VHD limit. I have had lots of trouble getting an EXT3 local SR to work during install of XS. It always ends up broken and unplugged and not repairable. Creating a new EXT3 SR from scratch at the CLI seemed to yield the same outcome. 

It will be interesting to see if I have the same problem with XCP. I will let you know.

Sent from my iPhone

Perry Flaugh

**Comment by pflaugh** [comment]
As I suspected, Thin Provisioning seems to be broken just in XS. I just installed XCP-ng on a spare server with Thin Provisioning selected during the install process and everything is working beautifully. I have a Local EXT SR of 11TB, Thin Provisioning enabled.

Ill go ahead and close this since my "issue" is resolved by XCP.

Thanks again for all your hard work on this. If you need any help or testing of anything, please let me know. I am excited for the future of XCP-ng.

**Comment by olivierlambert** [comment]
Okay please keep up posted if you have issues. Maybe it's because something was fixed in XS 7.4?
