### ISSUE TITLE
Request: xoa auto logout function

### ISSUE THREAD

**Issue by akurzawa** [xcp-ng/xcp#171]
Hi

can we make a logon timeout function in xoa?

Something like this:
![image](https://user-images.githubusercontent.com/20043789/55860429-7e037300-5b74-11e9-8f5e-fd56e135a5ce.png)

**Comment by olivierlambert** [comment]
Hi,

1. You aren't in the right repo (it's XCP-ng here, not Xen Orchestra)
2. This feature already exists, you need to edit your `xo-server` configuration file and add/edit the value called `permanentCookieValidity`

Here is an example:

```
#permanentCookieValidity = '30 days'

# Default to `undefined`, ie as long as the browser is not restarted
#
# https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Set-Cookie#Session_cookie
#sessionCookieValidity = '10 hours'
```

However, I don't this it into the official XO doc. Can you please create an issue in Xen Orchestra repo to ask for this feature to be documented?

**Comment by akurzawa** [comment]
Done , can You delete this issue?
https://github.com/vatesfr/xen-orchestra/issues/4136

**Comment by olivierlambert** [comment]
Nope, an issue can't be delete, but we leave it closed.

**Comment by olivierlambert** [comment]
It seems you also missed the point of my answer: I explained how to do so, and asked to create an issue in XO to ask for an official documentation :confused:
