### ISSUE TITLE
Have followed https://github.com/xcp-ng/xcp/wiki/GlusterFS , driver not creating SR module

### ISSUE THREAD

**Issue by darrynza** [xcp-ng/xcp#174]
after following the wiki page mentioned in the topic i end up here. 

There was an SR backend failure.
status: non-zero exit
stdout: 
stderr: Traceback (most recent call last):
  File "/opt/xensource/sm/GlusterFSSR", line 14, in <module>
    import SR
ImportError: No module named SR

I am a bit slow today, but not sure how to proceed from this point

**Comment by olivierlambert** [comment]
Please provide the command line you used to create the SR, and display the files you modified. Also double check you restarted XAPI after file modifications.

**Comment by stormi** [comment]
Closing due to absence of answer.
