### ISSUE TITLE
Add Cross Server Private Network support

### ISSUE THREAD

**Issue by benjamreis** [xcp-ng/xcp#175]
Adding the possibility to create a private network (through VxLan and/or GRE tunnels) between VMs on separate hosts in the same pool.

**Comment by benjamreis** [comment]
A beta is coming!
You can read more [here](https://xen-orchestra.com/blog/xo-sdn-controller/)!

**Comment by benjamreis** [comment]
Functionality has been implemented in [xen-orchestra](https://github.com/vatesfr/xen-orchestra).

I'll close this issue, do not hesitate to open a new one on the xen-orchestra repo if any problem is encountered! :)

**Comment by ismo-conguairta** [comment]
And how to use this functionality without xen-orchestra?

**Comment by stormi** [comment]
> And how to use this functionality without xen-orchestra?

I guess you could look in the code at how it was implemented and do it in command line on your host. But I'm not sure this answers your question fully.

**Comment by benjamreis** [comment]
Hello,

The only way to create pool-wide private networks is using a SDN controller to control all the openvswitch bridges of the pool's hosts.
Therefore the solution must be external to XCP-ng. We decided to implement in xen-orchestra since it's already our product to create networks.
Citrix also offers a solution: Ditributed Virtual Switch Controller, but it's closed source and requires to install a VM dedicated to running the controller. And the control UI is only available through Internet Explorer.

The private network creation can be done manually with XAPI and OpenVSwitch commands but the monitoring to keep it running when the pool's network configuration (removal of a host PIF, or restart of a host for instance)

**Comment by ismo-conguairta** [comment]
Thanks @benjamreis! It's all clear. This feature will be available only with Premium plan, isn't it?

**Comment by benjamreis** [comment]
In case you need support, yes it's part of the Premium plan.
However it is also available freely if you build xen-orchestra from source.
