### ISSUE TITLE
Lenovo BIOS RAID - install unrecoverable error

### ISSUE THREAD

**Issue by RKENS** [xcp-ng/xcp#176]
I'm installing XCP-NG on a new Lenovo ThinkServer. I thought I would try to enable the BIOS RAID 10 (4 SSD drives). The installer detects the drive array and starts the install process, but fails to install the bootloader for i386-pc platform. /usr/sbin/grub-install: error unable to identify a file system in hostdisk /dev/sdc; safety check can't be performed. I tried running the installer twice. 

Is using the Lenovo BIOS RAID not supported or not recommended? (I know I can use the XCP-NG software RAID option too).

Thanks,
Russ

**Comment by nagilum99** [comment]
That "BIOS RAIDs", aka fakeraid (chipset RAID) are _never_ recommended for _any_ non Windows system. They're worst of both worlds. Go for a 'true' RAID Controller with proper drivers or go for full software RAID (like MDADM).
...and even for Windows I'd not to that way. ;-)

Regards
 - Christof

**Comment by olivierlambert** [comment]
Agreed with @nagilum99 

Please avoid using fake RAID, and use mdadm instead or real hardware RAID.

**Comment by RKENS** [comment]
Thank you for your suggestions.

Russ
