### ISSUE TITLE
Loosing Network Configuration after removing server from pool

### ISSUE THREAD

**Issue by birduser** [xcp-ng/xcp#179]
I've run into an issue whilst doing tests with a server pool. 
After removing a server from the pool all network settings of this server are removed and have to be re-configured directly on the server. Is there a away to avoid this?

**Comment by olivierlambert** [comment]
No, it's a "normal" (expected) behavior. Ejecting a server from a pool will clean its database, with all the settings.

**Comment by birduser** [comment]
Alright, thanks for letting me know. 

BR
