### ISSUE TITLE
Need to use Joliet long to build XCP-ng ISO if mounted on Windows

### ISSUE THREAD

**Issue by Ultra2D** [xcp-ng/xcp#18]
PXE booting into the installer works. I get stuck when trying to use remote storage (NFS and HTTP):
> Problem With Location
> Setup  was unable to access the location you specified - please check and try again.

It seems the file names are wrong. From the web server logs (where it apparently fails on the first file):
> "GET [[installation source]]/repodata/4549ebed7e162f6addd8c658f7e66d8ca1b0ad604c15f34b1389f65d1c5397e0-primary.xml.gz HTTP/1.1" 404 558 "-" "Python-urllib/2.7"

In the XCP-ng ISO the file name actually is
> 4549ebed7e162f6addd8c658f7e66d8ca1b0ad604c15f34b1389f65d1c5397e0

**Comment by olivierlambert** [comment]
In the XCP-ng ISO, in repodata, I got:

```
31107ede8c741786a02829c4dfcbadba75d24fa1b2bf89c8934c0ee4f9082f70-other.sqlite.bz2
3d1fde872cf971ec617272af04618c1daa77064320c50b374e698670e3eecebb-filelists.sqlite.bz2
4549ebed7e162f6addd8c658f7e66d8ca1b0ad604c15f34b1389f65d1c5397e0-primary.xml.gz
4c3191ba4d1ca98b0d5d082edd5f784f0469fddb6960eac7164198d2786e4dda-filelists.xml.gz
4c6381aef10cc23cd60ad0638dee8a00ea8ccfb921a3e202d7836109a241ea06-other.xml.gz
6bae95c9e8487517398e382871008227f5569bf3c4e4fcb4df258d04bc658022-groups.xml
b37a2ec1dae3ec01945a9a25dfeae6a02f7753758c5b65f4c6bd90aa219f956f-groups.xml.gz
e360adbf99102b989348ab8509d82dad11068414615213dd8d2659e5e1e120c7-primary.sqlite.bz2
repomd.xml
```

Sounds good to me. Can you double check? I mean, there is maybe an issue, but it's maybe not due to what you think.

**Comment by JeffBerntsen** [comment]
I think I may have found the problem.  

It looks like an issue with the way the CD image is built, specifically long vs. short filenames.  If I mount the image file under Linux, the full names of the files show in the repodata folder as you just listed.  

If opened from utilities in Windows designed to open ISO images, such as 7Zip or Beyond Compare (which I believe uses 7Zip), the file name shows as the truncated version with just the hash value and no -<filename> at the end.  

Mounting the ISO image with a utility like IMDisk under Windows also shows the shorter name.  I haven't tested it (I easily can if you like), but mounting a burned CD under Windows will likely show the same problem as mounting the ISO image to a virtual DVD drive the way IMDisk does.

The XenServer 7.4 ISO image files don't seem to have any of these problems and show the long file names under all situations.

**Comment by olivierlambert** [comment]
That's probably the Joliet thing yes. So please mount it on Linux, and copy the content then. If it works, close the issue 👍

**Comment by JeffBerntsen** [comment]
That looks like the issue.  I'm not sure what the Citrix CDs are mastered with but they seem to be using long Joliet file names (i.e. equivalent of -jolient-long argument to mkisofs).  In addition to most of the repodata directory files being truncated, the qlogic-netxtreme2-4.4.0+10-modules-7.14.29.1-1.el7.centos.x86_64.rpm file in the Packages directory is also affected, with just the .rpm truncated there.

**Comment by Ultra2D** [comment]
I indeed used 7-Zip on Windows. This has always worked with XS, and the XS 7.4 ISO also works fine that way. So there is a difference in the way the ISO is created. I can work around it now for sure, but maybe other people will have some difficulties too.

**Comment by JeffBerntsen** [comment]
After correcting the truncated filename in my installation source, I was able to successfully install using an NFS source.  Installing from an FTP source still has a problem when when using some FTP servers (which also exists in the XenServer installer) but that's not unexpected.

**Comment by olivierlambert** [comment]
@JeffBerntsen I'll double check I use `-joliet-long` for the next ISO release (`7.4.1` then)

Thanks for your report, closing thins one 👍

**Comment by Ultra2D** [comment]
The problem seems to have returned in xcp-ng-7.5.0.iso (although I did not check 7.4.1).

**Comment by olivierlambert** [comment]
Yes, that's correct. It's planned to fix it with the latest ISO generation coming soon (with soft RAID support and netinstall)

**Comment by stormi** [comment]
Forum thread on this issue: https://xcp-ng.org/forum/topic/312/7-5-0-final-release-iso-repodata-files-missing-correct-extensions

**Comment by Ultra2D** [comment]
That one works fine in 7-zip (Windows and Linux) and when mounting in Windows. Note that all three did not work with the 7.5.0 ISO.

**Comment by olivierlambert** [comment]
Great! Thanks for your feedback @Ultra2D

**Comment by stormi** [comment]
Thanks. All future ISOs will now use this option. We plan to release an updated 7.5 ISO next week.
