### ISSUE TITLE
Patch MDS vulnerabilities

### ISSUE THREAD

**Issue by knd775** [xcp-ng/xcp#185]
[https://mdsattacks.com/](https://mdsattacks.com/)

I'm not sure the patches are available quite yet, but I figured I'd create an issue so that the vulnerabilities are on the radar.

**Comment by olivierlambert** [comment]
Hi,

Thanks a lot for the report. We are aware of this and patches are coming (from Citrix, that we'll apply for XCP-ng) :+1: 

P.S: I'd like to tell that Xen devs (and Citrix XS team on Xen) are doing fantastic work to provide those patches as fast as possible!

**Comment by knd775** [comment]
Looks like this has been resolved. Thanks!
[https://xcp-ng.org/blog/2019/05/21/xcp-ng-security-bulletin-mds-hardware-vulnerabilities-in-intel-cpus/](https://xcp-ng.org/blog/2019/05/21/xcp-ng-security-bulletin-mds-hardware-vulnerabilities-in-intel-cpus/)

**Comment by stormi** [comment]
Indeed. Working on a patch for 7.5.
