### ISSUE TITLE
Remaining user-visible XenServer branding

### ISSUE THREAD

**Issue by JeffBerntsen** [xcp-ng/xcp#19]
I think this is just cosmetic for now unless Citrix has a more serious problem with it.

There are a few places in the startup and shutdown sequence where the XenServer branding is still visible.  If you press escape during the boot or disable Plymouth or use nosplash instead of splash as a kernel boot parameter, there are a few places in the text still showing XenServer instead of XCP or XCP-ng:

* [ ] "welcome to" line which still shows as XenServer 7.4.0  It looks like this comes from the PRETTY_NAME field in /etc/os-release.

The others are places where XenServer still shows in the name of starting services in `/usr/lib/systemd/system`:

* [ ]  `xs-sm.service`
* [ ] `xsconsole.service`
* [ ] `xapi-nbd.service`

All still have XenServer in their descriptions which print out to the console whenever they are started or stopped.

I've manually edited them on my system and it doesn't seem to cause any problems.  There are also instances of XenServer in:

* [ ] the /etc/centos-release and other instances of it in the /etc/os-release files but I don't know if those are exposed to the user or not.

**Comment by olivierlambert** [comment]
Hi,

On a fresh install or upgrade?

**Comment by olivierlambert** [comment]
Thanks! I'll reformat a bit your original issue to expose more clearly each point :+1:

**Comment by Tandokude** [comment]
I also noticed this on the webpage, see attached. New install. 
![image](https://user-images.githubusercontent.com/18389226/38327338-f8b6627a-3815-11e8-9bfd-99874ffe8d04.png)

**Comment by olivierlambert** [comment]
This is already in the pipes to be fixed ;)

**Comment by skajter** [comment]
Can we update this one issue, as from last release 7.4 this page is replaced? :)

**Comment by olivierlambert** [comment]
Yup closing!
