### ISSUE TITLE
ZFS 0.8.0 in XCP-ng 8.0

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#192]
- [x] compile/build ZoL 0.8 for XCP-ng @stormi 
- [x] try previous features that didn't work before (`IO_DIRECT`) like VHD export @olivierlambert 
- [x] rebench it in sync/async mode @olivierlambert 
- [x] check if VHD merge is happening

**Comment by stormi** [comment]
The packages are now available in XCP-ng 8.0 beta

**Comment by olivierlambert** [comment]
Thanks, I'll try that :)

**Comment by olivierlambert** [comment]
I have **very** good news:

* creating the SR without the `io_direct` flag is working
* exporting a VM is working
* migrate a VM from or to this SR is working

Without any special configuration. Performance seems also **really** decent without having to disable sync! (cache poisoning is not longer a problem since `O_DIRECT` works).

So what's next? Maybe in another issue, we could probably start to work on:

* a SMAPIv1 better driver, with snapshots etc? but it might be worthless because…
* SMAPIv3 would be better to invest it.

We'll have to weight exactly what's missing in SMAPIv3 (outside performance wise) to invest into drivers for it

**Comment by olivierlambert** [comment]
Also I really got huge performances even in sync against async in previous ZFS version. That's really impressive.

**Comment by dpcinc** [comment]
This is super exciting, I've waited so long for zfs + xen.  After you guys tackle SR's, at some years down the road can you look at zfs on root for install?  I really hate relying on software or hardware raid for OS install.

**Comment by stormi** [comment]
Should we merge this issue with #74 ? (keeping this one here since it's got more details)

**Comment by olivierlambert** [comment]
@dpcinc having ZFS on root might be harder.

**Comment by borzel** [comment]
What about XCP-ng 7.6? Would like to have ZoL 8.0 on them, this would make my XCP-ng backup / replication host more attractive ;-)

**Comment by olivierlambert** [comment]
IDK, it's up to @stormi to decide :+1:

**Comment by stormi** [comment]
I don't intend to support them on 7.6 but I have built them for you to test. I haven't tested the packages myself. 

They should be installable with `yum install zfs --enablerepo='xcp-ng-updates_testing'`

If they don't work correctly I don't promise any update.

The "supported" (supported to some extent, still experimental there too) way will remain using XCP-ng 8.0 for this version of ZFS.

**Comment by borzel** [comment]
@stormi installed it on a XCP-ng 7.6 testhost, created a file SR ontop of ZFS - it seems to work just fine :-)

The only thing missing is the loading of the zfs module after reboot. I had to load it by hand.

**Comment by dpcinc** [comment]
Is it xen LVM SR on top of zfs or something else?

**Comment by borzel** [comment]
It's a File SR. I created a ZFS Pool with a ZFS dataset. The File SR is pointing into that dataset.
So it's pure ZFS and VHD files. No LVM.

`xe sr-create type=file ....`

**Comment by stormi** [comment]
On a nested XCP-ng 8.0 beta in which I simply installed the zfs packages (no pool created), the module is not loaded at boot and the `zfs-mount`, `zfs-share` and `zfs-zed` services can't start. Do you experience the same?

**Comment by stormi** [comment]
Ping @borzel and @olivierlambert: do the ZFS services start automatically for you?

**Comment by olivierlambert** [comment]
I think it is, but I can double check.

**Comment by olivierlambert** [comment]
So:

* ZFS module won't be loaded on boot if there is no ZFS dataset
* ZFS module will be loaded automatically if there is a ZFS dataset

I think it's pretty normal.

**Comment by stormi** [comment]
Ok. It's a bit dirty that it leads to 3 failed systemd services though.

**Comment by olivierlambert** [comment]
However I can confirm that I don't need to do a `depmod` anymore after ZFS install! :+1:

**Comment by stormi** [comment]
Do we need this issue open for further development, or can we consider it closed?

**Comment by olivierlambert** [comment]
No, let's close it :)

**Comment by nikade87** [comment]
I recently had a ticket with Nexentastor support and when investigating our Nexentastor-machines they noticed we had async enabled, they recommended turning it off for NFS shares and we really noticed that our VM's now feel "snappier".
According to them the access time will be better leaving async disabled.

**Comment by olivierlambert** [comment]
That's weird: async means the client won't wait for a write confirmation on the storage (it's fine if you have an UPS on your storage obviously, to mitigate the risk to lose inflight blocks).

Sync means the client will wait until the NFS server answers "it's written". You can also reduce the perf penalty of sync by using a SLOG.

**Comment by nikade87** [comment]
It also means that the timestamp of the VHD-files needs to be updated every time they are accessed over NFS, which creates a small wait for the NFS-client. That means a couple of ms higher latency.
This information came from "a guy who lives in the kernel" according to our Nexentastor support engineer.

I have never heard about this before and I am unable to verify this information.

**Comment by olivierlambert** [comment]
You mean in the `async` case? So in `sync` it shouldn't need to update the timestamp?

**Comment by nikade87** [comment]
Sorry, might be a confusion on my end here. The command they executed on our nodes was:

zfs list -Hr -t filesystem -o name | grep -v syspool | while read i; do echo $i; zfs set atime=off $i; done

So it is not the same thing.

**Comment by olivierlambert** [comment]
Okay they disabled atime to avoid touching the file everytime, makes sense.
