### ISSUE TITLE
xcp-ng.org is down

### ISSUE THREAD

**Issue by mensonen** [xcp-ng/xcp#195]
The xcp-ng.org website main page is down, getting an nginx default page instead of normal content.

**Comment by olivierlambert** [comment]
Hi,

Are you sure? Please refresh your browser.

**Comment by mensonen** [comment]
Well, no longer - but was like that for the past 24 hours.

**Comment by olivierlambert** [comment]
I assume it was stored on your cache when you visited it during maintenance. On our side, as soon we have been back on tracks, we got visits from around the world without any issues.

Thanks for your report!
