### ISSUE TITLE
[XAPI] Ability to create a VM with custom `suspend_VDI`

### ISSUE THREAD

**Issue by julien-f** [xcp-ng/xcp#196]
We would like to be able to back up VM with their memory in XO (vatesfr/xen-orchestra#645).

My initial approach is to create a checkpoint of the VM and then backup each of its VDIs (disk and `suspend_VDI`).

The issue is on the restoration side, I'm unable to:

- create a VM in a `suspend` power state
- set a `suspend_VDI`

**Comment by olivierlambert** [comment]
@johnelse could you "explore" to feel the difficulty level of this task, and if it could be delegated to a XAPI newcomer? Thanks :smile:

**Comment by johnelse** [comment]
There is already the `VM.set_suspend_VDI` API call - problem is it does a checksum to check that the old and new VDIs have the same content.

I think the simplest solution would be to add an optional `force` argument to this API call, which if true would bypass the checksum.

**Comment by johnelse** [comment]
As for creating the VM in a `suspend` power state, could you use the VM metadata-only export/import handlers?

**Comment by stormi** [comment]
Closing, done by @benjamreis and available in XO + XCP-ng 8.1
