### ISSUE TITLE
Virtual disk naming on system level

### ISSUE THREAD

**Issue by Barlog951** [xcp-ng/xcp#197]
Hi everyone,
first thanks for a great product 🙂

I try to virtualize my FreeNAS in xcp-ng,
PCI passthrough of external and internal SATA controllers end up great 
( thanks for a great [tutorial](https://github.com/xcp-ng/xcp/wiki/PCI-Passtrough) )

When I add virtual HDD and start installation system, in system level was like **ada0** but I already have **ada0** from my PCI controller

Change of HDD position works good but then the system doesn’t boot after install 😕

So It's possible to change the naming of virtual HDD from **ada0** to **da0**?

This works perfectly on VMware ESXi, but I would like to migrate to xcp-ng 🙂

Tanks for the answer

<img width="315" alt="Snímka obrazovky 2019-05-31 o 15 33 11" src="https://user-images.githubusercontent.com/9975572/58716169-b5e6a400-83c8-11e9-9e3f-05a674f51ca4.png">

**Comment by stormi** [comment]
Sorry for not answering sooner. I think no one answered because we don't know the answer. If you still have an issue, I suggest to also ask our experienced users on the forum.

Closing due to the issue being likely to be old, reopen if needed.

**Comment by weaselshit** [comment]
Hi, I have the same issue. Apparently, someone had some success in a similar setup on XenServer: https://forums.freebsd.org/threads/marvell-88se9230-passthrough-fails-for-combination-freebsd-as-xen-guest.66895/. Unfortunately, I don't understand what they meant by "Instead of allocating a image based IDE root device I switched to XEN bus type".

**Comment by olivierlambert** [comment]
@weaselshit that's because they are using Xen (the hypervisor, installed on a Ubuntu host) not XenServer (a distro with Xen inside by default). XenServer/XCP-ng are using XAPI as toolstack, not Xen alone (using xl)
