### ISSUE TITLE
Sources components to RPMs

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#2]
This will use `mock`. We have to figure out how it works exactly

**Comment by necouchman** [comment]
I'm trying this out based on the instructions at https://xenserver.org/blog/entry/building-xenserver-core.html.  It's taking a little tweaking because the repo URLs have changed, but I'm documenting as I go.

**Comment by olivierlambert** [comment]
In theory `xenserver-build-env` should be able to generate RPMs. I'll have more info coming next week :)

**Comment by necouchman** [comment]
Sounds good.  I was using the https://github.com/xenserver/buildroot repo, which hasn't been updated in a while.

**Comment by necouchman** [comment]
So, it looks like the default instructions provided in the xenserver-build-env directory rely on the "xs" repo.  I'm going to guess, as you mention, if we're going for a completely autonomous build, we do not want to rely on those and we want to build from source, instead.

**Comment by necouchman** [comment]
> edit: Christmas time for me, I'll be more or less AFK. But you're an admin too @necouchman , feel free to add people you want ;)

Sounds good.

**Comment by olivierlambert** [comment]
Current blocker: OCaml in 7.3 source ISO is **NOT** the right version to build the rest. We are waiting for Citrix to upload a new source ISO which the correct SRPMs packages.

**Comment by stormi** [comment]
I have renamed and updated our fork of xenserver-build-env at https://github.com/xcp-ng/xcp-ng-build-env and uploaded many rebuilt RPMS (including the -devel RPMs that aren't present in XS ISOs) in a `builddeps` repository that xcp-ng-build-env uses for the builds. It can successfully rebuild xen, xapi and many other packages, though some dependency may still be missing for some packages.

Have a look at https://github.com/xcp-ng/xcp-ng-build-env/blob/master/README.md !

**Comment by stormi** [comment]
We now have a build process that works, although not entirely automated yet. Closing this issue.
