### ISSUE TITLE
Open VxLAN port for SDN Controller

### ISSUE THREAD

**Issue by benjamreis** [xcp-ng/xcp#202]
In order to create VxLAN we need to open a port in XCP-ng.
`-A xapi-INPUT -p udp -m conntrack --ctstate NEW -m udp --dport 4789 -j ACCEPT`

**Comment by stormi** [comment]
There's a xapi plugin that does that: `/etc/xapi.d/plugins/firewall-port`

See how it's used in `/etc/xapi.d/plugins/openvswitch-config-update`

Can we do something similar ?

**Comment by benjamreis** [comment]
Hmm it's complicated, the SDN Controller is outside the hosts since it's a XO plugin, therefore it has no control on the hosts.
When could we call `/etc/xapi.d/plugins/firewall-port`?

**Comment by stormi** [comment]
We could look at when `openvswitch-config-update` is called and see if we could get some inspiration from it

**Comment by benjamreis** [comment]
It's called by a XAPI call:
`host.call_plugin(openvswitch-config-update)`

**Comment by benjamreis** [comment]
See https://github.com/xcp-ng/xcp/issues/207
