### ISSUE TITLE
[improvement] Switch to chrony and change the sync approach

### ISSUE THREAD

**Issue by maxcuttins** [xcp-ng/xcp#203]
Chrony is quickly becoming the standard for cloud system in order to have a lower clocks asyncs.
This because instead of NTP (which has been out for ages) is recent and built on modern technology (and use also NTP protocol if needed).

RedHat and CentOS upstream are already switch to this standard.
We should think about do the same.

Muchmore, Chrony is server and client alltogether, meaning that the master can become the source for the slaves hosts in the pools. This means minimum asyncs or even no asyncs  between pools.
So, only the master will be feeded with external source, while the rest of the pool will be in sync by querying the master.

I think this is the right way to achieve perfect syncs betweens clustered systems.
Let me know what do you think about

**Comment by stormi** [comment]
Thanks for the suggestion. I'm not able yet to judge the work that the switch would cause and the benefits from it, so I'm letting this bug open for community discussion first.

**Comment by maxcuttins** [comment]
This is a tipical "nice-to-have" enhancement as NTP doesn't work that bad to require immediate replacement.

However, having perfect sync with universal time on DOM0 is something valuable.
Most of the time you cannot see benefit when all time is in sync, because software just works.
But, you can be sure that you are gonna hit some hidden bug when you have your time out-of-sync.

**Comment by stormi** [comment]
Citrix Hypervisor 8.1, and thus XCP-ng 8.1, moved to chrony.

I don't know if master became the source of the slaves. Can you check that?
