### ISSUE TITLE
Update candidate: xapi with support for opening VxLAN port (7.6)

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#207]
Update candidate for XCP-ng 7.6: http://koji.xcp-ng.org/taskinfo?taskID=8961

Install with `yum update xapi-core xapi-xe xapi-tests --enablerepo='xcp-ng-updates_testing'`

**Comment by benjamreis** [comment]
Test was succesfull.

**Comment by stormi** [comment]
Pushed
