### ISSUE TITLE
Performance XCP 8.0 slower than on 7.6 - How to measure performance ?

### ISSUE THREAD

**Issue by sapcode** [xcp-ng/xcp#211]
Dear XCP team,

we have setup a new IBM x3650m3 with 2 Intel(R) Xeon(R) CPU X5675  @ 3.07GHz using the beta XCP 8.0. We have 2 SAP Systems running with each 12 vCPU's allocating most of the Host memory up to 144GB, both VM are on SSD disks.

It seems like that the response time is much slower than from XCP Version 7.6, we have the exact same VM machines on 7.6 as well.

Are there any commands how we can measure performance and find out which components are responsible for the performance loss ?

Best regards
sapcode

**Comment by stormi** [comment]
Hi! I suggest to ask on the forum first, where many users can have useful input for this, and we'll watch and/or take part in the thread ourselves.

**Comment by sapcode** [comment]
Discussion moved to forum: https://xcp-ng.org/forum/topic/1614/performance-xcp-8-0-slower-than-on-7-6-how-to-measure-performance
