### ISSUE TITLE
Cannot migrate a VMs which use vhci_hcd kernel module (usb over IP)

### ISSUE THREAD

**Issue by maxcuttins** [xcp-ng/xcp#215]
If I try to migrate a server with an active **USB over IP** I get this error:

```
dpm_run_callback(): plafrom_pm_freeze+0x0/0x70 returns - 16
[476...] PM: Device vhci_hcd failed to freeze: error -16
[476...] xen:manage: do_suspend: dpm_suspend_start -16
```

**Comment by stormi** [comment]
Is this related to https://xcp-ng.org/forum/topic/1626/live-migration-freeze-on-highly-loaded-vms ?

**Comment by stormi** [comment]
Closing as probable duplicate of https://github.com/xcp-ng/xcp/issues/304
