### ISSUE TITLE
yum update xsconsole warning

### ISSUE THREAD

**Issue by maxcuttins** [xcp-ng/xcp#217]
> do not run that command from a shell started from XSConsole. The reason for that: when the xsconsole package itself is updated, it restarts XSConsole and thus kills the current shell session, including the currently running yum command (unless you started it in the screen session). This leaves the rpm database in an unclean state.

Sooner or later somebody is gonna do this. I think this should be avoided.
I see that sometime during install `yum` make some preinstallation script or postinstallation.
I guess we can catch the update of xsconsole packages, verify if it's runned throught a xsconsole and skip the package (or forward to a subprocess that run over screen).

Sometime it's better a warning instead of a crashed system.

**Comment by stormi** [comment]
Done.

![Screenshot_20190716_123717](https://user-images.githubusercontent.com/451043/61288014-8b10ad80-a7c6-11e9-8d20-ff4354d9c1e3.png)
