### ISSUE TITLE
Updater plugin: disable concurrent running of updater.py

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#219]
Sending a lot of requests in a short amount of time to the updater plugin can eat up all a host's RAM. This has been experienced by a user who reported it on IRC.

The updater plugin should first check if it's already running. If it is, it should answer with an error and quit immediately.

For "update" requests, if we can detect that we're currently running a "check_update" request we might want to give it a few seconds to finish (maybe 10s, then fail), to avoid answering with an error just because the user asked for an update at the wrong time. If we can't or won't do that, then it would be nice that XO retries after a few seconds and only fails if the second try also fails. On XO side, we must also not forget that XO will try to update all hosts of the pool, so it must be able to react to errors appropriately in the context of multiple hosts too. This part about the "update" requests needs to be discussed with XO team.

**Comment by stormi** [comment]
This needs to be backported to 7.6 too.

**Comment by nraynaud** [comment]
should we use a PID file?
