### ISSUE TITLE
Not detecting disks

### ISSUE THREAD

**Issue by marcotuna** [xcp-ng/xcp#22]
Hello,
I am trying to install XCP-NG on a HP Gen 8 with a B320i Raid Controller however it seems that it is not detecting the Hard Disk Drives.

![xcp-ng](https://user-images.githubusercontent.com/6924105/38460764-68441160-3ab8-11e8-81c3-e9cc8b6eac58.png)

Any help is appreciated, thanks!

**Comment by olivierlambert** [comment]
What's the disk space do you have?

**Comment by marcotuna** [comment]
Previously I have/had VMware ESXI 6.5 U1 with only one VM occupying 100 GB from a total of 2 TB Mirror

**Comment by olivierlambert** [comment]
IIRC, XS/XCP need at 50GiB of free space to work, do you have this free space available somewhere?

**Comment by marcotuna** [comment]
Yes, I have. I am trying to install this on bare metal. Should I previously format my logical volume with gparted or something else? What is the recommended file system? EXT4?

**Comment by olivierlambert** [comment]
Nothing to format no, it's likely the disks aren't detected then. You should have the same result with XenServer, can you check it quickly? Also, you should google a bit for Xenserver and B320i support, maybe you'll find something :)

**Comment by marcotuna** [comment]
I tried the latest Xen Server 7.4.0 and I have the same issue.
I've been reading regarding this subject and it seems that the B320i Raid Controller Driver is Closed Source
I will try to search a little further on HP website and foruns.

**Comment by marcotuna** [comment]
I found a way to kind of "solve" the problem. Instead of using Hardware Raid I had to disable the Raid Card in the BIOS.
According to this link: https://access.redhat.com/articles/118133
The installation finished and the disks were detected individually. Now I am having troubles booting the system. I will try to install XCP-NG on a Flash Drive and if supported I will try to create a software raid on the disks.

**Comment by olivierlambert** [comment]
You can install it on one disk, then use mdadm. Flash drive will die quickly due to how fast logs are written.

**Comment by borzel** [comment]
@marcotuna maybe a starting point for you: https://discussions.citrix.com/topic/378478-xenserver-7-raid1-mdadm-after-install-running-system/

I did build XenServers with mdadm at work, but it was a pain if you updated it with the iso, because the installer is not aware of mdraid.

This changes now with XCP-ng, because you simply use `yum upgrade` from inside the os :-)

**Comment by stormi** [comment]
We released an updated installer that has software RAID 1 support. I'm closing this issue since the original problem has been solved (undetected disks)
