### ISSUE TITLE
Deploying Web Panel not Working

### ISSUE THREAD

**Issue by hughesjs** [xcp-ng/xcp#222]
So I'm trying to deploy the web management VM using this command:

`bash -c "$(curl -s http://xoa.io/deploy)"`

It seems to run fine but when I go to the IP address I assigned it from another machine there's nothing there, it doesn't respond to pings and the management console says there are no VMs running.

I've tried assigning it both the same IP as the server itself and a different IP, neither seems to work.

Please advise.

**Comment by nagilum99** [comment]
I never tried that, but from a short look at the script (Just open the URL in a webbrowser): It deploys a VM.
If you give it the sam IP as your server, your stuff colapses/ends up in an undefined, very broken, state.

Also: Did you check if the VM is up and running? Check via console what's up?

**Comment by nagilum99** [comment]
As you closed the issue while I was checking your problem: It's good behaviour if you give a reason for close (e.g. what you did wrong/what fixed it)

**Comment by hughesjs** [comment]
@nagilum99 I then tried assigning it a different IP to the server and it made no difference. 

As stated in my OP, no VMs seem to get launched.

My bad, I closed the issue because I'm just going back to PVE for now as I'm having too many issues with xcp-ng.

**Comment by hughesjs** [comment]
That being said... I've changed my mind so I'm reopening this. Sorry for messing you around dude.

**Comment by borzel** [comment]
@hughesjs have you set a default SR? Without the script is known to fail.

**Comment by olivierlambert** [comment]
Please use our web deploy solution instead of deploy script: http://xen-orchestra.com/#!/xoa

It's far easier, and you have a SR and network choice if needed.

**Comment by stormi** [comment]
Closing, if someone has a similar problem in the future they can still reopen.
