### ISSUE TITLE
Allow yum to fallback to a mirror if mirrorbits is down

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#225]
If for some reason our mirrorbits instance is down, it would be good that yum has a fallback mirror that it can contact directly, bypassing mirrorbits altogether until the issue is solved.

**Comment by stormi** [comment]
So, after asking around and testing, here's how I see things:

* Add the fallback mirror at the end of baseurl
* Either disable the fastestmirror altogether or just exclude the fallback mirror from its configuration, which will make it not select it unless there's no mirror left. Exactly what we want! If we leave fastestmirror enabled, the benefit is that it can exclude the main mirror automatically if it doesn't answer, thus avoiding error messages. The drawback is that it will keep using the fallback mirror until the next time that it refreshes its cache.

I favour leaving fastestmirror enabled and use the exclusion mechanism.

**Comment by olivierlambert** [comment]
Indeed, excluding seems a good option :)
