### ISSUE TITLE
Update url in README.txt for windows guest tools

### ISSUE THREAD

**Issue by unusual-aspect** [xcp-ng/xcp#231]
Current:
https://github.com/xcp-ng/xcp/issues/23
To: 
https://github.com/xcp-ng/xcp/issues/181

**Comment by stormi** [comment]
I add some trouble understanding without the context, but now I get it. I'll fix that, thanks.

**Comment by stormi** [comment]
Meanwhile I have updated #23

**Comment by stormi** [comment]
I have modified the README so that it is more future-proof... I hope.

https://github.com/xcp-ng/xcp-ng-specs/commit/da515cc140b3d9aa4f2ba47059996cbdb92e2a72

**Comment by stormi** [comment]
Updated package pushed to 8.0 base repository and to 7.6 testing.
