### ISSUE TITLE
[Critical] Latest yum update on XCP-ng 7.6 breaks scsi tape devices

### ISSUE THREAD

**Issue by user-72632** [xcp-ng/xcp#232]
I have two separate Supermicro servers that have been using PCI passthrough 
successfully for years using XenServer and now XCP-ng. One host uses an Adaptec 
while another uses a LSI SCSI card. This production setup has been flawless for 
years with both servers running CentOS VMs using the passed through SCSI cards
directly with the Bareos backup software to access two separate Tape Autoloader
devices. 

After this latest yum update and reboot, access to the both Tape Autoloaders shows
unrecoverable robotics errors resulting in bricked devices. Clearly, something has 
changed resulting in these errors. One of the Autoloaders has already been RMA'd 
and replaced while the other unfortunately is too old for servicing so it is 
permanently bricked.

In the past, just prior to updating XenServer, all VM's were evacuated from the host.
Perhaps there is a valid hardware reason for this after all (especially with pass
through devices). In future, I will no longer leave any VMs running on the host that 
is about to have a yum update. I am still investigating the cause of this but this 
feels like erroneous or probing SCSI commands were sent to the autoloaders in error 
as a result of "sm" and "rawhba" updates. I can't be certain as I am still investigating. 

Below is the yum changes from the yum.log during this update. I have marked the
likely suspects that may be causing the problems. 

Jul 07 13:46:30 Updated: 2:microcode_ctl-2.1-26.xs5.1.xcpng.x86_64
Jul 07 13:46:30 Updated: conversion-plugin-8.0.0-1.1.noarch
Jul 07 13:46:31 Updated: sm-1.25.0-1.0.3.el7.centos.x86_64            <<== likely suspects
Jul 07 13:46:31 Installed: xcp-ng-generic-lib-1.1.1-1.xcpng.x86_64
Jul 07 13:46:31 Updated: vendor-update-keys-1.3.6-1.1.noarch
Jul 07 13:46:31 Installed: xcp-ng-xapi-plugins-1.4.0-1.xcpng.noarch
Jul 07 13:46:31 Updated: sm-rawhba-1.25.0-1.0.3.el7.centos.x86_64     <<== likely suspects
Jul 07 13:46:32 Updated: xapi-tests-1.110.1-1.7.xcpng.x86_64
Jul 07 13:46:32 Updated: xcp-ng-deps-7.6.0-5.noarch
Jul 07 13:46:33 Updated: xcp-emu-manager-1.1.2-1.xcpng.x86_64
Jul 07 13:46:33 Updated: xapi-xe-1.110.1-1.7.xcpng.x86_64
Jul 07 13:46:41 Updated: xapi-core-1.110.1-1.7.xcpng.x86_64
Jul 07 13:46:41 Erased: xcp-ng-updater-1.1.0-3.noarch

I am still looking through the source to see what may be wrong but now I am very concerned 
that during another reboot, will this start another round of strange SCSI initialization that 
breaks the autoloaders robotics once again. This is because I can't be positive if the SCSI 
commands or scanning operations are not occurring directly from the dom0 kernel or the domU 
kernel. If the former, then shutting down the VM before updating will have no affect on this 
outcome. I also feel that downgrading would do nothing as the damage has already been done and would likely happen again if I were to re-install the updates!

In the meantime, I would revisit the notion about running yum updates in situ and with live VMs 
on a host. Or, at the very least, discuss warnings for users who are passing through hardware devices prior to an update until this has been resolved. As an aside, I have been using this technology since before Citrix bought XenSource; therefore, I am not new to this.

I hope this helps someone else.

**Comment by stormi** [comment]
Thanks for the report. It looks like we'll need to be extra careful about sm / sm-rawhba updates. I'll try to check the update process to see if it's running scripts or anything. I'm sorry that it bricked one of your devices :/
Do you have a way to do tests if we were to produce update candidates, without bricking other devices?
Keep us posted with the results of your investigations!

**Comment by user-72632** [comment]
Thanks for the sympathetic ear; I wish that could help my two bricked autoloaders.
I do blame myself for not turning these devices off and taking the VMs offline. You
guys have been doing so well with the integration, I did not feel it necessary. Besides,
who would think an update would touch a SCSI channel like this anyway.

As far as my investigations go, I have checked the SMlog at about the time of the
issue and it does appear that the vdi was touched during that. I just am not sure if
it was a normally access or not. I am also still looking through some of the higher
level pyton driver code to see if anything has changed.

I noticed that when you first mentioned the testing updates, they appeared here: 
https://xcp-ng.org/forum/topic/365/updates-announcements-and-testing/21

You mentioned that the updates were by a third party contributor and that they only
affected NFS 4.1. I wonder if any SCSI aspects were changed as part of that update.
Is it possible for you to reach out to the parties involved to rule out any of that?

As far as providing a system under test for this situation, this is highly unlikely
as it is a production setup. As mentioned, this process broke two devices. One has
been RMA'd/replaced and the other is permanently bricked due to age. We cannot afford
to lose the one that has been fixed as it provides access to years of storage and only
a small subset has been replicated in the cloud.

If I were currently onsite, I might be inclined to setup a hardware SCSI capture
to the bricked device to see what commands are being sent. However, I can only access
these systems remotely at the moment. Hence, this is why I am looking into non-intrusive
developments.

I am also liaising with the tape drive companies as I have sent them dumps and trace logs during the update issues. They may send a response but it is doubtful now that the device has been replaced.

Will try to keep you informed. Please do the same on this thread if you hear anymore as
any immediate upgrade to XCP-ng 8.0 has been postponed.

**Comment by stormi** [comment]
I am pretty sure that nothing was changed regarding SCSI. You can check the patch here in case I missed something, though: https://github.com/xcp-ng-rpms/sm/tree/7.6/SOURCES

However there may be scripts (from Citrix) that are run automatically each time the `sm` or `sm-rawhba` (built from the same sources and RPM spec file) is updated. For example, I see [here](https://github.com/xcp-ng-rpms/sm/blob/7.6/SPECS/sm.spec#L42) that the sm-multipath service is started after the `sm` RPM is either installed or updated (%post is executed in both cases, unless there's a condition in the script to differentiate between those two operations). 

Could `service sm-multipath start` be what sends probing SCSI commands?

**Comment by user-72632** [comment]
Thanks for the multipath reference. It looks like the multipath operations force the creation of multipath devices on all SCSI devices it finds if the configuration variable find_multipaths is set to yes in /etc/multipath.conf, which it is by default in XCP-ng. This auto creation can be disabled on devices that are blacklisted in the configuration file. The default devices that are blacklisted do not include /dev/sgX devices which are the dom0 kernel device nodes for the SCSI tape devices. The only thing I can see at this point then is that during the update, the creation of multipath devices happens thereby sending strange commands to the /dev/sgX devices. The SCSI devices clearly do not know what to make of them. This is only speculation, but I wonder if we blacklisted the sg devices in multipath.conf, if that would stop the errant initialization in the blacklist something like:
.....
        devnode "^sg[0-9]*"
.....

Sources: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/dm_multipath/ignore_localdisk_procedure

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/dm_multipath/config_file_defaults

**Comment by stormi** [comment]
This is definitely an interesting lead. I have no idea how to test at the moment, though. Maybe someone from the community can help. We'll also create a bug report for Citrix Hypervisor which is equally affected.

**Comment by stormi** [comment]
I have added a warning in the official documentation: https://github.com/xcp-ng/xcp/wiki/Updates-Howto#precautions

**Comment by stormi** [comment]
I opened https://bugs.xenserver.org/browse/XSO-958

**Comment by rjt** [comment]
Your backup system is broke... ouch.

There have been many changes to lvm.conf from RedHat in the last year or
so.  Diffing lvm.conf vs lvm.conf.rpmnew
might lead to some clues.

I use the global_filter option to blacklist drives from _lvm_ , its in
/etc/lvm/lvm.conf

Device mapper ignores any drives in this list and these are drives i pass
thru for direct vm access.  Also edit lvm.conf on out storage server, so it
does not try to use those drives locally.

You probably know all that and already do that anyway.

Best of luck.

**Comment by stormi** [comment]
> I opened https://bugs.xenserver.org/browse/XSO-958

Someone from Citrix answered and closed the report as Not a bug. Apparently the sm-multipath service is not what caused the SCSI activity.

**Comment by user-72632** [comment]
Thanks @stormi for all the follow-up. I think placing the warning text in the Wiki when updating will at least highlight the need for caution if users have pass through devices. I know I will approach yum updates differently for now on....
