### ISSUE TITLE
VM migration leave host in bad state after completion

### ISSUE THREAD

**Issue by benjamreis** [xcp-ng/xcp#234]
Citrix ticket: https://bugs.xenserver.org/browse/XSO-959

When migrating a VM from an host to another using `migrate_send` API, the migrate task is never cleaned from the host's `current-operations` even though the migration is finished.
Only a toolstack restart allows to remove the ghost operation.

**Comment by stormi** [comment]
This commit looks like a potential fix: https://github.com/xapi-project/xen-api/commit/e7358e0180153d3a55e7480cc6e24abfc5a36f0b

**Comment by stormi** [comment]
Fixed in 8.1
