### ISSUE TITLE
Change/improve update mechanism for xcp-server

### ISSUE THREAD

**Issue by blu-IT** [xcp-ng/xcp#237]
Hello,

when updating a XEN / XCP-server with XENCenter / XCPCenter via VPN the packages are:

- **first** downloaded to my local laptop with XENCenter / XCPCenter
- **then** uploaded to the XEN / XCP-server

So the packages are **sent twice** over a VPN-connection and if it is also a slow connection, you loose a lot of time.

I would prefer that selected updates via XENCenter / XCPCenter are downloaded **directly from XEN / XCP-server (e.g. with wget) to itself.**

Regards

**Comment by olivierlambert** [comment]
I'm not sure about what you are talking about. There's only `yum` to update package, and these updates are exposed through a XAPI plugin (hence you can update via Xen Orchestra).

I'm not aware of any update mechanism available in XCP-ng Center for now

**Comment by blu-IT** [comment]
@oliverlambert 

Oh, I'm sorry! I was working with XEN Center and the mechanism there is described as above. I was guessing, that this is the way also XCP-Center works. But now I see there is no "Tools -> Install Updates" entry...

**Comment by borzel** [comment]
> But now I see there is no "Tools -> Install Updates" entry...

This is on purpose ;-)
