### ISSUE TITLE
xcp-ng SR_BACKEND_FAILURE_181

### ISSUE THREAD

**Issue by marcos0ps** [xcp-ng/xcp#240]
cat xensource.log | grep SR_BACKEND_FAILURE_181

xapi: [error|sp4-01-fd99vw2|7087 UNIX /var/lib/xcp/xapi||backtrace] Raised Server_error(SR_BACKEND_FAILURE_181, [ ; Error in Metadata volume operation for SR. [opterr=Error introducing Metadata Volume: Input/output error];  ])

**Comment by borzel** [comment]
Please add more details and at least ask a question :-)

**Comment by marcos0ps** [comment]
i'm creating a new volume for xcp
xe sr-create type=lvm content-type=user device-config:device=/dev/sdb1 name-label=StorageGeral shared=false

After I create, I try to create a disk for a machine and give me this error.
SR_BACKEND_FAILURE_181

xe sr-list

uuid ( RO)                : bd8037b8-a644-5bfe-79dc-65e83a05e439
          name-label ( RW): StorageGeral
    name-description ( RW): 
                host ( RO): xyz
                type ( RO): lvm
        content-type ( RO): user

xe pbd-list sr-uuid=bd8037b8-a644-5bfe-79dc-65e83a05e439
uuid ( RO)                  : 38a305bb-3e43-e171-8d4b-91f6d76c4ed9
             host-uuid ( RO): 4560aebe-88c3-44c8-9e64-fd4610da3942
               sr-uuid ( RO): bd8037b8-a644-5bfe-79dc-65e83a05e439
         device-config (MRO): device: /dev/sdb1
    currently-attached ( RO): false

 xe pbd-plug uuid=38a305bb-3e43-e171-8d4b-91f6d76c4ed9

Error code: SR_BACKEND_FAILURE_181
Error parameters: , Error in Metadata volume operation for SR. [opterr=Error introducing Metadata Volume: Input/output error],

**Comment by olivierlambert** [comment]
I think this isn't the right place to discuss this. It's probably a configuration problem and not a bug *per se*. Please ask on https://xcp-ng.org/forum :smile:

**Comment by marcos0ps** [comment]
thanks
