### ISSUE TITLE
xcp web interface - sometimes http sometimes https

### ISSUE THREAD

**Issue by akurzawa** [xcp-ng/xcp#250]
Hi

:very low priority: - just to check.

as in topic - on few servers after getting to ip address of xcp the http or https page is loading, on some server http is redirecting to https, on some server landing page stays on http

**Comment by olivierlambert** [comment]
I'm not aware about any automated HTTPS redirection. @stormi ?

**Comment by akurzawa** [comment]
I'm wondering if that is not a Chrome browser "thing"

**Comment by stormi** [comment]
I don't think there's anything that redirects to HTTPS on our side.
