### ISSUE TITLE
Bug: Upgrade from 7.6 to 8.0 lost /etc/hosts edits

### ISSUE THREAD

**Issue by Slugger** [xcp-ng/xcp#251]
Just completed an upgrade of a prod pool.  Basically no issues except that the upgrade overwrote my /etc/hosts file on all hosts which then caused problems connecting to nfs storage on reboot.  Once I replace the entries all was good.  But /etc/hosts should be preserved during an upgrade scenario.

**Comment by stormi** [comment]
Hi. As noted in https://github.com/xcp-ng/xcp/wiki/Upgrade-Howto#using-the-installation-iso-recommended the upgrade process does not keep manual changes made to the domain controller. You can copy them back after the upgrade from the backup partition (`/dev/sda2` usually).
