### ISSUE TITLE
Cannot authenticate XCP-NG hosts to the network using 802.1x

### ISSUE THREAD

**Issue by CorruptComputer** [xcp-ng/xcp#252]
We use PEAP authentication as a requirement of all devices which access the network. I have been scratching my head to try to get XCP-NG to connect to the network, even tried to install wpa_supplicant via my mobile data connection, however the package isn't available in your repositories. 

Is there something I'm doing wrong here, or is this just not supported? If the case is the latter I would love to see some support for it.

**Comment by stormi** [comment]
Hi. Wireless connection is not common in datacenters as far as I know, so it is possible that it is not supported, depending on how the kernel was built. I've seen discussion about wireless in the forum so that's where I would start to get help: https://xcp-ng.org/forum/

**Comment by CorruptComputer** [comment]
I am not setting it up over wireless, this would be a wired connection. However I am not able to authenticate with the network because the wpa_supplicant package is not available.

**Comment by stormi** [comment]
Ok, I associated wpa_supplicant with wireless but I was wrong :)

I think you may be the first to raise this use case, so indeed the package is not available in the repositories. I'll consider adding it.

**Comment by stormi** [comment]
I have imported it from CentOS into the testing repository for XCP-ng 8.0. You can install it with `yum install wpa_supplicant --enablerepo=xcp-ng-testing`. Please keep us posted.

**Comment by CorruptComputer** [comment]
That seems to be working, I am able to auth with it now. I think it would be nice to have it available out of the box so I don't need to use my cells mobile tethering, but I would imagine its a niche thing and most people won't use it. Thanks!

**Comment by stormi** [comment]
I have moved the package to the updates repository so that people can install it with `yum install wpa_supplicant`.

**Comment by CorruptComputer** [comment]
Sweet, thank you!
