### ISSUE TITLE
BlkDiscard Nolonger Supported on XCP-NG 8.0

### ISSUE THREAD

**Issue by prowebuk** [xcp-ng/xcp#253]
Since upgrading a pool to XCP-NG 8.0, I'm no longer able to reclaim freed space from my thin provisioned LVoHBA volumes with the following error:

lkdiscard: /dev/VG_XenStorage-7a3660c4-aa65-756e-d244-d6b8fdd902a2/7a3660c4-aa65-756e-d244-d6b8fdd902a2_trim_lv: BLKDISCARD ioctl failed: Operation not supported

Aug  5 16:11:37 pw-xcp-3 SM: [5832] do_trim: {'sr_uuid': '7c45b277-8d4a-0240-684c-44a721edba1d'}
Aug  5 16:11:37 pw-xcp-3 SM: [5832] lock: opening lock file /var/lock/sm/7c45b277-8d4a-0240-684c-44a721edba1d/sr
Aug  5 16:11:37 pw-xcp-3 SM: [5832] lock: tried lock /var/lock/sm/7c45b277-8d4a-0240-684c-44a721edba1d/sr, acquired: True (exists: True)
Aug  5 16:11:37 pw-xcp-3 SM: [5832] ['/sbin/lvs', '--noheadings', '/dev/VG_XenStorage-7c45b277-8d4a-0240-684c-44a721edba1d/7c45b277-8d4a-0240-684c-44a721edba1d_trim_lv']
Aug  5 16:11:37 pw-xcp-3 SM: [5832] FAILED in util.pread: (rc 5) stdout: '', stderr: '  Failed to find logical volume "VG_XenStorage-7c45b277-8d4a-0240-684c-44a721edba1d/7c45b277-8d4a-0240-684c-44a721edba1d_trim_lv"
Aug  5 16:11:37 pw-xcp-3 SM: [5832] '
Aug  5 16:11:37 pw-xcp-3 SM: [5832] Ignoring exception for LV check: /dev/VG_XenStorage-7c45b277-8d4a-0240-684c-44a721edba1d/7c45b277-8d4a-0240-684c-44a721edba1d_trim_lv !
Aug  5 16:11:37 pw-xcp-3 SM: [5832] ['/sbin/vgs', '--noheadings', '--nosuffix', '--units', 'b', 'VG_XenStorage-7c45b277-8d4a-0240-684c-44a721edba1d']
Aug  5 16:11:37 pw-xcp-3 SM: [5832]   pread SUCCESS
Aug  5 16:11:37 pw-xcp-3 SM: [5832] ['/sbin/lvcreate', '-n', '7c45b277-8d4a-0240-684c-44a721edba1d_trim_lv', '-l', '100%F', 'VG_XenStorage-7c45b277-8d4a-0240-684c-44a721edba1d', '-W', 'n']
Aug  5 16:11:37 pw-xcp-3 SM: [5832]   pread SUCCESS
Aug  5 16:11:37 pw-xcp-3 SM: [5832] ['/usr/sbin/blkdiscard', '-v', '/dev/VG_XenStorage-7c45b277-8d4a-0240-684c-44a721edba1d/7c45b277-8d4a-0240-684c-44a721edba1d_trim_lv']
Aug  5 16:11:38 pw-xcp-3 SM: [5891] Matched SCSIid, updating 3600c0ff0003b55faacf03f5d0100000

The scsi disks appear support unmap and space reclaim was ok in XCP 7.6

cat /sys/class/scsi_disk/5:0:3:1/provisioning_mode
unmap

cat /sys/class/scsi_disk/5:0:3:1/thin_provisioning
1

lsblk -S -D

NAME HCTL       TYPE VENDOR   MODEL             REV TRAN NAME DISC-ALN DISC-GRAN DISC-MAX DISC-ZERO
sdg  5:0:3:1    disk HPE      MSA 2050 SAN     V270 fc   sdg         0       32M       1G         0

Grateful for any idea's of where to go next?

**Comment by stormi** [comment]
Any chance you could test with CH 8.0 to see if it is specific to XCP-ng or not?

**Comment by prowebuk** [comment]
Hi Stormi,

Yeah, leave it with me for a few days and I'll have a go

**Comment by prowebuk** [comment]
Hi Stormi,

Works fine on CH 8, took a host our of the XCP pool so same HBA's, infrastructure and san, just provisioned a new volume of the same over committed pool.

Aug  6 13:53:21 pw-xcp-3 SM: [14380] do_trim: {'sr_uuid': 'b03c8944-b9fc-5660-6a59-64a9364729c7'}
Aug  6 13:53:21 pw-xcp-3 SM: [14380] lock: opening lock file /var/lock/sm/b03c8944-b9fc-5660-6a59-64a9364729c7/sr
Aug  6 13:53:21 pw-xcp-3 SM: [14380] lock: tried lock /var/lock/sm/b03c8944-b9fc-5660-6a59-64a9364729c7/sr, acquired: True (exists: True)
Aug  6 13:53:21 pw-xcp-3 SM: [14380] ['/sbin/lvs', '--noheadings', '/dev/VG_XenStorage-b03c8944-b9fc-5660-6a59-64a9364729c7/b03c8944-b9fc-5660-6a59-64a9364729c7_trim_lv']
Aug  6 13:53:21 pw-xcp-3 SM: [14380] FAILED in util.pread: (rc 5) stdout: '', stderr: '  Failed to find logical volume "VG_XenStorage-b03c8944-b9fc-5660-6a59-64a9364729c7/b03c8944-b9fc-5660-6a59-64a9364729c7_trim_lv"
Aug  6 13:53:21 pw-xcp-3 SM: [14380] '
Aug  6 13:53:21 pw-xcp-3 SM: [14380] Ignoring exception for LV check: /dev/VG_XenStorage-b03c8944-b9fc-5660-6a59-64a9364729c7/b03c8944-b9fc-5660-6a59-64a9364729c7_trim_lv !
Aug  6 13:53:21 pw-xcp-3 SM: [14380] ['/sbin/vgs', '--noheadings', '--nosuffix', '--units', 'b', 'VG_XenStorage-b03c8944-b9fc-5660-6a59-64a9364729c7']
Aug  6 13:53:21 pw-xcp-3 SM: [14380]   pread SUCCESS
Aug  6 13:53:21 pw-xcp-3 SM: [14380] ['/sbin/lvcreate', '-n', 'b03c8944-b9fc-5660-6a59-64a9364729c7_trim_lv', '-l', '100%F', 'VG_XenStorage-b03c8944-b9fc-5660-6a59-64a9364729c7', '-W', 'n']
Aug  6 13:53:21 pw-xcp-3 SM: [14380]   pread SUCCESS
Aug  6 13:53:21 pw-xcp-3 SM: [14380] ['/usr/sbin/blkdiscard', '-v', '/dev/VG_XenStorage-b03c8944-b9fc-5660-6a59-64a9364729c7/b03c8944-b9fc-5660-6a59-64a9364729c7_trim_lv']
Aug  6 13:53:21 pw-xcp-3 SM: [14380]   pread SUCCESS
Aug  6 13:53:21 pw-xcp-3 SM: [14380] Stdout is /dev/VG_XenStorage-b03c8944-b9fc-5660-6a59-64a9364729c7/b03c8944-b9fc-5660-6a59-64a9364729c7_trim_lv: Discarded 99979624448 bytes from the offset 0
Aug  6 13:53:21 pw-xcp-3 SM: [14380]
Aug  6 13:53:21 pw-xcp-3 SM: [14380] Trim on SR: b03c8944-b9fc-5660-6a59-64a9364729c7 complete.
Aug  6 13:53:21 pw-xcp-3 SM: [14380] ['/sbin/lvs', '--noheadings', '/dev/VG_XenStorage-b03c8944-b9fc-5660-6a59-64a9364729c7/b03c8944-b9fc-5660-6a59-64a9364729c7_trim_lv']
Aug  6 13:53:21 pw-xcp-3 SM: [14380]   pread SUCCESS
Aug  6 13:53:21 pw-xcp-3 SM: [14380] ['/sbin/lvremove', '-f', '/dev/VG_XenStorage-b03c8944-b9fc-5660-6a59-64a9364729c7/b03c8944-b9fc-5660-6a59-64a9364729c7_trim_lv']
Aug  6 13:53:21 pw-xcp-3 SM: [14411] Matched SCSIid, updating 3600c0ff0003b116f2f6c495d01000000
Aug  6 13:53:21 pw-xcp-3 SM: [14411] MPATH: Updating entry for [3600c0ff0003b116f2f6c495d01000000], current: [4, 4]
Aug  6 13:53:21 pw-xcp-3 SM: [14411] mpath cmd: show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:21 pw-xcp-3 SM: [14411] mpath output: multipathd> show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:21 pw-xcp-3 SM: [14411] 3600c0ff0003b116f2f6c495d01000000 dm-0 HPE     ,MSA 2050 SAN
Aug  6 13:53:21 pw-xcp-3 SM: [14411] size=93G features='0' hwhandler='0' wp=rw
Aug  6 13:53:21 pw-xcp-3 SM: [14411] |-+- policy='service-time 0' prio=1 status=active
Aug  6 13:53:21 pw-xcp-3 SM: [14411] | `- 4:0:4:0 sdb 8:16 active ready running
Aug  6 13:53:21 pw-xcp-3 SM: [14411] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:21 pw-xcp-3 SM: [14411] | `- 4:0:5:0 sdc 8:32 active ready running
Aug  6 13:53:21 pw-xcp-3 SM: [14411] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:21 pw-xcp-3 SM: [14411] | `- 5:0:1:0 sdd 8:48 active ready running
Aug  6 13:53:21 pw-xcp-3 SM: [14411] `-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:21 pw-xcp-3 SM: [14411]   `- 5:0:5:0 sde 8:64 active ready running
Aug  6 13:53:21 pw-xcp-3 SM: [14411] multipathd>
Aug  6 13:53:21 pw-xcp-3 SM: [14411] mpath cmd: show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:21 pw-xcp-3 SM: [14411] mpath output: multipathd> show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:21 pw-xcp-3 SM: [14411] 3600c0ff0003b116f2f6c495d01000000 dm-0 HPE     ,MSA 2050 SAN
Aug  6 13:53:21 pw-xcp-3 SM: [14411] size=93G features='0' hwhandler='0' wp=rw
Aug  6 13:53:21 pw-xcp-3 SM: [14411] |-+- policy='service-time 0' prio=1 status=active
Aug  6 13:53:21 pw-xcp-3 SM: [14411] | `- 4:0:4:0 sdb 8:16 active ready running
Aug  6 13:53:21 pw-xcp-3 SM: [14411] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:21 pw-xcp-3 SM: [14411] | `- 4:0:5:0 sdc 8:32 active ready running
Aug  6 13:53:21 pw-xcp-3 SM: [14411] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:21 pw-xcp-3 SM: [14411] | `- 5:0:1:0 sdd 8:48 active ready running
Aug  6 13:53:21 pw-xcp-3 SM: [14411] `-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:21 pw-xcp-3 SM: [14411]   `- 5:0:5:0 sde 8:64 active ready running
Aug  6 13:53:21 pw-xcp-3 SM: [14411] multipathd>
Aug  6 13:53:21 pw-xcp-3 SM: [14411] MPATH: Update done
Aug  6 13:53:21 pw-xcp-3 SM: [14380]   pread SUCCESS
Aug  6 13:53:21 pw-xcp-3 SM: [14380] ['/sbin/dmsetup', 'status', 'VG_XenStorage--b03c8944--b9fc--5660--6a59--64a9364729c7-b03c8944--b9fc--5660--6a59--64a9364729c7_trim_lv']
Aug  6 13:53:21 pw-xcp-3 SM: [14380]   pread SUCCESS
Aug  6 13:53:21 pw-xcp-3 SM: [14380] lock: released /var/lock/sm/b03c8944-b9fc-5660-6a59-64a9364729c7/sr
Aug  6 13:53:21 pw-xcp-3 SM: [14380] lock: closed /var/lock/sm/b03c8944-b9fc-5660-6a59-64a9364729c7/sr
Aug  6 13:53:22 pw-xcp-3 SM: [14453] Matched SCSIid, updating 3600c0ff0003b116f2f6c495d01000000
Aug  6 13:53:22 pw-xcp-3 SM: [14453] MPATH: Updating entry for [3600c0ff0003b116f2f6c495d01000000], current: [4, 4]
Aug  6 13:53:22 pw-xcp-3 SM: [14453] mpath cmd: show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:22 pw-xcp-3 SM: [14453] mpath output: multipathd> show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:22 pw-xcp-3 SM: [14453] 3600c0ff0003b116f2f6c495d01000000 dm-0 HPE     ,MSA 2050 SAN
Aug  6 13:53:22 pw-xcp-3 SM: [14453] size=93G features='0' hwhandler='0' wp=rw
Aug  6 13:53:22 pw-xcp-3 SM: [14453] |-+- policy='service-time 0' prio=1 status=active
Aug  6 13:53:22 pw-xcp-3 SM: [14453] | `- 4:0:4:0 sdb 8:16 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14453] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14453] | `- 4:0:5:0 sdc 8:32 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14453] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14453] | `- 5:0:1:0 sdd 8:48 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14453] `-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14453]   `- 5:0:5:0 sde 8:64 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14453] multipathd>
Aug  6 13:53:22 pw-xcp-3 SM: [14453] mpath cmd: show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:22 pw-xcp-3 SM: [14453] mpath output: multipathd> show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:22 pw-xcp-3 SM: [14453] 3600c0ff0003b116f2f6c495d01000000 dm-0 HPE     ,MSA 2050 SAN
Aug  6 13:53:22 pw-xcp-3 SM: [14453] size=93G features='0' hwhandler='0' wp=rw
Aug  6 13:53:22 pw-xcp-3 SM: [14453] |-+- policy='service-time 0' prio=1 status=active
Aug  6 13:53:22 pw-xcp-3 SM: [14453] | `- 4:0:4:0 sdb 8:16 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14453] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14453] | `- 4:0:5:0 sdc 8:32 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14453] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14453] | `- 5:0:1:0 sdd 8:48 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14453] `-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14453]   `- 5:0:5:0 sde 8:64 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14453] multipathd>
Aug  6 13:53:22 pw-xcp-3 SM: [14453] MPATH: Update done
Aug  6 13:53:22 pw-xcp-3 SM: [14489] Matched SCSIid, updating 3600c0ff0003b116f2f6c495d01000000
Aug  6 13:53:22 pw-xcp-3 SM: [14489] MPATH: Updating entry for [3600c0ff0003b116f2f6c495d01000000], current: [4, 4]
Aug  6 13:53:22 pw-xcp-3 SM: [14489] mpath cmd: show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:22 pw-xcp-3 SM: [14489] mpath output: multipathd> show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:22 pw-xcp-3 SM: [14489] 3600c0ff0003b116f2f6c495d01000000 dm-0 HPE     ,MSA 2050 SAN
Aug  6 13:53:22 pw-xcp-3 SM: [14489] size=93G features='0' hwhandler='0' wp=rw
Aug  6 13:53:22 pw-xcp-3 SM: [14489] |-+- policy='service-time 0' prio=1 status=active
Aug  6 13:53:22 pw-xcp-3 SM: [14489] | `- 4:0:4:0 sdb 8:16 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14489] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14489] | `- 4:0:5:0 sdc 8:32 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14489] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14489] | `- 5:0:1:0 sdd 8:48 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14489] `-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14489]   `- 5:0:5:0 sde 8:64 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14489] multipathd>
Aug  6 13:53:22 pw-xcp-3 SM: [14489] mpath cmd: show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:22 pw-xcp-3 SM: [14489] mpath output: multipathd> show map 3600c0ff0003b116f2f6c495d01000000 topology
Aug  6 13:53:22 pw-xcp-3 SM: [14489] 3600c0ff0003b116f2f6c495d01000000 dm-0 HPE     ,MSA 2050 SAN
Aug  6 13:53:22 pw-xcp-3 SM: [14489] size=93G features='0' hwhandler='0' wp=rw
Aug  6 13:53:22 pw-xcp-3 SM: [14489] |-+- policy='service-time 0' prio=1 status=active
Aug  6 13:53:22 pw-xcp-3 SM: [14489] | `- 4:0:4:0 sdb 8:16 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14489] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14489] | `- 4:0:5:0 sdc 8:32 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14489] |-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14489] | `- 5:0:1:0 sdd 8:48 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14489] `-+- policy='service-time 0' prio=1 status=enabled
Aug  6 13:53:22 pw-xcp-3 SM: [14489]   `- 5:0:5:0 sde 8:64 active ready running
Aug  6 13:53:22 pw-xcp-3 SM: [14489] multipathd>
Aug  6 13:53:22 pw-xcp-3 SM: [14489] MPATH: Update done

**Comment by prowebuk** [comment]
And on XCP-NG 8.0 

Aug  6 13:58:06 pw-xcp-2 SM: [12149] do_trim: {'sr_uuid': '5741eae2-5eb1-101c-e059-5f31aa484c16'}
Aug  6 13:58:06 pw-xcp-2 SM: [12149] lock: opening lock file /var/lock/sm/5741eae2-5eb1-101c-e059-5f31aa484c16/sr
Aug  6 13:58:06 pw-xcp-2 SM: [12149] lock: tried lock /var/lock/sm/5741eae2-5eb1-101c-e059-5f31aa484c16/sr, acquired: True (exists: True)
Aug  6 13:58:06 pw-xcp-2 SM: [12149] ['/sbin/lvs', '--noheadings', '/dev/VG_XenStorage-5741eae2-5eb1-101c-e059-5f31aa484c16/5741eae2-5eb1-101c-e059-5f31aa484c16_trim_lv']
Aug  6 13:58:06 pw-xcp-2 SM: [12149] FAILED in util.pread: (rc 5) stdout: '', stderr: '  Failed to find logical volume "VG_XenStorage-5741eae2-5eb1-101c-e059-5f31aa484c16/5741eae2-5eb1-101c-e059-5f31aa484c16_trim_lv"
Aug  6 13:58:06 pw-xcp-2 SM: [12149] '
Aug  6 13:58:06 pw-xcp-2 SM: [12149] Ignoring exception for LV check: /dev/VG_XenStorage-5741eae2-5eb1-101c-e059-5f31aa484c16/5741eae2-5eb1-101c-e059-5f31aa484c16_trim_lv !
Aug  6 13:58:06 pw-xcp-2 SM: [12149] ['/sbin/vgs', '--noheadings', '--nosuffix', '--units', 'b', 'VG_XenStorage-5741eae2-5eb1-101c-e059-5f31aa484c16']
Aug  6 13:58:06 pw-xcp-2 SM: [12149]   pread SUCCESS
Aug  6 13:58:06 pw-xcp-2 SM: [12149] ['/sbin/lvcreate', '-n', '5741eae2-5eb1-101c-e059-5f31aa484c16_trim_lv', '-l', '100%F', 'VG_XenStorage-5741eae2-5eb1-101c-e059-5f31aa484c16', '-W', 'n']
Aug  6 13:58:07 pw-xcp-2 SM: [12149]   pread SUCCESS
Aug  6 13:58:07 pw-xcp-2 SM: [12149] ['/usr/sbin/blkdiscard', '-v', '/dev/VG_XenStorage-5741eae2-5eb1-101c-e059-5f31aa484c16/5741eae2-5eb1-101c-e059-5f31aa484c16_trim_lv']
Aug  6 13:58:07 pw-xcp-2 SM: [12149] FAILED in util.pread: (rc 1) stdout: '', stderr: 'blkdiscard: /dev/VG_XenStorage-5741eae2-5eb1-101c-e059-5f31aa484c16/5741eae2-5eb1-101c-e059-5f31aa484c16_trim_lv: BLKDISCARD ioctl failed: Operation not supported
Aug  6 13:58:07 pw-xcp-2 SM: [12149] '
Aug  6 13:58:07 pw-xcp-2 SM: [12149] ['/sbin/lvs', '--noheadings', '/dev/VG_XenStorage-5741eae2-5eb1-101c-e059-5f31aa484c16/5741eae2-5eb1-101c-e059-5f31aa484c16_trim_lv']
Aug  6 13:58:07 pw-xcp-2 SM: [12149]   pread SUCCESS
Aug  6 13:58:07 pw-xcp-2 SM: [12149] ['/sbin/lvremove', '-f', '/dev/VG_XenStorage-5741eae2-5eb1-101c-e059-5f31aa484c16/5741eae2-5eb1-101c-e059-5f31aa484c16_trim_lv']
Aug  6 13:58:08 pw-xcp-2 SM: [12149]   pread SUCCESS
Aug  6 13:58:08 pw-xcp-2 SM: [12149] ['/sbin/dmsetup', 'status', 'VG_XenStorage--5741eae2--5eb1--101c--e059--5f31aa484c16-5741eae2--5eb1--101c--e059--5f31aa484c16_trim_lv']
Aug  6 13:58:08 pw-xcp-2 SM: [12149]   pread SUCCESS
Aug  6 13:58:08 pw-xcp-2 SM: [12149] lock: released /var/lock/sm/5741eae2-5eb1-101c-e059-5f31aa484c16/sr
Aug  6 13:58:08 pw-xcp-2 SM: [12149] lock: closed /var/lock/sm/5741eae2-5eb1-101c-e059-5f31aa484c16/sr

**Comment by prowebuk** [comment]
Hi Stormi,

Just tested on a stand alone XCP-NG 8 host and reclaim is working fine so must be an issue with a volume

Sorry to waste your time

**Comment by stormi** [comment]
No problem, I like happy endings :)

**Comment by prowebuk** [comment]
FAILED in util.pread: (rc 1) stdout: '', stderr: 'blkdiscard: /dev/VG_XenStorage-7a3660c4-aa65-756e-d244-d6b8fdd902a2/7a3660c4-aa65-756e-d244-d6b8fdd902a2_trim_lv: BLKDISCARD ioctl failed: Operation not supported

**Comment by prowebuk** [comment]
Sort of happy.. reclaim is running on a host 2 but /dev/VG_XenStorage-7a3660c4-aa65-756e-d244-d6b8fdd902a2 doesn't exist on that host, it does exist on host 1 (the master) though

 FAILED in util.pread: (rc 1) stdout: '', stderr: 'blkdiscard: /dev/VG_XenStorage-7a3660c4-aa65-756e-d244-d6b8fdd902a2/7a3660c4-aa65-756e-d244-d6b8fdd902a2_trim_lv: BLKDISCARD ioctl failed: Operation not supported

So wonder why it's trying to run reclaim on host 2?

**Comment by stormi** [comment]
Hi. I have the feeling, months after the last comments, that it is more likely to be a support issue rather than an actual bug. It may be a bug, but we'd know only after investigating through support (be it community support on forum or IRC, or pro support). Thus closing the issue for now.
