### ISSUE TITLE
XCP-ng 8.0.0 installer problem with Software RAID LVM 2 DD of 2 To

### ISSUE THREAD

**Issue by papyWbng31** [xcp-ng/xcp#259]
The installer does not take into account the creation of the RAID1 volume with 2 2 TB disks.
A progress bar should be proposed before moving on to the next screen.

Because of this, the installation of XCP-ng 8.0.0 becomes difficult for a newbiz.

Thanks.

**Comment by papyWbng31** [comment]
With the combination of ALT key and right arrow, I tried to create the matrix raid1 by hand. After having verified by a cat / proc / mdstat the success of the operation with my matrix / dev / md127 active, I returned to the installer (ALT + left arrow). I selected my RAID1 array for installation and continued to the beginning of the installation. Sadly. The installation always falls into error:
Failed to create root filesystem: err: wipefs: error / dev / sda1 probing initialization failed: device or resource busy

**Comment by papyWbng31** [comment]
The installer tells me to restart.
I restart.
And hop Bingo!
The Virtual Machine Storage screen tells me just one option for choosing the disk:

[*] RAID: / dev / md127 (sda, sdb) - 1863 GB [ATA HGST HUS724020AL]

It would be nice if you take the greatest care of the installer. Hoping that my report can help you in this way.

**Comment by olivierlambert** [comment]
Hi,

I'm not sure to understand the issue. Why the RAID creation failed in the first place?

**Comment by nagilum99** [comment]
I guess he doesn't understand/know that the drive is instantly usuable and you can but don't need to wait for a full sync.

**Comment by papyWbng31** [comment]
Hi all

"Why the RAID creation failed in the first place?" Yes. I had to create the raid by hand and reboot for the installer to offer me.

"I guess he doesn't understand/know that the drive is instantly usuable and you can but don't need to wait for a full sync." Yes, I did not understand why the installer did not offer me RAID. That's why I created it by hand then reboot for it to work.

We are at OVH and I install 8.0.0 via an ISO in the JAVA IPMI applet from my workstation. We have a 100 Mbps Internet connection.

Thanks.

**Comment by nagilum99** [comment]
You basically didn't answer any questions that came up. We still only know, that you did it by hand - not what your actual problem was (or what _exactly_ your goal was/is).

**Comment by papyWbng31** [comment]
> You basically didn't answer any questions that came up. We still only know, that you did it by hand - not what your actual problem was (or what _exactly_ your goal was/is).

I am sorry. My goal is that I want to install 8.0.0 with software raid. As the installer proposes. My problem is that the installer does not create my software raid that I ask him, and I do not understand why he does not do it.

English is also difficult for me. I try to be as clear as possible, though.

**Comment by papyWbng31** [comment]
But if there is someone here who understands French, I will be able to better explain my objective and my problem and answer clearly the questions asked ...

**Comment by papyWbng31** [comment]
Example :
> Salut,
> 
> Je ne suis pas sûr de comprendre le problème. Pourquoi la création RAID a-t-elle échoué en premier lieu?

Salut Olivier Lambert. Je ne sais pas pourquoi. J'ai deux disques de 2 To. Lorsque j'arrive à l'écran des disques, je clique sur le bouton du milieu pour créer le raid 1 logiciel. Je selectionne mes deux disques puis appui sur le bouton Créer puis ensuite sur le bouton ok. Quand je passe à l'écran suivant pour l'espace des machines virtuelles, l'installeur ne me propose pas la matrice RAID 1 que j'ai créé. Il me ré-affiche simplement mes deux disques /dev/sda et /dev/sdb. Je ne comprends pas pourquoi il ne me propose pas ma matrice RAID 1 de 1780 Go. 

Pour me sortir de là, je dois créé à la main la matrice RAID 1 puis rebooter la machine. A ce moment, et sans créer de nouveau ma matrice RAID 1 dans l'interface. l'écran pour l'espace des machines virtuelles me propose par magie mon volume RAID 1. Et l'installeur m'installe bien la 8.0.0 aux derniers écrans. Sans cette manip lourde, je suis coincé. Impossible d'installer la 8.0.0 avec du raid logiciel avec LVM.

Nous connaissons une même personne, Olivier. Si tu as un mail à m'indiquer, nous pourrions éventuellement échanger nos téléphones pour communiquer plus efficacement. Je suis sur Toulouse. Merci du temps passé à me consacrer ici.

**Comment by papyWbng31** [comment]
J'ai trouvé ton mail Olivier dans ton profil. Je t'écris un mail, en espérant que cela ne te dérange pas...

**Comment by papyWbng31** [comment]
https://xcp-ng.org/blog/2018/09/21/xcp-ng-new-install-features/

That's my goal :-)

But that does not work for me. The screen titled "Virtual Machine Storage" does not offer me the only choice: RAID

I use ISO: https://updates.xcp-ng.org/isos/8.0/xcp-ng-8.0.0.iso

**Comment by stormi** [comment]
Is there an error visible in the logs console (ALT+right once or twice) when the RAID creation step completes?

**Comment by stormi** [comment]
Closing because we can't debug without feedback. Feel free to reopen if needed.
