### ISSUE TITLE
PCI Pass-Through

### ISSUE THREAD

**Issue by marcusrushy** [xcp-ng/xcp#26]
Followed ths guide https://xenserver.org/blog/entry/pci-pass-through-on-xenserver-7-0.html but cannot get pci pass-through working. Is this a feature that is working or will be working. Thanks

**Comment by olivierlambert** [comment]
Can you be more specific than "cannot get it working"?

**Comment by marcusrushy** [comment]
Yeah sure. I ran lspci to find the SAS card I want to hide from the host. Then ran the command to hide the SAS card and reboot the host. Then when I run lspci the card is still there. I ran the command to attach it to the VM which will be running freenas and it doesn't see the disks attached to the SAS card. I have IOMMU enabled in the bios and passthrough works in esxi free but I don't want to use esxi :-)

**Comment by olivierlambert** [comment]
It's probably not an "issue" that's specific to XCP-ng. You should open a post on XCP-ng forum, maybe you could find some assistance there.

**Comment by marcusrushy** [comment]
I don't think it works in Xen 7.4 either with the guide I followed. I already have opened a post on the forum but I thought I would try here too. Someone has posted something for me to try which I will tonight. Thanks

**Comment by olivierlambert** [comment]
Okay thanks :) Keep us posted! Closing the issue here :+1:

**Comment by olivierlambert** [comment]
I'm a bit surprised that's XCP-ng related. We didn't changed a lot of stuff vs XenServer, except branding and license daemon.

So there it doesn't make sense that's only a XCP-ng problem despite they share 99% of the base code (more or less the logos!)

**Comment by christianuhlmann** [comment]
ok,
i will check this with the fresh citrix xenserver installation and come back with the information if this works or not

**Comment by olivierlambert** [comment]
Thanks!

**Comment by marcusrushy** [comment]
Hi all

Been testing Xen 7.4 and XCP-ng in virtualbox trying to hide a network adapter. It seems that when you run 

opt/xensource/libexec/xen-cmdline --set-dom0 "xen-pciback.hide=(00:08.0)" 

on Xen 7.4 it adds xen-pciback.hide=(00:08.0) to /boot/grub/grub.cfg in 2 areas

menuentry 'XenServer' {

and

menuentry 'XenServer (Serial)' { 

and seems to hides it but when you run it on XCP-ng it only adds it to 1 area

menuentry 'XenServer (Serial)' { 

and not 

menuentry 'XenServer' {

if you manually add xen-pciback.hide=(00:08.0) to the area it is missing from it seems to hide it ok.

I will hopefully test it tonight with my SAS card to see if it works.

Thanks
Mark

**Comment by olivierlambert** [comment]
Thanks for your feedback! So their script maybe use hardcoded entries in Grub.

**Comment by marcusrushy** [comment]
manually adding xen-pciback.hide=(2a:00.0) to /boot/grub/grub.cfg at the end of the first module2 line has worked for hiding the SAS card as when I do an fdisk -l the disks don't show up. now how do I add the SAS card to the vm. the disks don't show up during installation of freenas when I have run . xe vm-param-set other-config:pci=0/0000:2a:00.0 uuid=4<uid>.

**Comment by christianuhlmann** [comment]
hmm sorry, my mistake
My test server has an Intel G3220 installed, that was a lot of work in 2014 until it ran, no idea what it was.
so citrix xenserver definitely is not.
a pity :(
what could that have been on my old debian system with xen project that it has worked?
