### ISSUE TITLE
Extend (ext4) SR by adding new DISK in to VG (stripe)

### ISSUE THREAD

**Issue by Petahh** [xcp-ng/xcp#261]
Hello everyone,
I have ext4 SR configured, 

`
  PV /dev/sdb   VG XSLocalEXT-e723f66c-de28-aae7-e6b8-c4cdfca4812e   lvm2 [298.08 GiB / 0    free]
`

lsblk info,

`
sdb                                                            LVM2_member               vx3qrT-YzgE-g04K-6eOd-QgEX-TfeZ-LClQa0
`
`└─XSLocalEXT--e723f66c--de28--aae7--e6b8--c4cdfca4812e-e723f66c--de28--aae7--e6b8--c4cdfca4812e
`

Configured with help of the command,

`
xe sr-create type=ext4 name-label=EXT4-SR-HDD host-uuid=2a576cf4-cc67-4aae-89ea-03088cb2c9e9 device-config:device=/dev/sdb
`

I would like to extend it with the additional disk `/dev/sdc3`

```
Disk /dev/sdc: 640.1 GB, 640135028736 bytes, 1250263728 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disk label type: gpt

#         Start          End    Size  Type            Name
 1     46139392     83888127     18G  Microsoft basic
 2      8390656     46139391     18G  Microsoft basic
 3     87033856   1250263694  554.7G  Linux LVM <-------------- this one
 4     83888128     84936703    512M  BIOS boot parti
 5         2048      8390655      4G  Microsoft basic
 6     84936704     87033855      1G  Linux swap
```

Or vice versa, both disks are empty, I'm currently looking for a way how to join those two in the stripe to have it a bit faster and bigger.

**Is there any way how to achieve this?**

I have found several articles from XEN:

https://support.citrix.com/article/CTX217668
https://discussions.citrix.com/topic/243057-7-steps-to-easily-resize-a-xenserver-storage-repository/

But I also hear that it's not recommended to mess up with LVM metadata.

I'm using XCP-ng 7.6

Thanks in advance for any bits of advice.

**Comment by olivierlambert** [comment]
If both disks are empty, you could forget the existing SR, and before creating a new one, using manual LVM commands to create a volume group with 2 physical disks (partitions in your case) and then create the SR on top of this VG.

**Comment by stormi** [comment]
Closing because this issue is more about asking advice (prefer the [forum](https://xcp-ng.org/forum/) for that) than a bug.
