### ISSUE TITLE
iSCSI XCP-ng 8.0.0  install fails with no gateway

### ISSUE THREAD

**Issue by gburgert** [xcp-ng/xcp#264]
Im getting this error when installing XCP-ng 8.0.0  in the first steps of install
'global name errno is not defined'

![Screen Shot 2019-07-31 at 18 25 44](https://user-images.githubusercontent.com/38225702/62886328-6a7a3b80-bd11-11e9-8a4b-c3daf4cc28bf.png)
![Screen Shot 2019-08-02 at 11 11 41](https://user-images.githubusercontent.com/38225702/62886333-71a14980-bd11-11e9-87f1-1555c8e09dd5.png)

The problem is this 'if' in opt/xensource/installer/diskutil.py
that runs when there is no gateway configured in  iSCSI interfaces

if e.errno == errno.ENOENT:

 I don't know python and some tests I've made weren't successful, so I did this noob workaround...

```
624 #        try:
625 #            with open(os.path.join(e, 'gateway'), 'r') as f:
626 #                gw = f.read().strip()
627 #        except IOError as e:
628 #            if e.errno == errno.ENOENT:
629 #                gw = None
630 #            else:
631 #                raise
632         gw = <fake IP here>
```
XCP now installs ok, expecting this fake gw only needed for install!

**Comment by gburgert** [comment]
After applying patch I have this error

![Screen Shot 2019-08-30 at 15 20 07](https://user-images.githubusercontent.com/38225702/64043618-44d79980-cb3b-11e9-972b-358d53ab56f9.png)
I can do other tests or provide more info if necessary.

**Comment by stormi** [comment]
Oops, I missed that message. I'll have a look.

**Comment by stormi** [comment]
Okay, you clearly are in a situation that has never been tested, according to me. There's a name conflict on the variable name `e` so everything fails afterwards. Can you try to apply the patch I just committed in addition to the first one?

**Comment by gburgert** [comment]
Its working now. Thank you.

**Comment by stormi** [comment]
Thanks for the test. I'll keep the patches in our repository so they will be included the next time we build installation ISOs.

**Comment by stormi** [comment]
Closing because the fix is in our git repository for the installer, although we haven't produced new installation ISOs yet.
