### ISSUE TITLE
IPsec support in openvswitch

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#266]
We want IPsec support in openvswitch in XCP-ng 7.6 and 8.0.

For this we need to:
* add the IPsec support script and related service to the openvswitch package (or to an openvswitch-ipsec package)
* import the latest libreswan to XCP-ng and add it as a dependency to either openvswitch or openvswitch-ipsec.
* if we do it as an openvswitch-ipsec package, make it installed by default (add it as a dependency to `xcp-ng-deps`)

**Comment by benjamreis** [comment]
https://github.com/xcp-ng-rpms/openvswitch/pull/1

**Comment by stormi** [comment]
The packages are available, but not installed by default in dom0. This is documented in XO docs and a link to it is present in the UI. Closing.
