### ISSUE TITLE
Change Realtek RTL8139 to Intel E1000

### ISSUE THREAD

**Issue by gangsterrapper22** [xcp-ng/xcp#27]
Could you please make the Intel E1000 as default NIC when no PV Drivers are installed? The Intel E1000 NIC can 1GB/s and the Realtek can only do 100Mbit/s. 
For example if you image an Virtual Machine, then this would be a lot faster with the E1000 NIC instead of the Realtek and the E1000 is also compatible with the most OS.

You have to tadd this Line "argv = [arg.replace('rtl8139','e1000') for arg in argv]" to def main(argv): in the File /usr/libexec/xenopsd/qemu-dm-wrapper.

The Section should looke like then:
```
def main(argv):

    argv = [arg.replace('rtl8139','e1000') for arg in argv]
    qemu_env = os.environ
    domid = int(argv[1])
    qemu_dm = qemu_dm_path(domid, argv)
    qemu_args = ['qemu-dm-%d'%domid] + argv[2:]
```
Please check if this can be implemented by default if wanted.

**Comment by dumiller** [comment]
+1 for this. I have some software that requires to E1000 and not having to manually modify the qemu-dm-wrapper would be nice. :) If not default at least and option to enable.

**Comment by olivierlambert** [comment]
Can you tell me which OS isn't compatible with e1000?

**Comment by olivierlambert** [comment]
So, after checking a bit, the rate reported inside the VM isn't "real". The only limiting factor would be Qemu anyway (it's NOT capped at 100Mbits with the realtek thing)

Plus there is an extra flag in "platform" value you can pass since 7.4 that can switch to e1000. I'm checking which one.

**Comment by olivierlambert** [comment]
So you can edit the platform field of VM object and add this key/value: `platform:nic_type=e1000`

**Comment by gangsterrapper22** [comment]
Thanks for checking. Can you tell me in which file the platform value has to be set, that the e1000 can be enabled instead of patching the qemu-dm-wrapper?

**Comment by olivierlambert** [comment]
It's not a file, you need to change it with `xe` CLI for example: `xe vm-param-set platform:nic_type=e1000 uuid=<VM UUID>`

**Comment by gangsterrapper22** [comment]
I have tested you command but it doesn't set the Realtek NIC to the e1000. It still starts with the Realtek.

I did also an iPerf Test which you can see, that it makes an difference if you use the Realtek NIC or the E1000_.

Realtek:
![iperf_realtek](https://user-images.githubusercontent.com/26838368/39083920-29f0c312-456d-11e8-85dc-b4abf88da286.png)
_

e1000
![iperf_e1000](https://user-images.githubusercontent.com/26838368/39083924-3544c4ac-456d-11e8-9289-1c4dfdb8d5e0.PNG)

**Comment by olivierlambert** [comment]
Maybe because it should be a string, please try:

`xe vm-param-set platform:nic_type="e1000" uuid=<VM UUID>`

Also, did you installed PV drivers after your initial benchmark?

**Comment by gangsterrapper22** [comment]
With this command I still get the Realtek and not the e1000.  In this case I didn't install the PV drivers, because then I will only get the PV NIC.

**Comment by dumiller** [comment]
It's not an OS that isn't compatible with e1000 I have an application that requires the e1000 driver and if it sees the rtl8139 nic it will not license properly. The application is at www.exacq.com and called ExacqVision. I have a couple clients that we tried to use Xen and couldn't get it to work due to this so we put it on VMWare as it natively allows you to set the network driver at e1000. Both of those clients would like to move it over to Xen however until it is natively supported through GUI to set this they will not.

[https://exacq.com/kb/#loadAnswer~872dd883-65ad-6832-84e8-56040ecf6bdc](url)

**Comment by randadinata** [comment]
This is nice to have for windows pe based backup recovery bootable isos. Tenants often have their own backup software inside vm eg. Acronis

**Comment by stormi** [comment]
So is there something to do about it in XCP-ng, or is it something that relates more to management interfaces such as Xen Orchestra and XCP-ng Center?

**Comment by olivierlambert** [comment]
It's not related to XCP-ng. BTW, we've exposed the feature in XO. See:

![image](https://user-images.githubusercontent.com/1241401/45894026-7f826f00-bdcd-11e8-8402-330f1558389f.png)

**Comment by olivierlambert** [comment]
We could close the issue, we don't want to have an extra patch to maintain for something like this. But @gangsterrapper22 can try to make a PR and a XSO to get Citrix embed this. Until then, the change on xe/XO is possible :)

**Comment by stormi** [comment]
I agree, I'd rather not change the default before Citrix does, if it does, and the setting is exposed in Xen Orchestra and a similar setting is being worked on for XCP-ng Center. Closing.

**Comment by MaXaMaR** [comment]
When importing VM in XCP-ng Center - Transfer VM is created with network card set to RTL8139 = 12Mbyte/s max recv speed. So needs to be automatically changed to E1000.

**Comment by olivierlambert** [comment]
@MaXaMaR that's not how it works. Emulation is emulation, and the bottleneck is not linked to the NIC model. It's QEMU.

Also we do NOT recommend to use XCP-ng Center, "Transfer VM" is really an ugly piece of hack.

**Comment by MaXaMaR** [comment]
But the speed is almost equal to 100mbps... as @gangsterrapper22 has shown. It's the only way I found to actually import ESXi OVA images.

**Comment by olivierlambert** [comment]
Again, it doesn't work like that. The negotiation speed in the VM **doesn't** limit the transfer. There's just no meaning at all. Even when you have the PV drivers, the virtual NIC is detected at 1Gbit in the OS, but it goes faster than that.

Remember: it's a **virtual** machine.

The bottleneck is the QEMU emulated device, which is really slow. And until you have PV drivers, there's nothing you can do.

**Comment by olivierlambert** [comment]
Also @MaXaMaR you can use Xen Orchestra to import OVA images. Please avoid using XCP-ng Center for that.

**Comment by sarangtc** [comment]
> Can you tell me which OS isn't compatible with e1000?

zeroshell

**Comment by borzel** [comment]
@sarangtc what are you talking about? You can switch to e1000 in XO -> VM -> advanced tab.

**Comment by sarangtc** [comment]
> @sarangtc what are you talking about? You can switch to e1000 in XO -> VM -> advanced tab.

Yes. This has been pointed out. The reply was in answer to which OS doesn't support realtek NIC.

Also, is there a something like e1000 for 10g NIC?

**Comment by olivierlambert** [comment]
There's no point of a 10GiB NIC because it's emulated hardware, meaning a 10Mbit virtual NIC won't limit either. The max speed is the speed of the qemu emulated hardware, which is very slow.

Changing virtual NIC before tools is only here for compatibility reasons (I re-asked about that recently to some Xen/Citrix devs)

**Comment by rushikeshjadhav** [comment]
I was experiencing intermittent kernel crash on RTL. After switching it to e1000, kernel does not crash. e1000 gave almost 20-30% extra & consistent speed than RTL driver. Speed is also related to kernel module which handles the traffic.

The setup is nested XCP-NG and Im using XAPI Host internal network which is not attached to any physical NIC.

**Comment by swchok** [comment]
After reading the threads, can I conclude that as of now, since QEMU is the limiting factor, a 10gbps network card will only work as fast as QEMU, which is probably about... 2gbps?

**Comment by olivierlambert** [comment]
It won't if you install PV drivers in your VM.

**Comment by nagilum99** [comment]
It's new to me, that QEMU statically limits the speed.
AFAIK it depends on the CPU (especially single-thread performance).

For common use, I select less cores/higher frequency models and the benefits of massive cores is very limited in many small/mid environments.

**Comment by ezsolution** [comment]
> Maybe because it should be a string, please try:
> 
> `xe vm-param-set platform:nic_type="e1000" uuid=<VM UUID>`
> 
> Also, did you installed PV drivers after your initial benchmark?

Doing this, works for me on Win SRV 2019 STD. Tnks!
