### ISSUE TITLE
xe sr-scan unable to find disk bus type when specified through /dev/disk/by-id

### ISSUE THREAD

**Issue by woopla** [xcp-ng/xcp#271]
Hello,

I'm using a variant of the disk passthrough article found [here](https://www.zerodispersion.com/xenserver-whole-disk-passthrough/):
```bash
# mkdir /srv/FreeNAS_Disks
# xe sr-create name-label=”FreeNAS_ZFS_Array" name-description=”FreeNAS Disks for the ZFS array" type=udev content-type=disk device-config:location=/srv/FreeNAS_Disks
# ln -s /dev/disk/by-id/ata-WDC_WD20EFRX* /srv/FreeNAS_Disks
# xe sr-scan uuid=7e740535-837f-4e31-41bf-2f3b873aefda
# xe vdi-list sr-uuid=7e740535-837f-4e31-41bf-2f3b873aefda
uuid ( RO)                : ede66d6f-230d-47dc-b98e-27d7b19b0dba
          name-label ( RW): Unrecognised bus type
    name-description ( RW):
             sr-uuid ( RO): 7e740535-837f-4e31-41bf-2f3b873aefda
        virtual-size ( RO): 0
            sharable ( RO): false
           read-only ( RO): false
```

But if if I replace the `ata-WDC_WD20EFRX*` symlinks by symlinks to `/dev/sd?` and re-scan, I'm getting this:
```bash
uuid ( RO)                : 831ae6b4-0c64-4df6-b8a1-686bc9cb4b87
          name-label ( RW): SCSI 5:0:0:0
    name-description ( RW): ATA model WDC WD20EFRX-68E rev 0A80 type 0
             sr-uuid ( RO): 7e740535-837f-4e31-41bf-2f3b873aefda
        virtual-size ( RO): 2000398934016
            sharable ( RO): false
           read-only ( RO): false
```

The `/dev/disk/by-id/` entries are symlinks to `/dev/sd?` devices themselves, so it's pointing to the exact same info.

Any idea what's going on? I'm using 8.0.0, and I want to use the `by-id` entries to get stable names, because `/dev/sd?` entries can be moved around if a new disk is inserted in the machine.

Thanks,

Clément

**Comment by olivierlambert** [comment]
Hi,

This setup is a kind of workaround/hack, so please use the [forum to ask](https://xcp-ng.org/forum), I don't think having a Gtihub issue for this specific setup is relevant.

**Comment by woopla** [comment]
Thanks Olivier. If I ever find the time to work on this, would you accept a PR?

**Comment by olivierlambert** [comment]
I don't remember that disk passthrough is even possible in SMAPIv1. Using `udev` is a hack/workaround. So what kind of PR would you have in mind?

**Comment by woopla** [comment]
OK I just tried to look for info on SMAPIv1, and all I could find was 'SMAPIv1 is undocumented, let's switch to SMAPIv3' :) So I have no idea either.

What I ideally want is a supported way to do whole-disk passthrough in XCP-NG. Would it make sense for me to look in SMAPIv3 docs @ https://xapi-project.github.io/xapi-storage?

**Comment by olivierlambert** [comment]
I don't think there's a way to do so directly, but you can maybe build your own "driver" in SMAPIv3

**Comment by woopla** [comment]
OK guess I'll have to dive into the SMAPIv3 doc then.
