### ISSUE TITLE
3ware 9650SE 3DM2 not working

### ISSUE THREAD

**Issue by arthurfreycobraag** [xcp-ng/xcp#273]
I'm working with an older 3ware RAID-Controller (9650SE). To get notifications about the RAID health, you'll need 3dm2 which is a webinterface. I got it working on XenServer 6.2

But with the newest xcp-ng (8.0) it doesnt seem to be working. No netstat, nothing. Even added it to iptables, but to no avail. Now im questening my sanity.

Attached are strace, configs and other outputs. As well as the used installation files.

[3ware.zip](https://github.com/xcp-ng/xcp/files/3626621/3ware.zip)

**Comment by stormi** [comment]
Sorry for not answering earlier. Actually I should have answered right away that the best place to ask advice for using 3rd party tools on XCP-ng would be the [forum](https://xcp-ng.org/forum/).
