### ISSUE TITLE
PCI passthrough attempt breaks XCP-ng

### ISSUE THREAD

**Issue by woopla** [xcp-ng/xcp#279]
Hello,

I have an Nvidia GTX 1070 that I want to pass through to a Linux VM. While I can set up the passthrough, it completely hoses up XCP-ng - no VMs are starting and `xe` is unable to connect 75% of the time:
```bash
# xe vm-list
Error: Connection refused (calling connect )
```

I cannot start VMs manually with `xe`.

Here are the PCI bus IDs according to `lspci`:
```bash
# lspci | grep -i nvidia
0a:00.0 VGA compatible controller: NVIDIA Corporation GK208B [GeForce GT 710] (rev a1)
0a:00.1 Audio device: NVIDIA Corporation GK208 HDMI/DP Audio Controller (rev a1)
0b:00.0 VGA compatible controller: NVIDIA Corporation GP104 [GeForce GTX 1070] (rev a1)
0b:00.1 Audio device: NVIDIA Corporation GP104 High Definition Audio Controller (rev a1)
```

The `0a:00` device is my VGA console so I want to leave this to XCP-ng. I went ahead and hid the `0b:00` from `dom0`:
```bash
# /opt/xensource/libexec/xen-cmdline --set-dom0 "xen-pciback.hide=(0b:00.0)(0b::00.1)"
```

(BTW I edited the [wiki page on passthrough](https://github.com/xcp-ng/xcp/wiki/PCI-Passtrough) to use `xen-cmdline`, as it sets things properly for BIOS or UEFI depending on your configuration)

And then I rebooted. Upon reboot, I'm getting this message from the kernel:
```
[   2.126177] pciback 0000:0b:00.0: timed out waiting for pending transaction: performing function level reset anyway
```

Which seems to be related to the fact that GPUs do not support the `FLReset+` device capability, and should not be an issue with passthrough, according to documentation I saw somewhere else.

The GPU is available for allocation to VMs though:
```bash
# xl pci-assignable-list
0000:0b:00.0
0000:0b:00.1
```

But since I cannot start VMs it's pretty useless for me to try :) In any case, as soon as I run `/opt/xensource/libexec/xen-cmdline --delete-dom0 "xen-pciback.hide"` and reboot the issue is gone (but I don't have the passthrough set up).

I don't see error messages through `journalctl`, so I don't know what I can do to debug this further and help with a clear error message. Any help is appreciated!

Thanks,

Clément

**Comment by stormi** [comment]
Thanks for your detailed report. I don't know personnally where to go from there, so I suggest to also try the forum to reach our experienced users there, if you haven't already: https://xcp-ng.org/forum/

**Comment by olivierlambert** [comment]
@woopla even if you succeed to passthrough the GPU, Nvidia drivers won't install because of specific checks to avoid running in a virtual machine. Only quadro GPU can be passed to the guest.

**Comment by woopla** [comment]
@olivierlambert I want to use the nouveau driver in Linux anyway so that shouldn't be an issue. What's weird is that in XCP-ng Center, even without the `xen-pciback.hide` setting I can choose to pass that GPU to a VM. Not so with XOA though...

@stormi I'll try the forum, thanks for the suggestion!

**Comment by imtrobin** [comment]
@olivierlambert does it mean u pass throuh 1080 with nvidia drivers installed successfully?

**Comment by olivierlambert** [comment]
No, passthrough worked and the card is visible in the VM. But Nvidia driver won't load because there's a restriction to install driver of consumer grade cards into VMs.

**Comment by imtrobin** [comment]
I see, someone managed to do it, do you have any idea how?

https://gridforums.nvidia.com/default/topic/8934/#

**Comment by 500lb-Bench** [comment]
This doesn't work for NIC passthrough either.

Executing the following causes xcp-ng to break:
/opt/xensource/libexec/xen-cmdline --set-dom0 xen-pciback.hide=(05:00.0)

While this restores it.
/opt/xensource/libexec/xen-cmdline --set-dom0 xen-pciback.hide

**Comment by borzel** [comment]
> [18:17 localhost ~]# /opt/xensource/libexec/xen-cmdline --set-dom0 xen-pciback.hide=(05:00.0)
-bash: syntax error near unexpected token `('

I had the same error last week while i tried to pass-through some PCI-cards. In the end I edidet /boot/grub.cfg by hand (like now described here https://github.com/xcp-ng/xcp/wiki/PCI-Passtrough#2a-known-issue-borzel-26112019)

**Comment by woopla** [comment]
@500lb-Bench  and @borzel you have to put quotes to prevent Bash from interpreting the parentheses:
```bash
/opt/xensource/libexec/xen-cmdline --set-dom0 "xen-pciback.hide=(05:00.0)"
```

**Comment by borzel** [comment]
I removed the workaround from the wiki :-)

**Comment by stormi** [comment]
According to the [forum thread](https://xcp-ng.org/forum/topic/2070/nvidia-gpu-passthrough-attempts-breaks-all-vms) an UEFI BIOS update fixed the original problem.
