### ISSUE TITLE
make command

### ISSUE THREAD

**Issue by HelderFSFerreira** [xcp-ng/xcp#28]
I'm trying to install a drive from an USB NIC , but i can't do the 'make' command.
There is any official repo for installing the gcc from XCP-ng or there is any developer tools avaliable?

The NIC: D-Link dub-1312
Driver [URL](https://media.dlink.eu/ftp/products/dub/dub-1312/driver_software/DUB-1312_drv_revA1_Linux1-14-3_eu_multi_20160818.zip)

Thank you!

**Comment by HelderFSFerreira** [comment]
Thank you for the hint!

I was trying to install the ddk iso using the command line and it didn't work.
This is the ISO that i'm using: [link](http://downloadns.citrix.com.edgesuite.net/10106/XenServer-6.5.0-DDK.iso).

After uploading to the xcp-ng server the iso i tried the following commands:
 - mkdir -p /mnt/tmp
 - mount <path_to_DDK_ISO>/ddk.iso /mnt/tmp –o loop,ro
 - xe vm-import filename=/mnt/tmp/ddk/ova.xml

The mount command "mount /root/XenServer-6.5.0-DDK.iso /mnt/tmp –o loop,ro" outputs [this](http://prntscr.com/j9vypy) and nothing is created on /mnt/tmp.

Is that an incompatibility?

Thank you alot!

**Comment by olivierlambert** [comment]
Please use a more recent DDK (7.x), it should be available as a XVA that you just import.

**Comment by stormi** [comment]
Closing this is neither a but report nor enhancement request. Please use the community forum at https://xcp-ng.org/forum/ if you need more help :)
