### ISSUE TITLE
Dell Poweredge T20 hanging on reboot.

### ISSUE THREAD

**Issue by shymega** [xcp-ng/xcp#286]
Hi,

I've got a Dell Poweredge T20 server I'm running XCP-ng on (I know, I know, its not on the HCL!), and for the most part, I'm very happy with the install, and it works correctly. However, when I reboot the server, it hangs indefinitely on 'Reached shutdown target', and I'm not sure why. Is this a bug?

I can try and get other logs, but as it completely locks up, there's very little I can immediately see.

Thanks.

**Comment by olivierlambert** [comment]
Check your BIOS settings. I think the forum might be a better place to discuss this than GitHub, that we use when we have a more precise idea of what's going on.

**Comment by shymega** [comment]
Alright - I'll post on the forum, and close this for now. If it does appear that it is a bug, I'll reopen it. Thanks.

**Comment by olivierlambert** [comment]
You are welcome, see you on the forum!

**Comment by shymega** [comment]
For those wondering if this was resolved, please see my [post](https://xcp-ng.org/forum/topic/2033/dell-poweredge-t20-hangs-during-shutdown-reboot/11) on the forum (it was resolved!).
