### ISSUE TITLE
CentOS and Intel I219-LM negotiate 10mbit

### ISSUE THREAD

**Issue by astrugatch** [xcp-ng/xcp#287]
As per this redhat bug report there is an issue with the kernel in XCP 8 (CentOS) that causes the Intel I219-LM to negotiate to 10 mbit.

https://bugzilla.redhat.com/show_bug.cgi?id=1627816

**Comment by stormi** [comment]
According to the Fedora bug, you can workaround this with `modprobe -r e1000e; modprobe e1000e`

**Comment by stormi** [comment]
They say 

> The upstream commit is def4ec6dce39 ("e1000e: PCIm function state support")

@rushikeshjadhav do we have a backport of this commit in our latest kernel-alt?

**Comment by rushikeshjadhav** [comment]
Given patch def4ec6dce393e2136b62a05712f35a7fa5f5e56 is against 5.3.x line but I checked that it can be back ported to kernel-alt. I can push it if @astrugatch is waiting or we can wait till it comes to downstream. We can also try and push it to 4.19.x tree but don't know if kernel team will accept the earlyness.

**Comment by rushikeshjadhav** [comment]
Another bug at https://bugzilla.kernel.org/show_bug.cgi?id=205047 shows that this patch may introduce issues for other users.. I think it would be better to have `e1000e-alt` for this specific use case.

**Comment by stormi** [comment]
We're a few months later. Does our latest kernel-alt have the fixes now? (in case kernel.org had included the patches in the 4.19 branch).

**Comment by rushikeshjadhav** [comment]
This is now fixed with `intel-e1000e-alt`. Its still not in kernel-alt or 4.19.x tree.

**Comment by stormi** [comment]
Reopening while testing is ongoing

**Comment by stormi** [comment]
Have we had confirmation that the `intel-e1000e-alt` package fixed the issue?

**Comment by rushikeshjadhav** [comment]
IIRC yes. This has also helped other users for different issue.

**Comment by stormi** [comment]
XCP-ng 8.2 has a newer e1000e driver by default.
