### ISSUE TITLE
Feature Request: memtest in UEFI mode

### ISSUE THREAD

**Issue by nagilum99** [xcp-ng/xcp#288]
I guess it would be a cool idea (maybe also for debugging of running systems!) to add memtest to at least the install medium, so one could just plug the USB-stick/ISO and check the memory.

It's pretty small and I've seen it integrated on some Linux distros - sadly couldn't find it, when I needed it.

**Comment by olivierlambert** [comment]
That's a good idea. We'll study how to do that easily :+1:

**Comment by stormi** [comment]
It's already there :-)
Type F2 to display advanced options. Among them is `memtest`.

**Comment by olivierlambert** [comment]
I even forgot we already got it :man_facepalming:

**Comment by nagilum99** [comment]
Well... that's half-true: I'm not sure if memtest86 doesn't work under UEFI, but at least grub doesn't offer it there. There's also no GUI, just a TUI and no "F2" displayed.

**Comment by stormi** [comment]
Indeed, I had not checked in UEFI mode.

**Comment by bplessis** [comment]
Neither the FOSS Memtest86 version nor the memtest86+ fork are compatible with an UEFI boot (it's legacy 16-bits code while an UEFI boot directly in 32bits)

Memtest86 v8 is compatible with UEFI but not available in an "Open-Source capacity"

**Comment by olivierlambert** [comment]
Pinging @ydirson

**Comment by stormi** [comment]
XCP-ng 8.3 Beta 1 has memtest86+ in UEFI mode in the installer ISO, so this feature request can be closed. Offering a boot entry for memtest86+ from the installed system would be a separate feature request.
