### ISSUE TITLE
Allow to increase `max_grant_frames` for guests

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#289]
Context: the current default value, 32, is too low for some legitimate uses (such as creating more than a certain number of VIFs), see https://xcp-ng.org/forum/topic/2109/error-in-xenopsd

If I understood correctly, previous versions of XCP-ng and XS allowed to raise that value through the `platform/max_grant_frames` VM parameter, but this ability disappeared due to changes in Xen. In order to take them into account again with the version of Xen that XCP-ng 8.0 uses, one needs to patch xenguest.

Update: a patched version of Xen packages is available for testing:
```
yum update xen-dom0-libs xen-dom0-tools xen-hypervisor xen-libs xen-tools --enablerepo=xcp-ng-testing
reboot
```

In order to limit the amount of change on the existing XCP-ng 8.0 installations, we keep 32 as the default value, but we restore the ability to override it through the `platform/max_grant_frames` VM parameter (set it to 64 if 32 is not enough). Default value for `max_maptrack_frames` (which is less likely to be modified by users, but shared the same fates as `max_grant_frames`) remains 1024.

We may choose to set the default value for `platform/max_grant_frames` to 64 if we get enough confidence that it is the best default (the main drawback is a bit of increased memory use).

To change a VM's value for `max_grant_frames` to 64:
```
xe vm-param-set uuid={your_VM_UUID} platform:max_grant_frames=64
```
Then restart the VM.
Then you can search for `max_grant_frames` in `/var/log/daemon.log` to check that the change was applied.

**Comment by stormi** [comment]
We are not sure of the impact if we raised it to 64 for everyone, so I'll keep this in a standby status for now.

**Comment by stormi** [comment]
With @benjamreis we have successfully built `xen` packages whose xenguest now takes the value of `platform:max_grant_frames` into account again

**Comment by stormi** [comment]
Update published: https://xcp-ng.org/blog/2019/11/08/xcp-ng-security-bulletin-november-2019/

**Comment by danieldemoraisgurgel** [comment]
May this functionality be migrated to XCP 8.1

**Comment by stormi** [comment]
We will either retain the functionality in 8.1 or switch to a new way to provide the same level of functionality through other Xen mechanisms, depending on what Citrix did in CH 8.1.
