### ISSUE TITLE
Print list of supported drivers in error messages.

### ISSUE THREAD

**Issue by tomkcpr** [xcp-ng/xcp#290]
When running commands such as these:

```
[19:02 xcpng01 ~]# xe sr-create content-type=user type=glusterfs name-label="xcpnggv" shared=true device-config:server=192.168.0.91:/xcpnggv device-config:backupservers=192.168.0.90 device-config:fetchattempts=2
The SR could not be connected because the driver was not recognised.
driver: glusterfs
[19:02 xcpng01 ~]#
```

The system tells you that the driver isn't supported but doesn't indicate which drivers are. 
 Could the message also indicate a list of supported drivers?  

Cheers,
TK

**Comment by nagilum99** [comment]
As it makes sense to read some documentation about what one is using, I would rather not add the maintenance to this.
If one wants to be that free, he's better off with custom Debian + Xen or alternative solutions.

If you add the drivers here, you'd need a rather complex thing, as depending on the repos you include, the output would vary.

**Comment by tomkcpr** [comment]
Edited it to clarify the ask.

**Comment by olivierlambert** [comment]
This is related on how SMAPIv1 is working. It was created circa 2008, and it's far from being flexible. The only thing you can do to list available driver is to use `xe` CLI autocompletion during `sr-create` command, on `type=`. This should list all the drivers.

This will be far easier with SMAPIv3 which is designed to have "drivers" added dynamically.

**Comment by tomkcpr** [comment]
Thanks both!
