### ISSUE TITLE
boot.log:[ TIME ] Timed out waiting for device dev-mapper-vmsrvg\x2dvmsrlv.device.

### ISSUE THREAD

**Issue by tomkcpr** [xcp-ng/xcp#291]
Created storage as follows:

```
pvcreate /dev/sdb --config global{metadata_read_only=0}
vgcreate vmsrvg /dev/sdb --config global{metadata_read_only=0}
lvcreate -L 128G -n vmsrlv vmsrvg --config global{metadata_read_only=0}
mkfs.xfs /dev/vmsrvg/vmsrlv
xe sr-create content-type=user device-config:device=/dev/disk/by-id/dm-uuid-LVM-pirJM0blfRvI8f65frH3fyN21jA2dqGBQxYeS2RpmAG2gieD7TpaCObO2a1mwHdw host-uuid=c133b4f5-61ab-4f82-b517-854e9277cfcd  name-label="LVM /dev/sdb" shared=false type=lvm
```

This works and is visible in the XCP-ng Center 8.0.1.  Until reboot when this is seen:

boot.log:[ TIME ] Timed out waiting for device dev-mapper-vmsrvg\x2dvmsrlv.device.

And the volume doesn't mount.  Any reason why?

Followed page here to create it:

https://support.citrix.com/article/CTX121313

Cheers,
TK

**Comment by olivierlambert** [comment]
It's not meant to be created like that. You should pass directly a physical device to your SR create: no need to create any pv/vg/lv before. I strongly suggest that you use Xen Orchestra to create your SR, you can't make this mistake.

Also, please try to avoid filling the bug tracker with "usage" requests, the forum is a better place for that (I'm trying to "preserve" XCP-ng developer time on identified bugs here)

**Comment by tomkcpr** [comment]
Apologies.  Thought for a moment this might be a bug.  Feel free to delete this.
