### ISSUE TITLE
All packages needed to build XCP

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#3]
We must get a list of every RPM needed to get from a CentOS to a XCP like.

## Using XS RPMs

XS RPMs are available in the XS ISO install. The only package we need to build ourselves is XAPI in the end. We got them uploaded there: https://cloud.vates.fr/index.php/s/L01f4oWE2qajs3Q

The only notable exception would be XAPI, because we'll use a RPM based on a fork.

## Alternative: "Plain" Xen?

Problem: packaging quality could lead to issues with the rest of the stack.

### Package list

See https://wiki.centos.org/HowTos/Xen/Xen4QuickStart

It's pretty easy:

```
yum install centos-release-xen
yum update
yum install xen
```

Once you reboot, verify that xen is running with `xl info`

## XAPI Toolstack

See issue #1 and #2 for requirements

**Comment by necouchman** [comment]
> Using XS RPMs

We can discuss more, but my opinion is that we should avoid using XS RPMs directly.  If Citrix decides they don't like the fact that we're basically forking XenServer and moving in a different direction, they could shut down those XS repos and make it impossible for us to build if we're relying on those repos/RPMS.  Generating our own "xcp-ng" RPMs (maybe from the XS SRPMS for the time being) seems to be the safest route to go to maintain independence from Citrix and make sure we have a working product moving forward.

**Comment by olivierlambert** [comment]
Yes, but we need a quick way to build XCP-ng ASAP (because we'll probably discover some subtle things).

It doesn't mean we won't use SRPMs then, but remember those SRPMs are also distributed by Citrix.

**Comment by Storycrafter** [comment]
To my mind, the SRPMS are supposed to be there by license requirements (GPL, etc). That doesn't mean they'll be timely, and we may have to even take serious action to have them released after a release update by them. See what Oracle did with "OpenSolaris" after they took it back inhouse.

**Comment by olivierlambert** [comment]
I agree, but I don't see another alternative to get XCP-ng on tracks quickly. Maybe I'm wrong, do you have an idea then?

**Comment by necouchman** [comment]
> See what Oracle did with "OpenSolaris" after they took it back inhouse.

Yes, this is certainly something to keep in mind.

> I agree, but I don't see another alternative to get XCP-ng on tracks quickly. Maybe I'm wrong, do you have an idea then?

I think the initial goal of creating a XS-compatible distribution and getting this pushed out quickly requires that we leverage these SRPMS, and demand them from Citrix, if necessary.  However, looking forward, we should definitely keep OpenSolaris in mind, with an eye toward one of the two possibilities:
- That XCP-ng becomes its own product, a community-driven derivative of XenServer, that then takes on a life of its own, and Citrix and XCP-ng part ways.  (The Solaris/OpenSolaris/Illumos model.)  Eventually we lose compatibility with XenServer, and that's okay.
- That XCP-ng becomes the upstream driver for Citrix's XenServer product, where new features are introduced into XCP-ng and then Citrix pulls those into XenServer as part of their commercial offering.  (The Red Hat model.)  This requires significant buy-in from Citrix.

I think the first one is much more likely, as Citrix has demonstrated what their attitude is toward Open Source software, but we can still hope that they'll come around.  Either way, in my humble opinion, XCP-ng needs to become a community-driven project, not a Citrix-driven project.  So, we leverage SRPMS provided by Citrix to get off the ground, once that's successful we build our own RPMS from the various source repositories without Citrix SRPMS, and then we move on to driving the project with the code and features that we, as a community, want to see.

:-)

**Comment by derrickmehaffy** [comment]
As much as I would like to see the Red Hat model adopted I feel your correct with option 1. Community driven fork of XS.

**Comment by olivierlambert** [comment]
In short term, the first option is not really possible (because we -the community- first need to understand in depth how it works). You can't master a huge piece of various software in few weeks.

But obviously, more we are able to work with it, more we'll have occasions to add our own stuff. **BUT** in the first place, I would like to have our changes merged in upstream. This will avoid to device efforts in 2 things.

If there is no way to have our changes included upstream, I suppose the project will be more and more independent (if the community continue to drive it)

**Comment by stormi** [comment]
Many components are not released in other ways as source RPMs currently, and source RPMs also contain upgrade scripts that are important. We have no short-term means of building everything from other source distributions, not until Citrix opens some repositories to the OSS community.

Closings this issue which was about being able to build XCP-ng, if I understand it correctly.
