### ISSUE TITLE
Cross Server Private Network when all network interfaces are bonded together

### ISSUE THREAD

**Issue by ismo-conguairta** [xcp-ng/xcp#300]
I have all interfaces in bonding and when I try to create a private-network (on XOA-from-the-sources) the only available options are the physical adapter (eth0, eth1, ...). Creating the private-network on ethX interface generates the following error (I can see it in logfile) **XapiError: CANNOT_ADD_TUNNEL_TO_BOND_SLAVE**
It seems, from Citrix documentation, that a bond slave PIF cannot have a tunnel on it. How to proceed in such situation? Any advice?

**Comment by olivierlambert** [comment]
How did you create the tunnel? In modern XO versions, you can't create a tunnel on a bonded network. It's just not possible: XAPI doesn't support that.

**Comment by ismo-conguairta** [comment]
Ok Olivier, indeed in XO I don't see the bond interfaces but only the single interfaces (eth0, eth1, eth2, eth3). The issue comes from that all the ethX interfaces are part of a bond interface (bond0=eth0+eth2, bond1=eth1+eth3). So I try to create a tunnel on eth0 (or eth1, or eth2, or eth3) and the task seems to end successfully. Nevertheless,

- no PIF tunnel was created (in XO->Pool->Network I can see the item name without info about the PIF)
![Screenshot_2019-10-29_17-27-33](https://user-images.githubusercontent.com/3636147/67787922-ae0f5680-fa71-11e9-9e8f-70811de2034a.png)

- the task generates the following error (take a look at the logs)
**XapiError: CANNOT_ADD_TUNNEL_TO_BOND_SLAVE**
[logs.txt](https://github.com/xcp-ng/xcp/files/3784703/logs.txt)

**Comment by benjamreis** [comment]
From https://xapi-project.github.io/xapi/design/bonding-improvements.html:
> It is no longer possible to place a tunnel on a bond slave. The exception CANNOT_ADD_TUNNEL_TO_BOND_SLAVE is raised when trying to do so.

It's not possible to create a tunnel on a bond slave. Xapi won't allow it, I'll change the behavior of the sdn controller to hide the PIF that are bond slaves.

**Comment by benjamreis** [comment]
I'm working on a fix here: https://github.com/vatesfr/xen-orchestra/pull/4633
Thanks for the report!

**Comment by ismo-conguairta** [comment]
You are welcome! It's a pleasure to contribute to the project.

However, I'd like to discuss further on such situation. I don't know if this is the right channel, so feel free to route the conversation wherever you want to. According to my configuration I'm not able to create a cross-private-network with sdn-controller. Is that correct? Don't you think that can be a common configuration and therefore a recurring problem with sdn-controller?
How to proceed over? Any advice? Do I have to revise network configuration?

Thanks for the terrific work that all of you do to build and enhance the solution.

**Comment by benjamreis** [comment]
Thank you :)

We can discuss here. You're correct, you're configuration is incompatible with sdn-controller's private networks. A private network is based on the xapi object `tunnel`. A tunnel is a link between a physical PIF (ie ethX) and a virtual PIF used by the private networks.
By Xapi design tunnel can only be created on physical pif with an ip configuration and the pif must not be a bond slave nor in a sr-iov network. So our hands are tied.

I'm don't know if your configuration is current or not so I can't tell if a lot a people can't use the sdn-controller. I know about several people who use it. 

Would that be a problem in your configuration to reserve a physical PIF for a private networks (you can create several tunnels on a single pif) and put the others in a bond?

**Comment by benjamreis** [comment]
Since the fix has been merged, i'll close the issue.
Do not hesitate top open  ticket on [our forum](https://xcp-ng.org/forum/category/12/xen-orchestra) to continue the discussion. :)

**Comment by ismo-conguairta** [comment]
In my test configuration, I have a 2-host-pool  with 2 OPNsense VMs in HA that act as firewall/gateway for all other VMs. The first bond interface is for Management and for all VLANs (LAN in general), while the second one is for WAN traffic. The interfaces are all configured as bond slaves in order to achieve the fault-tolerance. So the question I asked my self is: with a private cross-server-network based on a physical PIF how can you guarantee the fault tolerance?

**Comment by ismo-conguairta** [comment]
> How did you create the tunnel? In modern XO versions, you can't create a tunnel on a bonded network. It's just not possible: XAPI doesn't support that.

@olivierlambert However, It seems that DVSC allows to create a cross-private-network (then a tunnel interface) on Management interface (that is built on a bond network). How is it possible?

**Comment by olivierlambert** [comment]
I have no idea. @benjamreis have we tried to create the tunnel on top of a bond? (not a PIF inside the bond)

**Comment by benjamreis** [comment]
From https://xapi-project.github.io/xapi/design/tunnelling.html
> Tunnels can only exist on top of physical/VLAN/Bond PIFs

I might be possible indeed. I'll take a look.

**Comment by bvitnik** [comment]
+1 for tunnels over bonds. We are also relying heavily on bonds for high availabiloty.

**Comment by olivierlambert** [comment]
I'll let decide @benjamreis if we reopen this issue or if we create a new one with the new specification (tunnels on top of bonds)

**Comment by benjamreis** [comment]
I didn't open a new issue but the feature is implemented [here](https://github.com/vatesfr/xen-orchestra/pull/4682/).
