### ISSUE TITLE
November 2019 security update

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#302]
Following [this advisory](https://support.citrix.com/article/CTX263477) from Citrix, we built update candidates for XCP-ng 8.0 and 7.6.

We will release them to everyone only once they have received sufficient testing, both internal and from users, so everyone's help is welcome, as fast as possible so that we can release it quickly (a few days).

They are mainly related to the following advisories from the Xen project:
- [XSA-296](http://xenbits.xen.org/xsa/advisory-296.html)
- [XSA-298](http://xenbits.xen.org/xsa/advisory-298.html)
- [XSA-299](http://xenbits.xen.org/xsa/advisory-299.html)
- [XSA-302](http://xenbits.xen.org/xsa/advisory-302.html)

### What to test
Mainly that nothing breaks.

### Install on XCP-ng 8.0
```
yum update xapi-core xapi-tests xapi-xe xen-dom0-libs xen-dom0-tools xen-hypervisor xen-libs xen-tools xenopsd xenopsd-xc --enablerepo=xcp-ng-testing
```
And reboot.

### Install on XCP-ng 7.6
```
yum update xen-dom0-libs xen-dom0-tools xen-hypervisor xen-libs xen-tools xenopsd xenopsd-xc xenopsd-xenlight --enablerepo=xcp-ng-updates_testing
```
And reboot.

### Feedback
Please provide your feedback through comments to this github issue.

**Comment by stormi** [comment]
Last chance to test before I release them based only on our internal testing.

**Comment by HeMaN-NL** [comment]
Installed it on my xcp-ng 8.0.0 homelab
Rebooted, noticed no problems or errors in normal way of operation here
Did not specifically test for the vulnerabilities.

**Comment by stormi** [comment]
Thanks!

**Comment by stormi** [comment]
Updates published: https://xcp-ng.org/blog/2019/11/08/xcp-ng-security-bulletin-november-2019/

**Comment by nikade87** [comment]
Installed it on my homelab running 8.0, so far so good.
