### ISSUE TITLE
BRAND_CONSOLE blocking error on boot

### ISSUE THREAD

**Issue by andrevalladares** [xcp-ng/xcp#303]
Hey guys!

So we had a power outage here that shutdown our xcp-ng server. Upon returning, it no longer boots, or should I say, reaches the end of the boot process? It goes through most of it, it shows the splash screen, but then it gets stuck on this error shown on the attached picture
![IMG_0061_resize](https://user-images.githubusercontent.com/54600613/68158325-2b354280-ff2e-11e9-85bd-5aa925bb7746.jpg)
 (sorry for the picture, only way I can capture that).

The only keyboard output that works is ctrl+alt+del. Any ideas?

**Comment by stormi** [comment]
I've never seen such an error, but I'd suppose a damaged filesystem. Maybe it has trouble reading `/etc/xensource-inventory`.

Alt+Right doesn't work to get a shell session?

I suggest to continue the discussion on the forum since this is not really a bug as far as I can tell.

**Comment by andrevalladares** [comment]
Fair enough.  I'll open a thread there and post what I find. Did not know about Alt+Right.
