### ISSUE TITLE
PVHVM VMs crashing when migrating after XCP-ng 7.6 november updates

### ISSUE THREAD

**Issue by Ultra2D** [xcp-ng/xcp#307]
When migrating from a 7.6 host without the patches from #302 to a host in the same pool that was just updated and rebooted, three PVHVM virtual machines did migrate but got completely stuck after migration. CPU at 0%, RAM at 100%, no console, no response to ping. Two other PVHVM VMs migrated successfully.

For one VM there is an error message, but for the others I could not find one.
`xenopsd-xc: [ info|<host>|20 |Async.VM.pool_migrate R:530659fd4af3|xenops_server] Caught Domain.Emu_manager_failure("Received error from emu-manager: Connection refused") executing ["VM_migrate",["<vm_uuid>"` .

Might this be related to the fix for some other migration problem to 7.6 (#72)?

**Comment by stormi** [comment]
I think it depends how many updates were missing on the other host. Latest updates only change xen packages and xenopsd. If xcp-ng-emu-manager was very old, then maybe it is #72 (see https://github.com/xcp-ng/xcp/wiki/Updates-Howto#a-special-word-about-xcp-ng-75-76-and-live-migrations).

If your hosts were all up to date before we released the latest updates, then I don't think emu-manager bugs are involved. In the past, I've seen issues when migrating during a pool update, especially when versions of xenopsd differed. That's why I advise in https://github.com/xcp-ng/xcp/wiki/Updates-Howto to first update all hosts, then restart the toolstack on all hosts, and only then reboot the master.

**Comment by Ultra2D** [comment]
Only the latest 8 updates were missing.

Thanks, I will change my update procedure to patch all hosts first, then restart all toolstacks and only then reboot master.

**Comment by stormi** [comment]
> edit: Although it does frighten me a bit to patch a host while there are virtual machines running on it.

Indeed. There's no known adverse effects of this method for now, and running VMs are untouched (of course don't restart the toolstack while there are XAPI tasks being run), but there's still a risk that there exists a case we haven't foreseen.

**Comment by Ultra2D** [comment]
I updated the other hosts, restarted the toolstacks of them, then rebooted one of them. After that I moved a PVHVM VM from a host that still needs to be rebooted to the rebooted one. The VM is hanging now.

**Comment by stormi** [comment]
Do you think it could be caused by a too low dynamic memory setting? See #268

**Comment by Ultra2D** [comment]
Nope. All VM's have static memory.

It seems it happens to any PVHVM VM where `user-version ( RW): 1`. Also, `list_domains` only shows H, no B or R.

**Comment by olivierlambert** [comment]
Can you change this `user-version` number to `2` on the faulty VMs? This way we could rule out this (or not).

**Comment by Ultra2D** [comment]
All VMs in this pool have been migrated by now unfortunately. All VMs with `1` failed, and those with `2` did not.
What I can do is change the value on another pool, but that pool actually needs more patches. So the test case will not be exactly the same. There's only two PVHVM with `1` though.

**Comment by Ultra2D** [comment]
Well, I tried this with another pool:
1. changed `user-version` from `2` to `1` for one VM
1. patched all host sequentially (master first)
1. restarted toolstacks sequentially (master first)
1. migrated the VM with modified `user-version` -> no problem
1. migrated VM where `user-version` is `1` -> gone 
1. force reboot it
1. can move it without any problem now
1. power cycled another VM with `user-version` is `1`
1. migrated it successfully

The host were restarted later.

There's not much I can test now. I did power cycle the VM with the modified `user-version`. If it crashes next time, we will know more.

**Comment by Ultra2D** [comment]
There have been no crashes any more.

**Comment by olivierlambert** [comment]
Aahhh great news then :+1:

**Comment by Ultra2D** [comment]
Well, the cause of the previous crashes is still not clear to me, but if they won't occur any longer I'm happy anyway.

**Comment by olivierlambert** [comment]
Okay, we'll try to keep in mind the `user-version`. Maybe we should put in into our doc somewhere?

**Comment by Ultra2D** [comment]
It's not clear if it is related. It's the only difference I could find in the VM config, but after changing that value (1->2 and 2->1) there were no more crashes.
