### ISSUE TITLE
Supplemental Packs (container management) incompatible

### ISSUE THREAD

**Issue by Bodge-IT** [xcp-ng/xcp#31]
I tried installing v7.3 but fails on all my coreos vms.  "Not compatible with this server version"
I know you guys have other stuff to prioiritise but is there intent to make these packs work at some point? 

Also JFYI, XCP-ng guesttutilies installer for windows still showing Citrix branding.

**Comment by Bodge-IT** [comment]
Hi @olivierlambert, that was the exact error.  That was reported in the precheck when installing the iso as an update in the new XCP-ng Center.  My server version is now 7.4.1 but the citrix documnetation reports that the conatiner pack is same for 7.3. and 7.4.

**Comment by olivierlambert** [comment]
Please check your logs or try to install the pack from CLI or Xen Orchestra (or any other reliable interface) to get the real error message.

How did you installed your 7.4.1 exactly?

**Comment by Bodge-IT** [comment]
7.4.1 was an upgrade from 7.2.

Even on 7.2 was not able to install from cli as command just hung.  But was always able to install from Update mechanism.

**Comment by olivierlambert** [comment]
Please paste the result of `cat /etc/xensource-inventory`

**Comment by Bodge-IT** [comment]
PRIMARY_DISK='/dev/disk/by-id/ata-Crucial_CT250MX200SSD3_1528101C7C2B'
DOM0_VCPUS='4'
PRODUCT_VERSION='7.4.0'
DOM0_MEM='752'
CONTROL_DOMAIN_UUID='ad794232-7a00-4ef0-a75a-bb395801b7a4'
MANAGEMENT_ADDRESS_TYPE='IPv4'
COMPANY_NAME_SHORT='Open Source'
PARTITION_LAYOUT='ROOT,BACKUP,LOG,BOOT,SWAP,SR'
PRODUCT_VERSION_TEXT='7.4'
INSTALLATION_UUID='50ce19a0-b345-4b21-9a27-e341f9c1de1b'
PRODUCT_BRAND='XCP-ng'
BRAND_CONSOLE='XCP-ng Center'
PRODUCT_VERSION_TEXT_SHORT='7.4'
MANAGEMENT_INTERFACE='xenbr0'
PRODUCT_NAME='xenenterprise'
STUNNEL_LEGACY='true'
BUILD_NUMBER='release/jura/master/100'
PLATFORM_VERSION='2.5.0'
PLATFORM_NAME='XCP'
BACKUP_PARTITION='/dev/disk/by-id/ata-Crucial_CT250MX200SSD3_1528101C7C2B-part2'
INSTALLATION_DATE='2018-05-02 17:56:31.241140'
COMPANY_NAME='Open Source'

**Comment by Bodge-IT** [comment]
When I try from cli using xe-install-supplemental-pack, I now get:
`Error: No sr-uuid parameter was given, and the pool's default SR is unspecified or invalid. Please explicitly specify the SR to use in the sr-uuid parameter, or set the pool's default SR.`

**Comment by olivierlambert** [comment]
You need to specify a default SR then.

**Comment by Bodge-IT** [comment]
The update precheck stage failed: the server is of an incorrect version.
update: xscontainer
installed_version: platform-version = %{PLATFORM_VERSION}
required_version : platform-version >= 2.3

**Comment by olivierlambert** [comment]
Hmm `PLATFORM_VERSION='2.5.0'` in your inventory file, so I don't understand. Can you try to reboot your host?

**Comment by Bodge-IT** [comment]
I can see installed_version: platform-version = %{PLATFORM_VERSION}
is missing a % to turn it into a placeholder no?

**Comment by olivierlambert** [comment]
Where you see that?

**Comment by Bodge-IT** [comment]
In the response, that was copied exactly.  Normally placeholders are %{placeholders}%

**Comment by olivierlambert** [comment]
Yes but that's not my questions:

* are you able to find where in your host this placeholder is still present?
* did you rebooted?

**Comment by Bodge-IT** [comment]
Not sure I follow.
I'm just reading the output after trying to install the pack on the cli of the pool master.
Didn't reboot.

**Comment by olivierlambert** [comment]
I completely understand what you mean, but that's not what I need to help you.

I need to know where this place holder is found on your host by the pack installer. So please make a search on hosts for files containing the string `%{PLATFORM_VERSION}` and let me know where.

**Comment by Bodge-IT** [comment]
I've used:
`grep -rnw '/' -e '%{PLATFORM_VERSION}'`

**Comment by olivierlambert** [comment]
It's up to you, are you familiar with Linux command line or not at all?

You could use something like that: `grep -ri "%{PLATFORM_VERSION}" / --exclude-dir=sys --exclude-dir=proc`

**Comment by olivierlambert** [comment]
So did you find anything?

**Comment by Bodge-IT** [comment]
it's thinking I think

**Comment by olivierlambert** [comment]
Alternatively, you can also use `xe host-param-list uuid=<YOUR HOST UUID>` and  see what you have in software-platform entry. Also, please restart the toolstack before.

**Comment by Bodge-IT** [comment]
Software-version (MRO): product_version: 7.4.0; product_version_text: 7.4; product_version_text_short: 7.4; platform_name: XCP; platform_version: 2.5.0; product_brand: XCP-ng; build_number: release/jura/master/100; hostname: localhost; date: 2018-02-19; dbv: 0.0.1; xapi: 1.20; xen: 4.7.4-4.1; linux: 4.4.0+10; xencenter_min: 2.9; xencenter_max: 2.9; network_backend: openvswitch; db_schema: 5.134

**Comment by olivierlambert** [comment]
Everything seems fine from there too.

**Comment by Bodge-IT** [comment]
Surely the issue must be in the xe-install script?

**Comment by Bodge-IT** [comment]
Does this shed any light:
May  3 04:02:01 rubik daily-license-check: ALERT exited abnormally with [2]
May  3 10:58:21 rubik pool_update.precheck INFO: pool_update.precheck ['yum', 'install', '-y', '--noplugins', '-c', '/tmp/a527b2f0-82de-446a-a150-4f3f103eddfb/yum.conf', u'control-xscontainer'] returncode=1 output:
May  3 10:58:21 rubik pool_update.precheck INFO: Resolving Dependencies
May  3 10:58:21 rubik pool_update.precheck INFO: --> Running transaction check
May  3 10:58:21 rubik pool_update.precheck INFO: ---> Package control-xscontainer.noarch 0:1.0.1-1 will be installed
May  3 10:58:21 rubik pool_update.precheck INFO: --> Processing Dependency: platform-version >= 2.3 for package: control-xscontainer-1.0.1-1.noarch
May  3 10:58:21 rubik pool_update.precheck INFO: --> Finished Dependency Resolution
May  3 10:58:21 rubik pool_update.precheck INFO: Error: Package: control-xscontainer-1.0.1-1.noarch (xscontainer)
May  3 10:58:21 rubik pool_update.precheck INFO:            Requires: platform-version >= 2.3
May  3 10:58:21 rubik pool_update.precheck INFO:            Installed: xenserver-release-7.4.0.xcp-1.x86_64 (@install/$releasever)
May  3 10:58:21 rubik pool_update.precheck INFO:                platform-version = %{PLATFORM_VERSION}
May  3 10:58:21 rubik pool_update.precheck INFO:  You could try using --skip-broken to work around the problem
May  3 10:58:21 rubik pool_update.precheck INFO:  You could try running: rpm -Va --nofiles --nodigest
May  3 10:58:21 rubik pool_update.precheck INFO:
May  3 12:13:51 rubik pool_update.precheck INFO: pool_update.precheck ['yum', 'install', '-y', '--noplugins', '-c', '/tmp/a527b2f0-82de-446a-a150-4f3f103eddfb/yum.conf', u'control-xscontainer'] returncode=1 output:
May  3 12:13:51 rubik pool_update.precheck INFO: Resolving Dependencies
May  3 12:13:51 rubik pool_update.precheck INFO: --> Running transaction check
May  3 12:13:51 rubik pool_update.precheck INFO: ---> Package control-xscontainer.noarch 0:1.0.1-1 will be installed
May  3 12:13:51 rubik pool_update.precheck INFO: --> Processing Dependency: platform-version >= 2.3 for package: control-xscontainer-1.0.1-1.noarch
May  3 12:13:51 rubik pool_update.precheck INFO: --> Finished Dependency Resolution
May  3 12:13:51 rubik pool_update.precheck INFO: Error: Package: control-xscontainer-1.0.1-1.noarch (xscontainer)
May  3 12:13:51 rubik pool_update.precheck INFO:            Requires: platform-version >= 2.3
May  3 12:13:51 rubik pool_update.precheck INFO:            Installed: xenserver-release-7.4.0.xcp-1.x86_64 (@install/$releasever)
May  3 12:13:51 rubik pool_update.precheck INFO:                platform-version = %{PLATFORM_VERSION}
May  3 12:13:51 rubik pool_update.precheck INFO:  You could try using --skip-broken to work around the problem
May  3 12:13:51 rubik pool_update.precheck INFO:  You could try running: rpm -Va --nofiles --nodigest
May  3 12:13:51 rubik pool_update.precheck INFO:
May  3 13:08:26 rubik scripts-block: backend/vbd3/4/5696: remove
May  3 13:08:26 rubik scripts-block: backend/vbd3/4/768: remove
May  3 13:08:26 rubik vif-real: Called as: /usr/libexec/xenopsd/vif-real vif 4 1 offline
May  3 13:08:26 rubik scripts-vif: Called as "vif 4 1 offline" domid:4 devid:1 mode:openvswitch
May  3 13:08:27 rubik vif-real: Called as: /usr/libexec/xenopsd/vif-real vif 4 1 remove
May  3 13:08:27 rubik scripts-vif: Called as "vif 4 1 remove" domid:4 devid:1 mode:openvswitch

**Comment by olivierlambert** [comment]
I edited your post to add Markdown backticks ````` for your code block.

**Comment by olivierlambert** [comment]
So the RPM package is doing a check on `platform-version` (but where?) and find an incorrect value. The thing is: I don't know where it finds it.

**Comment by olivierlambert** [comment]
But where is stored this potential non-replaced place holder? I can't find it anywhere :/

**Comment by cocoon** [comment]
I searched with grep, too.
Did not find it. 

I tried to start to follow what the pool_update.precheck script is doing, but it is a bit complex, usiing api to get a yum config for example:

https://github.com/xcp-ng/xen-api/blob/master/scripts/extensions/pool_update.precheck#L253

**Comment by olivierlambert** [comment]
Can you do to that and tell me if it installs the plugin:

1. `yum install xscontainer`
2. `xe-toolstack-restart`

**Comment by olivierlambert** [comment]
It seems to work for me:

![capture d ecran de 2018-05-03 22-10-10](https://user-images.githubusercontent.com/1241401/39600380-d87c87e4-4f1e-11e8-812a-a464f02b5077.png)

**Comment by cocoon** [comment]
I see you have added it to your online repository, so it would not work for me without internetconnection, but I will try today a bit more and then I can try with a proxy if it will be working with a simple yum install xscontainer.

**Comment by Bodge-IT** [comment]
This worked for me!  Thanks @olivierlambert and @cocoon Now for Orchestra to round everything off!

**Comment by cocoon** [comment]
Just was thinking: what about a central synced repository on the xoa appliance with management in xoa, like sync scheduling, monitor disk space etc.

**Comment by olivierlambert** [comment]
You mean having XOA acting like a RPM proxy? That sounds possible (but it's a Debian distro, so we it won't be out of the box I suppose).

Regarding monitor disk space: you mean for the dom0 or SR? (for SR there is already the alert plugin)

**Comment by olivierlambert** [comment]
Yes, this will work as a cache.  But we can't store "by default" the packages, because we release a new XOA once every 3y or so ;) But yes, that's really a good idea to use XOA as proxy/cache for XCP-ng!

**Comment by cocoon** [comment]
regarding: "we can't store "by default" the packages" ... why not? I meant that there will be a constant / scheduled sync (thin a bit like WSUS for Windows).

**Comment by olivierlambert** [comment]
I mean, we build XOA once every 2 or 3 years, if we bundle those packages by default, they'll be outdated very quickly. But with `apt-cacher-ng`, it's not a problem: after your first request, all the needed packages will be stored in cache anyway (in XOA). Sounds the most clean solution!

**Comment by cocoon** [comment]
Yes I understand that, if you would bundle fixed packages without automatically updating / syncing them constantly from the internet it would not make sence.
apt-cacher-ng is doing what I meant, it is downloading new packages for example every day and keeps to be up2date.

**Comment by Bodge-IT** [comment]
@olivierlambert I spoke a little too soon.  Although this has installed to the host and has enable management of the containers, it hasn't added the container management setting or the cloud-init config panel to the properties of the vm.  I ran xscontainer-prepare-vm for the vm which was successful but it didn't change, tried rebooting VM too. any suggestions?

**Comment by olivierlambert** [comment]
Please be sure to have the package installed on all hosts, and toolstack restarted too :)

**Comment by cocoon** [comment]
Hey what about this:
https://github.com/xcp-ng/xcp-ng-specs/blob/3a79cfada49cabb861cbad2087e4323b028299fa/SPECS/xenserver-release.spec#L46

I think I installed the supplemental pack without a problem with 7.4.0 if I remember correctly, as I had reported a problem in the past but that was a license problem, so I thought it must have been introduced with some later changes?

**Comment by olivierlambert** [comment]
Those place holders are replaced during the install (that's why I told everyone to use the upgrade and not install the package manually, because it's the **install process that replace those placeholders**). So I don't understand why it's related to this issue. That doesn't make sense.

Except if people used `yum upgrade` from a 7.4.0 or installed manually the xenserver-release package themselves.

**Comment by Bodge-IT** [comment]
I used CD

**Comment by olivierlambert** [comment]
Yes, otherwise your `xensource-inventory` file would have the place holders itself. It doesn't make sense… Anyway, `yum` way is preferred to install containers now.

**Comment by Bodge-IT** [comment]
Any idea how I can get my cloud-config back?

**Comment by cocoon** [comment]
I used the ISO to upgrade an official 7.2 XenServer and it got this problem, I did not install anything manually.

I am not sure, but for me it looks like the package is providing the text from the meta data.
I don't know where it is saved or how yum is comparing it from, but it seems to be that it has to be replaced in the metadata, too.

Look at this comparison between the ctx 7.2 rpm and the xcp-ng rpm:

![platform_version](https://user-images.githubusercontent.com/1071741/39650855-0dde17b0-4fea-11e8-8172-59b46e1a7952.jpg)

**Comment by olivierlambert** [comment]
Pinging @johnelse for looking at this when he will be back (Tuesday)

**Comment by cocoon** [comment]
I have more details.

**The values are stored in one of the rpm databases that are located here:**

/var/lib/rpm/

The one we had problems now is stred in this database:
/var/lib/rpm/Providename
(might be: Berkeley DB (Hash, version 7, native byte-order) )

**To get the package that provides the required value:**

rpm -q --whatprovides platform-version
xenserver-release-7.4.0.xcp-1.x86_64

**ORIG:**

```
rpm -q --provides xenserver-release-7.4.0.xcp-1.x86_64
centos-release = 7
centos-release(upstream) = 7.2
config(xenserver-release) = 7.4.0.xcp-1
platform-name = XCP
platform-version = %{PLATFORM_VERSION}
produce-version-text-short = %{PRODUCT_VERSION_TEXT_SHORT}
product-brand = XCP-ng
product-build = 0x
product-version = %{PRODUCT_VERSION}
product-version-text = %{PRODUCT_VERSION_TEXT}
redhat-release = 7.2
system-release = 7.2
system-release(releasever) = 7
xenserver-release = 7.4.0.xcp-1
xenserver-release(x86-64) = 7.4.0.xcp-1
```



**PATCHED:**

```
[root@xcp-ng-vm1 rpm]# rpm -q --provides xenserver-release-7.4.0.xcp-1.x86_64
centos-release = 7
centos-release(upstream) = 7.2
config(xenserver-release) = 7.4.0.xcp-1
platform-name = XCP
platform-version = 2.5.000000000000000
produce-version-text-short = 7.400000000000000000000000000
product-brand = XCP-ng
product-build = 0x
product-version = 7.4.00000000000000
product-version-text = 7.400000000000000000000
redhat-release = 7.2
system-release = 7.2
system-release(releasever) = 7
xenserver-release = 7.4.0.xcp-1
xenserver-release(x86-64) = 7.4.0.xcp-1
```

**Comment by fabiorauber** [comment]
@Bodge-IT, I'm having the same issue after installing xscontainer via yum. I don't see the Cloud-Config panel on the VMs. The cloud-config panel is lost when moving the VM even on XenServer 7.2, but exporting it to XVA and reimporting it made the panel reappear. Tried the same on XCP-ng 7.4.1, with no luck.
Unfortunately I can't even create a new CoreOS VM with cloud-config on XCP-ng Center, so I think XCP-ng Center is not detecting the xscontainer plugin.

**Comment by olivierlambert** [comment]
did you restarted the toolstack? did you installed it on all hosts?

**Comment by fabiorauber** [comment]
@olivierlambert Yes to both. Even tried rebooting the hosts.

**Comment by olivierlambert** [comment]
Can you create a CoreOS VM in Xen Orchestra and tell me if it works?

**Comment by fabiorauber** [comment]
@olivierlambert Created CoreOS VM with cloud-config, but the configdrive, although present, is not mounted on /media/configdrive

**Comment by Bodge-IT** [comment]
I spun mine up and I think I have same. 
Symptoms are VM stuck in 6.2 tools not 7.1 and cannot pu xs-vm-prepare to VM becuase xe-daemon not running on VM.
I do not have cloud-config option, strangely.

**Comment by cocoon** [comment]
@olivierlambert I think it was this [commit](https://github.com/xcp-ng/branding-xcp-ng/commit/b7dec5c95cc99623b85d69d62a39c81de3d3b311) that broke the branding for the "xenserver-release.spec" file.

**Comment by olivierlambert** [comment]
No, that's something I added to do tests myself. In fact, as I already said, the `%{FOOBAR}` thing is replaced **during the install**.

**Comment by johnelse** [comment]
@cocoon The branding and release RPMs are fairly easy to build with the standard RPM build tools on CentOS 7.4 (a VM or docker container is fine). You can install the build tools with `yum install -y rpm-build`.

Download the specfiles from [here](https://github.com/xcp-ng/xcp-ng-specs/blob/master/SPECS/branding-xcp-ng.spec) and [here](https://github.com/xcp-ng/xcp-ng-specs/blob/master/SPECS/xenserver-release.spec), then for each of those download the source tarball given on the `Source0` line (you'll need to replace the %{version} sections).

Put the specfiles at `~/rpmbuild/SPECS` and the tarballs at `~/rpmbuild/SOURCES`, then you should be able to run

```
rpmbuild -bb ~/rpmbuild/SPECS/branding-xcp-ng.spec
sudo rpm --install ~/rpmbuild/RPMS/branding-xcp-ng*
rpmbuild -bb ~/rpmbuild/SPECS/xcp-ng-release.spec
```

That will give you an `xcp-ng-release` RPM in `~/rpmbuild/RPMS`

Building many of the other packages (e.g. `xcp-featured`) is more involved, as it can involve building and installing a lot of dependencies from the XenServer source ISO. As @olivierlambert says, we hope to have this better documented and automated soon.

**Comment by cocoon** [comment]
@johnelse many thanks for that! That is enough to keep me busy a while.

**Comment by Bodge-IT** [comment]
I'm a little overwhelmed here.  Is there a way for me to fix access to my cloud-init file?

**Comment by olivierlambert** [comment]
Did you tried with an older version of CoreOS?

**Comment by Bodge-IT** [comment]
older? no, why?

**Comment by Bodge-IT** [comment]
I had it working on 1688.5.3 with xen 7.2

**Comment by borzel** [comment]
@fabiorauber the issue with cloud-config is resolved in XCP-ng Center 7.4.2-RC2
https://github.com/xcp-ng/xenadmin/releases

**Comment by Bodge-IT** [comment]
I have also tried to export my current VMs but the configdrive is not being picked up in the export option.
System does report xvdb being "attached" to the VM.  Also tried to spin up new CoreOS VM but it doesn't load properly falling back to Emergency session or something.  Won't let me install to disk.  Tried this on both of my hosts.

**Comment by olivierlambert** [comment]
I don't understand: when you create the coreOS VM (for example in XO), you have the cloud init disk created right? If you mount it manually, do you see the cloud init content?

If it's just that the disk is not mounted inside CoreOS, for me it's something wrong happening inside CoreOS.

**Comment by Bodge-IT** [comment]
I agree, I think there is more than one issue at play here but I used to be able to spin up a CoreOS VM without issue and install to disk from CD booted version.

Now I can get the OS installed but doesn't run properly and can't install to disk from CD.  On the New VM wizard, yes the option for Cloud-cofig is presented but I only get some sort of emergency shell and can't "do anything" in it.

On existing VMs, Container Management option is there but no Cloud-config panel, I haven't tried importing yet but did notice that the export didn't include the configdrive, so don't hold out much hope for that.

I haven't had time to sort out XO yet, sorry...

**Comment by Bodge-IT** [comment]
OK I fixed the boot from CD issue.  The issue on the screenshot above was simply lack of required ram for the VM.  So by rebuilding my VMs I can get everything backup and running including cloud-config.

Will there be a fix for moving CoreOS VMs from host to host without losing cloud-config panel?

**Comment by olivierlambert** [comment]
I suppose this is more a XCP-ng Center issue then, no?

**Comment by Bodge-IT** [comment]
yes, I think so.

I can do some tests but need to rebuild VMs first.
