### ISSUE TITLE
CentOS 8: xe-guest-utilities

### ISSUE THREAD

**Issue by discostur** [xcp-ng/xcp#310]
Hi,

just tried to install xe-guest-utilities under CentOS 8 but it seems not ready get:

```
bash /mnt/Linux/install.sh 
Detected `CentOS Linux release 8.0.1905 (Core) ' (centos version 8).

Unable to install guest packages for distribution
CentOS Linux release 8.0.1905 (Core)  (centos).

Unknown RedHat Linux variant `centos 8'.

You should manually install a version of
xe-guest-utilities which is suitable for your
distribution.
```

**Comment by stormi** [comment]
What version of XCP-ng is it? Is it fully updated?

**Comment by discostur** [comment]
@stormi i ugpraded my xcp-ng hosts to the latest version - it works now ;)

**Comment by stormi** [comment]
Thanks for the feedback. One issue less in the bugtracker \o/.

**Comment by tansei** [comment]
`/mnt/Linux/install.sh -d centos -m 8`
did the trick for my cento8 stream
