### ISSUE TITLE
nvme0: controller is down; will reset: CSTS=0xffffffff, PCI_STATUS=0xffff

### ISSUE THREAD

**Issue by Qasher** [xcp-ng/xcp#311]
Hey hi XCP folks,

I am having issue with installing XCP-NG on my new NUC8i7HNK3. 
Current setup: Adata XPG SX8200 Pro 512GB nvme2 ssd, 16GB rams. 
Bios Setting: UEFI off, Secure boot off, AHCI storage instead of RAID.

I am having the issue when I am trying to install xcp on to my machine, getting the error message "nvme0: controller is down; will reset: CSTS=0xffffffff, PCI_STATUS=0xffff" and after the error message have been shown, computer restarted and goes back to the installation menu. (Looping).

**Comment by olivierlambert** [comment]
Hi,

Please use our forum for that feedback, we try to keep the issue tracker for identified bugs :)

https://xcp-ng.org/forum
