### ISSUE TITLE
Plugin request: ups monitoring via snmp 

### ISSUE THREAD

**Issue by akurzawa** [xcp-ng/xcp#314]
Hi

Big request for creating the plugin that could do snmpget and if vaule =/</> than X then run script or command. 

Currently I'm monitoring my ups battery level by snmpget and needed to install separate vm (...). 
For small setup monitoring ups and raid is sufficient, would be great if that function would be included in xoa.

```
root@xxx:/home/aku# snmpget -v1 -c public 10.0.0.15 .1.3.6.1.4.1.43943.1.1.3.4.0
iso.3.6.1.4.1.43943.1.1.3.4.0 = INTEGER: 91
root@xxx:/home/aku#
```

**Comment by stormi** [comment]
If that request is for XOA, then the issue tracker is at https://github.com/vatesfr/xen-orchestra/issues
