### ISSUE TITLE
Lost Connection to 'Server' via XCP-NG Windows Client

### ISSUE THREAD

**Issue by DPerkunas** [xcp-ng/xcp#316]
XCP-ng Center 8.0.1 (also occurs in 8.0.0)

My windows client XCP-ng Center keeps disconnecting.

I've checked a couple of things, the IP is not being used by another VM or host anywhere on the environment, hardware is not malfunctioning (NIC). Attempted switching NICs with same issue.

Occurs about once every minute. Reconnects just fine.

Saw something online about possibly checking something in the BIOS?

**Comment by olivierlambert** [comment]
Hi,

This looks like an IP conflict. The forum will be a better place to search for community assistance. We tend to keep GitHub repo for identified issues.

https://xcp-ng.org/forum

See you there :+1:
