### ISSUE TITLE
Unable to install lm_sensors using yum install

### ISSUE THREAD

**Issue by syifashafirah** [xcp-ng/xcp#317]
[12:47 xen1 ~]# yum install lm_sensors
Loaded plugins: fastestmirror
Determining fastest mirrors
Excluding mirror: updates.xcp-ng.org
 * xcp-ng-base: mirrors.xcp-ng.org
Excluding mirror: updates.xcp-ng.org
 * xcp-ng-updates: mirrors.xcp-ng.org
http://mirrors.xcp-ng.org/8/8.0/base/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.xcp-ng.org; Unknown error"
Trying other mirror.

 One of the configured repositories failed (XCP-ng Base Repository),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:
1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=xcp-ng-base ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable xcp-ng-base
        or
            subscription-manager repos --disable=xcp-ng-base

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=xcp-ng-base.skip_if_unavailable=true

failure: repodata/repomd.xml from xcp-ng-base: [Errno 256] No more mirrors to try.
http://mirrors.xcp-ng.org/8/8.0/base/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirrors.xcp-ng.org; Unknown error"

**Comment by stormi** [comment]
Hi. mirrors.xcp-ng.org is working correctly. Either that was a transient error, or there's something on your network (a proxy?) that prevents you from contacting the mirrors.

**Comment by borzel** [comment]
@stormi nope
![image](https://user-images.githubusercontent.com/5782951/69895005-71f93b00-1328-11ea-9c11-d1e10756fd7d.png)

**Comment by borzel** [comment]
seems like an issue with redirects

**Comment by olivierlambert** [comment]
IIRC, it will work with a browser that never visited the forum. So it shouldn't affect XCP-ng hosts while doing yum update.

**Comment by stormi** [comment]
I confirm what Olivier said.

**Comment by borzel** [comment]
I can also confirm it.
But in the end the redirection is not right? Caused by an update?

**Comment by borzel** [comment]
O, I deleted my webcache and cookies for mirrors.xcp-ng.org and now the website is working again :-)

**Comment by stormi** [comment]
> I can also confirm it.
> But in the end the redirection is not right? Caused by an update?

The problem is, for some reason the forum software started adding `includeSubDomains` to the `StrictTransportSecurity` header despite being configured not to do so. So once you've visited the forum, your browser considers that any *.xcp-ng.org address is to be adressed in HTTPS mandatorily. However mirrors.xcp-ng.org does not handle HTTPS at the moment, so you end in an endless redirection loop from http to https to http to https...

All this is unrelated to the original poster's issue, whose host could not even resolve mirrors.xcp-ng.org.
