### ISSUE TITLE
Pciback Driver Not Loaded

### ISSUE THREAD

**Issue by DustyArmstrong** [xcp-ng/xcp#320]
This issue is likely just confined to me, but I seem to get an issue with pciback when trying to pass through an Ultrium tape drive. My process went as follows (generally following https://github.com/xcp-ng/xcp/wiki/PCI-Passtrough and other guides): 

Attempt to locate the BDF. I initially did this using `lspci`, however this did not yield a result for the tape drive. I found another resource that suggested using `dmesg`, where I was able to locate what I gather to be the controller (*0000:07:00.0*) and the drive (*scsi 1:0:1:0:*). 

At that time, I ran the command as found in the guide `opt/xensource/libexec/xen-cmdline --set-dom0 "xen-pciback.hide=(1:0:1:0:)"`. I assumed this to be correct, but as the BDF formatting looks different, perhaps it wasn't. The command appeared to run (no output, but no error). I rebooted the system at this point.

On restart, I ran the command `xl pci-assignable-list`, which resulted in the following output:

`libxl: error: libxl_pci.c:415:libxl_device_pci_assignable_list: Looks like pciback driver not loaded`. 

Resources I found suggested that `pciback` was compiled into the kernel, and not a module. I'm not sure particularly though how that would lead to me resolving the issue. Running `modprobe xen-pciback` yields no result (no output at all). Running a grep for `pciback` under available modules (may have done incorrectly) yields no result. 

I ran `xl dmesg` to do some checks (as well as some other commands). Below are some points that may be relevant from the output of that: 

`Xen Version 4.11.1-7.3.xcpng8.0`
`I/O virtualisation enabled`
`- Dom0 mode: Relaxed`
`HVM: ASIDs enabled`
`HVM: VMX enabled.`

I also noticed in this output the following: `Intel VT-d Dom0 DMA Passthrough not enabled`. I researched some items about turning IOMMU on, but I'm unsure of it. There are also other `Intel VT-d` results from `dmesg`, if they are useful in resolving I'm happy to provide. 

Under `/etc/grub.cfg`, I don't see any update as suggested in resource guides I've looked at. I also note that under `menuentry 'XCP-ng'`, iommu has no entry. Would I be correct that I need to append `iommu = 1`? The relevant line is (if going by guide): 

`multiboot2 /boot/xen.gz dom0_mem=2672M,max:2672M watchdog ucode=scan do$`

EDIT: More research, I believe IOMMU is on based on dmesg - `Intel VT-d Interrupt Remapping enabled`. 

-----

Hopefully this isn't too tough to diagnose and this makes sense to someone. I'm not that knowledgeable about XCP, this is the first time I've tried to pass something through. 

I should note that it appears the tape drive entries from dmesg have reduced a lot, so I'm not sure if something has occurred from my original attempts, and whether it's salvageable from this point. Any help would be appreciated. 

EDIT: Tape drive still appears to be present in `dmesg`, with the same details as noted.

**Comment by stormi** [comment]
The `xen-pciback` module is built-in, indeed:
```
[14:57 xcp-ng-sam1 ~]# rmmod xen-pciback
rmmod: ERROR: Module xen_pciback is builtin.
```

On my host (without any passthrough), `xl pci-assignable-list` works (and yields no results as expected).

I don't know why you get such an error in your case. You may reach more people on the forum.

**Comment by DustyArmstrong** [comment]
Thanks for the response @stormi. 

I ran `rmmod xen-pciback`and found the same result as you. 

Interestingly, I ran `xl pci-assignable-list` on my other host and that did run (yielded no results of course). 

I did an upgrade in-place from XCP 7.X, would that maybe have something to do with it? Honestly, one of the disks just failed anyway so I might just move the VMs off and rebuild the whole thing to see if that solves it.

**Comment by stormi** [comment]
An in-place upgrade is mostly a clean install + restoring your XAPI database and maybe some other configuration files. So I don't think it should have anything to do with it.

**Comment by DustyArmstrong** [comment]
Hmm fair enough. The problem server is a DL380, the one working is a "custom built", basically just a board and the relevant components in a case. 

It does seem odd, I expected it just to sort of, work. I'll have a try on the forums.

**Comment by DustyArmstrong** [comment]
Update on this. 

I migrated my VMs to the secondary host, and blew the whole thing away. Re-installed from scratch, and that seems to now allow me to run the commands without error. I did have a feeling it was to do with the upgrade. 

I'm still not 100% on what exactly I need to put in the command to ignore, as the BDF notation still seems incorrect for the tape drive? I'd rather be sure but I suppose it's an odd case. 

I'll close this for now, fix was to re-install XCP from scratch.

**Comment by bsmokeman** [comment]
I have an hp dl380 gen7, I'm trying to get working with xcp-ng.  I know the built in hp controller is now depracated in the current install(centos8 forward), so I installed xcp-ng 7.6, so I didn't run into any issues.  I also want this box to be a truenas host, with the truenas vm hosted on the same 128 gig ssd I installed the dom0/xenserver to.  I have an lsi HBA I want to pass through to truenas.  I followed the tutorials on passing through a pcie device, matching the commands in this thread.  I'm getting the same error.  
[[root@xcp-ng-up-link ~]# xl pci-assignable-list
libxl: error: libxl_pci.c:418:libxl_device_pci_assignable_list: Looks like pciback driver not loaded
](url)
this should be fairly straight forward, finding the pcie id, and disabling it in dom0 with the above command, then assigning it to the vm, and starting it.  why on earth am I getting this error...? no upgrade, fresh install, this is literally the first thing I've done besides install the truenas vm, and add the iso smb repository shared from another host.

**Comment by bsmokeman** [comment]
I see lots of discussion on this, and the various iterations of commands, why on earth is this not a part of the gui yet?  select pcie device, it gets disabled in dom0, and enabled for passthrough, set the vm for passthrough, done!

**Comment by bsmokeman** [comment]
if you hide the pcie device from dom0, without running this command, which was left off of one of the tutorials I was following, then you will get the same error, I document here.
make sure you have run this:
`/opt/xensource/libexec/xen-cmdline --delete-dom0 xen-pciback.hide`

**Comment by olivierlambert** [comment]
Hi. It's not part of UI because our backlog is already very huge and we have to prioritize. However, contributions are very welcome :)

Also, the process is documented here: https://xcp-ng.org/docs/compute.html#pci-passthrough (the doc can be also modified by the community, there's a link on the bottom of each page to contribute).
