### ISSUE TITLE
windows vm network performance inconsistent with HP Ethernet 1Gb 4-port 331FLR adapters

### ISSUE THREAD

**Issue by loopway** [xcp-ng/xcp#321]
We currently use 3 HP ProLiant DL380p Gen8 servers in a pool and experience inconsistent network performance within Windows 10 VMs. The network cards are HP Ethernet 1Gb 4-port 331FLR adapters (Broadcom BCM5719 chipset).

- With iperf3 we get around 400 Mbits/sec, where we get around 806 Mbits/sec with a different card with an intel I218-V chipset
- Latest XCP-ng Windows PV Tools 8.2.2.200-RC1 installed.
- No performance issues with Linux VMs and XCP-ng dom0.

Are there any restrictions or issues for this network card known? According to the Citrix
Hypervisor Hardware Compatibility List the 331FLR adapters are supported by them...

**Comment by stormi** [comment]
Hi. There are no known issues for this network card that I am aware of, but many sysadmins that I know would advise to avoid Broadcom NICs. I suggest to ask on our forum to see if other users have the same hardware and similar results, or ideas to debug.

**Comment by loopway** [comment]
https://xcp-ng.org/forum/topic/2432/network-performance-windows-10-vm
