### ISSUE TITLE
Enable VGA Graphics in Xcp-ng Center.

### ISSUE THREAD

**Issue by amarnath-jena** [xcp-ng/xcp#325]
i am using xcp-ng center . how i can enable VGA graphics in xcp-ng. Kindly help me out.

Thank you.

**Comment by stormi** [comment]
Hi. We do not provide official support for XCP-ng Center. The main supported UI is Xen Orchestra. I can leave this issue open for a while to let users and contributers from the community answers, but I think using the forum would be more suited and efficient.

**Comment by amarnath-jena** [comment]
As you said i will do that and share the solution.

**Comment by borzel** [comment]
This feaure is currently not implemented in XCP-ng Center. You can create a feature request here: https://github.com/xcp-ng/xenadmin/issues
