### ISSUE TITLE
can't link a windows SMB when host is on a win 10 account that is using a Microsoft account

### ISSUE THREAD

**Issue by raykai** [xcp-ng/xcp#326]
Hi,
im trying to add a windows File Sharing SMB but the host of the folder is on a windows 10 that has a Microsoft account (Hotmail account) linked to it. What credentials do we need to use? 

I tried: 

- hotmail account and Hotmail account password = not working 

- hotmail account and pin = not working

- MicrosoftAccount\xxx@hotmail.com and Hotmail password =not working

I can get it to work fine when using a local account but not when it's linked to a Microsoft account.

**Comment by stormi** [comment]
Hi. We try to keep the github issues for bugs and development. For support requests like this, you can either post on [our forum](https://xcp-ng.org/forum) or open a support ticket if you have a [support subscription](https://xcp-ng.com/).
