### ISSUE TITLE
xcp 7.6 tapdisk hight cpu - server disk are fully loaded - all vm works slow

### ISSUE THREAD

**Issue by akurzawa** [xcp-ng/xcp#329]
Hi

I have a problem with heavy disk load ? - xcp 7,6 all patches till 24.01.2020. The vms works very slow - the speed in vm is about 10-20MB/s instead of usual 140-160MB/s.

- dell r510 / h700 / 128GB RAM
- raid 10 using 4x8TB WdReds
- local storage

Vms localted on this host became very unresponsive due to low disk speed - raw speed of this raid10 setup tested on Windows 10 installed directly on Dell r510 is 350MB/s read and 300MB/s write.

What the xcp-ng is currently doing, why it become so slow?

```
[root@XCP01 ~]# xe task-list 
uuid ( RO)                : 5dc784ea-3aed-f4a7-52fa-71f70ec9d5f2
          name-label ( RO): Async.SR.update
    name-description ( RO): 
              status ( RO): success
            progress ( RO): 1.000
```

No task but xcp-ng is continously doing something - tapdisk spikes to 80-90%

![image](https://user-images.githubusercontent.com/20043789/73061901-790d7700-3e9b-11ea-8215-0c077a54df4d.png)

**Comment by olivierlambert** [comment]
You should probably go on the forum first, we try to keep this repo for clearly identified/reproducible issues.
