### ISSUE TITLE
xcp-ng.org is down

### ISSUE THREAD

**Issue by aaaaaaudrey** [xcp-ng/xcp#33]
I'm not sure if this is the right place to put this. 

IIRC @olivierlambert and XO are managing the site, should anyone else be alerted?

**Comment by olivierlambert** [comment]
Sorry, misconfiguration on Nginx, fixed! Thank for the report!

**Comment by aaaaaaudrey** [comment]
@olivierlambert 

https://xcp-ng.org/forum/ is broken now

**Comment by olivierlambert** [comment]
Nope :angel:
