### ISSUE TITLE
XCP-ng Center 8.0.1 is not compatible with XCP-ng Beta 8.1

### ISSUE THREAD

**Issue by leirbagvalle** [xcp-ng/xcp#331]
I can't connect to my servers after upgrading the beta version 8.1 from my Center (windows), where can I download the new Center version?

**Comment by olivierlambert** [comment]
Hi, please ask on the right repo: https://github.com/xcp-ng/xenadmin

You might find the answer here: https://github.com/xcp-ng/xenadmin/releases
