### ISSUE TITLE
xe vm-import INTERNAL_ERROR

### ISSUE THREAD

**Issue by jimiebolha** [xcp-ng/xcp#332]
When trying to import from xenserver 6.5 to xcp-ng 8.0 via command line I have the following error.
Follow the command executed:

xenserver 6.5:
xe vm-snapshot vm=pv-vm new-name-label=pv-vm-export
xe template-param-set is-a-template=false ha-always-run=false uuid=b6c547c7-e5b7-cc3b-41da-6434e1090791
 xe vm-export vm=b6c547c7-e5b7-cc3b-41da-6434e1090791 filename=pv-vm-export

xcp-ng 8.0
xe vm-import sr-uuid=42d6c810-d0e9-8787-6bbe-959b46a34ae1 filename=pv-vm-export

ERROR:
msg: INTERNAL_ERROR: [ Xmlrpc.Parse_error("open_tag(value)", "close_tag(name)", _)

**Comment by stormi** [comment]
Hi. Importing from xenserver 6.5 may fail due to unpatched issues in xenserver 6.5. However, I've never seen the error message you got, so this may be something totally different. I think it's related to XS 6.5 or to the current state of your XAPI database, rather than a bug in XCP-ng 8.0.
