### ISSUE TITLE
Virtual Disks an ESET Virus scanner with activated media control: No access to drive.

### ISSUE THREAD

**Issue by LLS-Marc** [xcp-ng/xcp#333]
Hi folks!

Thanks for your great work!

We recently ran into an issue with a Windows 10 VM, ESET EndPoint Security 7.2 and XCP-ng 8.0.0:

We created a new virtual drive for the VM. It showed up in the Windows drive manager and we were able to initialize it. But when we tried to format it, Windows raised an error message, that it is not possible to access this drive. After two hours we had the idea to check the media control log of the ESET Virus EndPoint Security Software. The result: XCP-ng virtual drives seem to look like an USB drive to the Virtual machine. Thus the Virus Software is blocking the device. This does not happen when using e.g. VMware. There seems to be some difference how the Hypervisors declare drives to the system.

**Comment by stormi** [comment]
Hi. Can you detail how you create and add the new disk?

**Comment by stormi** [comment]
Closing due do inactivity. Feel free to reopen with the wanted information.
