### ISSUE TITLE
Unable to see CPU and memory usage on xsconsole

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [xcp-ng/xcp#335]
Hi there,

A week ago I updated existing Citrix XenServer 7.6 to XCP-ng 8.0 using ISO image. The installation went very well without any issue so far.

Today, I wanted to see the CPU usage of one of our guest, and I was not able to see the usage; however, I could check from `xentop` program. I'm not clearly sure that is a bug because of updating from XenServer. That's why I wanted to file this behaviour.

The effected tabs are "Virtual Machines > Host Performance Information" and "Virtual Machines > VMs Running On This Host > **any virtual machine usage**"

Is there anything (logs, screenshots, etc.) I can post or share?

Thanks
B

**Comment by olivierlambert** [comment]
Hi,

For general purpose questions, the forum is a best place: https://xcp-ng.org/forum

The bug tracker tends to be here only for identified/reproducible issues only (to reduce the triage effort for our devs).

See you there!

**Comment by BerkhanBerkdemir** [comment]
> Hi,
> 
> For general purpose questions, the forum is a best place: https://xcp-ng.org/forum
> 
> The bug tracker tends to be here only for identified/reproducible issues only (to reduce the triage effort for our devs).
> 
> See you there!

Thanks for your reply but don't want to create an account for now. If I find a way to reproduce a jump from Citrix XenServer 7.6 to XCP-ng 8.0, I definitely will published it.

**Comment by stormi** [comment]
You can log in with your github account :)
