### ISSUE TITLE
qlogic-netxtreme2 patch to fix null pointer dereference in bnx2x_del_all_vlans() on some hw

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#336]
Upstream patch from the linux kernel tree. Patch is not present in NEWER versions of the drivers by broadcom. I hope it will eventually since an upstream commit reference is given. Until then we apply it ourselves to qlogic-netxtreme2 and qlogic-netxtreme2-alt.

The affected driver is `bnx2x`.

See https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/net/ethernet/broadcom/bnx2x?h=v4.19.102&id=6384c67c64b59fb0a3e0b414a9171ec8147eaae1

Thanks to @rushikeshjadhav for pointing me in the right direction.

Tasks:
* 8.0
  * [x] Patched qlogic-netxtreme2 in xcp-ng-testing
  * [x] Patched qlogic-netxtreme2 pushed as an official update to 8.0
  * [x] Patched qlogic-netxtreme2-alt in xcp-ng-testing
* 8.1
  * [x] Patched qlogic-netxtreme2 in xcp-ng-base before the final release
  * [x] Patched qlogic-netxtreme2-alt in xcp-ng-base before the final release
  * [x] Patched in installer filesystem (install.img)

**Comment by stormi** [comment]
If you came here because you are using XCP-ng 8.0 and you don't have any network available because of this bug and still need the update, see https://xcp-ng.org/forum/post/22667

**Comment by stormi** [comment]
Actually the patch IS present in broadcom's upstream drivers, but they apparently failed as copying it, and theirs missed half the affected models... That's why the patch backported from the linux kernel is still necessary.

**Comment by olivierlambert** [comment]
> Actually the patch IS present in broadcom's upstream drivers, but they apparently failed as copying it, and theirs missed half the affected models...

Broadcom and drivers, a long story. Just pinging @sammcj for the fun.

**Comment by stormi** [comment]
Pushed as an official update to 8.0 along with the last security updates.

**Comment by sammcj** [comment]
Broadcom... the gift that keeps on giving...

![image](https://user-images.githubusercontent.com/862951/79556460-74e0a680-80e4-11ea-91cb-1021ecfe70c6.jpeg)
