### ISSUE TITLE
XCP-NG 8.0 ALL Tasks Fail

### ISSUE THREAD

**Issue by JustinTimperio** [xcp-ng/xcp#338]
I have been using XCP-NG for about 2 months now and the experience has been good so far. I recently have run into an issue so serious I am considering abandoning the entire platform. After running for more than a few hours, my Host will continue to run any existing VM's but hangs on literally every other command. I can't add disks, shutdown or start VM's. I can't do anything, other than hard reset the Host by unplugging it. 

I have tried:
- Restarting the Toolstack, which crashes the server and it never responds again.
- Force killing the UUID task does nothing.
- I have reinstalled XCP-NG and that did nothing
- I have updated and patched

Host Specs:
Dell R910
80 Threads
256GB Ram
4x Evo SSD
12x Seagate 5tb

At this point, I am begging for help from anyone who might know how to fix this. I don't want to abandon XCP-NG but I genuinely have no idea how to salvage what is now +40TB of VM's and Data.

**Comment by stormi** [comment]
Hi. I suggest to post to the [forum](https://xcp-ng.org/forum/) (that we also read), since we try to keep the issues here for bug tracking. 

Unless there have been serious hardware failures or big mistakes through manual tweaking of the storage layer, there's probably a way to recover the VMs. If you haven't saved the metadata before reinstalling XCP-ng, though, this will probably be made harder, depending of the number of virtual disks to manually pair with new VMs. 

As to the initial cause, it's hard to say. Could be anything. Have you checked whether that was full system (`/`) or /var/log partition ? (please answer on the forum, I'll see the answer)

**Comment by nagilum99** [comment]
Also: You should give more details of the CPU (on the forum) and controller used.
Threads alone usually don't matter, same for the used hardware devices - at least if the controller is unknown.
But The combination of cheap storage devices in that server is already a big dark-red point. Good chances for incompatibilities, probably the same for memory, then.
Also give them infos about Firmware versions and if they're all up2date - which is a very common problem, if not.

**Comment by JustinTimperio** [comment]
Hi stormi and nagilum99, 
I posted this here as it is definitely a bug. I also have a Dell R420 running the same version of XCP-NG and it doesn't have that issue. Additionally, this machine has run XCP 8.0 for 2 months without issue. I doubt it is 'cheap storage' either as it runs on 4 Evo Pro's in Raid 5. I have never had any issues with the storage and it has had well over a year of on-time. Not to mention I reinstalled from scratch, wiping the main drive and the issue is still there. 

Here are more detailed specs:

- 4x Intel Xeon E7-4870
- PERC H700 (6Gb/s) with 512MB cache
- 256GB of Samsung Ram (idk model but it's interlaced)
- Bios is at V2.10 (Most recent is 2.12)

**Comment by JustinTimperio** [comment]
I'm happy to upload logs and move to the forum if that's what you like to do though.

**Comment by JustinTimperio** [comment]
https://xcp-ng.org/forum/topic/2633/all-tasks-hang-fail-on-host-after-3-hours-ontime

**Comment by JustinTimperio** [comment]
A note to anyone experiencing hanging, unplug any usb hubs or external storage from your machine. After working on the forum with others, the issue traced back to disk timeout on an external drive. While unexpected, it will cause your whole host to become unusable. 

Many thanks to the people on the forum!!!!
