### ISSUE TITLE
Upgrade from 7.6 to 8.0 caused iscsi failure due to MTU issues. (bnx2)(kernel issue)

### ISSUE THREAD

**Issue by michael-newsrx** [xcp-ng/xcp#339]
I was upgrading a two node cluster running ha-lizard and ran into serious issues at the 50% upgrade mark.

The DRBD instances would no longer sync and I could not switch which machine was the iscsi master.

The cause was a change in the bnx2 driver. The pool was previously configured to use a MTU of 9000 on bonded interfaces for direct connected DRBD replication.

After upgrading to XCP-ng 8.0, the interfaces in the bond began dropping packets with sizes > the standard MTU of 1500.

After finally discovering this, I did a CLI change on the pool's bond to switch it to the standard MTU 1500 and rebooted and the DRBD cluster resumed normal operations.

The offending interfaces are bnx2 (Broadcom NetXtreme II™).

**Comment by olivierlambert** [comment]
> The offending interfaces are bnx2 (Broadcom NetXtreme II™)

This is a running joke around here. NetXtreme Shit II :smile: 

Anyway, we strongly discourage to change the MTU anyway, on any modern CPU (<10y old) you won't have any visible perf gains.

**Comment by michael-newsrx** [comment]
So, no performance gain with jumbo packets for DRBD replication on a dedicated link?

**Comment by olivierlambert** [comment]
Bigger MTU means less CPU work to "cut" packets. But since CPU are powerful enough about 10y ago, the gain of this change is more and more meaningless. But its adoption cost/config is the same.

**Comment by michael-newsrx** [comment]
Ok, thanks!
