### ISSUE TITLE
XCP-ng update from XAPI

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#34]
To avoid people doing a `yum upgrade` on each host manually, we could write a XAPI plugin that will be a simple interface to `yum` command.

## Context

* the plugin must be distributed as a `rpm` package first, and embed directly in future XCP-ng releases
* XO should be able to detect if the plugin is here and run some scheduled checks. If the plugin is missing, XO should display a clear documentation on that. More to come in a dedicated XO issue.
* XO should expose one button to update a whole pool at once (see future XO issue for this)

## Design

We should do something simple at start (function calls could be renamed, it's just a draft):

- [ ] `check-update` will use `yum check-update` command. Note than `yum` command returns  exit  value of 100 if there are packages available for an update. Also returns a list of the packages to be updated in list format. Returns 0 if no packages are available for update. Returns 1 if an error occurred. We should have something similar on the plugin return call, to be able to list packages to update and report errors etc.
- [ ] `update` will call `yum update -y` to start the update process without confirmation (we should know what do update with `check-update` command previously called

We won't cover upgrade cases for now.

## Cache

We could use XO as a cache to avoid downloading *n* times those packages (with *n* number of hosts in the pool).

## Advanced usage

- we should know when a reboot is needed on a host after updates. We need a way to detect that.

**Comment by koumdros** [comment]
re: **## Advanced Usage** case.  
XenServer decides on whether it needs to reboot post-update by parsing the "after=apply-guidance" in the relevant patch entry in the file "http://updates.xensource.com/XenServer/updates.xml".

while this wont be a 1-1 issue, as if I understand correctly we will "break" each update into the rpms that comprise it, nevertheless it will provide a good baseline.

**Comment by olivierlambert** [comment]
Maybe yes. But I suppose "guidance" is filled by someone somewhere. So it would be good to know what dictate those rules in the end, to be able to find what to do ourselves.

**Comment by olivierlambert** [comment]
Addition: it could be great if we can have the changelog since the current installed version up to the version that we'll update to (details for each package)

**Comment by olivierlambert** [comment]
Closing, it works. We'll include the package in 7.5
