### ISSUE TITLE
Please create test packages to help with USB support (related to CA-328130 )

### ISSUE THREAD

**Issue by ScottyGuy** [xcp-ng/xcp#342]
As discussed in https://xcp-ng.org/forum/topic/266/usb-passthrough-test-reports-in-7-5rc1 it looks like Citrix added code to xapi and xenopsd to improve USB handling, especially where the speed of the device is slower than the speed of the port it is plugged into (e.g. USB1 device into USB2 port)

Specifically commit ab15e6c3b1b06b2eac4f2a8be724eac50c9d4b22  in xenopsd (pull request #683 in that project)

Looks like pull requests #4009 and #3984 in xen-api (multiple commits under those pull requests)

**Comment by olivierlambert** [comment]
Thanks for the report!

Can you do links toward those commits? (just paste the URL it will be formatted automatically by GitHub).

Thanks again :+1:

**Comment by ScottyGuy** [comment]
xenopsd pull request:  https://github.com/xapi-project/xenopsd/pull/683
xenopsd commit: https://github.com/xapi-project/xenopsd/pull/683/commits/ab15e6c3b1b06b2eac4f2a8be724eac50c9d4b22

First xen-api pull request: https://github.com/xapi-project/xen-api/pull/3984
commits: https://github.com/xapi-project/xen-api/pull/3984/commits/da190399972fcaf2643892434091d2a29a97e2d2
https://github.com/xapi-project/xen-api/pull/3984/commits/a9ece061773876b6a2207e259856320945853642
https://github.com/xapi-project/xen-api/pull/3984/commits/d1d023d20f98e42028b6a3751b401c0fc2cbd277

Second xen-api pull request: https://github.com/xapi-project/xen-api/pull/4009
commits: https://github.com/xapi-project/xen-api/pull/4009/commits/57c4dc68244e4ceeb3427885b032f4f4c7ab389b

**Comment by stormi** [comment]
The commits are now in XCP-ng 8.2.
