### ISSUE TITLE
High IO guests crash upon migration

### ISSUE THREAD

**Issue by Arkenklo** [xcp-ng/xcp#347]
Info:
XCP-ng version 7.5
Hosts use local storage
Guest is Ubuntu 16.04

Issue:
When migrating a guest sometimes migration appears to succeed, but upon completion the guest becomes unresponsive and has to be force rebooted. After reboot the guest works normally.
The problem is more easily triggered on a guest with high IO load. I've written a script that rsyncs some data back and forth, and it triggers the issue about 30% of the time. Otherwise it's much more rare, maybe 3-5%.

Symptoms:
 - Guest console prints `INFO: task jbd2/dm-0-8:319 blocked for more than 120 seconds` or similar when freezing
 - Guest responds to ping, but not to any other network traffic
 - CPU, RAM, outgoing network activity is 0% per XCP-ng Center
 - Interactive shells over console or SSH sometimes keep working, sometimes freezes. But any command freezes the shell.

Gut-feel is that the guest loses access to its storage. But I'm not sure where to start looking.
I can semi-reliably reproduce the issue - are there any tests I could run to get more data? Which xcp-ng logs should I look at?

Attached is a screenshot of the console of a frozen guest.
![2020-03-10-171052_1024x694_scrot](https://user-images.githubusercontent.com/1564832/76333681-40fab000-62f2-11ea-8961-07fd5e7ae75c.png)

**Comment by olivierlambert** [comment]
XCP-ng 7.5 isn't supported since a bit now. Please upgrade to 8.0.
