### ISSUE TITLE
netinstall not properly detected in UEFI

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#348]
The current code of the installer fails to detect netinstall situations when in UEFI mode.

This is probably because we only updated isolinux.cfg but not grub.cfg.

**Comment by stormi** [comment]
Fixed, will be in next iteration of the installer.

**Comment by marnel007** [comment]
> Fixed, will be in next iteration of the installer.

You know when the next installer will be out ??

**Comment by stormi** [comment]
That will probably be for the final release of 8.1. 

Note that netinstall does work already in UEFI, it simply offers a local media option that it shouldn't. Just ignore it.

**Comment by marnel007** [comment]
Has anyone set this up on packet.com?? There Tech team has been great and gotten us to a login prompt..

**Comment by stormi** [comment]
Such questions do not belong to this specific issue. Please use the forum.

**Comment by marnel007** [comment]
> Such questions do not belong to this specific issue. Please use the forum.

Sorry
