### ISSUE TITLE
etc/shadow(-) is missing in install.img

### ISSUE THREAD

**Issue by netmax79** [xcp-ng/xcp#35]
During my installation tests i noticed that the default root console on tty2 is not logged in during installation.

The root cause is, that install.img is missing /etc/shadow (/etc/shadow-). Both are present
in original xenserver install.img.

I re-created install.img for my tests including both files and then a bash was available on tty2 again.

Can this please be fixed for next release?

**Comment by olivierlambert** [comment]
Thanks for your report, I'll take a look.

**Comment by olivierlambert** [comment]
Can you check our doc on how we generate the img file to see if we missed something there?

**Comment by olivierlambert** [comment]
See https://github.com/xcp-ng/xcp/tree/master/iso/7.4#installimg-modification

**Comment by netmax79** [comment]
I used the documentation for re-creating the image. I copied the shadow files from original xenserver install.img to the xcp-ng intsall.img. I think they were already lost in xcp-ng 7.4.0 release.

**Comment by olivierlambert** [comment]
okay, I'll be extra careful for next release then. By the way, what's the practical consequence of this? I mean, your use case.

**Comment by netmax79** [comment]
On some existing xenserver installations i had to do a "vgchange -a n" before i can confirm the language selection dialog. Not doing this sometimes results in a crash of the installer and a quite corrupted screen. I think sometimes i also had to stop lvmetad before proceeding with installation.

This all seem to happen because the base image scans/activates all LVM volumes.

**Comment by olivierlambert** [comment]
Got it! Again, thanks for your helpful report :+1:
