### ISSUE TITLE
Xcp-ng 8.0 fresh install does not load the local sr. 

### ISSUE THREAD

**Issue by skunniyur** [xcp-ng/xcp#352]
Hi,
I’m new to xcp. I have a dell pe 2950 with 3 drives as raid 0. 2*1 tb and 1*3 tb. 
I installed xcp in drive sdb(the installer showed up the 3 hdd). This is one of the 1 tb drives. 
The install went ok. But when I log in to the server using the xcpng center it does now show the remaining unused space. 
But I can see the 830gb as sdb3 from cli. 

I tried the install with ext, lvm during multiple installs with no luck. 

Anyone had similar issue and got this fixed. Please let me know. I’m going nuts with this.

**Comment by olivierlambert** [comment]
Can you tell us about the error?

**Comment by skunniyur** [comment]
It does not show any error. It uses 2gb for the install. Creates sb1,sdb2,sdb4 for log,boot,swap, sdb3 890 gun is nothing free unused and unattached as a local sr.

**Comment by nagilum99** [comment]
> Hi,
> I’m new to xcp. I have a dell pe 2950 with 3 drives as raid 0. 2_1 tb and 1_3 tb.

You mean 2x 1 TB and 1x 3 TB? (Underscore is pretty bad choice for that) as RAID 0?
That's a very weird config: All drives should have the same size, for performance reasons (and to not loose the space). Also that's very risky.

Also as you write they are all in RAID 0 but name sdb, it indicates you're not using a RAID-Controller, instead using some chipset/fake-RAID stuff. Don't do that. Never, ever use that. Get a real controller or use Software-RAID via XCP-ng.
Maybe that also fixes your problems.

**Comment by skunniyur** [comment]
Hi nagilum,
You are right it is 2 x 1 tb and 1 x 2 tb. 

This is not a fake raid controller it is dell perc 6ir sas controller. I was running 2 drives on an array with raid. Basically mirroring. 
 I wanted to used the drives independently without any array. So this setup. 

My 3 drives are showing up correctly during the setup process and in cli. The problem is the drive on which I install is non usable as a local sr. 

I can try software raid option during install. But when I see you tube videos they are doing the same and I was following them. 

But is there a reason why the installed drive ox xcp not showing as local sr.

**Comment by stormi** [comment]
Hi. I hope you have good backups if you're going to use RAID 0 since there's no redundancy. However back to the subject.

The installer *should* be able to use the remainder of the installation disk as a local SR. What choice was offered to you as the local SR creation screen? (that's the one where you can choose between EXT and LVM).

Please share the /var/log/installer/install-log file, maybe we'll find useful errors in it.

Despite the fact that the unused space was not attributed to a SR yet, you can still do it manually after the installation, via command line. Create a partition using the remaining space, don't format it, then see https://support.citrix.com/article/CTX121313.

**Comment by stormi** [comment]
Oh... Just remembered something important.

If you are OK to do it, wipe the dell diagnostics partitions from the disk (if there are any) before installing. The installer gets confused when it finds one and the partitioning gives weird results. I've reported it to Citrix already but no move yet. See https://bugs.xenserver.org/browse/XSO-940

**Comment by skunniyur** [comment]
Hi Stromi,
Thanks for the input. I will try this also. But for the moment,
I moved back to xcp 7.6 version. I used an ssd drive in my data controller.
Formatted the drive to ext3 type and loaded scp. By default the install and the unused partitions are showing up.
I tried the same with my other drives (Formatted to ext3 and it worked fine.

Thanks.
Samba.
