### ISSUE TITLE
Unable to find my passthrough drives in my FREENAS box running on XCP-NG 7.6

### ISSUE THREAD

**Issue by skunniyur** [xcp-ng/xcp#356]
Hi,
I am running scp-ng 7.6 version on my dell Pe2950. I installed freenas 11.6U1.
I followed the following steps as mentioned below for hiding the drives in xcp and enabling it to freenas.(https://www.ixsystems.com/community/threads/xcp-ng-7-5-0-pci-pass-through.70855/)
But, now i am unable to see the drives in xcp which is successful. But the drives are not showing up in freenas. Has anyone got an similar issue. Please comment.

Thanks in advance.

Regards.
Samba.

**Comment by stormi** [comment]
Hi, I suggest asking [on the forum](https://xcp-ng.org/forum), where you will reach more users, and come back to github only if a bug is suspected.
