### ISSUE TITLE
Unable to create storage repository on new local disk

### ISSUE THREAD

**Issue by thegrownupgeek** [xcp-ng/xcp#359]
I am experiencing issues when adding a new local disk storage repository.  When using the command 
`xe sr-create name-label=ssd_two shared=false device-config:device=/dev/sdc type=ext content-type=user`
an error is returned "The SR operation cannot be performed because a device underlying the SR is in use by the host."  This is a new disk with a fresh partition and does not show as mapped 

There is no storage repository attached to this disk.  I have attached the outputs i have looked at to resolve but if you require any further info please let me know. The issue is the same for /dev/sdc and [/dev/sdd.
[disk by id.txt](https://github.com/xcp-ng/xcp/files/4408567/disk.by.id.txt)
[xe sr-list.txt](https://github.com/xcp-ng/xcp/files/4408568/xe.sr-list.txt)
[lsblk.txt](https://github.com/xcp-ng/xcp/files/4408569/lsblk.txt)
[SMLog File.txt](https://github.com/xcp-ng/xcp/files/4408570/SMLog.File.txt)

**Comment by olivierlambert** [comment]
Please try to wipe the drive with a `dd` command to be sure there's no leftover from a previous install/OS.

Also, the forum is in general a better place to talk about specific problems: https://xcp-ng.org/forum

We try to keep this for identified bugs/issues. Thanks! :+1:
