### ISSUE TITLE
upgrade from 8.0.0 fails to start XAPISSL

### ISSUE THREAD

**Issue by jmrapin** [xcp-ng/xcp#361]
Upgrade a master on 8.0.0 with all fixes available to 8.1.0 and suddenly cannot connect with XCP-NG Admin Center.

Checked the server and did a xe-toolstack-restart :

[12:05 xcp-ng-server2 ~]# xe-toolstack-restart 
Executing xe-toolstack-restart

Failed to kill stunnel processes! Output:
which: no stunnel4 in (/sbin:/usr/sbin:/bin:/usr/bin)
Stopping xapi SSL: cannot stop xapi SSL: xapi SSL is not running./opt/xensource/libexec/xapissl: line 182: failure: command not found

done.

Anyone one has this issue?

**Comment by nagilum99** [comment]
Did you upgrade XCP-ng center FIRST?
Older versions usually can't connect to newer server and will show a message for that.
(Just asking, as you didn't say you updated it and it's a common problem)

Also after that upgrade a reboot of the system should be needed. I guess it breaks cuz you restart things that aren't suppost to work together, as you now have a 'hybrid' system until reboot.

**Comment by jmrapin** [comment]
Yes I have done all that. 

I have the latest version of admin center. Build 20.03.01.31 64-bit
I have restarted a few times. 
I also though maybe it's my windows but also all the other slaves xcp-ng cannot connect to the pool. So plus the error message when i try and restart the toolstack points to XAPISSL...

**Comment by stormi** [comment]
There are forum threads that look similar to your issue. I've listed them there: https://github.com/xcp-ng/xcp/wiki/XCP-ng-8.1-Known-Issues#being-investigated.

Could you open a ticket on xen-orchestra.com so that we could exchange credentials and try to investigate directly on your host?

**Comment by stormi** [comment]
That is, if you can leave the master in that state. Else restore the backup as you said.

**Comment by jmrapin** [comment]
I can’t give you access to the machine as it is in a enterprise network. 

I wouldn’t want to restore from backup if it can be resolved.... but yes I will need access at some point. 

I might be able to setup a teamviewer access 

Regards

Jean-Michel Rapin

**Comment by jmrapin** [comment]
Or better, since I am in Australia (I won’t be at work when you are online) if you let know what you need to can give you logs etc ... 

Regards

Jean-Michel Rapin

**Comment by olivierlambert** [comment]
We have a special reverse secure tunnel that you can open so we can access Xen Orchestra appliance, then the host :) That's why we suggest you open the tunnel, and keep it that way. There's no risk, we are the only ones to have the key and you'll told us in private the randomly generated ID.

**Comment by jmrapin** [comment]
Ok but I don’t have xen orchestra Installed anywhere as I don’t use it.
Since I can’t access my pool master I can’t add it. 

Regards

Jean-Michel Rapin

**Comment by olivierlambert** [comment]
Don't you have any other XOA running elsewhere in your internal infrastructure?

**Comment by jmrapin** [comment]
Hi Olivier, 

No I don't have any other xcp-ng. They are all in the pool :). I will open a ticket an go from there.

**Comment by stormi** [comment]
Hi. We have found the root cause of all this.

Run:
```
yum install gpumon
reboot
```

Then if not all is operational, you may have to do an emergency network reset and reconnect the SRs.

**Comment by jmrapin** [comment]
Hi @stormi 

yes I was reading the thread you pointed out this morning and the steps you highlighted in there fixed my issue. I have *only* nvidia graphic cards lol.

Thanks.

**Comment by stormi** [comment]
Update released: https://xcp-ng.org/forum/post/24618
