### ISSUE TITLE
46Gb really needed?

### ISSUE THREAD

**Issue by lw3eov** [xcp-ng/xcp#362]
Hi, 

I need a to run win xp (not server) (preferably 64 bits) in a virtual machine under Ubuntu 18.04.4, if possible with GPU support. For this I've found XCP as a possibility while searching the web. (VMWare Workstation does not have support for GPU and Vspere Hypervisor is available only for Windows) 
However in the requirements, XCP-NG says it needs 46Gb disk space minimun! Is it a mistake? I don't want to install such a huge piece of software for my simple and small implementation. Can you suggest something? Thanks. Regards. 

Marcelo

**Comment by olivierlambert** [comment]
Hi!

Please use [the forum](https://xcp-ng.org/forum) for such questions. Bug tracker is for identified issues.
