### ISSUE TITLE
Send hostname in case of DHCP enabled host

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#363]
For now, in DHCP mode, XCP-ng (`xcp-networkd`) won't send its hostname.

This is not great, because you can't use that to populate automatically your DNS with the name.

Current dhclient config file is:

```
interface "xenbr0" {
  request subnet-mask, broadcast-address, time-offset, host-name, nis-domain, nis-servers, ntp-servers, interface-mtu, routers, domain-name, domain-name-servers;
}
```

But it should be like this:

```
interface "xenbr0" {
  send host-name = gethostname();
  request subnet-mask, broadcast-address, time-offset, host-name, nis-domain, nis-servers, ntp-servers, interface-mtu, routers, domain-name, domain-name-servers;
}
```

No variable, no moving parts :+1: 

This configuration is tested and works on 8.1 hosts.

Relevant code: https://github.com/xapi-project/xcp-networkd/blob/e231cf37778945b46fb900f11e808e6d86928e12/lib/network_utils.ml#L749

**Comment by johnelse** [comment]
https://github.com/xapi-project/xcp-networkd/pull/175

**Comment by stormi** [comment]
Patched `xcp-networkd` packages are available for testing in XCP-ng 8.0 and 8.1:
```
yum update xcp-networkd --enablerepo=xcp-ng-testing
```

**Comment by stormi** [comment]
Anyone tested the update candidates?

**Comment by olivierlambert** [comment]
It's online since a bit in our lab.

**Comment by biztems** [comment]
Cheers guys - I won't be able to test this until September, but much appreciated.
