### ISSUE TITLE
XCP-ng 8.1.0 cannot mount NFS ISO SR

### ISSUE THREAD

**Issue by sheo0147** [xcp-ng/xcp#366]
I installed XCP-ng 8.1.0 to Ryzen7 3700X machine.
```
# cat /etc/os-release
NAME="XCP-ng"
VERSION="8.1.0"
ID="xenenterprise"
ID_LIKE="centos rhel fedora"
VERSION_ID="8.1.0"
PRETTY_NAME="XCP-ng 8.1.0"
ANSI_COLOR="0;31"
HOME_URL="http://xcp-ng.org/"
BUG_REPORT_URL="https://github.com/xcp-ng/xcp"
```
And I setup it with iSCSI configuration, and it runs well.
But, when I create NFS ISO SR, it does not work.

[RyzenPC] --+--[FreeBSD NAS] (iSCSI using ctld and NFS)

1. On XCP-ng Center and followings are failed.
  "New Storage" -> "ISO Library/NFS ISO" -> .... NFSv3, NFSv4 => fail
  Error Message: SM has thrown a generic python exception. Check your settings and try again.
2. On Console
  xe-mount-iso-sr xx.xx.xx.xx:/nfs/export/ISOs => fail
3. On Console
  mount.nfs4 xx.xx.xx.xx:/export => Success
  mount.nfs xx.xx.xx.xx:/nfs/export/ISOs => Fail (Protocol not supported)
  -> mount.nfs: trying text-based options 'vers=4.1,addr=xx.xx.xx.xx,clientaddr=yy.yy.yy.yy'
  mount.nfs -v -o vers=3 10.1.250.249:/zfs/Zhdd/export/ISOs /mnt
  -> mount.nfs: timeout set for Tue Apr  7 19:27:42 2020
  -> mount.nfs: trying text-based options 'vers=3,addr=yy.yy.yy.yy'
  -> mount.nfs: prog 100003, trying vers=3, prot=6
  -> mount.nfs: portmap query retrying: RPC: Program not registered
  -> ...
  -> mount.nfs: portmap query failed: RPC: Program not registered
  -> mount.nfs: requested NFS version or transport protocol is not supported

I did not understand followings.
* Why mount_nfs using NFSv4.1?
* Why RPC: Program not registered
* Why NFSv4 fail on xcp-ng center but success command line?
* How can I use NFS ISO on XCP-ng 8.1?

**Comment by olivierlambert** [comment]
Hi,

For general questions, please go to https://xcp-ng.org/forum

We try to keep this place for identified/reproducible bugs :+1:
