### ISSUE TITLE
Backup restore fails on UEFI systems - EFI boot issue

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#368]
There have been reports of failing backup restore on hosts that are using ~~software RAID~~ UEFI.

Grub fails to install apparently.

 See https://xcp-ng.org/forum/topic/2849/post-8-1-upgrade-boot-fails-and-restore-fails

**Comment by user-72632** [comment]
Please reference #357 here as I mentioned this some time ago (i.e., grub issue).

**Comment by stormi** [comment]
About #357 the error message is different, so at first sight it seems a different issue to me, but the outcome is the same indeed.

**Comment by stormi** [comment]
Bug reproduced, reported to Citrix, and workaround documented. See https://xcp-ng.org/forum/post/25608 and https://github.com/xcp-ng/xcp/wiki/XCP-ng-8.1-Known-Issues#backup-partition-restore-from-installer-fails-on-uefi-hosts

Fixing the python issue is not enough, because the files are not written to the EFI boot partition (and that was already the case in Citrix Hypervisor and XCP-ng 8.0)

Since there is a documented workaround, I'm not sure I will release new installation ISOs for this bug (once fixed).

**Comment by nagilum99** [comment]
Any reasons to not keep the install images up2date (at least integrating major bugfixes)?
Eventually offereing original release and most current one?

**Comment by stormi** [comment]
Yes, the huge amount of testing an ISO must receive in order to replace the previous one safely.

**Comment by stormi** [comment]
According the installer code diff, this issue seems to have been fixed in CH 8.2. To be tested once we get XCP-ng alpha ISOs.

**Comment by stormi** [comment]
Tests OK.
