### ISSUE TITLE
XCP-ng 8.1 host stays disabled after reboot

### ISSUE THREAD

**Issue by user-72632** [xcp-ng/xcp#369]
Prior versions of XCP/XS would re-enable the host after a restart even if you called host-disable at shutdown (i.e., in a script). This version, after restart leaves the host disabled until you manually enable it (i.e., host-enable).

**Comment by stormi** [comment]
Hi. I don't know about this behaviour. Maybe re-enabling the host was a bug? I suggest to reach out to the forum to share experiences with other users and help identify more precisely what's going on.

https://xcp-ng.org/forum/

**Comment by user-72632** [comment]
After a few installs of XCP-ng 8.1, I noticed that it would happen randomly once after a reboot then it would clear itself after subsequent reboots. Therefore, I am closing this issue.
