### ISSUE TITLE
Ubuntu Live iso Hangs on XCP-ng 8.1.0; Guest Reports: 'watchdog: BUG: soft lockup'

### ISSUE THREAD

**Issue by wsciaroni** [xcp-ng/xcp#371]
I have a fresh install of XCP-NG 8.1.  I made sure the pool is fully patched.  I have tested this with two known good images of Ubuntu Server 18.04. (18.04.2 and 18.04.4)
When I attempt to start this VM to install Ubuntu Server, I get to the language selection before the VM locks up.  On the same host, I was able to boot from and install Debian 10.0 without issue.  However, when I go back to any Ubuntu Server image, the vm locks up and I see 100% CPU usage on the guest.  I would be happy to provide more information or test with different iso images.

### Context

- **XCP-ng: 8.1.0
- Good behavior with Debian 10.0
- Bad behavior with Ubuntu Server 18.04

### Expected behavior

When I boot into Ubuntu Server 18.04 Live iso, I should be able to install the OS.

### Current behavior

The VM hangs and gives the errors seen in the image below. "watchdog: BUG: soft lockup - CPU#1 stuck for 22s! [lsusb:1887]" and "watchdog: BUG: soft lockup - CPU#2 stuck for 22s! [sfdisk:1777]"

![Screenshot from 2020-04-09 10-11-43](https://user-images.githubusercontent.com/26583386/78910477-a73a3600-7a4a-11ea-8e1b-adf6b34e852b.png)

**Comment by olivierlambert** [comment]
Triple check your ISO isn't corrupted. Also in advanced, try to:
* switch RTL card to e1000
* raise VGA memory

**Comment by wsciaroni** [comment]
I have tried these things already.  
- I double checked my sha256 sum of the ISO and I created a VM with it on in VirtualBox on a separate machine. It is working as expected.
- Raised VGA memory to the 16MiB
- Switched NIC card to e1000

**Comment by olivierlambert** [comment]
Okay and disabling VGA?

**Comment by wsciaroni** [comment]
I have tried this as well

**Comment by olivierlambert** [comment]
Can you give me a link to the ISO you are using to test in our lab?

**Comment by wsciaroni** [comment]
Yes,  I downloaded the most recent 18.04 LTS Live Server image from this page:
https://ubuntu.com/download/server

I had tried with an old image I had laying around first (18.04.2).  Because that didn't work, I tried a fresh ISO of the latest version (18.04.4).

**Comment by olivierlambert** [comment]
Are you in BIOS or UEFI mode?

**Comment by olivierlambert** [comment]
![Capture d’écran de 2020-04-09 17-52-17](https://user-images.githubusercontent.com/1241401/78914570-e2f4f000-7a8a-11ea-9358-e71fd8226561.png)

Can't reproduce here, seems to install correctly (BIOS mode)

**Comment by wsciaroni** [comment]
I am in BIOS mode

**Comment by olivierlambert** [comment]
Nothing to report here, using default template settings:

![Capture d’écran de 2020-04-09 17-59-08](https://user-images.githubusercontent.com/1241401/78915180-d3c27200-7a8b-11ea-99a7-88d614b4ab3d.png)

Try [on the forum](https://xcp-ng.org/forum) if you find other people with your issue. I'll reopen here as soon we have any clue that's due to something into XCP-ng itself :+1:

**Comment by wsciaroni** [comment]
Linking here in case anyone stumbles upon this thread with the same issue:
https://xcp-ng.org/forum/topic/2860/ubuntu-live-iso-hangs-on-xcp-ng-8-1-0-guest-reports-watchdog-bug-soft-lockup-371
