### ISSUE TITLE
Repo failures on update

### ISSUE THREAD

**Issue by magikmw** [xcp-ng/xcp#376]
I've had the same problems reported at #277 today - HTTPS 302 Error Found

It seems at least some mirrors fail (cert expiration on April 16th):
- https://mirror.chmuri.net/xcp-ng/8/8.1/updates/x86_64/Packages/xen-libs-4.13.0-8.4.xcpng8.1.x86_64.rpm

It seems there are no fallback mechanisms for an initial failure on one of the chosen mirrors. Yum has no other mirrors configured than the mirrors.xcp-ng.org alias.

I've finally managed to install the updates by persistance, but I don't think the issue is solved as long as this can happen.

**Comment by stormi** [comment]
Thanks for the report. I've disabled the faulty mirror.

**Comment by stormi** [comment]
Note that yum is supposed to fallback to updates.xcp-ng.org if everything else fails, but it does not work in every situation. I'll create an issue about that.
