### ISSUE TITLE
Replace gpumon with a dummy package OR fix XAPI

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#381]
In 8.2 XAPI will probably not be ready to function without gpumon, so let's build a dummy gpumon that just answers any requests with harmless data (empty lists if possible?).

OR 

Fix XAPI to make it accept that gpumon is not present.

**Comment by stormi** [comment]
Detailed XAPI GH issue about this: https://github.com/xapi-project/xen-api/issues/4072

**Comment by benjamreis** [comment]
https://github.com/xapi-project/xen-api/issues/4072

**Comment by stormi** [comment]
The following thread is the history of discovery and analysis of that bug. Linking to the specific post where I give the logs (filtered in `startup]`) that show that the startup process just stalls: https://xcp-ng.org/forum/post/24528

Fuller log at https://xcp-ng.org/forum/assets/uploads/files/1585777463321-xensource.log.txt

IIRC the last meaningful line after "[task] Starting up database engine" was:
```
Apr  1 11:15:32 vmserver1 xapi: [error||0 |dbsync (update_env) R:4c0a3231226e|xapi] Ignoring error parsing /usr/share/nvidia/vgpu/vgpuConfig.xml: (Sys_error#012  "/usr/share/nvidia/vgpu/vgpuConfig.xml: No such file or directory")#012Raised by primitive operation at file "stdlib.ml", line 390, characters 28-54#012Called from file "stdlib.ml" (inlined), line 395, characters 2-45#012Called from file "ocaml/xapi/xapi_vgpu_type.ml", line 520, characters 15-32
```
I don't remember if that line was present on working systems too or not.

But soon after that, XAPI's startup process stalls.

**Comment by benjamreis** [comment]
The line is present on both working and non working cases. However it is the LAST line in the non working case.

**Comment by stormi** [comment]
Building a "mock" version of gpumon allowed XAPI to start. Tests and/or code investigation needed to see whether there could be adverse effects.
