### ISSUE TITLE
Retain guest ISO feature

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#382]
XAPI has been changed to remove the guest ISO SR by default. A simple parameter should allow to keep it.
See https://github.com/xapi-project/xen-api/pull/4092

**Comment by benjamreis** [comment]
Hopefully setting `create-tools-sr` to `true` would be enough. :)
https://github.com/xapi-project/xen-api/pull/4092/files#diff-c7ad4027c580575079b338524da5f2d6R913
