### ISSUE TITLE
Control Domain Memory Usage

### ISSUE THREAD

**Issue by john-arvid** [xcp-ng/xcp#383]
Got this message in XCP-ng Center today. Is slowly but steadily increasing.

Running on 8.0 build date 2019-06-25
Uptime 235 days

When I run htop and sort by MEM% I find around 50 of 
`/opt/xensource/bin/xapi -nowatchdog -writereadyfile /var/run/xapi_startup.cookie -writeinitcomplete /var/run/xapi_init_complete.cokkie -onsystemboot`
and to many to count of 
`/usr/sbin/CROND -n`
and
`/usr/lib64/sa/sadc -F -L -S DISK 1 1 -`

Is this a known problem and is there something I should do? (Would like to avoid a reboot)

**Comment by olivierlambert** [comment]
1. Uptime 235 days: you should have rebooted anyway, we had security patches requiring a reboot since
2. you can restart toolstack to release memory of XAPI

**Comment by john-arvid** [comment]
I'm not that concerned about security patches. Running this server at home with a closed network and with no critical data. 
And yes that also says that it's no problem to do a reboot, but I wanted to check if this is something that is interesting to solve without a reboot or restart of the toolstack.

**Comment by stormi** [comment]
This could be interesting indeed. I think in your case the best way to get help diagnosing this to find the root cause would be to ask our experienced and often helpful users on the forum.

**Comment by john-arvid** [comment]
Ok, I will do that. I will leave the issue open for now.

**Comment by john-arvid** [comment]
Swap got full so I had to reboot the server. I created a post in the forum if anyone is interested at a later time. [https://xcp-ng.org/forum/topic/3004/control-domain-memory-usage/](https://xcp-ng.org/forum/topic/3004/control-domain-memory-usage/)

Looks like CROND and sadc was the sinner, but I don't know why.
