### ISSUE TITLE
Windows Server 2019 cannot be installed from current evaluation ISO

### ISSUE THREAD

**Issue by bogdantomasciuc** [xcp-ng/xcp#384]
Steps to reproduce results below.  
Freshly downloaded ISO for Windows Server 2019 from Microsoft. Created a new VM using Windows Server 2016 x64 as Template as there is no Windows Server 2019 Template. Went through the setup checking the whole virtual disk as destination and launching the installer.

![Setup-Destination](https://user-images.githubusercontent.com/23525491/81687128-8c9c1800-9461-11ea-9be8-e1effcc0edf0.png)  

After the installer reaches the second stage (checkmark) with the title **Getting files ready for installation** it loads this stage around 10% after which the VM reboots and presents the error below:  
`````
An operating system wasn't found. Try disconnecting any drives that don't contain an operating system.
`````
![after reboot error](https://user-images.githubusercontent.com/23525491/81688996-9d00c280-9462-11ea-860d-922a20f34618.png)

ISO build details: 17763.737.190906-2324.rs5

**Comment by bogdantomasciuc** [comment]
Aditional details:  
Using XCP-NG 7.6

**Comment by olivierlambert** [comment]
Hi,

XCP-ng 7.6 isn't supported anymore for security fixes, and potentially bugs. Can you try on XCP-ng 8.1 or at worst 8.0?

**Comment by bogdantomasciuc** [comment]
After first boot I am dropped to this shell:  
![after-boot](https://user-images.githubusercontent.com/23525491/81715975-8322a800-9481-11ea-8509-ee5e5a82b1a6.png)
Is this expected?

**Comment by nagilum99** [comment]
When you install an OS, that is officially not supported an even use a foreign template - nothing is expected, except, maybe, that it's not working (whyever).

IIRC UEFI was mainly introduced/supported with CH/XCP-ng 8/8.1 and Server 2019 only supports UEFI:
https://docs.microsoft.com/en-us/windows-server/get-started-19/sys-reqs-19

**Comment by bogdantomasciuc** [comment]
The second screenshot is after I upgraded to XCP-NG 8.1 and used the template Windows Server 2019. But thank you for chiming in. :)

**Comment by nagilum99** [comment]
You're very welcome. That minor detail is pretty important, as one has to expect you still try with 7.6 - as long as you don't give other details.

I have a Server 2019 running on XCP-ng 8.0 with the 2019 template without any problems.
Never seen that shell.

As you upgraded to 8.1: What exactly did you do to get this screen?
Is that your first bootscreen or is that also happening at some point during install?

**Comment by bogdantomasciuc** [comment]
I updated to version 8.1 then used the latest Windows Server 2019 downloaded from microsoft. Setup a new VM with default settings. After first reboot that is where i ended up. Other machines i hav already set up up on version 7.6 still work as expected. I am facing this issue only on the new Windows Server 2019 installation.

**Comment by nagilum99** [comment]
I see that MS says UEFI is mandatory, but from what I can see, the VM I installed is running in BIOS Bootmode. Did you try that?

**Comment by bogdantomasciuc** [comment]
Yes, I tried both with UEFI mode and BIOS mode. In both cases on the second step of the setup where it says **Getting files ready for installation** it loads 10-15% and then suddenly reboots. After reboot I am dropped to that shell. If I were to take a guess I would say that somewhere in the setup the installer no longer recognizes the virtual disk and crashes. Perhaps a driver issue?

**Comment by bogdantomasciuc** [comment]
A little detail. If I try to install in UEFI mode after (forced I assume) reboot I am dropped to the EFI shell. If I attempt to install in BIOS mode I am dropped to the screen shown in the first post with the message "An operating system wasn't found..." This I asume is normal behavior considering the installation failed and it's basically the same message shown in the different boot modes.

**Comment by bogdantomasciuc** [comment]
@nagilum99 Maybe you can try to make a fresh install on your system with the current ISO from Microsoft trial center if you have the storage and time available: [https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019](https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019). It would help if the issue is replicate-able on a different system.

**Comment by nagilum99** [comment]
It's a customer system and in production. I can't test that there anymore.
I used Windows Server 2019 Essentials, didn't try that eval ISOs. Also still running on 8.0 Can't say how much changed to 8.1.

And yes: The shell should belong to UEFI and pops up because it's missing an UEFI OS entry.

**Comment by bogdantomasciuc** [comment]
Guess I'll wait for a response from @olivierlambert or somebody else from the XCP-NG team. I ran out of ideas and I really don't want to start the setup with some hack. I want this to be as clean as possible.

**Comment by olivierlambert** [comment]
Please create the VM via Xen Orchestra and be sure to set UEFI in the advanced options :)

**Comment by bogdantomasciuc** [comment]
I did use XO from the start and uefi is set in advanced options. I have redownloaded the ISO to eliminate disk corruption from the table. After setup I am left at the same shell prompt - it is just not working. I have documented all steps below. Also the last 2 screens show the logs of $windows.~bt\Sources\Panther\setupact.log(final part) and $windows.~bt\Sources\Panther\setuperr.log.  
Settings:
![XO_SetupScreen1](https://user-images.githubusercontent.com/23525491/81907713-dc4d2180-95d0-11ea-9da3-1da18fa8b840.png)
![XO-SetupScreen2](https://user-images.githubusercontent.com/23525491/81907718-e0793f00-95d0-11ea-9b76-5f3ef907784e.png)
First boot starting:  
![XO-SetupScreen3](https://user-images.githubusercontent.com/23525491/81907726-e53df300-95d0-11ea-9a56-94a975ac90dd.png)  
OS Selection screen:  
![XO-SetupScreen4-Windows1](https://user-images.githubusercontent.com/23525491/81907739-ea02a700-95d0-11ea-80db-0f65a01be875.png)  
Installation disk sellection screen:  
![XO-SetupScreen5-Windows2](https://user-images.githubusercontent.com/23525491/81907750-ecfd9780-95d0-11ea-97e5-4cdb96428da7.png)  
Windows Setup starting:  
![XO-SetupScreen6-Windows3](https://user-images.githubusercontent.com/23525491/81907760-eff88800-95d0-11ea-810c-67ba3c0ec2ec.png)  
After unexpected boot. SetupErr.log (went to Repair -> CMD to get contents)
![XO-SetupScreen7-Windows4-setuperrlog](https://user-images.githubusercontent.com/23525491/81907765-f25ae200-95d0-11ea-8ecb-83848c599fae.png)  
After unexpected boot. SetupAct.log (went to Repair -> CMD to get contents)
![XO-SetupScreen8-Windows5-setupactlog](https://user-images.githubusercontent.com/23525491/81907774-f4bd3c00-95d0-11ea-86c7-30aba8375a73.png)  
Screen I get to if I let the boot process run without intervention of any kind:  
![XO-SetupScreenError](https://user-images.githubusercontent.com/23525491/81907791-fa1a8680-95d0-11ea-871b-155b856a1f9f.png)  
Perhaps somebody else can try to setup the current build of Windows Server 2019 Trial on their machine and chip in with a little feedback?

**Comment by bogdantomasciuc** [comment]
On a completely different topic, there is something that has bothered me for some time in XO but i didn't get to mention it. The drop-down control for the selection of pool, storage, boot ISO, disk, etc. is rather small in length and I can't see properly the selection especially using longer descriptive names. Presently I am kinda hacking the browser using the developer tools to increase the width of the control to see what my selection is if i have multiple similar selections. Would it be ok if I created a new issue to improve the control by making the drop-down selection box resize-able or maybe include some form of hover tip to read the whole selection text?

![XO_SetupScreen-ControlSize](https://user-images.githubusercontent.com/23525491/81909461-4ebf0100-95d3-11ea-94b9-28b435c2f7e9.png)

**Comment by olivierlambert** [comment]
About the last thing: it's a know issue that will be solved by XO 6 new UI.

**Comment by bogdantomasciuc** [comment]
> About the last thing: it's a know issue that will be solved by XO 6 new UI.

Super! Looking forward to new version! :grin:

**Comment by olivierlambert** [comment]
Tested with a fresh install of the same version than you, it works perfectly:

![Capture d’écran de 2020-05-14 10-31-10](https://user-images.githubusercontent.com/1241401/81911836-1c5ed500-95ce-11ea-818f-0157173600b6.png)

**Comment by olivierlambert** [comment]
Also installed XCP-ng tools, it's fast :)

![Capture d’écran de 2020-05-14 10-39-41](https://user-images.githubusercontent.com/1241401/81912721-4369d680-95cf-11ea-8e47-b72085a10a68.png)

Bench using our NFS in the lab:

![Capture d’écran de 2020-05-14 10-48-50](https://user-images.githubusercontent.com/1241401/81913633-85474c80-95d0-11ea-803d-242580d24827.png)

**Comment by bogdantomasciuc** [comment]
Well only thing different i guess is that i am using local storage. My system is a Dell PE 620 Server.

**Comment by stormi** [comment]
Maybe late for that question, but I suppose the ISO's checksums are right?

**Comment by olivierlambert** [comment]
I have this `md5sum`:
```
70fec2cb1d6759108820130c2b5496da  17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso
```

**Comment by bogdantomasciuc** [comment]
My md5sum is 70fec2cb1d6759108820130c2b5496da. Seems to match.
I am in the process of obtaining an older ISO. Will try with that one and post results.

**Comment by nagilum99** [comment]
I wonder about the first error it shows:

> An Error occurred while removing the MultiEdition key from the blackboard

That seems to be a problem with your image, ather the XCP-ng.
https://www.google.com/search?q=An+Error+occurred+while+removing+the+MultiEdition+key+from+the+blackboard
Maybe there's something helpful. Some Errors to go templates/sysprep...

The later logs show, that Windows makes itself unbootable.
Probably due to the key-error they don't want to leave a half-working Windows install?

**Comment by bogdantomasciuc** [comment]
Same results :disappointed: . @olivierlambert is your xcp host setup on uefi? I believe my host is setup in legacy bios mode. Idk if that may be the root cause. In the meantime I tried to create the VM with remote NFS storage such as in your example so that is not the issue. So I am beginning to believe it may be related to a BIOS setting that is incompatible.

**Comment by nagilum99** [comment]
You didn't give any hardware specs, but that may be the point:
HPE boots to UEFI per default, so I assume my XCP-ng installs are all running via UEFI boot.

**Comment by bogdantomasciuc** [comment]
It seems a host reboot and moving some RAM around VMs solved the issue. I am not satisfied I didn't find the cause but now it works and can't replicate the issue anymore so I will consider it solved. Thank you for the time everyone invested in troubleshooting this!

**Comment by olivierlambert** [comment]
Good news then 👍
