### ISSUE TITLE
Xen 7.6 free edition upgrade to XPG-ng 8.1 (Lisence error)

### ISSUE THREAD

**Issue by crazynds** [xcp-ng/xcp#386]
I upgraded a server from xen server 7.6 to xcp-ng 8.1 to be able to use the usb-passthrough feature as described in the tutorial https://github.com/xcp-ng/xcp/wiki/USB-Pass-Through. The update went well, however when executing the command xe vusb-create returned a license error as shown in the print below:
![image](https://user-images.githubusercontent.com/36674096/82761590-002f1500-9dd2-11ea-9a23-10b275b5e824.png)
I didn't find anything that mentioned a similar problem.

**Comment by stormi** [comment]
Hi. XCP-ng's license daemon answers "allowed" for all license requests, so you're not supposed to have this error message.

Can you describe how you upgraded to XCP-ng 8.1?

**Comment by crazynds** [comment]
The update was done on the main server of the pool using a usb with the iso
file of version 8.1.0-2 keeping the virtual machines that were on the xen
7.6 server.
The server that was installed is a dell poweredge T110 II. The installation
was normal and I start the server with the xcp-ng interface. I entered the
console and started to configure the usb passthrowgh and resulted in the
reported license problem.

I read a license issue in another thread
https://xcp-ng.org/forum/topic/459/licencing-problem-when-adding-a-new-host-to-an-existing-pool.
I'll update the rest of the pool and test again to see if it works.

>
