### ISSUE TITLE
acpi: spcr unexpected spcr access width. defaulting to byte size

### ISSUE THREAD

**Issue by szeldavid** [xcp-ng/xcp#393]
Fresh install on a Dell R720.
Getting "acpi: spcr unexpected spcr access width. defaulting to byte size" on boot for a few seconds after that it boots fine.

**Comment by olivierlambert** [comment]
Closing as dup of https://xcp-ng.org/forum/topic/3128/acpi-spcr-unexpected-spcr-access-width-defaulting-to-byte-size
