### ISSUE TITLE
GRUB: unknown filesystem

### ISSUE THREAD

**Issue by d3dx9** [xcp-ng/xcp#396]
Hi,

I tried to install as RAID 10 mdadm. As soon it is installed I getting into grub rescue saying unknown filesystem. HW is a Dell PowerEdge R620 with a H310 raid card in IT mode.

Any idea, how to fix this?

Best regards,
Julian

**Comment by nagilum99** [comment]
Only an idea: Different boot modes between install media and storage? (Legacy/BIOS vs. UEFI)

**Comment by olivierlambert** [comment]
Hi,

Only RAID1 is supported.

**Comment by d3dx9** [comment]
I tried to install as legacy and also uefi and I'm getting the errors in both bootmodes.

**Comment by d3dx9** [comment]
> Hi,
> 
> Only RAID1 is supported.

Oh, makes sense. Any idea how I can get this working? Or should I flash the card back in RAID mode?

**Comment by nagilum99** [comment]
Actually I was wondering about Mode 10, as I didn't see that option yet.
Probably your way to go is to get the controller back to RAID Mode.
It seems to be no fakeraid (just no cache included), so that should be fine for RAID10.

**Comment by stormi** [comment]
Closing since RAID 10 for system is not supported
