### ISSUE TITLE
cryptosetup on dom0

### ISSUE THREAD

**Issue by adnae** [xcp-ng/xcp#40]
Hi guys,

first of all thanks for this nice fork :)

XenServer has removed the cryptosetup package on 7.x image. But it it possible to add cryptosetup again into the dom0? We need this for encrypting USB storages .

thanks and best regards

Sascha

**Comment by olivierlambert** [comment]
Hi,

Please give us a link to the CentOS packages and if there is any extra dependency.

> Note: each new package means maintenance for them, so we won't add too many stuff

**Comment by stormi** [comment]
We'll handle this request in #56 and decide if we can provide and maintain this package.
Closing.
