### ISSUE TITLE
VDI metadata lost after rebooting to alternate kernel when using ZFS

### ISSUE THREAD

**Issue by egberdun** [xcp-ng/xcp#400]
# XCP-ng Version: 8.1

## Reference

https://xcp-ng.org/forum/topic/3004/control-domain-memory-usage/23

## Symptoms

All virtual disks have no metadata anymore (as shown on XCP-ng Center), which causes VMs not to have storage configured, which broke every single VM. After this happened, I installed Xen Orchestra inside the same system, and the disks that remained unlabeled at that point didn't show any info either (it seems that whatever XCPC and XO looks for, it's not there)

## Steps taken to produce: 

* Upgraded to kernel alt, versions shown below:

kernel.x86_64                     4.19.19-6.0.11.1.xcpng8.1 @xcp-ng-updates
kernel-alt.x86_64                 4.19.108-3.xcpng8.1       @xcp-ng-base

* Rebooted system to kernel-alt.
* VM boot failed with "Cannot find VDI Storage". (To note, I'm not using VDIs, these are plain VMs, so to speak)
* Rebooted system to normal kernel.
* Issue persists:

![image](https://user-images.githubusercontent.com/55469531/84658637-8e3b7e80-aeec-11ea-95f9-944b1c0dd453.png)

## Miscelaneous: 

* The system currently has the following storage setup:

NVME SSD (boot disk).
Local ZFS pool, RAID10 (4 disks).

* The system is on consumer hardware (Ryzen 7 1700, 32GB non-ECC ram, X370 motherboard with latest hardware).

* Manual recovery was attempted; the disks themselves are still there luckily, unfortunately the recovery required mounting every single disk and try to guess which VM and how old it was.

Let me know if I can provide any other info ^_^.

**Comment by stormi** [comment]
Quoting myself from the forum:
> I think what happened is that the ZFS kernel module is built against the standard kernel, not against the alternate kernel. So after a reboot, the VDIs could not be found. The XAPI probably did not notice that there was something wrong since it probably just saw an empty directory where the VDIs were supposed to be, so it just thought the VDIs had been removed. Then when the VDIs came back they were like new ones to it. This is a drawback of using a "local filesystem" SR driver for ZFS SRs: there's no check that the ZFS FS is correctly mounted.

**Comment by stormi** [comment]
I have created #401 for creating a dedicated ZFS driver that is aware of the mount status of the directory and thus avoids scanning when it's empty.

**Comment by stormi** [comment]
Closing, as XCP-ng 8.2 now has a dedicated ZFS driver that avoids metadata loss.
