### ISSUE TITLE
No link with the standard kernel using the r8169 driver in the main xcp-ng kernel

### ISSUE THREAD

**Issue by JanHolbo** [xcp-ng/xcp#403]
Installing xcp-ng 8.1 on my ThinkPad L430 resulted in a missing carrier on the built-in Realtek NIC. 

lspci -k:
```
0c:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 07)
	Subsystem: Lenovo Device 21f7
	Kernel driver in use: r8169
	Kernel modules: r8169
```

ip a:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast master ovs-system state DOWN group default qlen 1000
    link/ether 3c:97:0e:9f:07:46 brd ff:ff:ff:ff:ff:ff
3: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 42:00:4c:b8:c2:42 brd ff:ff:ff:ff:ff:ff
4: xenbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether 3c:97:0e:9f:07:46 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.33/24 brd 192.168.2.255 scope global xenbr0
       valid_lft forever preferred_lft forever
```
ethtool eth0:
```
Settings for eth0:
	Supported ports: [ TP MII ]
	Supported link modes:   10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Half 1000baseT/Full 
	Supported pause frame use: Symmetric Receive-only
	Supports auto-negotiation: Yes
	Supported FEC modes: Not reported
	Advertised link modes:  10baseT/Half 10baseT/Full 
	                        100baseT/Half 100baseT/Full 
	                        1000baseT/Half 1000baseT/Full 
	Advertised pause frame use: Symmetric Receive-only
	Advertised auto-negotiation: Yes
	Advertised FEC modes: Not reported
	Speed: Unknown!
	Duplex: Unknown! (255)
	Port: MII
	PHYAD: 0
	Transceiver: internal
	Auto-negotiation: on
	Supports Wake-on: pumbg
	Wake-on: g
	Current message level: 0x00000033 (51)
			       drv probe ifdown ifup
	Link detected: no
```
dmesg:
```
[    2.940877] libphy: r8169: probed
[    2.941401] r8169 0000:0b:00.0 eth0: RTL8168evl/8111evl, 3c:97:0e:9f:07:46, XID 2c900800, IRQ 56
[    2.941404] r8169 0000:0b:00.0 eth0: jumbo features [frames: 9200 bytes, tx checksumming: ko]
[    2.944414] ehci-pci 0000:00:1a.0: irq 16, io mem 0xf251a000
.....
[   16.278757] r8169 0000:0b:00.0 side-1013-eth0: renamed from eth0
.....
[   36.165620] r8169 0000:0b:00.0: invalid large VPD tag 7f at offset 0
[   36.658495] r8169 0000:0b:00.0 eth0: renamed from side-1013-eth0
[   37.160297] 8021q: 802.1Q VLAN Support v1.8
[   38.440397] openvswitch: Open vSwitch switching datapath
[   40.404132] device ovs-system entered promiscuous mode
[   40.481649] device xenbr0 entered promiscuous mode
[   40.603803] RTL8211E Gigabit Ethernet r8169-b00:00: attached PHY driver [RTL8211E Gigabit Ethernet] (mii_bus:phy_addr=r8169-b00:00, irq=IGNORE)
[   41.569480] device eth0 entered promiscuous mode
```

I have tried to set the interface to static during installation as well as DHCP (I have tried installing several times)

However installing and booting on the alternate kernel solved the problem
(https://xcp-ng.org/forum/topic/3199/problems-installing-latest-xcp-ng-on-a-thimkpad-l430)

**Comment by nagilum99** [comment]
The original kernel doesn't officially support RTL NICs, as it's focussed on professional hardware.
I guess that's (also what the alternate Kernel is made for)

...though: Most RTL chips work with the default Kernel.

**Comment by stormi** [comment]
Here, the default kernel does have the driver for the device, so it seems there's a bug somewhere. I agree that that kind of device is not a priority, but if we can fix it at little cost, we may do it.

**Comment by JanHolbo** [comment]
While I fully understand and appreciate the necessity of concentrating on what makes most sense re hardware, I have to say that I know of servers deployed in e.g. Africa on Laptops as these could be prepared from an international IT department and brought to the country of service in the checked-in luggage of the IT technician travelling to deploy.

**Comment by nagilum99** [comment]
Which sounds like: It should be changed to allow profit maximazation of international companies, because Laptops with a proper NIC would probably be more expensive.

Generally Distributions like CH (which XCP-ng is based on) are made for professional servers. That doesn't mean self-buildt servers are excluded, as long as you use enterprise-grade components. When you want to de-concentrage and officially support every cheap SOHO component, someone needs to bring that support.
I'm sure that there would be a lot more possible, if the companies, which benefit from OSS and have special needs, would actively support such by paying developers to contribute (but that would lower the savings-effect, right?).

My 5 cents: I don't see that anyone should take care of such constellations.
A different thing would be, if there are - non profit! - projects in Africa, that can't afford expensive hardware and would need support.

**Comment by olivierlambert** [comment]
I'm on @stormi side: if it's a bug in the driver from the current kernel and the diff is not big (ie easy to integrate), I think it will be a good idea to get it.

**Comment by JanHolbo** [comment]
@nagilum99 for the use case I mentioned, it is a non-profit/NGO that is deploying servers like this to support their regional/national offices.

**Comment by nagilum99** [comment]
It would probably be a good idea to find models, that use e.g. Intel NICS, as they're known to work smoother than RTL thingies.
Sounds like an interesting concept overall. 

Form the log you posted:
https://www.google.com/search?client=firefox-b-d&q=invalid+large+VPD+tag+7f

It seems that problem is already known (if that's the part where it failes - sometimes you get errors but that device is still working).

https://bugzilla.kernel.org/show_bug.cgi?id=196287
It affected Kernel Version: 4.12.0-041200-generic

IIRC Kernel ALT is way newer than the default 4.19 kernel, so there shoudl be a patch somewhere?

**Comment by olivierlambert** [comment]
Yep likely. @rushikeshjadhav is our star to find that :laughing:

**Comment by JanHolbo** [comment]
@nagilum99 I must admit that kernel module Development is not my forte, I can only tell you the outcome. Everytime I boot on the main kernel, it 'recognises' the NIC but the link never comes up - the software cannot see a link, and the switch and NIC does not light their LEDs to indicate that there is a link. If I use the alternate kernel, the link comes up without any user interventions.

**Comment by rushikeshjadhav** [comment]
`kernel-alt` tested by @JanHolbo and found to be working. Thus we can back port from recent kernel which has working driver.

**Comment by stormi** [comment]
The `r8169-module-alt` package will be available in `xcp-ng-testing` repos for 8.1 within a few minutes. For use with the main kernel.

To install:
```
yum install r8169-module-alt --enablerepo=xcp-ng-testing
```

Then reboot on the main kernel.

**Comment by stormi** [comment]
@JanHolbo did the `r8169-module-alt` RPM work for you?

**Comment by stormi** [comment]
I would have like feedback, but will simply close this as solved. Feel free to reopen if the additional driver package doesn't work for you.

**Comment by JanHolbo** [comment]
> I would have liked feedback, but will simply close this as solved. Feel free to reopen if the additional driver package doesn't work for you.

Sorte for there lack of feedback. Life is really busy for me at the moment. 

I never changed from the alternate kernel so did not test the module. I am not running xcp-ng currently and am not able to test this.

I consider it solved and closed. Thank you for your hard work!
