### ISSUE TITLE
Rewrite of varstored for UEFI guests

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#405]
Tests:
* [x] UEFI windows 10 installation on 8.2
* [x] UEFI windows 10 installed on 8.1 with proprietary varstored still works fine after upgrade (yum or ISO, no importance)
* [ ] Test what happens when upgrading a 8.0 XCP-ng that has a UEFI Windows VM to 8.2
* [x] UEFI windows 10 installed on 8.1 and exported then imported to 8.2 works fine
* [x] UEFI windows 10 live migration from 8.1 to 8.2 during RPU
* [x] UEFI windows 10 live migration from 8.2 to 8.2
* [x] UEFI windows 10 cross-pool live migration from 8.1 to 8.2
* [x] UEFI windows 10 cross-pool live migration 8.2 to 8.2

Other tests
* [x] installation of UEFI windows 2016 server on 8.2: ~~currently fails at bootloader installation~~ fixed in 0.2.2
* [x] installation of UEFI CentOS 8 on 8.2: ok, but there are messages on the console after reboot: `MODSIGN: couldn't get UEFI db list` and `Couldn't get size: 0x800000000000000e` (twice). Such messages are also present with varstored.
* [x] VM created and first boot with varstored, then install uefistored instead
* [x] VM created and first boot with uefistored, then install varstored instead: VM gets no display currently
* [x] uefistored logs go to daemon.log and are not verbose enough to cause /var/log filling in case of heavy workloads
* [x] installation of a maximum of different windows versions in UEFI (list them here)
  * [x] Windows 10 
  * [x] Windows 2016 server
  * [x] Windows 2019 server
* [x] Check what happens if one attempts to setup secure boot in Windows

**Comment by beshleman** [comment]
Before I forget, I think we should test what the behavior is when the user attempts to setup secure boot.  The current response is an error code, which Linux is okay with, but I'm not sure about Windows.

**Comment by stormi** [comment]
Ok, added in the list of tests.

**Comment by beshleman** [comment]
Regarding  `[x] Check what happens if one attempts to setup secure boot in Windows`:

As per [Microsoft documentation](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/disabling-secure-boot#re-enable-secure-boot), SB is enabled from the UEFI interface.

Upon attempting to set the PK, the user is told it is not allowed via a pop-up window in the OVMF tui.  This is the desired behavior.  

Tested with Windows 10.

**Comment by stormi** [comment]
Closing. A separate issue addresses secure boot support : #406
