### ISSUE TITLE
Feature Request: QEMU - enable support for vmxnet3 / e1000e NICs

### ISSUE THREAD

**Issue by stack1313** [xcp-ng/xcp#416]
HI team,

Like https://github.com/xcp-ng/xcp/issues/239 is possible to enable vmxnet3 and e1000e support for qemu on xcp-ng ? 
because we want to move from VMware to XCP-NG and some of our applications are only compatible with vmxnet3/e1000e NICs.

Thank you,

**Comment by stack1313** [comment]
@stormi maybe you can help us for this ?

**Comment by olivierlambert** [comment]
Hi,

Xen is a bit different: emulation is only used during boot, not after the kernel boots (after proper Xen PV drivers are loaded). In short, you don't need `vmxnet3` as soon the VM kernel will detect Xen devices.

You can set `e1000` already, but as soon you booted, install PV drivers (if on Windows, no need on Linux). That's it :)

**Comment by stack1313** [comment]
hi @olivierlambert 

Thank you for your explanations, but our applications check the VID and DID of the NIC devices to load some files and mark the machine as "safe".

**Comment by olivierlambert** [comment]
Windows or Linux?

Anyway, `vmxnet3` won't be possible I suppose. `e1000` will but without PV drivers it will be really slow. So in the end, I don't think what you want to achieve is really doable.

Can your application check that's Xen PV drivers instead of VMware stuff?

**Comment by stack1313** [comment]
Windows Machine. 

Today I have these applications running well on a lab kvm host with vmxnet3 as network device.

Why with xen the virtio driver work and vmxnet3 will not ? 

What happen if we activate the vmxnet3 module on qemu and try to boot vm with this device ?

**Comment by olivierlambert** [comment]
Currently, there's no way I'm aware of to use something outside Xen PV drivers or basic emulation (e1000). There's no VirtIO support in Xen (yet).

Xen is not KVM. XCP-ng is not just Xen neither.
