### ISSUE TITLE
Build XCP-ng-Server-SDK

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xcp#42]
There is the XenServer-7.4.0-SDK ... I wonder from what sources they build that, couldn't find a repo (https://github.com/xenserver) with relation to the SDK.

Has anyone the answer?

**Comment by borzel** [comment]
found a bit after some searching:

`XenServer-7.4.0-SDK\XenServer-SDK\XenServer.NET\src` comes from `xenadmin\XenModel\XenAPI`

**Comment by stormi** [comment]
What is this SDK for?

**Comment by borzel** [comment]
it's a (C#) library to interact with XAPI

https://xenserver.org/partners/developing-products-for-xenserver.html

**Comment by stormi** [comment]
xenserver-sdk is built. I never tested it though. https://koji.xcp-ng.org/buildinfo?buildID=1813
