### ISSUE TITLE
Document the ZFS driver

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#424]
At https://xcp-ng.org/docs/storage.html#storage-types

**Comment by stormi** [comment]
https://xcp-ng.org/docs/storage.html#zfs still contains outdated instructions.

By the way I'd like us to move what's still relevant from the [wiki ZFS page](https://github.com/xcp-ng/xcp/wiki/ZFS-on-XCP-ng) to the official documentation. 

We'll also need to document how to transition from the file SR to a zfs SR, both in the ZFS section of the storage page and in the release notes' known issues.

**Comment by stormi** [comment]
> https://xcp-ng.org/docs/storage.html#zfs still contains outdated instructions.
> 
> By the way I'd like us to move what's still relevant from the [wiki ZFS page](https://github.com/xcp-ng/xcp/wiki/ZFS-on-XCP-ng) to the official documentation.
> 
> We'll also need to document how to transition from the file SR to a zfs SR, both in the ZFS section of the storage page and in the release notes' known issues.

**Comment by olivierlambert** [comment]
Okay I can do it. Can you edit this Wiki page to left only what's relevant? When it's done, I'll transpose it to the official doc.

**Comment by stormi** [comment]
Actually, I don't know what's relevant or not. I've always looked at ZFS stuff from a distance and never tried to deeply understand how it works. I agree that everything that is related to ZFS pre-8.0 is to be removed.

**Comment by stormi** [comment]
> https://xcp-ng.org/docs/storage.html#zfs still contains outdated instructions.

I see that what I called "outdated instructions" has been added today :)

The outdated part is that it should use the `zfs` SR type, not `file`.

**Comment by stormi** [comment]
> > https://xcp-ng.org/docs/storage.html#zfs still contains outdated instructions.
> The outdated part is that it should use the `zfs` SR type in 8.2, not `file`.

Handling this part right now, this is the most urgent now that the beta was released and the forum announcement links to the doc.
