### ISSUE TITLE
Document the CephFS driver

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#428]
At https://xcp-ng.org/docs/storage.html

See also the existing wiki page that needs being migrated https://github.com/xcp-ng/xcp/wiki/Ceph-on-XCP-ng-7.5-or-later while dropping anything related to XCP-ng < 8.1

**Comment by stormi** [comment]
The above commit is a step towards closing this issue, but is not enough, so reopening. The wiki page still needs to be migrated and redirected to the new doc.

**Comment by rushikeshjadhav** [comment]
Hope this is closed now.
