### ISSUE TITLE
Strange networking issue

### ISSUE THREAD

**Issue by petercelentanojr** [xcp-ng/xcp#43]
Hi all, 

I am using XCP-NG version 7.4.  I am having a strange networking issue within my xcp-ng box.  The hardware is an i3 with 16GB of ram and a realtek nic.  I currently have 4 VMs running on this host, all in hvm mode, and all using the default "Pool-wide network associated with eth0" virtual NIC.

When running more then 1 VM at a time, and attempting to connect or work with these VMs over the network, the VMs seem to "compete" for use of the single physical NIC on the XCP-NG host.  I can't run iperf simultaneously on two VMs at the same time (on the same physical host).  Is this a normal behavior with VMs running in HVM mode? Is there something else I'm missing here?  What information can I provide to help troubleshoot this issue?

**Comment by necouchman** [comment]
A couple of questions:
- Do the communications issues exist between VMs on the same XCP-NG install?  Or only when they try to communicate with hosts that traverse the physical adapter?
- Have you successfully used this configuration with this same hardware on something other than XCP-NG (e.g. XenServer, VMware, etc.)?
- What type of physical switch is it connected to?

Depending on the answers to those questions, this seems like it may be something on the physical switch causing issues.  Obviously if it's happening in VM-to-VM communications on that single host that's not the issue, but I know at one of my previous places of employment we would limit the number of MAC addresses that could be used on most of the access switch ports as a method of detecting/preventing loops and also to deter folks from doing something like deploy their own wireless access point under their desks.  Again, depending on your environment this may not be the issue, but just what popped into my head.

**Comment by petercelentanojr** [comment]
```Do the communications issues exist between VMs on the same XCP-NG install? Or only when they try to communicate with hosts that traverse the physical adapter?```
Generally, the VMs on my XCP-NG box are not communicating with each other, but when testing communication between each other (without traversing the physical NIC), they are not able to communicate with each other.  They also seem to be able to communicate over the physical NIC one-at-a-time, and the first VM to get a network request responds first, with the other VMs waiting to respond over the physical NIC until after the first request has been completed
```Have you successfully used this configuration with this same hardware on something other than XCP-NG (e.g. XenServer, VMware, etc.)?```
While the box I'm using for XCP-NG currently is a test machine, the hardware is identical to what I am currently running in production under VMware ESXi 6.5.
```What type of physical switch is it connected to?```
The problematic XCP-NG box is connected to a TPlink TL-SG1024 unmanaged switch, going upstream to a ubiquity edgerouter ERPro-8.

Given that I'm using an unmanaged switch, could a looping issue be possible?

**Comment by necouchman** [comment]
> Generally, the VMs on my XCP-NG box are not communicating with each other, but when testing communication between each other (without traversing the physical NIC), they are not able to communicate with each other.

Yeah, this means something else is going on, probably not related to the physical NIC.

> The problematic XCP-NG box is connected to a TPlink TL-SG1024 unmanaged switch, going upstream to a ubiquity edgerouter ERPro-8.

This also makes it unlikely that my initial scenario was correct - unmanaged switches don't usually limit MAC addresses (except by the available memory to store MAC forwarding tables), and it wouldn't matter anyway since you can't change it.

> Given that I'm using an unmanaged switch, could a looping issue be possible?

You'd definitely want to verify you don't have a loop, but you'll usually see other odd behavior - enormous amounts of traffic on the ports, etc. - and not just that more than one VM can't communicate at one time.

You might try toggling the switching mode using either `xe-switch-network-backend bridge` or `xe-switch-network-backend openvswitch` to toggle from one mode to the other.  I think OpenvSwitch (OVS) is the default, so maybe try switching to bridge, first, and see if that works?

You're also welcome to try XenServer 7.4/7.5, instead, and see if that works to nail down whether it's an issue specific to XCP-NG or an upstream issue in the XenServer code.

**Comment by necouchman** [comment]
> Given that I'm using an unmanaged switch, could a looping issue be possible?

Oh, you might also verify your MAC and IP addresses to make sure you don't have any duplicates - if you cloned the VMs or copy/paste some part of the configuration then it's possible that the MAC address got duplicated, and, if you're using DHCP, this could also mean duplicate IP addresses.

**Comment by petercelentanojr** [comment]
My apologies for not replying sooner, but I nailed down the issue. When I imported my vms, for some reason they all had the same Mac address. I regenerated all of their macs, fixed the vms adapter settings to use them with the new macs, and now they are functioning properly. Dunno how I overlooked that... Thank you for your help!
