### ISSUE TITLE
Doumentation: still very brief and full of erros

### ISSUE THREAD

**Issue by akurzawa** [xcp-ng/xcp#432]
Mostly very brief. The open source is great, but sometimes great open source projects (like xcp-ng) lacks the good documentatnion. Unfortunatley (don't hate me for that) xcp-ng is a prime example of that. I know that everyone have limites resources but if You want to get your project more widely available You should document it well, especially document well things that are defferent and unique comparing to Citrix's Hypervisor.

To the point: this time I was browsing some docs about the xo san: few click later 404 error:

https://xen-orchestra.com/docs/xosan_requirements.html

IDK how do You want convince the people to start using Your soft, that have so brief and inclomplete documentatnion. I think it's about the time to make some decisions in this area, and get it covered.

**Comment by olivierlambert** [comment]
We recently moved our doc to VuePress with a nice search bar:

* https://xen-orchestra.com/docs/
* https://xcp-ng.org/docs

So we might have some dead links around, and reporting them (where you found them exactly so we can fix them) would be more efficient than just complaining.

Also, you are posting this on the wrong repo.
