### ISSUE TITLE
XCP-ng Windows : Slow network dowload using WinNAT

### ISSUE THREAD

**Issue by turric4n** [xcp-ng/xcp#433]
Hi,

Currently we have a pool of XCP-ng 8.0.0 hosts, we want to use some Windows Server VM's with Windows Containers support in (Windows docker containers). 

We have critical problems with container WinNAT network inside. Upload speed is fine... but download is slow. 
VM's network it's running fine. 

We tried to remove some things from the ethernet driver like RSC without success because some people point as a valid workarround.

Our network Windows drivers are these XCP-ng Windows PV Tools 8.2.2.200-RC1

![imagen](https://user-images.githubusercontent.com/7852968/91973666-e4b29f00-ed1c-11ea-93c6-0ab150018169.png)

**Comment by olivierlambert** [comment]
Hi,

Be sure to have your server BIOS with Performance mode activated. Outside that, the best place to discuss about this is to use the forum: https://xcp-ng.org/forum

We tend to use the bug tracker for identified/pinpointed issues so we can pass it to devs.
