### ISSUE TITLE
Backport Xen patch to support Ice Lake and Comet Lake CPUs

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#434]
Patch is here: https://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=1fe406685cb19e9544681c6243e7d376deb0297e

It should be trivial.

**Comment by olivierlambert** [comment]
Thanks a lot to @andyhhp for the hint :wink:

**Comment by rushikeshjadhav** [comment]
The patch needed some reformatting but its here. https://github.com/xcp-ng-rpms/xen/pull/3

**Comment by stormi** [comment]
What's the target? 8.2 for sure, but do we also need the change in 8.1?

**Comment by rushikeshjadhav** [comment]
Current patch target is 8.1 as that's what is being used by user. Need to look for its applicability/fitment for 8.2. Will check and create another PR for 8.2.

**Comment by stormi** [comment]
Ok, so I have pushed the patched Xen packages to the testing repository for XCP-ng 8.1.

Install it with:
```
yum update xen-dom0-libs xen-dom0-tools xen-hypervisor xen-libs xen-tools --enablerepo=xcp-ng-testing
```

Then check that `rpm -q xen-hypervisor` says `xen-hypervisor-4.13.0-8.6.2.xcpng8.1.x86_64`

Then reboot.

**Comment by jstorgaard** [comment]
Installed the patch and testing again. 
Very happy to report that everything works great now! No crashes in the VM and application starts as intended.
Thank you all!

**Comment by rushikeshjadhav** [comment]
> Current patch target is 8.1 as that's what is being used by user. Need to look for its applicability/fitment for 8.2. Will check and create another PR for 8.2.

Same patch is applicable and works for 8.2.

**Comment by olivierlambert** [comment]
Nice job lads!

**Comment by stormi** [comment]
The Xen packages in XCP-ng 8.1 that have been pushed with the latest security updates also contain that patch. Closing.
