### ISSUE TITLE
XCP-ng 8.1.0 - vm autostart not working

### ISSUE THREAD

**Issue by Alphaprot** [xcp-ng/xcp#450]
I do not know if this is a XCP-ng Center (20.04.00) bug or related to XCP-ng 8.1.0:

Virtual machines (even the turnkey XOA) with the "autostart on server start" flag enabled won't start automatically. If I list the vm config in the xcp-ng shell ('xe vm-param-get param-name=other-config uuid=uuid-of-vm', I get a feature-flag for `auto_poweron: true`

Side-note: I had a problem on first boot, where the SR (a NVMe flash drive on a PCIe-adapter) which servers as the vm-storage, was not attached when xcp-ng tried to start the VMs. It was attached automatically later on, though.

Is there anything to watch out in `/var/log/daemon.log`? Searching this log for any VM-UUID that should technically auto-start yields nothing.

**Comment by nagilum99** [comment]
I already noticed that you had to go the 'manual way' once. After that, it's possible to add VMs to autostart via XCP-ng center.
Can't tell about XOA for sure.

**Comment by olivierlambert** [comment]
Have you enabled autostart via Xen Orchestra? Please try and report.

**Comment by Alphaprot** [comment]
Thank you for the hint with XO, @olivierlambert - I toggled the autostart option for each VM (the slider was already set to "on", so I disabled and then reenabled it) and rebooted the server. Works like a charm now, so it really appears to be a problem with XCP-ng Center.

Found another bug, though - but that will be the content of a new bug report as it has nothing to do with this one.

**Comment by nagilum99** [comment]
IIRC there was more than to adjust the VM, there was a host/pool setting needed to enable autostart function at all.
It seems that it's not automatically being set, when you enable it for a VM. (But I'm sure XOA did that, a while ago)
For XCP-ng center it doesn't do the host (pool?) task.

(For those who ask why: It could end in a mess, if you have a pool and HA active - so they (Citrix) set that to manual instead of implementing more smart fuctions to safely enable HA)

**Comment by olivierlambert** [comment]
Closing then :)

**Comment by nagilum99** [comment]
Why are you closing it, if XCP-ng center would need a fix to enable autostart if it hasn't set before?

**Comment by Alphaprot** [comment]
@nagilum99 XCP-ng Center is a community driven implementation of Citrix XenCenter and not maintained by the XCP-ng project - so it is fair to close it. I could open this issue on their GitHub repo though

**Comment by olivierlambert** [comment]
Because it's an *XCP-ng Center* thing, not XCP-ng related. Feel free to report on the appropriate repo.

**Comment by Alphaprot** [comment]
Ta da, now on the appropriate repo.

**Comment by nagilum99** [comment]
Thanks, didn't notice it's a different repo.

**Comment by Alphaprot** [comment]
Hm, GitHub automatically linked it as soon as I mentioned it, so clicking on this information should take you there.
But in case it really isn't displayed on your client - here you go: [Link to the issue on xenadmin-Repo](https://github.com/xcp-ng/xenadmin/issues/172#issue-477858853)

**Comment by sojimp** [comment]
My new install of xcp-ng wasn't working with autostart. I don't have XO, so it was necessary to set the "auto_poweron" flag on the pool. Hope this helps someone else that finds this issue.

```
# xe pool-list
# xe pool-param-set uuid=[the_pool_uuid] other-config:auto_poweron=true
```

After a reboot, all my VMs auto started as expected.

Reference: https://www.incredigeek.com/home/auto-start-vm-after-xenserver-reboot/
Based on: https://support.citrix.com/article/CTX133910 (404)
