### ISSUE TITLE
Will this work on W7 x64?

### ISSUE THREAD

**Issue by djcrawleravp** [xcp-ng/xcp#456]
Hello there and thanks in advance for your time, Can you tell me if these drivers will work on Windows 7 x64?

**Comment by olivierlambert** [comment]
What are "these drivers" specifically?

**Comment by djcrawleravp** [comment]
Attempting to install the xcp-ng (as a requirement from my VPS provider) on Windows 7 won't let me run the agents after the installation.

**Comment by olivierlambert** [comment]
I don't understand. You don't install XCP-ng on Windows. What are you trying to achieve exactly?

**Comment by djcrawleravp** [comment]
My VPS provider told me to install this version https://github.com/xcp-ng/win-pv-drivers/releases/tag/v8.2.2.200-RC1 <https://github.com/xcp-ng/win-pv-drivers/releases/tag/v8.2.2.200-RC1> on Windows 7

**Comment by olivierlambert** [comment]
See https://github.com/xcp-ng/xcp/wiki/Windows-guest-tools-community-testing and https://github.com/xcp-ng/win-pv-drivers/releases/download/v8.2.2.200-RC1/XCP-ng.Windows.PV.Drivers.8.2.2.200-rc1.zip for the drivers. I'm not sure they are tested for Windows 7.

Please contact your VPS vendor for more details.
