### ISSUE TITLE
UEFI VM clone failing on 8.2

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#458]
See https://xcp-ng.org/forum/topic/3856/xcp-ng-8-2-can-t-clone-windows-eufi-host

Reproduced internally.

It fails because `varstored-tools` is missing.

```
Nov 23 15:19:44 r620-5 forkexecd: [error||0 ||forkexecd] 31020 (/usr/bin/varstore-rm -c d535371a-1c0c-3bac-1f1f-1bd012f43bec -r /var/run/xen/...) exited with code 127 
```

**Comment by stormi** [comment]
See https://github.com/xapi-project/xen-api/commit/273339d5f5ff97edf8dc907f291d7d4a6376094a

**Comment by stormi** [comment]
And https://github.com/xapi-project/varstored/commit/814e77abcfe4b1675e4f4a25b66a1045c266484c

**Comment by stormi** [comment]
Also related: even with varstored-tools installed, in my tests a Windows 2019 VM, cloned from CR VM with uefistored takes a looooooot longer to boot (long black screen with just the tianocore logo) than the same VM cloned with varstored.

**Comment by beshleman** [comment]
Got it.  I'll run some tests.  Optimizing the search is still TODO, so I'm expecting that to be the culprit.

**Comment by beshleman** [comment]
@stormi I confirmed that the Windows boot debugger and boot debug wait time was still on.  After disabling that, the VM boot time drops to around a half a minute as normal.

**Comment by stormi** [comment]
Update pushed to 8.2 updates repos on last Wednesday
