### ISSUE TITLE
Leaving xentools in dvd drive before upgrading to xcp-ng leaves vm unbootable.

### ISSUE THREAD

**Issue by planeturban** [xcp-ng/xcp#46]
As above.

Replicate: 
Deploy vm on xenserver, mount xentools iso. Upgrade DOM0. DVD drive will be "" (nothing) and xcp will report it couldn't attach storage and not boot vm.

Changing DVD drive to <Empty> will allow boot.

I acctually reported this on Xenserver 6.5 (or if it was 6.0?) so one could say it works as designed.

**Comment by olivierlambert** [comment]
Hi @planeturban 

I'm not sure to get it. What could we do against this?

**Comment by planeturban** [comment]
I’d say set the DVD drive to “<Empty>” if the image configured in the vm is not found.

**Comment by planeturban** [comment]
Unmount the missing image that is.

**Comment by olivierlambert** [comment]
But where to do so? I don't understand. It's up to the user to clear that before starting to upgrade, so it should be explained in the documentation, right?

**Comment by planeturban** [comment]
You're completely right, documentation is the key. Looking at the Xenserver upgrade guide is says "Empty the CD/DVD drives of the VMs in the pool(s)." as prereq.

Is there a documentation project for xcp-ng?

**Comment by olivierlambert** [comment]
There is a blog post here: https://xcp-ng.org/2018/06/11/migrate-from-xenserver-to-xcp-ng/
I'll update it with the info :)

**Comment by olivierlambert** [comment]
Done: I added:

> > Note: also think to eject all CD inserted in your VMs. This can be done with `xe vm-cd-eject --multiple`.

**Comment by planeturban** [comment]
Perfect!
