### ISSUE TITLE
XSConsole DNS settings not retained after reboot

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#461]
See https://xcp-ng.org/forum/topic/3277/dns-config-on-8-1-hosts-disappearing

Looks like it only modifies `resolv.conf` without updating the XAPI configuration

**Comment by olivierlambert** [comment]
I think we should:

1. Write a patch
2. Ask Citrix to publish that code in a repo in the end…

**Comment by benjamreis** [comment]
Solved by: https://github.com/xcp-ng-rpms/xsconsole/pull/3

To be closed on release @stormi?

**Comment by stormi** [comment]
Ideally, yes, only when the fix is released.

**Comment by stormi** [comment]
Fix released and contributed upstream. https://github.com/xapi-project/xsconsole/pull/2
