### ISSUE TITLE
Fix guest tools on CentOS 8.3

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#464]
See https://github.com/xenserver/xe-guest-utilities/pull/89

**Comment by stormi** [comment]
Also add support for CentOS Stream: https://github.com/xenserver/xe-guest-utilities/pull/92

**Comment by wranders** [comment]
Was waiting for it to get merged before I mentioned it, but glad you're keeping an eye out.

**Comment by wranders** [comment]
@stormi Followed up with the upstream maintainers and they have merged my PR.

**Comment by stormi** [comment]
Thanks for letting us know.

**Comment by stormi** [comment]
Done, will be released as an update to XCP-ng 8.2 soon.
