### ISSUE TITLE
Xcp guest utils iso is returning distribution/version not found for centos 8

### ISSUE THREAD

**Issue by wcom939** [xcp-ng/xcp#467]
Hello,

OS Version info:
![image](https://user-images.githubusercontent.com/16446451/102613271-316d8a80-4100-11eb-890a-581a9567caf8.png)

XCP host version info:
![image](https://user-images.githubusercontent.com/16446451/102613349-4fd38600-4100-11eb-9aa4-34d0c8433030.png)

Error message:
![image](https://user-images.githubusercontent.com/16446451/102613417-709bdb80-4100-11eb-8e5c-96624d684025.png)

**Comment by stormi** [comment]
There's been a fix upstream for CentOS 8.3 (see #464). I wasn't aware CentOS 8.2 would be affected.

We will release a fixed ISO at some point. Until then, you can use the `xe-guest-utilities-latest` package from EPEL, which is maintained by @cheese.

**Comment by stormi** [comment]
Correction: you are probably using CentOS 8.3, or CentOS Stream. I thought it was 8.2 but that was the version of the XCP-ng host.

**Comment by stormi** [comment]
Closing as duplicate for #464 then.

**Comment by wcom939** [comment]
@stormi  just a heads up xe-guest-utilities-latest doesnt seem to be working either

![image](https://user-images.githubusercontent.com/16446451/102614454-421f0000-4102-11eb-952a-3b9cfc9482d7.png)

I'll try and use the linked fix and see if that works

**Comment by stormi** [comment]
I think the update to EPEL has not been validated by Fedora yet: https://xcp-ng.org/forum/post/34309

**Comment by wcom939** [comment]
Thanks very much I'll give that a try

this and CentOS stream are just more reasons for me to move my CentOS boxes to Ubuntu!

**Comment by cheese** [comment]
> Thanks very much I'll give that a try
Please enable epel-testing repo to get the update for now.
