### ISSUE TITLE
PCI passthrough issues

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#470]
Cf https://xcp-ng.org/forum/topic/4001/passthough-on-8-2-hangs-on-vm-reboot-and-stops-other-vms-passthough-devices-working

Steps to fix the problem:

1. Reproduce it internally
2. Port Xen from 8.1 into 8.2, test and see if it still a problem (or vice-versa)
3. If Xen is the issue, open a thread on xen-devel. If not investigate the dom0

**Comment by stormi** [comment]
Debugging it with the help of the users led to report an issue to the Xen project who issued a security advisory about it: https://xenbits.xen.org/xsa/advisory-360.html

**Comment by stormi** [comment]
Update candidate available, see https://xcp-ng.org/forum/post/35658

Closing. The rest is standard process for handling update candidates.
