### ISSUE TITLE
[SOLVED] XCP-ng.Windows.PV.Drivers.8.2.2.200-rc1 Not working correctly.

### ISSUE THREAD

**Issue by fishscene** [xcp-ng/xcp#474]
2021/01/12:
Server: XCP-NG 8.1, Build date 2020-06-02
VM: Fresh install of Windows 10 x64 Professional. All updates installed as of today.

In Device Manager:
- Storage Controllers
-- XenServer PV Storage Host Adapter
Windows cannot start this hardware device because its configuration information (in the registry) is incomplete or damaged. (Code19)

- System devices
--XenServer Interface
Windows cannot start this hardware device because its configuration information (in the registry) is incomplete or damaged. (Code19)
-- XenServer PV Network Class
Windows cannot start this hardware device because its configuration information (in the registry) is incomplete or damaged. (Code19)

Also, upon first reboot after installing drivers, a message appears saying the drivers failed to install. This message sometimes pops up while windows is booting just before the logon interface is displayed.

Ordinarily I'd report this in repo for the driver, but there's 1 issue listed that says to report issues here.
Source: https://github.com/xcp-ng/win-pv-drivers/issues

*Update*
I tried my usual trick of trying to extract the drivers manually from the %TMP% directory after initiating the installation, but no temp files are created.

**Comment by olivierlambert** [comment]
Hi,

Please check you didn't mix Citrix Windows update tools enabled and our XCP-ng drivers. This will cause this kind of issues.

To see if it's enabled, in XO, advanced tab: "Windows update tools".

**Comment by fishscene** [comment]
1) Shut down the VM
2) Take snapshot.
3) In Xen Orchestra, click on Win10 VM. 
4) Click on Advanced.
5) Toggle off Windows Update Tools.
6) Fire up Win10 VM.
7) Download drivers from: https://github.com/xcp-ng/win-pv-drivers/releases/tag/v8.2.2.200-RC1
8) Install the drivers.
9) Reboot Win10 VM.
10) Success!

Thanks @olivierlambert 
Sorry this took a while for me to follow up on. Real life and all. :)

**Comment by olivierlambert** [comment]
Thanks for the feedback :+1:

**Comment by alonsoknet** [comment]
Many thanks
