### ISSUE TITLE
xcp-ng 7.5.0 yum upgrade - missing symlink from xcp-featured - can't connect to anything

### ISSUE THREAD

**Issue by oallart** [xcp-ng/xcp#48]
Disclaimer: I know it is experimental, but I wanted to have a try :)
After doing a 7.5.0 yum upgrade, server rebooted fine. SSH fine. VMs are up. 
No connection on 443.
I tracked the issue down to v6d.service not running.
By inspecting the log, I found out that /opt/xensource/libexec/v6d is missing
`systemd[11596]: Failed at step EXEC spawning /opt/xensource/libexec/v6d: No such file or directory`

And indeed, it is missing after upgrade.

yum tells me that /opt/xensource/libexec/v6d is part of package xcp-featured-1.1.0-2.el7.centos.x86_64 : XCP-ng feature daemon

yum reinstall fixed it. It is actually a symlink though;
`/opt/xensource/libexec/v6d -> /opt/xensource/libexec/xcp-featured`

Something that went missing in  the upgrade somehow, but that fixed for me with `xe-toolstack-restart`

**Comment by olivierlambert** [comment]
Hmmm strange, it sounds random, I couldn't reproduce it myself. Thanks for the feedback.

**Comment by borzel** [comment]
I ran into the same issue just now

Testlab at work, two hosts; Upgraded the master from 4.7.1 to 7.5.0 with `yum`. Creation of the symlink with `ln -s /opt/xensource/libexec/xcp-featured /opt/xensource/libexec/v6d` solved it.

**Comment by borzel** [comment]
before I try to update the second host I preserve it's actual state to the backuppartition (using dd).

So we have something to look at :-)

**Comment by borzel** [comment]
same on the second host :-|

@stormi let my know what info you need to find the root cause here. (I'm in vacation from 24. August till September)

**Comment by stormi** [comment]
@borzel I'm currently in vacation myself :)

I think /var/log/yum.log could be useful

**Comment by borzel** [comment]
/var/log/yum.log (from the second host in pool)

```
Aug 15 14:44:24 Installed: xcp-ng-release-7.5.0-3.x86_64
Aug 15 14:44:25 Installed: xcp-ng-center-7.5.0.8-3.noarch
Aug 15 14:44:26 Updated: systemd-libs-219-19.el7_2.7.xs7.3.x86_64
Aug 15 14:44:31 Updated: systemd-219-19.el7_2.7.xs7.3.x86_64
Aug 15 14:44:32 Installed: systemd-networkd-219-19.el7_2.7.xs7.3.x86_64
Aug 15 14:44:34 Installed: xcp-ng-release-config-7.5.0-3.x86_64
Aug 15 14:44:35 Installed: libempserver-1.0.3-1.x86_64
Aug 15 14:44:36 Installed: xcp-ng-pv-tools-7.29.0-2.2.xcp.noarch
Aug 15 14:44:36 Installed: xcp-ng-updater-1.1.0-2.noarch
Aug 15 14:44:37 Installed: xcp-ng-deps-7.5.0-3.noarch
Aug 15 14:44:37 Updated: systemd-sysv-219-19.el7_2.7.xs7.3.x86_64
Aug 15 14:44:37 Erased: xenserver-release-config-7.4.0-1.x86_64
Aug 15 14:44:38 Erased: xencenter-7.4.0.5932-1.noarch
Aug 15 14:44:38 Erased: xenserver-pv-tools-7.24.0-1.noarch
Aug 15 14:44:39 Erased: xenserver-release-7.4.0-1.x86_64
Aug 15 14:44:40 Erased: vgpu-7.3.0-1.x86_64
Aug 15 14:46:25 Updated: 1:openssl-libs-1.0.2k-8.el7.x86_64
Aug 15 14:46:25 Updated: libqb-1.0.1-6.el7.centos.x86_64
Aug 15 14:46:26 Updated: corosynclib-2.4.0-12.xs+1.2.0.x86_64
Aug 15 14:46:26 Updated: corosync-2.4.0-12.xs+1.2.0.x86_64
Aug 15 14:46:33 Updated: kernel-4.4.52-4.0.7.1.x86_64
Aug 15 14:46:34 Updated: message-switch-1.11.0-6.el7.centos.x86_64
Aug 15 14:46:34 Updated: dlm-lib-4.0.7-3.el7.centos.x86_64
Aug 15 14:46:35 Installed: libtool-ltdl-2.4.2-21.el7_2.x86_64
Aug 15 14:46:36 Installed: pacemaker-libs-1.1.16-12.el7.centos.9.x86_64
Aug 15 14:46:36 Installed: pacemaker-cluster-libs-1.1.16-12.el7.centos.9.x86_64
Aug 15 14:46:37 Installed: sbd-1.3.0-6.xs+1.0.0.x86_64
Aug 15 14:46:37 Updated: dlm-4.0.7-3.el7.centos.x86_64
Aug 15 14:47:19 Updated: xengt-4.4.0+10-modules-4.0.0-1.x86_64
Aug 15 14:47:21 Updated: vhd-tool-0.20.0-4.2.xcp.el7.centos.x86_64
Aug 15 14:47:22 Updated: 1:openssl-1.0.2k-8.el7.x86_64
Aug 15 14:47:22 Updated: xapi-storage-0.16.0-1.el7.centos.x86_64
Aug 15 14:47:23 Updated: xcp-python-libs-2.0.3.xcp-1.noarch
Aug 15 14:47:23 Installed: xcp-emu-manager-0.0.3-1.x86_64
Aug 15 14:47:24 Updated: xapi-xe-1.90.6-1.x86_64
Aug 15 14:47:24 Installed: sm-transport-lib-0.5.0-1.el7.centos.noarch
Aug 15 14:47:24 Updated: xengt-userspace-4.0.0-1.x86_64
Aug 15 14:47:25 Updated: gfs2-utils-3.1.10-3.el7.centos.x86_64
Aug 15 14:47:27 Updated: forkexecd-1.8.0-5.el7.centos.x86_64
Aug 15 14:47:27 Installed: libseccomp-2.2.1-1.el7.x86_64
Aug 15 14:47:28 Updated: xen-hypervisor-4.7.5-5.5.1.xcp.x86_64
Aug 15 14:47:28 Updated: xen-libs-4.7.5-5.5.1.xcp.x86_64
Aug 15 14:47:28 Updated: xen-dom0-libs-4.7.5-5.5.1.xcp.x86_64
Aug 15 14:47:29 Installed: 2:qemu-dp-2.10.2-1.2.0.x86_64
Aug 15 14:47:31 Updated: 2:qemu-2.10.2-3.0.5.x86_64
Aug 15 14:47:31 Updated: xen-tools-4.7.5-5.5.1.xcp.x86_64
Aug 15 14:47:32 Updated: xen-dom0-tools-4.7.5-5.5.1.xcp.x86_64
Aug 15 14:47:32 Installed: nbd-3.14-2.el7.x86_64
Aug 15 14:47:33 Installed: xapi-storage-plugins-1.6.0-1.x86_64
Aug 15 14:47:34 Installed: inotify-tools-3.14-8.el7.x86_64
Aug 15 14:47:37 Installed: xapi-clusterd-0.9.0-1.el7.centos.x86_64
Aug 15 14:47:46 Updated: xapi-core-1.90.6-1.x86_64
Aug 15 14:48:25 Updated: guest-templates-json-1.7.8-1.noarch
Aug 15 14:48:44 Updated: guest-templates-json-data-windows-1.7.8-1.noarch
Aug 15 14:48:44 Updated: xenops-cli-1.1.0-5.el7.centos.x86_64
Aug 15 14:48:44 Updated: xenopsd-0.52.1-1.el7.centos.x86_64
Aug 15 14:48:46 Updated: xenopsd-xenlight-0.52.1-1.el7.centos.x86_64
Aug 15 14:48:48 Updated: xenopsd-xc-0.52.1-1.el7.centos.x86_64
Aug 15 14:48:48 Updated: guest-templates-json-data-xenapp-1.7.8-1.noarch
Aug 15 14:48:50 Updated: guest-templates-json-data-other-1.7.8-1.noarch
Aug 15 14:49:09 Updated: guest-templates-json-data-linux-1.7.8-1.noarch
Aug 15 14:49:10 Updated: gpumon-0.11.0-5.el7.centos.x86_64
Aug 15 14:49:13 Updated: rrdd-plugins-1.1.7-4.el7.centos.x86_64
Aug 15 14:49:14 Updated: ocaml-xenops-tools-2.0.0-6.el7.centos.x86_64
Aug 15 14:49:16 Updated: squeezed-0.18.0-5.el7.centos.x86_64
Aug 15 14:49:18 Updated: xapi-tests-1.90.6-1.x86_64
Aug 15 14:49:19 Updated: xcp-rrdd-1.6.0-4.el7.centos.x86_64
Aug 15 14:49:20 Updated: blktap-3.5.0-1.17.x86_64
Aug 15 14:49:21 Updated: xen-device-model-0.10.2.xs-3.0.1.x86_64
Aug 15 14:49:21 Updated: xengt-modules-4.0.0-1.x86_64
Aug 15 14:49:21 Updated: xenserver-firstboot-1.0.7-1.1.xcp.noarch
Aug 15 14:49:21 Updated: interface-rename-2.0.2-1.noarch
Aug 15 14:49:22 Updated: 1:openssl-perl-1.0.2k-8.el7.x86_64
Aug 15 14:49:22 Updated: qlogic-fastlinq-8.30.15.0-1.el7.centos.x86_64
Aug 15 14:49:23 Updated: intel-igb-5.3.5.3-2.el7.centos.x86_64
Aug 15 14:49:24 Updated: openvswitch-2.5.3-2.2.3.x86_64
Aug 15 14:49:25 Updated: xapi-nbd-1.3.0-3.el7.centos.x86_64
Aug 15 14:49:26 Updated: sm-rawhba-1.18.0-1.31.x86_64
Aug 15 14:49:26 Updated: xsconsole-10.1.7-1.x86_64
Aug 15 14:49:26 Updated: control-slice-1.1.0-1.x86_64
Aug 15 14:49:27 Updated: vendor-update-keys-1.3.6-1.noarch
Aug 15 14:49:28 Updated: rrd2csv-1.0.5-5.el7.centos.x86_64
Aug 15 14:49:28 Updated: linux-guest-loader-2.2.1-1.noarch
Aug 15 14:49:30 Updated: sm-1.18.0-1.31.x86_64
Aug 15 14:49:32 Updated: xcp-networkd-0.29.0-1.el7.centos.x86_64
Aug 15 14:49:32 Updated: host-upgrade-plugin-1.1.5-1.noarch
Aug 15 14:49:33 Updated: sm-cli-0.17.0-5.el7.centos.x86_64
Aug 15 14:49:34 Updated: vncsnapshot-1.2a-xs18.x86_64
Aug 15 14:50:01 Updated: pbis-open-8.2.2-1.7.2.x86_64
Aug 15 14:50:02 Updated: 2:microcode_ctl-2.1-26.xs1.x86_64
Aug 15 14:50:04 Updated: xapi-storage-script-0.21.0-1.el7.centos.x86_64
Aug 15 14:50:05 Updated: xcp-featured-1.1.0-2.el7.centos.x86_64
Aug 15 14:50:08 Updated: linux-guest-loader-data-2.2.1-1.noarch
Aug 15 14:50:15 Updated: linux-firmware-20170622-3.2.noarch
Aug 15 14:50:15 Updated: strace-4.9-1.1.5.x86_64
Aug 15 14:50:16 Updated: wsproxy-1.4.0-5.el7.centos.x86_64
Aug 15 14:50:24 Updated: QConvergeConsoleCLI-Citrix-2.0.00-24.3.xcp.x86_64
Aug 15 14:51:26 Erased: emu-manager-0.0.6-1.x86_64
```

**Comment by oallart** [comment]
Specfile for `xcp-featured-1.1.0-2` is at https://github.com/xcp-ng-rpms/xcp-featured/blob/master/SPECS/xcp-featured.spec
but the one for a previous version `xcp-featured-1.0.0-2` 
https://github.com/xcp-ng/xcp-ng-specs/blob/e139eb4324513874a660954058e0ea479b77bf50/SPECS/xcp-featured.spec
 has an interesting comment and matching code;

> * Wed Apr 25 2018 John Else <john.else@gmail.com> - 1.0.1-2
> - Prevent symlink deletion on upgrade

To clarify, `xcp-featured-1.1.0-2` also has that comment but no code to handle the difference it seems.

The deletion is highlighted here:
https://github.com/xcp-ng-rpms/xcp-featured/commit/6247e52b5989d04d1c369873908592dbec84a2cc#diff-d70e182c8eea4af9d3ff6606e74bb886

```
%post
case "$1" in
  1)
    # initial install
    ln -fs %{_libexecdir}/xcp-featured %{_libexecdir}/v6d
    ;;
  2)
    # upgrade
    ;;
esac
%systemd_post v6d.service

%postun
case "$1" in
  0)
    # uninstall
    rm -f %{_libexecdir}/v6d
    ;;
  1)
    # upgrade
    ;;
esac
```

It's actually a regression from this commit: https://github.com/xcp-ng/xcp-ng-specs/commit/4e2a614ffb31336795262517c3495b983489d193#diff-d70e182c8eea4af9d3ff6606e74bb886

I could be wrong but I think we need this bit of code to fix our problem.

**Comment by olivierlambert** [comment]
Thanks for your report, @stormi will take a look as soon he's back :+1:

**Comment by stormi** [comment]
To understand https://github.com/xcp-ng/xcp-ng-specs/commit/4e2a614ffb31336795262517c3495b983489d193#diff-d70e182c8eea4af9d3ff6606e74bb886 you need to know that during a RPM update, %postun of the old package gets executed after %post of the new package. So with xcp-featured-1.0.1-1 the symlink would get deleted on the next upgrade. 

xcp-featured-1.0.1-2 tried to fix that in making the removal only when the package is uninstalled, but not during upgrades. But it only partly worked because upgrading xcp-featured-1.0.1-1 to xcp-featured-1.0.1-2 would still execute the %postun section of the older package after %post of the newer package.

xcp-featured-1.1.0-2 changes the way it works by making the symlink belong to the package rather than being handled in scriptlets. It's cleaner. Since the symlink belongs to the package, it's installed with it (no need to do it in %post) and uninstalled with it (no need to do it in %postun).

However, I missed that upgrading xcp-featured-1.0.1-1 to xcp-featured-1.1.0-2 would still remove the symlink since the old %postun that blindly removes the symlink gets executed at the end. 

I see no reason why upgrading xcp-featured-1.0.1-2 to xcp-featured-1.1.0-2 would remove the symlink, though. Could it be that your hosts had xcp-featured-1.0.1-1 ?

**Comment by oallart** [comment]
Thanks for that comprehensive review.
If it is any help here's an extract from my yum history;
`
    Updated     xcp-featured-1.0.0-1.el7.centos.x86_64               @install/$releasever
    Update                   1.1.0-2.el7.centos.x86_64               @xcp-ng-base
`
I did upgrade from 7.4.0 to 7.5.0 (didn't go through 7.4.1)

**Comment by olivierlambert** [comment]
That's probably the reason, we had an issue with `xcp-featured` in 7.4.0.

**Comment by stormi** [comment]
That's the reason indeed. @borzel does it explain your issue too?

**Comment by oallart** [comment]
Does that mean it is discouraged to upgrade from 7.4.0 straight to 7.5.0 then ? We had a look at the changes from 7.4.0 to 7.4.1 and decided we didn't need to upgrade. 7.5 was definitely an option. 
My point is, a potentially large number of people may try to upgrade without the intermediate step to 7.4.1. I understand the upgrade path with yum is still experimental, but it's a great feature.

**Comment by olivierlambert** [comment]
I would recommend to upgrade with ISO, this way you are sure it's OK. `yum` process is still young, despite the fact it works pretty well from 7.4.1. But from 7.4.0, yeah, go for ISO if you want peace of mind. Otherwise, expect to tinker a bit to get back `xcp-featured` (not a big deal but you'll have the issue)

**Comment by stormi** [comment]
I could fix it with a %triggerun scriplet but whether it's worth spending a few hours on it depends on whether we expect to support upgrading 7.4.0 via yum in the future.

**Comment by olivierlambert** [comment]
I think it's far from being a priority right now :dancer:

**Comment by oallart** [comment]
And we have this https://github.com/xcp-ng/xcp/issues/48 with a workaround to get things going so that's nice :+1:

**Comment by borzel** [comment]
I did an upgrade last week (from XCP-ng 7.4.0 (i think)) without any issue :-) was suprissed

**Comment by stormi** [comment]
This issue is adressed in the upgrade documentation: https://github.com/xcp-ng/xcp/wiki/Upgrade-Howto#5-workaround-an-upgrade-bug-in-xcp-ng-740-only-if-current-installed-version--740
