### ISSUE TITLE
First time password change

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#481]
## Context

In some case (bundling XCP-ng with hardware for OEMs), we might want a specific setup where at first boot, the user can set its own password, avoiding to keep a generic default password (unsecure).

## Workflow

* `xsconsole` seems the best place to ask about new password before anything else
* XO Lite might be another possibility later

## Technical implem

* A key in the installer (selecting "change password at first boot") that will be read by first boot script and do a `chage -d 0 root`?
* directly in the installer commands maybe?
* We must change xsconsole to support it

**Comment by benjamreis** [comment]
Feature is already available when installing an host during PXE without providing a password.
At first boot, creating a password will be demander by the XSConsole UI.

It's not possible using the installation ISO, but I don't think it's relevant.

**Comment by olivierlambert** [comment]
Yup, closing it.
