### ISSUE TITLE
After XCP-ng installation I see just the BIOS

### ISSUE THREAD

**Issue by RGB-Error** [xcp-ng/xcp#484]
What I use:

- **Mainboard**: H310M PRO-D
- **Processor**: i5-9400F (no internal GPU)
- **BIOS version**: E7B33IHB.180
- **BIOS build Date**: 05/27/2019
- **BIOS mode**: UEFI
- **GPU**: GTX 1660 ti

- **Program**: "Rufus" to set up the installation medium
- **XCP-ng version**: 8.2

After the successfull installation process  you can see the request to remove the installation medium.
The installation run through like in the [dokumentation ](https://xcp-ng.org/docs/install.html#iso-installation)descripted.
After the reboot of the PC XCP-ng is not loading. It boots direct in to the BIOS. No error or something else!
From other drives (Linux, Windows) the PC starts without problems.

The boot prioprity was edited too, but without changes.
The BIOS is runns on default settings, but "secure boot" is disabled.

This is the partitioning of the drive from a linux live system:

Partition|FileSystem|Label|Size|Used|Unused|Flags|
---------|------------|-----|-----|-----|---------|-----|
/dev/sda5|ext3|logs-qwthqe|4 GiB|135,01 MiB|3,87 BiB|msftdata
/dev/sda2|unknown|---|18 GiB|---|---|msftdata
/dev/sda1|ext3|root-qwthqe|18 GiB|1,68 GiB|16,32 GiB|msftdata
/dev/sda4|fat16|BOOT-QWTHQE|512 MiB|---|---|boot,esp
/dev/sda6|linux-swap|swqp-qwthqe|1 GiB|0,00 B|1,00 GiB|swap
/dev/sda3|unknown|---|405.64 GiB|---|---|lvm

XCP-ng with the version 8.2 based on the kernel verison 4.19. With the infomation of [ohter sites ](https://linux-hardware.org/index.php?probe=f08ce9bd47)the drivers should be ok.
Is there a reason why XCP-ng is not booting or not recognized? Maybe the partitions, mainboard, chipset or ...?

Thank you for your advice.

**Comment by olivierlambert** [comment]
Hi!

It's better to use community forum for "specific" questions/issues than a reproducible bug :)

We'll help you there: https://xcp-ng.org/forum/ :+1:
