### ISSUE TITLE
KB4535680 will not be installed 

### ISSUE THREAD

**Issue by BoarderEB** [xcp-ng/xcp#487]
Hi,

the Windows security update KB4535680 cannot be installed. It end with the error code 0x800f0922.
I have the problem on different XCP-NG Servers with different Windows versions as a guest. 

**Quote from Microsoft** 
Issue: Some original equipment manufacturer (OEM) firmware might not allow for the installation of this update.
Workaround: To resolve this issue, contact your firmware OEM.

[kb4535680](https://support.microsoft.com/en-us/topic/kb4535680-security-update-for-secure-boot-dbx-january-12-2021-f08c6b00-a850-e595-6147-d0c32ead81e2)

System: 
XCP-NG 8.1 and also after update to 8.2
XCP-ng Windows PV Tools 8.2.2.200-RC1
Windows 10 + Windows Server 2019

**Comment by olivierlambert** [comment]
That's because it's an update related to secure boot. VM secure boot is coming very soon in XCP-ng, but until then, I think it's normal the update can't be applied.

**Comment by olivierlambert** [comment]
Note: after secure boot is released in XCP-ng, we'll reopen the issue if that doesn't fix it.

**Comment by BoarderEB** [comment]
Yes, it has no security relevance for XPC-NG . But being unable to install the kb4535680 breaks the auto-update function of Windows Server 2019. I only get the auto-updates to work again when the install of the fix is deactivated with wushowhide. This is of course also a problem for Microsoft. But it should make it clear why it is very important to solve it.  There will be some machines in the wild that won't get any updates. 

I'm still looking for a way to update it:

Is there current a way to boot in bios-mode? As you described it [here](https://github.com/vatesfr/xen-orchestra/issues/4264).

After a `xe vm-param-set  uuid=[vm-uuid] HVM-boot-params:firmware=bios ` i get by start of the vm the massage "qemu-upstream-uefi don't boot in bios mode".

**Comment by olivierlambert** [comment]
You need to also set another parameter (removing `qemu-upstream-uefi` key if I remember) to be able to boot on BIOS.

**Comment by BoarderEB** [comment]
Thanks,

to change the vm from uefi to bios this:
```
xe vm-param-set uuid=[vm-uuid] platform:device-model=qemu-upstream-compat
xe vm-param-set uuid=[vm-uuid] HVM-boot-params:firmware=bios
```
And back from bios to uefi:
```
xe vm-param-set uuid=[vm-uuid] platform:device-model=qemu-upstream-uefi
xe vm-param-set uuid=[vm-uuid] HVM-boot-params:firmware=uefi
```

But I find no way to boot the win-vm without to change partitionstabelle to a mbr. I think that's even more complicated than [hiding the update](https://www.zdnet.com/article/microsoft-releases-tool-to-hide-or-block-unwanted-windows-10-updates/) from the autoupdater with [wushowhide.diagcab](https://dlgbit.winfuture.de/Ynd-cr_Ma5O_-k8FzY5oOA/1617139704/3535/software/wushowhide/wushowhide.diagcab).

I'm waiting that secure boot is released.

**Comment by olivierlambert** [comment]
We'll keep you posted, it shouldn't be that long now :)

**Comment by stormi** [comment]
Both secure boot support and the fix for this KB installation are now available for testing: https://xcp-ng.org/forum/post/41541

**Comment by BoarderEB** [comment]
Woohoo! 👍
