### ISSUE TITLE
Is IBM System x3100 compatible with XCP-NG?

### ISSUE THREAD

**Issue by gillerby** [xcp-ng/xcp#490]
It's a bit of an old server, so it's not in citrix compatibility list.
The server is currently running VMware ESXi 5.0.0, so I don't think there should be a problem, but I'd rather ask in case there's something I should look out for.

IBM System x3100 with intel Core i3-2100 CPU 3.10GHz

The manual, just in case 
https://www.manualslib.com/manual/830415/Ibm-System-X3100-M4.html

**Comment by olivierlambert** [comment]
Hi,

For questions and suggestions, it's better to open [a thread of the forum](https://xcp-ng.org/forum) to avoid notification for XCP-ng devs :)

About your question, check what we say on: https://xcp-ng.org/docs/hardware.html

In short, if not in HCL, download and test :) If you can see the installer, it means that it will work in 99% of case.
