### ISSUE TITLE
Slow network interface initialization during automated install on devices with many NICs

### ISSUE THREAD

**Issue by ed-at-protectli** [xcp-ng/xcp#494]
When installing via PXE and answerfile, the first step of the installer shows an ncurses window stating "Attempting to configure networking" while each interface is negotiated individually. We are using hardware that has multiple interfaces, but not all are connected to a network during the installation phase. For example, we may have a 6-interface device with just one connection active to the PXE/installation server.

The installation script appears to just go through each interface sequentially (but backwards), run ifup, and wait for a default timeout (60 seconds or so). Though it is not a major inconvenience, it does add about 5 minutes to the installation process, and there is not much indication to the user as to what is happening behind the scenes unless tabbing into another TTY to view the actual logs.

Is there a recommended way to speed this process up for our use case? In the event that we adopt a device with (for example) 48 ports, the installation process needs at least 47 minutes to start, assuming only one jack is populated. Or, is it reasonable to have checking before/during ifup for cases where no carrier is detected, and immediately jump to the next interface? Finally, we see that the interfaces are polled in reverse order (e.g. starts at eth5 and ends at eth0). I do not think it is a "bug" per se, but perhaps it could have unintended consequences?

**Comment by nagilum99** [comment]
I would generally like to see more output and less GUI stuff. XCP-ng is mostly ran/maintained by admins for who that information makes sense and there's no need to hide that behind fancy things. That doesn't fix everything but at least you (maybe) more often see what's up instead of just watching a screen not giving any useful info.

**Comment by stormi** [comment]
Hi @ed-at-protectli I'll try to help you find a solution. Maybe we can reduce the timeout, or simply make it not try to init interfaces that are not mentioned in the answerfile...

About @nagilum99's comment: agreed. Unfortunately the installer is definitely not built around that concept currently and there's no easy way to contribute upstream. Let's not discuss this on this issue though.

**Comment by stormi** [comment]
Could you share the contents of your answerfile to me?

**Comment by ed-at-protectli** [comment]
```
<?xml version="1.0"?>
    <installation mode="fresh">
        <primary-disk>sda</primary-disk>
        <keymap>us</keymap>
        <root-password type="hash">!!</root-password>
        <source type="url">http://[redacted]/xcp-ng/8.2.0/</source>
        <admin-interface name="eth0" proto="dhcp" />
        <timezone>Europe/Paris</timezone>
    </installation>
```

**Comment by stormi** [comment]
I think a solution already exists: see https://github.com/xcp-ng/host-installer/blob/master/doc/parameters.txt#L142

The `--network_device` parameter of the installer defines what interface to bring up in order for the installer to access the answerfile. It defaults to `all`. You can pass this parameter to the installer by adding `network_device=eth0` as a kernel parameter, next to your existing `answerfile=...` parameter. Any unused kernel parameter is automatically translated to a `--name-of-param` parameter for the installer.

Can you test and tell me if that solves your issue?

**Comment by ed-at-protectli** [comment]
This solves it perfectly. Thank you! If I could make a suggestion, it was not clear to me that during the "Attempting to configure networking" phase that this was just the first step for finding an answerfile, as opposed to upping all interfaces for some other reason. So, adjusting the message from "Attempting to configure networking" to "Attempting to configure networking for answerfile retrieval" or similar would be nice.

Also, as mentioned in the start of this issue,

> Finally, we see that the interfaces are polled in reverse order (e.g. starts at eth5 and ends at eth0). I do not think it is a "bug" per se, but perhaps it could have unintended consequences?

I can't think of there being a real "negative" here. It was more of a "Huh, that's peculiar." moment. But, if there is consensus that this may need to be looked at further, I'd happy file another issue to track it.

**Comment by stormi** [comment]
> This solves it perfectly. Thank you! If I could make a suggestion, it was not clear to me that during the "Attempting to configure networking" phase that this was just the first step for finding an answerfile, as opposed to upping all interfaces for some other reason. So, adjusting the message from "Attempting to configure networking" to "Attempting to configure networking for answerfile retrieval" or similar would be nice.

To be honest, it was not obvious to me until I looked at the code :)

I agree with your suggestion, the only downside to doing it until we find a way to collaborate with Citrix more closely on the installer (they don't have a public repo where we can open pull requests), as we managed to do on some other components (e.g. XAPI), is that every change we bring to the installer we have to carry over from release to release, with potential conflicts to resolve each time we rebase on the latest version. So we're selective regarding what we allow ourselves to change or not.

> I can't think of there being a real "negative" here. It was more of a "Huh, that's peculiar." moment. But, if there is consensus that this may need to be looked at further, I'd happy file another issue to track it.

I don't think it's an issue though I'd be curious to know whether this is on purpose or not. It's good to know, however.
