### ISSUE TITLE
XCP iso

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#5]
Modifying the existing XS 7.4 ISO, we need to make it "XCP-ng" like.

It will require to:

* [x] modify some theme related packages (release info, logo, brand names etc.)
  * [x] xcp-ng-plymouth theme to replace xenserver one
  * [x] splash logo
  * [x] some minor files in the boot folder of the ISO
* [x] modify the host-installer RPM package
  * [x] modify/remove trademarks
  * [x] add xcp-ng repo
* [x] include our own stuff
  * [x] xcp-ng-plymouth
  * [x] v6d replacement
* [x] change welcome HTML page
* [x] change Grub name entries (XenServer to XCP-ng)
* [x] build the ISO

**Comment by olivierlambert** [comment]
I need people with CentOS and RPM experience to take a look a bit into the binary ISO of XS ([download link](http://downloadns.citrix.com.edgesuite.net/13371/XenServer-7.3.0-install-cd.iso)):

* which packages contains Citrix specific code that must be removed (for example, `v6d` is the licensing daemon), and roughly where are stored some default values (partitioning, etc.)
* which packages contains "Citrix" and other "XenServer" release name, to be removed or replaced by XCP-ng
* recreate a working ISO with that stuff (in the mean time, @johnelse is working on giving us a XAPI package the remove the restrictions and the need for `v6d` to start)

The first one to get something will be the hero of xcp-ng `0.0.0` 😆

**Comment by Storycrafter** [comment]
I'm working this on #4

**Comment by Storycrafter** [comment]
## This may be the list of RPM's on the XS iso that have no source on the Source ISO, and may be the list of Citrix specific items that need to be removed.

- QCS-CLI-30.0.22-0
- QConvergeConsoleCLI-Citrix-2.0.00-24A
- elxocmcore-11.1.218.4-1
- elxocmcorelibs-11.1.218.4-1
- elxocmlibhbaapi-11.1.218.4-1
- emu-manager-0.0.2-1
- pbis-open-8.2.2-1.7.1
- pbis-open-upgrade-8.2.2-3
- update-XS73-1.0-1.noarch.rpm
- v6d-citrix-10.29.0-1.el7.centos
- vendor-update-keys-1.3.3-2.noarch.rpm
- xs-clipboardd-0.0.2-1

**Comment by olivierlambert** [comment]
Got it, answered there.

**Comment by fetzerms** [comment]
As an addition (Phase 3?) it would be great to have ootb support for MDADM-Raid-Devices - so XCP runs on software raid1. Should I open an extra ticket for this, as a feature request?

**Comment by necouchman** [comment]
> Should I open an extra ticket for this, as a feature request?

Yes, that would probably be a separate feature request.  Gluster support would be nice, too - oVirt is using that to enable hyper-converged configurations, and I think XCP-ng could benefit from it, as well.

**Comment by olivierlambert** [comment]
Gluster support would be easy, we already got a Gluster driver working (used in XOSAN) So it's just a matter of bundle it!

See https://github.com/vatesfr/glusterfs-driver

**Comment by Storycrafter** [comment]
Where should I focus my time next? I _was_ thinking about taking a 7.2 Centos install image and stripping it down to bare essentials and then bundling with the open binary packages from XenServer. Then trying to take a tally of just how many "non-free" proprietary binary packages are needed to get a working XS.

Alternatively, to say closer to the ticket's intent, I suppose I should go spelunking in the initial boot environment and install to find out where the configuration parameters and toggles are, including:
- logos
- license/documentation
- partitioning configuration + information
- source list for packages

**Comment by olivierlambert** [comment]
hey thanks @Storycrafter 

Indeed, can you check, in the source ISO, which packages contain "Citrix" or "XenServer" name, because we should be careful to remove those or replace by XCP-ng. At least there is splash boot screen, `/etc/issue` etc.

And OK for the rest, that's exactly what we need!

Keep up the good work

**Comment by skajter** [comment]
Update:

We can tick:
- change welcome HTML page
- add xcp-ng repo

:)

**Comment by olivierlambert** [comment]
Done and closing!
