### ISSUE TITLE
Weird htop memory issue

### ISSUE THREAD

**Issue by Olionkey** [xcp-ng/xcp#504]
Hi trying to resolve this weird issue with a fresh install of XCP-NG (8.2) on a HP DL170e-G6 node on a HP DL2000, with XCP-NG running on a flashdrive. 
The issue is that the bios and the dashboard is showing the correct amount of ram installed on the machine (16gb). But when I ssh into the server or run the command shell directly on the server and run Htop it shows up as only 1.48gb.
Have tried to multiple re-installs of XCP-NG, have tried it on different nodes on the HP DL2000, but it all comes up with the same issue. Have also tried moving ram around inside the machine, swapping sticks, and looking into the bios to see if there is anything miss configured in there.

**Comment by olivierlambert** [comment]
It's not an issue, that's even how XCP-ng and Xen is working :)

It's a type 1 hypervisor. It means what you call the "host" is in fact a special virtual machine, called dom0. This special VM have access to all physical network and disks. The rest of the memory is used for your new VMs. There's also few MiB used by Xen itself.

See:

![](https://wiki.xenproject.org/images/thumb/f/f9/Xen_Arch_Diagram_v2.png/800px-Xen_Arch_Diagram_v2.png)
