### ISSUE TITLE
FAILED_TO_START_EMULATOR on virtual machine

### ISSUE THREAD

**Issue by aguinaldoabbj** [xcp-ng/xcp#508]
After a power blackout, my XCP-ng hypervisor was rebooted. Since this event, some vms just cannot start anymore. Error logs for those vms shows:

`FAILED_TO_START_EMULATOR(OpaqueRef:280dbf79-fa6c-434b-a6b8-4758c6089078, domid 18, QMP failure at File "xc/device.ml", line 2616, characters 55-62)
`
All virtual machines run the same OS (Debian 10) and were built on the same base template at the same time. I'm running XCP-ng 8.1.0.

I cannot understand why the problem happens only on some vms, since they have the very same characteristics.

Thanks in advance.

**Comment by olivierlambert** [comment]
Hi,

We tend to keep the bug tracker for repeatable/reproducible bugs. In the meantime, please open a thread here: https://xcp-ng.org/forum

We'll help there, and re-open here if it's something we can trigger :+1:
