### ISSUE TITLE
Remove the /var/update folder during/after XS upgrade

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#51]
This folder cause a vulnerability in XAPI. See https://xenbits.xen.org/xsa/advisory-271.html

Fresh XCP-ng install aren't affected and can't be affected in the future.

**Comment by stormi** [comment]
Actually updated XCP-ng installs are not affected either because xapi has been patched, but let's remove it if we don't need it.

**Comment by stormi** [comment]
This folder is not present in XCP-ng 8.0 nor 8.1. Closing.
