### ISSUE TITLE
XCP-NG 8.2 supports Windows 7?

### ISSUE THREAD

**Issue by TrygonHex** [xcp-ng/xcp#518]
Hi,

Both citrix and xcp-ng guest tools do not support windows 7

**Comment by Daniel-Furcht** [comment]
Hi, can confirm Windows 7 VM migrated from Xenserver 7.6 run without problems on XCP 8.2. Without guest tools.

**Comment by TrygonHex** [comment]
> Hi, can confirm Windows 7 VM migrated from Xenserver 7.6 run without problems on XCP 8.2. Without guest tools.

I thought guest tools were a must for VMs?

**Comment by beshleman** [comment]
> > Hi, can confirm Windows 7 VM migrated from Xenserver 7.6 run without problems on XCP 8.2. Without guest tools.
> 
> I thought guest tools were a must for VMs?

They offer important gains in performance and manageability... but I've ran Windows 7 on 8.2 with no guest tools without issue. I did not use it extensively and did not place the VM under any serious load, however (my disclaimer).
