### ISSUE TITLE
Corrupted xcp-ng 8.2 shell

### ISSUE THREAD

**Issue by Morgyn** [xcp-ng/xcp#520]
Clean installation of xcp-ng 8.2 on a ASRock X470D4U with a Ryzen 3700x which uses ASPEED AST2500 graphics chip.

![image](https://user-images.githubusercontent.com/1760092/136581819-b50ccae5-9c60-440a-a435-caa7aad9358b.png)

**Comment by nagilum99** [comment]
What's the issue there? If there's nothing to see, there's nothing to see.
Also that info should be absolutely non-relevant and just informative?

**Comment by nagilum99** [comment]
...my fault. Where are you? Is that the full screen it shows?

**Comment by Morgyn** [comment]
I fear the 2nd screen shot has confused issues. That was purely to answer the question of @nagilum99 regarding running xsconsole in ssh. The output in the first post is the only one I am concerned about where the whole xsconsole is unable to be displayed, only showing the first 5 lines lower down than normal.

As previously stated this occurs on a dedicated monitor, the KVM and on the BMC. The first two have been used on multiple differing hardware with the same version of xcp-ng without issue.
