### ISSUE TITLE
Sync kernel-alt patches with latest main kernel

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#522]
The kernel RPM has received various patches since the last time kernel-alt was built:
* First commit: https://github.com/xcp-ng-rpms/kernel/commit/54be7632d2fc78329eb0d6781ba6a6f03d560249
* Second commit: https://github.com/xcp-ng-rpms/kernel/commit/37ba4d5ef88bca69151c12a157a2285aa6e55995

(and maybe check the history for previous commits in case I missed one).

kernel-alt needs to be updated with those patches.

**Comment by rushikeshjadhav** [comment]
Created PR https://github.com/xcp-ng-rpms/kernel-alt/pull/15 which includes issue fixes and other improvements.

**Comment by stormi** [comment]
This was done but we forgot to close the issue.
