### ISSUE TITLE
grub-install not run when installing to existing MDRAID/unable to boot after installing to existing MDRAID

### ISSUE THREAD

**Issue by tstivers1990** [xcp-ng/xcp#524]
I configured two MDRAID arrays on a single set of 4x2TB drives. I created two partitions on these drives. I then configured the first partitions to be RAID 1 for the system install (md0). The second partitions are configured as RAID 10 for virtual disk storage (md1). I installed XCP-NG to md0 and selected md1 for virtual disks during the install. Upon rebooting, BIOS is unable to find any bootable disks. 

I booted into a rescue system, mounted the root partition to `/mnt/temp` and the `/var/log` partition to `/mnt/temp/var/log`. Upon checking `/mnt/temp/var/log/installer/install-log` I determined that the grub-install log entry was missing. I ran the following and then chrooted into the xcp-ng system:

```bash
mount --bind /proc /mnt/temp/proc
mount --bind /sys /mnt/temp/sys
mount --bind /dev /mnt/temp/dev
```

Once chrooted in, I ran `grub-install --target=i386-pc /dev/sd[a,b,c,d]` to install the bootloader to all 4 drives' MBR. After rebooting, BIOS now saw the MBR and I was able to boot XCP-NG.

I'm not sure if this is caused by me installing to a mdraid across partitions rather than across the entire drive, as is the standard setup if you choose software raid during install. But I imagine it would be possible to figure out what drives are part of the raid array selected for root and install the bootloader to all of those drives.

Also is there any information I should know to prevent this from breaking on an update as well as ensure XCP-NG updates the bootloader as necessary?

**Comment by tstivers1990** [comment]
Here are some relevant logs:

Normal install, selecting the four drives as software raid through the installer:
```
INFO     [2021-11-12 00:33:32] ran ['sh', '-c', 'ls -d1 /sys/block/*/holders/*/dev']; rc 0
STANDARD OUT:
/sys/block/sda/holders/md127/dev
/sys/block/sdb/holders/md127/dev
/sys/block/sdc/holders/md127/dev
/sys/block/sdd/holders/md127/dev

INFO     [2021-11-12 00:34:32] ran ['chroot', '/tmp/root', '/usr/sbin/grub-install', '--target=i386-pc', '/dev/sda']; rc 0
STANDARD ERROR:
Installing for i386-pc platform.
Installation finished. No error reported.

INFO     [2021-11-12 00:35:13] ran ['chroot', '/tmp/root', '/usr/sbin/grub-install', '--target=i386-pc', '/dev/sdb']; rc 0
STANDARD ERROR:
Installing for i386-pc platform.
Installation finished. No error reported.

INFO     [2021-11-12 00:35:53] ran ['chroot', '/tmp/root', '/usr/sbin/grub-install', '--target=i386-pc', '/dev/sdc']; rc 0
STANDARD ERROR:
Installing for i386-pc platform.
Installation finished. No error reported.

INFO     [2021-11-12 00:36:35] ran ['chroot', '/tmp/root', '/usr/sbin/grub-install', '--target=i386-pc', '/dev/sdd']; rc 0
STANDARD ERROR:
Installing for i386-pc platform.
Installation finished. No error reported.
```

Manually creating MDRAID arrays prior to installation and selecting those pre-existing arrays during install:
```
INFO     [2021-11-12 03:29:54] ran ['sh', '-c', 'ls -d1 /sys/block/*/holders/*/dev']; rc 2
STANDARD ERROR:
ls: cannot access /sys/block/*/holders/*/dev: No such file or directory
```

**Comment by stormi** [comment]
Hi @tstivers1990 and thanks for the report.

Here are a few pointers for anyone willing to dig further into the issue until maybe contributing a fix:
* Sources for the installer are at https://github.com/xcp-ng/host-installer. It's python and not overly complicated. You may look up where `grub-install` is called. Any solution must retain compatibility with both BIOS and UEFI modes.
* Instructions to rebuild an installer ISO image with modified sources: https://xcp-ng.org/docs/develprocess.html#modify-the-installer-itself

**Comment by stormi** [comment]
Why close the issue? The report seems valid and well documented to me.
