### ISSUE TITLE
Changing PIF assignment per host in pool

### ISSUE THREAD

**Issue by pmooo** [xcp-ng/xcp#525]
Within a pool there seems to be no way ( with CLI, XOA, or XCP-NG Center) to change PIF assignments to each Pool Network per host. This is an issue when PIFs physical connections differ on each host. 

This issue forces you to line up eth# assignments with physical connections on each host.

I could be missing something, but it is never mentioned in any documentation.

**Comment by olivierlambert** [comment]
Hi,

This is a recommended practice to line up eth assignments with physical connections on each hosts in a pool. @Fohdeesha might bring more details.

**Comment by pmooo** [comment]
I get the reason for the recommended practice. However, in reality, this can become extremely tedious if your NIC configuration does not match exactly. Even with homogeneous hosts, NICs are often considered interchangeable, and the operating system may mount ports in different orders. 

In the current state, one has to manually map out the eth# assigned to each NIC rather than just building out virtual networks as other hypervisors do.

**Comment by stormi** [comment]
Could this help? https://xcp-ng.org/docs/networking.html#renaming-nics

**Comment by pmooo** [comment]
This will work as a work around for my case. Thanks!
