### ISSUE TITLE
UnicodeDecodeError when running usb_scan.py

### ISSUE THREAD

**Issue by alteredtech** [xcp-ng/xcp#526]
Running 8.2
I am trying to passthrough a bluray dvd drive to a vm. It does not show up in the list of usb passthrough devices on xcp-ng center. I am following this ["guide"](https://xcp-ng.org/forum/topic/266/usb-passthrough-test-reports-in-7-5rc1/5) from fjen. When I attempt to run usb_scan.py, I am meet with this error. 

```
Traceback (most recent call last):
  File "/opt/xensource/libexec/usb_scan.py", line 653, in <module>
    pusbs = make_pusbs_list(devices, interfaces)
  File "/opt/xensource/libexec/usb_scan.py", line 633, in make_pusbs_list
    return [to_pusb(d) for d in devices if d.is_ready() and policy.check(d)]
  File "/opt/xensource/libexec/usb_scan.py", line 609, in to_pusb
    pusb["description"] += "_" + pusb["serial"]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 1: ordinal not in range(128)
```

This is the device from user.log

```
Nov 20 19:16:42 xcp-ng usb_scan.py DEBUG: UsbDevice: (u'2-2', {'idVendor': '0e8d', 'ID_VENDOR_FROM_DATABASE': u'MediaTek Inc.', 'bConfigurationValue': '1', 'bDeviceClass': '00', 'ID_MODEL_FROM_DATABASE': u'Samsung SE-506 Portable BluRay Disc Writer', 'version': ' 2.00', 'idProduct': '1956', 'bNumInterfaces': ' 1', 'serial': '\xe3\x85\x93\xe4\x94\xb5\xe5\xa4\xb6\xe4\x99\x8d\xe3\x80\xb4\xe3\xa4\xb0\xe5\x85\x8e\xe2\x80\xa0\xe0\xa4\x81', 'bcdDevice': '0000', 'speed': '480'})#012#011|__ UsbInterface: (u'2-2:1.0', {'bInterfaceNumber': '00', 'bInterfaceClass': '08', 'bInterfaceProtocol': '50', 'bInterfaceSubClass': '02'})
```

I am hoping that this error is the reason I am not able to passthrough my dvd drive to my vm.

**Comment by olivierlambert** [comment]
Hi,

For general issue report, it's better to use our forums: https://xcp-ng.org/forum

We tend to keep the bug tracker for reproducible/"root cause found" bugs (so there's something to do on the dev side). This way, we reduce the burden on dev for triaging :)
