### ISSUE TITLE
Hang on shutdown/reboot

### ISSUE THREAD

**Issue by tstivers1990** [xcp-ng/xcp#527]
I have a machine that consistently hangs on shutdown/reboot. I have 3 other machines (same make/model) that also hang on shutdown/reboot at times.

It seems the hang doesn't occur after a fresh boot on any of the machines, but consistently occurs after the machine has been running for a bit of time.

One machine is a custom built system based on X10SDV-4C-TLN2F. The other 3 are DC3217IYE NUCs.

**Comment by tstivers1990** [comment]
When hitting ESC on the shutdown splash screen, these are the only 3 messages shown when this occurs.
![image](https://user-images.githubusercontent.com/14251176/142958962-6548ffe6-9634-4a45-b523-2b424e933b0d.png)

**Comment by olivierlambert** [comment]
Hi,

We tend to keep this repo for identified bug where we could take an action on it (ie dev to fix a bug). For investigating unknown issues, it's better to ask on https://xcp-ng.org/forum

See you there :)

Thank you!

**Comment by tstivers1990** [comment]
https://bugs.xenserver.org/browse/XSO-802?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

Experience the exact same symptoms. Install XCP-ng. Set up XO. Create pool. Add NFS SR. Reboot host after running for some time (24 hours). Hangs on shutdown.

![image](https://user-images.githubusercontent.com/14251176/146668425-48fcb604-8f4d-463e-88c4-07c307e59cc5.png)

**Comment by olivierlambert** [comment]
That's completely "normal": SMAPI is trying to disconnect the SR, but it's hanging. A network filesystem isn't meant to be disconnected (so the kernel is trying to reconnect it whatever happens).

If you want to avoid this, unplug the SR before shutting down the NFS VM. Also, in general, just don't host your NFS for your VM in a VM on the same host. That's a kind of antipattern.
