### ISSUE TITLE
Driver: Add support for intel i225 nic (igc)

### ISSUE THREAD

**Issue by hoerup** [xcp-ng/xcp#535]
Has been asked for at least twice 

https://xcp-ng.org/forum/topic/5454/anybody-using-11th-gen-intel-nuc-with-intel-i225-nics
https://xcp-ng.org/forum/topic/4998/i225-nic-driver-for-8-2?_=1642613018175

**Comment by stormi** [comment]
So the driver would be Intel's `igc`, it seems.

Where do you find this kind of devices usually?

**Comment by dziurr** [comment]
Higher end consumer/workstation motherboards and intel nucs.

**Comment by smiggiddy** [comment]
I can test

**Comment by stormi** [comment]
Here's a RPM you can install on an already installed XCP-ng: https://koji.xcp-ng.org/kojifiles/packages/igc-module/4.20.17/1.xcpng8.2/x86_64/igc-module-4.20.17-1.xcpng8.2.x86_64.rpm

If you couldn't install XCP-ng at all due to the missing driver, then I'll have to build a new installation ISO with it.

**Comment by dziurr** [comment]
just compiled it from source and it seams to work

**Comment by stormi** [comment]
Here's a test installation ISO image. Please test ASAP and tell me if it your network card is operational: https://updates.xcp-ng.org/tmp/xcp-ng-8.2.1-test5.iso

**Comment by dziurr** [comment]
i've installed your iso and its kind of working but i need to do `ifconfig eth0 down` and `ifconfig eth0 up` every start to make it working.

**Comment by stormi** [comment]
> i've installed your iso and its kind of working but i need to do `ifconfig eth0 down` and `ifconfig eth0 up` every start to make it working.

And not with the one you built from sources? Where did you get the sources from?

**Comment by dziurr** [comment]
> > i've installed your iso and its kind of working but i need to do `ifconfig eth0 down` and `ifconfig eth0 up` every start to make it working.
> 
> And not with the one you built from sources? Where did you get the sources from?

Same thing happens with driver build from source. Btw `dmesg` shows `igc: loading out of tree driver taints kernel` in both versions

**Comment by stormi** [comment]
The message in `dmesg` is expected when you load a driver that was not a builtin driver.

**Comment by stormi** [comment]
Can you try to identify why the down+up is necessary?

Could others test the installation ISO, too?

**Comment by dziurr** [comment]
> Can you try to identify why the down+up is necessary?
> 
> Could others test the installation ISO, too?

@stormi I probably found the problem. ethtool does not work with igc.

**Comment by stormi** [comment]
Here are the sources we build ethtool from: https://github.com/xcp-ng-rpms/ethtool/tree/8.2

If we can find a patch that fixes this issue, I could be able to integrate it in the 8.2.1 release. I've got a lot of other tasks to do so any help in this direction from you or the rest of the community would be wonderful.

**Comment by stormi** [comment]
> > Can you try to identify why the down+up is necessary?
> > Could others test the installation ISO, too?
> 
> @stormi I probably found the problem. ethtool does not work with igc.

By the way can you detail what leads you to this conclusion?

**Comment by dziurr** [comment]
`ethtool `  with every command expect `-i` shows **operation not supported** for eth0(i225-v). Just for test booted **xcp-ng** installer on another pc with realtek r8125 and `ethtool` works just fine. I am trying to add igc support to `ethtool` from your repo, but without any luck so far. i added igc code from newer ethtool and updated makefiles etc... it compiled just fine but it still wont work with igc. also tried installing `ethtool` 5.8 from centos rpms and the same story. For test purpose booted centos 7.2009 installer and ethtool works with igc.

**Comment by stormi** [comment]
Thanks. Now I have also feedback for r8125 thanks to you. Is your Realtek card an USB one or PCI-E?

**Comment by stormi** [comment]
> For test purpose booted centos 7.2009 installer and ethtool works with igc.

Did CentOS 7.9 recognise the device directly, or did you need to build the driver?

**Comment by dziurr** [comment]
> By the way can you detail what leads you to this conclusion?

r8125 in PCIe integrated in aorus x570 master motherboard.

**Comment by dziurr** [comment]
> > For test purpose booted centos 7.2009 installer and ethtool works with igc.
> 
> Did CentOS 7.9 recognise the device directly, or did you need to build the driver?

Surprisingly it installer recognized it right away and it has very old kernel 3.10. ethtool also worked

**Comment by stormi** [comment]
They probably backported the driver to their kernel.

**Comment by stormi** [comment]
Looking at how they did might reveal something we missed.

**Comment by dziurr** [comment]
After long investigation i found why it did not work. The problem lied in `igc`. I have been able to patch the driver and it seams to work. i also noticed that the driver backported to `kernel 4.20` does not support `ethtool`. I found latest version of `igc` in linux tree with `ethtool` support i patched it and compiled and it seams to work. i've also added added `igc` code to ethtool.

**Comment by rushikeshjadhav** [comment]
@dziurr can you share `lspci -kv` output from your working CentOS 7? Although we can not port `igc` driver from CentOS, I think there might be a relevant device driver from Intel's website.

**Comment by dziurr** [comment]
> you share `lspci -kv` output from your working CentOS 7? Although we ca
It was not working correctly with centos 7. It works with centos 8 (4.18 kernel).

**Comment by rushikeshjadhav** [comment]
Sorry I missed that C7 did not work. Anyways - I just needed the exact device PCI ID so that some relevant info could be dug up from internet.

**Comment by stormi** [comment]
Maybe the exact steps and patches used by @dziurr to make it work on XCP-ng based on latest `igc` from linux tree could help you @rushikeshjadhav, right?

**Comment by stormi** [comment]
> After long investigation i found why it did not work. The problem lied in `igc`. I have been able to patch the driver and it seams to work. i also noticed that the driver backported to `kernel 4.20` does not support `ethtool`. I found latest version of `igc` in linux tree with `ethtool` support i patched it and compiled and it seams to work. i've also added added `igc` code to ethtool.

Was modifying ethtool required to make it work with the device?

**Comment by dziurr** [comment]
> > After long investigation i found why it did not work. The problem lied in `igc`. I have been able to patch the driver and it seams to work. i also noticed that the driver backported to `kernel 4.20` does not support `ethtool`. I found latest version of `igc` in linux tree with `ethtool` support i patched it and compiled and it seams to work. i've also added added `igc` code to ethtool.
> 
> Was modifying ethtool required to make it work with the device?

Not really. but i found that much bigger problem. While `igc` seams to work and i can access internet from dom0. and connect via **xcp-ng center**, i can't access network from vm. Pinging dom0 works.

**Comment by stormi** [comment]
So, it's a bit sad, but I think I'll remove the igc driver from the installation ISO for XCP-ng 8.2.1, to give us time to make it work properly.

Anyone knows a distro that would be using kernel 4.19 and would have backported the driver yet?

**Comment by dziurr** [comment]
**Centos 8** works. it has kernel **4.18**. I tried compiling driver extracted from it but there where problems, missing defines etc... I try again. 
I there possibility that xcp-ng will jump to 5.X kernel?

**Comment by olivierlambert** [comment]
No. At least not for an LTS version, and likely not yet even of a next whole release (well, depends if it's in 6 months or 2 years obviously)

**Comment by dziurr** [comment]
**Build log for centos igc:**

/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'igc_tx_ctxtdesc':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:946:3: error: implicit declaration of function 'skb_txtime_consumed' [-Werror=implicit-function-declaration]
   skb_txtime_consumed(first->skb);
   ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'igc_tx_csum':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:971:3: error: 'fallthrough' undeclared (first use in this function)
   fallthrough;
   ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:971:3: note: each undeclared identifier is reported only once for each function it appears in
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:976:3: error: implicit declaration of function 'skb_csum_is_sctp' [-Werror=implicit-function-declaration]
   if (skb_csum_is_sctp(skb)) {
   ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'igc_tx_map':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:1178:2: error: implicit declaration of function 'netdev_xmit_more' [-Werror=implicit-function-declaration]
  if (netif_xmit_stopped(txring_txq(tx_ring)) || !netdev_xmit_more()) {
  ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'igc_build_skb':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:1569:2: error: implicit declaration of function 'net_prefetch' [-Werror=implicit-function-declaration]
  net_prefetch(va);
  ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'igc_construct_skb':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:1609:3: warning: passing argument 2 of 'eth_get_headlen' makes integer from pointer without a cast [enabled by default]
   headlen = eth_get_headlen(skb->dev, va, IGC_RX_HDR_LEN);
   ^
In file included from ./include/linux/if_vlan.h:16:0,
                 from /home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:6:
./include/linux/etherdevice.h:35:5: note: expected 'unsigned int' but argument is of type 'void *'
 u32 eth_get_headlen(void *data, unsigned int max_len);
     ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:1609:3: error: too many arguments to function 'eth_get_headlen'
   headlen = eth_get_headlen(skb->dev, va, IGC_RX_HDR_LEN);
   ^
In file included from ./include/linux/if_vlan.h:16:0,
                 from /home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:6:
./include/linux/etherdevice.h:35:5: note: declared here
 u32 eth_get_headlen(void *data, unsigned int max_len);
     ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'igc_can_reuse_rx_page':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:1663:2: error: implicit declaration of function 'dev_page_is_reusable' [-Werror=implicit-function-declaration]
  if (!dev_page_is_reusable(page))
  ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: At top level:
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4728:23: warning: 'struct tc_taprio_qopt_offload' declared inside parameter list [enabled by default]
          const struct tc_taprio_qopt_offload *qopt)
                       ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4728:23: warning: its scope is only this definition or declaration, which is probably not what you want [enabled by default]
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'validate_schedule':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4734:10: error: dereferencing pointer to incomplete type
  if (qopt->cycle_time_extension)
          ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4744:29: error: dereferencing pointer to incomplete type
  if (!is_base_time_past(qopt->base_time, &now))
                             ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4747:22: error: dereferencing pointer to incomplete type
  for (n = 0; n < qopt->num_entries; n++) {
                      ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4751:12: error: dereferencing pointer to incomplete type
   e = &qopt->entries[n];
            ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4756:8: error: dereferencing pointer to incomplete type
   if (e->command != TC_TAPRIO_CMD_SET_GATES)
        ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4756:21: error: 'TC_TAPRIO_CMD_SET_GATES' undeclared (first use in this function)
   if (e->command != TC_TAPRIO_CMD_SET_GATES)
                     ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4760:9: error: dereferencing pointer to incomplete type
    if (e->gate_mask & BIT(i))
         ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: At top level:
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4788:13: warning: 'struct tc_taprio_qopt_offload' declared inside parameter list [enabled by default]
      struct tc_taprio_qopt_offload *qopt)
             ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'igc_save_qbv_schedule':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4793:11: error: dereferencing pointer to incomplete type
  if (!qopt->enable) {
           ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4801:2: warning: passing argument 2 of 'validate_schedule' from incompatible pointer type [enabled by default]
  if (!validate_schedule(adapter, qopt))
  ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4727:13: note: expected 'const struct tc_taprio_qopt_offload *' but argument is of type 'struct tc_taprio_qopt_offload *'
 static bool validate_schedule(struct igc_adapter *adapter,
             ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4804:28: error: dereferencing pointer to incomplete type
  adapter->cycle_time = qopt->cycle_time;
                            ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4805:27: error: dereferencing pointer to incomplete type
  adapter->base_time = qopt->base_time;
                           ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4810:22: error: dereferencing pointer to incomplete type
  for (n = 0; n < qopt->num_entries; n++) {
                      ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4811:42: error: dereferencing pointer to incomplete type
   struct tc_taprio_sched_entry *e = &qopt->entries[n];
                                          ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4814:16: error: dereferencing pointer to incomplete type
   end_time += e->interval;
                ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4819:11: error: dereferencing pointer to incomplete type
    if (!(e->gate_mask & BIT(i)))
           ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4826:18: error: dereferencing pointer to incomplete type
   start_time += e->interval;
                  ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: At top level:
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4833:14: warning: 'struct tc_taprio_qopt_offload' declared inside parameter list [enabled by default]
       struct tc_taprio_qopt_offload *qopt)
              ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'igc_tsn_enable_qbv_scheduling':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4841:2: warning: passing argument 2 of 'igc_save_qbv_schedule' from incompatible pointer type [enabled by default]
  err = igc_save_qbv_schedule(adapter, qopt);
  ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4787:12: note: expected 'struct tc_taprio_qopt_offload *' but argument is of type 'struct tc_taprio_qopt_offload *'
 static int igc_save_qbv_schedule(struct igc_adapter *adapter,
            ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'igc_setup_tc':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:4854:7: error: 'TC_SETUP_QDISC_TAPRIO' undeclared (first use in this function)
  case TC_SETUP_QDISC_TAPRIO:
       ^
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c: In function 'igc_probe':
/home/builder/rpmbuild/BUILD/igc-module-4.20.19/igc_main.c:5206:38: error: 'DPM_FLAG_NO_DIRECT_COMPLETE' undeclared (first use in this function)
  dev_pm_set_driver_flags(&pdev->dev, DPM_FLAG_NO_DIRECT_COMPLETE);

**Comment by rushikeshjadhav** [comment]
Someone on the Linux kernel mailing list should be able to tell about the timelines for `igc` being available in 4.19 longterm. As soon as it becomes available, we will bake it into `kernel-alt` and then main kernel.

**Comment by hoerup** [comment]
In the forum thread https://xcp-ng.org/forum/topic/5596/intel-nuc10-nuc11-woes-nuc8-is-alright/53 

Andrew added a post linking to his igc drivers https://users.ntplx.net/~andrew/xcp/

**Comment by dziurr** [comment]
i will test is as soon as i can

**Comment by dziurr** [comment]
I,ve compiled it from this sources https://users.ntplx.net/~andrew/xcp/igc10.txz and it works. VMs have network access. I'm not able to check if vlans work

**Comment by hoerup** [comment]
@stormi could this be base for the igc rpm package ?

**Comment by stormi** [comment]
@hoerup Yes, probably. I've asked Andrew if he wants to contribute it.

**Comment by dziurr** [comment]
Update:
I ve been able to test vlans and it works! Also 2.5gb speed works!
Ethtool reports that checksuming offload works.

**Comment by ethicnology** [comment]
Do you have a link documentation that shows how install XCP-ng with Intel I225 IGC driver ?

**Comment by jamiecash** [comment]
I am rebuilding my lab and would like to use Andrews new driver. I have added to the ISO image under Packages, but it doesn't seem to be being picked up, and the F9 load device driver option can't find it. Could someone let me know where to add the rpm file on the install media?

**Comment by dziurr** [comment]
> I am rebuilding my lab and would like to use Andrews new driver. I have added to the ISO image under Packages, but it doesn't seem to be being picked up, and the F9 load device driver option can't find it. Could someone let me know where to add the rpm file on the install media?

When i was testing it i've used official 8.2 iso and manually installed driver from rpm. You need to go into shell, mount usb drive where you have drivers rpm and install it. Then you install xcp-ng normally, After installation you need to install the driver once again and it should work.

**Comment by jamiecash** [comment]
> 

Works perfectly. Tested network connectivity on host and XEN Orchestra VM.

**Comment by stormi** [comment]
The drivers are now available in the XCP-ng 8.3 alpha release: https://xcp-ng.org/blog/2022/11/18/xcp-ng-8-3-alpha/, thanks to @andrew64k.

**Comment by HansAndreManfredson** [comment]
Hi together,

i am still having issues with an Intel Corporation Ethernet Controller I225-V.

Even with using XCP-ng 8.3 beta 1 the nic toogle from up to down...

```
[11:47 xcp-ng-mfshjjxr ~]# tail -f /var/log/kern.log
Nov  6 11:48:47 xcp-ng-mfshjjxr kernel: [ 7140.243821] igc 0000:04:00.0 eth1: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Nov  6 11:48:57 xcp-ng-mfshjjxr kernel: [ 7150.683098] igc 0000:04:00.0 eth1: NIC Link is Down
Nov  6 11:49:10 xcp-ng-mfshjjxr kernel: [ 7163.246951] igc 0000:04:00.0 eth1: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Nov  6 11:49:10 xcp-ng-mfshjjxr kernel: [ 7163.486861] igc 0000:04:00.0 eth1: NIC Link is Down
Nov  6 11:49:20 xcp-ng-mfshjjxr kernel: [ 7173.102509] igc 0000:04:00.0 eth1: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Nov  6 11:49:26 xcp-ng-mfshjjxr kernel: [ 7179.449989] igc 0000:04:00.0 eth1: NIC Link is Down
Nov  6 11:49:39 xcp-ng-mfshjjxr kernel: [ 7192.169766] igc 0000:04:00.0 eth1: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Nov  6 11:49:41 xcp-ng-mfshjjxr kernel: [ 7194.237422] igc 0000:04:00.0 eth1: NIC Link is Down
Nov  6 11:49:50 xcp-ng-mfshjjxr kernel: [ 7203.865806] igc 0000:04:00.0 eth1: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Nov  6 11:49:51 xcp-ng-mfshjjxr kernel: [ 7204.528950] igc 0000:04:00.0 eth1: NIC Link is Down
Nov  6 11:50:07 xcp-ng-mfshjjxr kernel: [ 7220.576701] igc 0000:04:00.0 eth1: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Nov  6 11:50:08 xcp-ng-mfshjjxr kernel: [ 7221.176377] igc 0000:04:00.0 eth1: NIC Link is Down
```

```
04:00.0 Ethernet controller: Intel Corporation Ethernet Controller I225-V (rev 01)
        Subsystem: Intel Corporation Device 0000
        Flags: bus master, fast devsel, latency 0, IRQ 40
        Memory at fca00000 (32-bit, non-prefetchable) [size=1M]
        Memory at fcb00000 (32-bit, non-prefetchable) [size=16K]
        Expansion ROM at fc900000 [disabled] [size=1M]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable- Count=1/1 Maskable+ 64bit+
        Capabilities: [70] MSI-X: Enable+ Count=5 Masked-
        Capabilities: [a0] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [140] Device Serial Number 1c-83-41-ff-ff-32-1a-97
        Capabilities: [1c0] Latency Tolerance Reporting
        Capabilities: [1f0] Precision Time Measurement
        Capabilities: [1e0] L1 PM Substates
        Kernel driver in use: igc
        Kernel modules: igc
```

Any ideas?

**Comment by andrew64k** [comment]
Older i225 hardware (version 1 and 2) have well documented hardware bugs. You can ask your vendor for a RMA to replace it. If they won't, then at least ask them for a hardware firmware (NVM) update which may help. NVM Firmware is not included in the i225 driver.

**Comment by stormi** [comment]
This is now supported in the updated installation ISOs for XCP-ng 8.2.1, who are currently undergoing public testing at 
https://xcp-ng.org/forum/topic/8026/xcp-ng-8-2-1-refreshed-installation-iso-better-hardware-support.

Don't hesitate to try it and provide feedback.

**Comment by bleader** [comment]
The final 8.2.1 refreshed iso has been published with the `igc` driver integration.

https://xcp-ng.org/blog/2023/12/11/updated-installer-for-xcp-ng-8-2-1/

We'll close this issue as this is considered handled on our side, let us know if there are still issues.
