### ISSUE TITLE
How to remove Citrix Drivers from Windows Server 2019

### ISSUE THREAD

**Issue by jclementi725** [xcp-ng/xcp#537]
I did a fresh install of Windows Server 2019, and it is installing the Citrix drivers right away. So I cannot install the xcp-ng pv drivers and management agent. How can I remove the Citrix drivers and install the xcp-ng management software?
Thank in advance for your help.
![Image 1-30-22 at 9 26 PM](https://user-images.githubusercontent.com/98722852/151730973-ef6fa5da-cd24-4cc0-b3e3-e36daa3eaa5c.jpg)

**Comment by stormi** [comment]
Hi. Please favour the [orum](https://xcp-ng.org/forum/) for such questions that are not related to actual bugs.

You may find answers to your question at https://xcp-ng.org/docs/guests.html#windows
