### ISSUE TITLE
Unable to install XCP-ng 8.2.0 on Intel NUC 11 Pro Kit NUC11TNHi70L

### ISSUE THREAD

**Issue by esmsesms** [xcp-ng/xcp#542]
This is the Intel NUC 11 Pro Kit NUC11TNHi70L:
https://www.intel.com/content/www/us/en/products/sku/212513/intel-nuc-11-pro-kit-nuc11tnhi70l/support.html

This is the error I got, same reported at Reddit:
https://www.reddit.com/r/homelab/comments/mrmbks/trying_to_install_xcpng_on_intel_nuc_i7_10th/

This particular model does not have the Legacy BIOS option which would be a possible solution.

UEFI splash screen never shows up during the boot (in opposition of these instructions: https://xcp-ng.org/docs/install.html#iso-installation)

Any thoughts?

Thanks, e.

**Comment by esmsesms** [comment]
I do have XCP-ng 8.2 LTS up and running on NUCs from 2019, so I was surprised by this issue.

**Comment by orther** [comment]
I have a NUC11PAHi7 and that was fixed in 8.2.1 release for me.

I still haven't gotten Xen-ng installed because another issue related to the video drivers. I believe Intel Iris Xe require 5.x kernel and Xen is 4.11 see: https://github.com/xcp-ng/xcp/issues/436

**Comment by esmsesms** [comment]
Thank you for your quick reply. For the record I have just used 8.2.1 at the Intel NUC11TNHi70L and still got the same screen as shown at https://www.reddit.com/r/homelab/comments/mrmbks/trying_to_install_xcpng_on_intel_nuc_i7_10th/

**Comment by orther** [comment]
There’s a new [NUC Test 2 ISO](https://users.ntplx.net/~andrew/xcp/) that works on my NUC 11 w/ i915. You can find out more about it on this [XCP-NG community forum thread](https://xcp-ng.org/forum/topic/5596/intel-nuc10-nuc11-woes-nuc8-is-alright/68?_=1650889534131&lang=en-US)

**Comment by stormi** [comment]
This should be fixed in the XCP-ng 8.3 alpha installation ISOs, released today: https://xcp-ng.org/blog/2022/11/18/xcp-ng-8-3-alpha/

**Comment by jeremy-chua** [comment]
> This should be fixed in the XCP-ng 8.3 alpha installation ISOs, released today: https://xcp-ng.org/blog/2022/11/18/xcp-ng-8-3-alpha/

It's my first time installing XCP-ng and looking forward to getting it work.
The 8.3-alpha is not a LTS version. Is it possible to update to the LTS version once it's officially released without doing a fresh install?

**Comment by olivierlambert** [comment]
Hi,

8.3 won't be an LTS. I suppose your question is "how hard to upgrade to the final release of 8.3 if I start to use it now?", right?

**Comment by stormi** [comment]
This installation issue, besides being fixed in XCP-ng 8.3 beta, is now also fixed in refreshed installation ISOs for XCP-ng 8.2.1, that are currently undergoing public testing at https://xcp-ng.org/forum/topic/8026/xcp-ng-8-2-1-refreshed-installation-iso-better-hardware-support.

**Comment by esmsesms** [comment]
I believe with the release of the new XCP-ng 8.2.1 LTS installer on Dec 11, 2023 https://xcp-ng.org/blog/2023/12/11/updated-installer-for-xcp-ng-8-2-1/ we could close this ticket or perhaps merge it with
https://xcp-ng.org/forum/topic/5596/intel-nuc10-nuc11-woes-nuc8-is-alright/100

**Comment by stormi** [comment]
Yes, let's close it. Thanks for the reminder.
