### ISSUE TITLE
Update Java Version Installed With XOSTOR

### ISSUE THREAD

**Issue by evoelise** [xcp-ng/xcp#549]
Java gets installed as part of XOSTOR. 

```
>java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

It is using very old version of Java 1.8.0_191 - several years old at least - the latest version is 1.8.0_333. This version contains numerous critical patch advisories for security fixes. This is unlikely to be a problem as Java is not exposed but would be worthwhile seeing if this could be updated, the latest Java version should be backwards compatible as long as no insecure/out-dated cryptographic protocols are needed.

**Comment by stormi** [comment]
I think we can attempt it. The only other thing java is used for is a a build dependency for the `systemtap-runtime-java` RPM (https://github.com/xcp-ng-rpms/systemtap/blob/master/SPECS/systemtap.spec) which is not even installed by default on our servers. I'm not sure what use it has actually, if it has any.

So I don't think we risk breaking anything by updating it from the latest CentOS 7 updates.

**Comment by stormi** [comment]
Closing: this was done in the previous update to our linstor repository.
