### ISSUE TITLE
XO Enhanced VM & Storage Details for XOSTOR VDIs

### ISSUE THREAD

**Issue by evoelise** [xcp-ng/xcp#550]
It would be very useful in XO to be able to see how VDIs have been stored when XOSTOR is used. 

For example, for on VDI I can see that this is in Linstore as the following 

```
Node    ┊ Resource                                        ┊ StoragePool          ┊ VolNr ┊ MinorNr ┊ DeviceName    ┊ Allocated ┊ InUse  ┊    State 
...
XCPNG02 ┊ xcp-volume-b4b70bd0-903b-46a9-805d-289456592059 ┊ xcp-sr-linstor_group ┊     0 ┊    1003 ┊ /dev/drbd1003 ┊ 20.05 GiB ┊ Unused ┊ UpToDate ┊
XCPNG04 ┊ xcp-volume-b4b70bd0-903b-46a9-805d-289456592059 ┊ xcp-sr-linstor_group ┊     0 ┊    1003 ┊ /dev/drbd1003 ┊ 20.05 GiB ┊ InUse  ┊ UpToDate ┊
XCPNG05 ┊ xcp-volume-b4b70bd0-903b-46a9-805d-289456592059 ┊ xcp-sr-linstor_group ┊     0 ┊    1003 ┊ /dev/drbd1003 ┊ 20.05 GiB ┊ Unused ┊ UpToDate ┊
...
```

But I only know this is the actual volume as I watched it being created, otherwise it is difficult to determine which Linstore volumes are for which VM (unless I've missed something).

If the VM|Disks tab could show the reource/device name of the linstore that would be useful. Even better would be if the nodes the VDI were present on were listed and this could be invaluable when recovering HA situations.

Equally the same details are needed for XO's Storage|Disks page.

**Comment by olivierlambert** [comment]
Hi,

This is not related to this repo if it's linked to what display you'd like in XO 😉 Also, it's planned to develop an UI in XO specifically to manage your hyperconverged storage.
