### ISSUE TITLE
Weird XO Error Message When VM Started and All Servers Disabled

### ISSUE THREAD

**Issue by evoelise** [xcp-ng/xcp#556]
When an attempt to start a VM is done when all servers in the pool are disabled a weird error message is shown.

At first just a single letter is shown "g" when the VM is started, when the error is clicked to view in the error log then the following is shown - with the use name as the error. 

![Screenshot 2022-07-02 213826](https://user-images.githubusercontent.com/1719167/177015562-8384f49c-6df4-4c6e-9f8c-4f5c386b59c8.jpg)

It appears this happens as the actual error has no message:
```
vm.start
{
  "id": "122162af-de31-8a27-b78c-1**********f",
  "bypassMacAddressesCheck": false,
  "force": false
}
{
  "errors": [
    "XCPNG02: HOST_DISABLED(OpaqueRef:a1e9a8f3-0a79-4824-b29f-d**********0)",
    "XCPNG01: HOST_DISABLED(OpaqueRef:9ae9d4e6-3928-44c0-ad64-0**********e)",
    "XCPNG03: HOST_DISABLED(OpaqueRef:484dc396-2d90-497e-a35a-1**********c)"
  ],
  "message": "",
  "name": "Error",
  "stack": "Error: 
    at Xapi._startVm (file:///opt/xo/xo-builds/xen-orchestra-202206111352/packages/xo-server/src/xapi/index.mjs:880:15)
    at Xapi.startVm (file:///opt/xo/xo-builds/xen-orchestra-202206111352/packages/xo-server/src/xapi/index.mjs:916:7)
    at Api.callApiMethod (file:///opt/xo/xo-builds/xen-orchestra-202206111352/packages/xo-server/src/xo-mixins/api.mjs:310:20)"
}

```

**Comment by olivierlambert** [comment]
This is an XO issue, unrelated to XCP-ng. Please post on the right repo https://github.com/vatesfr/xen-orchestra/
