### ISSUE TITLE
Feature Request - SR-IOV Passthrough

### ISSUE THREAD

**Issue by Kal42** [xcp-ng/xcp#568]
Hi,

Is-it plan to support SR-IOV Passthrough in xcp-ng ? The goal is to have the vlan inside the VM, and not managed by the hypervisor.

Or I have missed something ?

Best regards.

**Comment by olivierlambert** [comment]
SR-IOV is already supported, not sure about the question?

**Comment by Kal42** [comment]
Yes sr-iov is supported, but vlan are no going to the VM. What I want to do, it's having the vlan tag inside the VM.

Actually vlan tagging is still managed by hypervisor, or I have missed something.

**Comment by olivierlambert** [comment]
Pinging @Fohdeesha

**Comment by nagilum99** [comment]
A few years ago (before SR-IOV) we had a problem with VLANs on XenServer. Might still be valid here:
You can either have the server doing VLAN tags or the VMs, this was a all or none. Once you enabled VLAN tags for a (physical) NIC, tags from inside any VM will be ignored.
I expect that to be the same with SR-IOV.

**Comment by Fohdeesha** [comment]
Indeed I believe Nagilum99 is correct, once you enable SR-IOV, you must use these virtual SR-IOV devices on the VMs

**Comment by Kal42** [comment]
I have an intel Intel X520-da2.

eth0 : is use "normally" with xcp-ng managing the network and the tag.

On eth1, I have just create a SR-IOV lan. (no vlan)

I put the sr-iov lan, on the VM. And try to use tag vlan. But actually it's not working.

I have also use 
/opt/xensource/libexec/xen-cmdline --set-dom0 "xen-pciback.hide=(0000:04:01.0)"
xe vm-param-set other-config:pci=0/0000:04:01.0 uuid=<vm uuid>

With one of the VF.

And it's very strange but it's same issue.

I use opnsense, as os in the VM, maybe the issue is related to freebsd driver?

Or I am totally wrong and it's not what I am supposed to do ?

**Comment by nagilum99** [comment]
If you set the VLAN tag on XCP-ng, the problem should be on their side, as it's handled to the guest VM like a normal NIC, not knowing about the tag.

**Comment by Kal42** [comment]
Thanks for everyone.

I didn't know that if we don't pull vlan on interface, all vlan will go to the VM. Maybe it could be added in the documentation ?

Regarding the issue, With tag on xcp-ng or with network managed by xcp-ng with no vlan, it's working. 
So I think the issue is the VF driver inside freebsd.

Best regards,
