### ISSUE TITLE
Kernel panic in installer when loading qla2xxx

### ISSUE THREAD

**Issue by jcharaoui** [xcp-ng/xcp#57]
When booting the install media from either XCP-ng 7.5.0 or 7.4.1 on a IBM HS21 blade, the system encounters a kernel panic related to the `qla2xxx` module and immediately reboots:

![capture d ecran de 2018-08-27 13-27-28](https://user-images.githubusercontent.com/89987/44675005-3ffa7a00-a9fd-11e8-976a-2284de5421c8.png)

When booting the installer media with `modprobe.blacklist=qla2xxx`, it works, although the FC adapter is non-functional.

I was able to trace this to a bug reported in the Ubuntu tracker: [#1554003: xenial kernel crash on HP BL460c G7 (qla24xx problem?)](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1554003). 

The patch which is reported to fix the problem is located here: [qla2xxx: Add irq affinity notification](https://patchwork.kernel.org/patch/7877421/)

I'd be willing to test a version of XCP-ng built with this patch. Thanks!

**Comment by stormi** [comment]
Does it still panic in XenServer 7.6?

**Comment by Biss2018** [comment]
Hi there, I have tried the installation file and getting the process abort with similar behaviour. I have two similar systems (one 16 core and one 24 core) one installed successfully. After reading this thread I have noticed it has a single channel FC card and the one with issues has a dual channel Qlogic FC board. Is there a workaround for this? Should I take the board out and replace it with a compatible one?

**Comment by stormi** [comment]
@Biss2018 I don't have the answers but you may want to try on the forum where more experienced users will be able to answer.

I suppose there's a way to add the FC card after installation, but I don't know how exactly, and the kernel will likely still panic unless a fixed driver is installed.

FYI the driver for qla2xxx that XCP-ng runs is not directly that of the kernel, but comes from an additional RPM package: `qlogic-qla2xxx`. If someone is willing to try to patch it (or update it to a newer version), I can try to provide guidance. (@rushikeshjadhav probably can too)

**Comment by stormi** [comment]
The source RPM for `qlogic-qla2xxx` is available at https://updates.xcp-ng.org/7/7.6/base/Source/SPackages/qlogic-qla2xxx-8.07.00.56.71-1.el7.centos.src.rpm
Tips for building it can be found at https://github.com/xcp-ng/xcp-ng-build-env

**Comment by Biss2018** [comment]
Hi Stormi, thanks for the prompt reply. I can confirm that I have a system installed now the issue being not the FC card but a problem with CPUs working at different frequencies (one of the CPUs was different) I haven't tested installing the FC card after that as I removed it suspecting this was the issue. I am planing to re-install XCP-ng 7.6 with the card installed to determine if this is also causing an issue and I will let you know.
Thanks again.

**Comment by mkaliyannan** [comment]
Did anyone resolved? I tried to upgrade xcp-7.6 on hp dl360. it's doesn't go through when reaches ql2xx card, kernel panic happened... tried several attemps no luck..

Finally I disable QLogic card from the bios, then restarted went well and got upgraded to xcp-7.6,

So I decided to enable Qlogic card on Bios, same problem.. when reaches certain point restarted the server right away..

**Comment by stormi** [comment]
The next version of XCP-ng will have a newer kernel and likely newer drivers too.

Meanwhile, we could try to provide updated test  `qla2xxx` drivers, if someone is willing to test them.

**Comment by bdonnahue** [comment]
I am having a similar problem with an amd A10 cpu. XS 7.2 - XS 7.5 work without issue.

**Comment by cheese** [comment]
I met the same issue with XCP-ng 7.6 with the FC device:
```
02:00.0 Fibre Channel [0c04]: QLogic Corp. ISP2432-based 4Gb Fibre Channel to PCI Express HBA [1077:2432] (rev 02)
        Subsystem: QLogic Corp. Device [1077:0138]
        Flags: bus master, fast devsel, latency 0, IRQ 11
        I/O ports at 8100 [size=256]
        Memory at dfc84000 (64-bit, non-prefetchable) [size=16K]
        Expansion ROM at dfc40000 [disabled] [size=256K]
        Capabilities: [44] Power Management version 2
        Capabilities: [4c] Express Endpoint, MSI 00
        Capabilities: [64] MSI: Enable- Count=1/16 Maskable- 64bit+
        Capabilities: [74] Vital Product Data
        Capabilities: [7c] MSI-X: Enable- Count=16 Masked-
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [138] Power Budgeting <?>
```

**Comment by stormi** [comment]
Could you try XCP-ng 8.0 beta? https://xcp-ng.org/forum/topic/1370/xcp-ng-8-0-0-beta-now-available

**Comment by cheese** [comment]
On 7.6 we removed the qlogic-qla2xxx package and loaded the in-tree qla2xxx driver and it works now. We may investigate further later.

**Comment by bdonnahue** [comment]
@stormi 8.0 works, thanks

**Comment by olivierlambert** [comment]
It's not bad, our own prod is on it :)

**Comment by bdonnahue** [comment]
Ahh ok, thanks @olivierlambert I will continue running it :)

**Comment by stormi** [comment]
Closing, as this driver bug is fixed in XCP-ng 8.x
