### ISSUE TITLE
Win10 Fails to Install ISO not seen?

### ISSUE THREAD

**Issue by billgertz** [xcp-ng/xcp#574]
Have tried to install Win10 54-bit using the Win10 64-bit template as bios, usefi, and uefi secure boot - all fail. With uefi and uefi secure boot after hitting any key within the few seconds of boot I get the same error:

```
Windows failed to start.
.
.
.
File: \EFI\Microsoft\Boot\BCG

Status: 0xc000000d

Info: The Boot Configuration Data for your PC is missing or contains errors. ...
```

With bios, it boots but then Windows 10 install complains there is a missing driver:

```
Load Driver

A media driver your computer needs is missing. This could be a DVD, USB or Hard disk driver. ...
``` 

In VM > Advanced > Windows Update tools is unchecked

In VM > Advanced > Boot order DVD-Drive is set first then Hard-disk second.

I have read the [xcp-ng VM Win10 documentation](https://xcp-ng.org/docs/guests.html) closely and cannot fathom the problem. Although it seems there is something going on with the ISO. Have downloaded and replaced the ISO (Win10_22H2_English_x64.iso) with no change in behaviour.

**Comment by billgertz** [comment]
Wow, third time downloading and dropping the iso into the iSo Library was the charm. Had to make space for the file by deleting other iso as the filesystem was full. it was silently truncating the iso during scp upload. My bad luck.

**Comment by billgertz** [comment]
Self-own and self-solved.

**Comment by nagilum99** [comment]
Very big warning here: Don't overdo it with ISOs on / (root)!
As also logs and other things are beeing stored there, it can make big damage to your XCP-ng installation and lead to instable systems.
It's fine using the free space, but always keep enough free space for system to work!
