### ISSUE TITLE
Unable to install xcp-ng in OVH cloud dedicated server. Stuck on 2%

### ISSUE THREAD

**Issue by anupamdutta-314e** [xcp-ng/xcp#577]
Hi all,

I am going to install xcp-ng 8.2.1 into ovh cloud dedicated server. But, it is stcuk on 2%. I have checked logs it is showing downloading state. But, I am able to install ubuntu from their template smoothly. I aslo tried to install on 2nd disk, the result is same. Below are details server and state screenshot. It is strange to me. Please help me any one. 

Thanks in advance.
State:
![2%-xcp-ng](https://user-images.githubusercontent.com/106244978/203996792-42f5a9b1-fa01-4a66-9daf-50b63cbca949.png)
Logs:
![downloading-packages-xcp-ng](https://user-images.githubusercontent.com/106244978/203996851-11edd07c-f738-4ae9-a805-e69adf0cd898.png)
Server Details:
![xcp-ng-hardware](https://user-images.githubusercontent.com/106244978/203997134-317ecef8-70aa-4639-b99c-ddabb19fbccc.png)

**Comment by nagilum99** [comment]
I see "Software RAID" - in case it's really active: Don't do that. Try again without.

**Comment by anupamdutta-314e** [comment]
Software raid is not active.

**Comment by olivierlambert** [comment]
Please post on the forum. This might NOT be an XCP-ng bug :)
