### ISSUE TITLE
"an error has occurred" in disks tab for normal users

### ISSUE THREAD

**Issue by NormanTUD** [xcp-ng/xcp#579]
I have a normal user on my XCPng installation. On each (newly created or old) VM I assign him to, he gets "an error has occurred" on the disks tab.

![Screenshot_20221130_092455](https://user-images.githubusercontent.com/34073778/204744949-76dcf431-78cd-44a4-8848-678f249ce4cf.png)

In the firefox command line, this error message pops up.

I have 3 pool servers defined, and they work, and the VM work on them, too, but on the "pools" tab for the user, none are shown.

I have xo-server 5.80.0.

**Comment by olivierlambert** [comment]
Hi,

This is not the right repository to report a Xen Orchestra issue. Please post on the forum first, in the Xen Orchestra category: https://xcp-ng.org/forum

Thanks!
