### ISSUE TITLE
Mirror management

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#58]
We need an official mirror list with location.

We also need to find the best way to sync (so far I asked to use `wget -mk https://updates.xcp-ng.org`

**Comment by stormi** [comment]
In the long term I think we should host the Tier-0 mirror on mirror.xcp-ng.org, have all mirrors sync from it, and make updates.xcp-ng.org behave intelligently to redirect to appropriate mirrors. And also allow people to switch to a specific mirror with some bundled script in XCP-ng (or use yum features for that, there's probably a way to do it).

Mirrorbrain might be an appropriate solution for this.

Not before we signed the repository metadata and RPMs though, otherwise there would be no way of identifying mirrors that would have been tampered with.

**Comment by olivierlambert** [comment]
Yes, we'll probably need to sign RPMs and repos first.

**Comment by NuxRo** [comment]
> Yes, we'll probably need to sign RPMs and repos first.

You should definitely sign your RPMs before deploying to mirrors! This is very important.

It's as easy as "rpm --resign /path/to/*.rpm" after you've generated/imported a gpg key into rpm.
I see some of the RPMs come directly from CentOS, including their signature, others are not signed at all.
You don't want to go through the shitstorm Alpine Linux went recently.

Having said that there's a mirror that updates hourly here:
http://mirrors.coreix.net/xcp-ng/updates.xcp-ng.org/
rsync://mirrors.coreix.net/mirrors/xcp-ng/updates.xcp-ng.org/

**Comment by stormi** [comment]
Yes

**Comment by olivierlambert** [comment]
@NuxRo fixed the NGINX in front, now we got an `A` grade.

**Comment by NuxRo** [comment]
> @NuxRo fixed the NGINX in front, now we got an `A` grade.

That's great, but I'm keen to see GPG signed packages. :-)

**Comment by stormi** [comment]
I'm on it :)

**Comment by stormi** [comment]
All packages for 7.6 are signed, the repodata too, and SHA256SUMS for ISOs and .repo files too.

https://github.com/xcp-ng/xcp/wiki/How-to-check-the-authenticity-of-files-downloaded-from-XCP-mirrors

**Comment by NuxRo** [comment]
That's excellent, you should think of shipping https://xcp-ng.org/RPM-GPG-KEY-xcpng in the base install somehow.
Now you can push to any mirrors, they won't be able to mess with the packages and https stops being so important.

**Comment by stormi** [comment]
Already taken care of :)
This will be in the next prelease ISO for XCP-ng 7.6.

**Comment by NuxRo** [comment]
Hi,

Do you have a rsync source for potential mirrors?

**Comment by chmuri** [comment]
Hi we could use http://www.staff.science.uu.nl/~penni101/mirmon/ in past it's working on https://www.salixos.org/mirmon.html or many other distros for mirror monitor.

How i could create mirror what is rsync address?

**Comment by stormi** [comment]
Thanks for the link. We're considering other mirror management tools too, but it's not ready yet (and the rsync address is not open yet either).

**Comment by stormi** [comment]
We're progressing on this topic. See https://github.com/xcp-ng/xcp/wiki/Mirrors

**Comment by chmuri** [comment]
Hi I will create new mirror today. Please tell me can it work only via https?

Wysłane z iPhone'a

**Comment by stormi** [comment]
We also need rsync to check the status of each file on the mirror.

**Comment by chmuri** [comment]
Ok cloud you have pre made configuration file for Rsyncd  ?  Please tell me how much space we need for whole mirror ?

Wysłane z iPhone'a

**Comment by stormi** [comment]
As written in https://github.com/xcp-ng/xcp/wiki/Mirrors you'll need approximately 30 GiB once XCP-ng 8.0 will have been released, and then it will grow with each new release.

Here's an example `/etc/rsyncd.conf`. Adapt it to your needs.

```
# /etc/rsyncd: configuration file for rsync daemon mode
# See rsyncd.conf man page for more options.
uid = nobody
gid = nobody
use chroot = no
pid file = /var/run/rsyncd.pid
transfer logging = yes
timeout = 600

[xcp-ng]
path = /path/to/mirror/files
comment = XCP-ng public mirror
read only = yes
list = yes
hosts allow = *
```

**Comment by chmuri** [comment]
Ok mirror created and request sent.

**Comment by olivierlambert** [comment]
You did a typo on the email address. It's on the dot org domain.

**Comment by chmuri** [comment]
Now its working fine @olivierlambert  :+1:

**Comment by olivierlambert** [comment]
We got it. Adding your mirror ASAP.

**Comment by olivierlambert** [comment]
Mirror added on our side, you should be able to sync.

**Comment by chmuri** [comment]
Perfect is working :+1:
Pozdrawiam Karol Chmurzyński



śr., 17 kwi 2019 o 18:54 Olivier Lambert <notifications@github.com>
napisał(a):

**Comment by chmuri** [comment]
@olivierlambert  http://mirrors.xcp-ng.org/?mirrorstats
![image](https://user-images.githubusercontent.com/19579448/56338763-af4ef500-61ab-11e9-85f4-ade11a7f9ba1.png)

**Comment by stormi** [comment]
Try visiting https://xcp-ng.org first and try again.

**Comment by chmuri** [comment]
@stormi thx now it's working. 
Please tell me if I need to be concerned that my point is on red?
![image](https://user-images.githubusercontent.com/19579448/56343588-74ed5400-61bb-11e9-87e7-f727b887341c.png)

**Comment by stormi** [comment]
I'm having a look at it and will tell you :)

**Comment by stormi** [comment]
Fixed. You gave us `http://mirror.chmuri.net/` as the mirror URL but it's `http://mirror.chmuri.net/xcp-ng/` actually :)

**Comment by chmuri** [comment]
@stormi My bad sorry :)

**Comment by stormi** [comment]
This is going quite well now. Closing.
