### ISSUE TITLE
SVG of XCP logo?

### ISSUE THREAD

**Issue by loganmarchione** [xcp-ng/xcp#583]
Hello there! 👋

I'm the maintainer of [homelab-svg-assets](https://github.com/loganmarchione/homelab-svg-assets) and would like to add the [XCP icon](https://github.com/xcp-ng/xcp/blob/master/misc/assets/logo-glossy-small.png) to my project. However, I didn't see any brand guidelines or a vector (SVG) version of the icon. Could you please provide one or both of these?

Thanks, and keep up the good work!

**Comment by olivierlambert** [comment]
Hello @loganmarchione 

Let me add @Marcpezin in this conversation

**Comment by Marcpezin** [comment]
Hello, 

I created a new page regarding brand guidelines, you will find logos of our different solutions there: https://vates.fr/blog/vates-brand-guidelines/

Thanks for bringing up that request.

**Comment by loganmarchione** [comment]
Perfect, thank you!
