### ISSUE TITLE
How to resize iscsi SR ?

### ISSUE THREAD

**Issue by drousseau** [xcp-ng/xcp#584]
I'm running XCP-ng 7.6.0

I have a SR that's running on an iscsi LUN, which was resized on the SAN.

The kernel correctly noticed the resize to 750G :

[78289551.102269] sd 15:0:0:0: [sdt] 1572864000 512-byte logical blocks: (805 GB/750 GiB)
[78289551.102273] sd 15:0:0:0: [sdt] 4096-byte physical blocks
[78289551.104656] sdt: detected capacity change from 644245094400 to 805306368000

    VG_XenStorage--b6749715--bdd6--3ad3--5980--50cebdc27716-VHD--d7c8e875--860f--42b6--af50--a083459d89dc (253:21)
     `-3600a098038314353763f505349676e35 (253:7)
        `- (65:48)

[root@ ~]# ls -l /dev/sdt
brw-rw---- 1 root disk 65, 48 Dec 30 16:11 /dev/sdt

But the SR is still shown as 600G :
( I tried xe sr-scan multiple times )

[root@ ~]# xe sr-param-get  uuid=b6749715-bdd6-3ad3-5980-50cebdc27716  param-name=physical-size 
644232511488

Also with pvs :

  /dev/mapper/3600a098038314353763f505349676e35 VG_XenStorage-b6749715-bdd6-3ad3-5980-50cebdc27716 lvm2 a--  599.99g  17.75g

I thought I could pvresize it but I get the same notice about lvmetad as in #104 :

[root@ ~]# pvresize /dev/mapper/3600a098038314353763f505349676e35
  /run/lvm/lvmetad.socket: connect failed: No such file or directory
  WARNING: Failed to connect to lvmetad. Falling back to internal scanning.
  pvresize /dev/mapper/3600a098038314353763f505349676e35: Command not permitted while global/metadata_read_only is set.

Of course I have a few important VMs running on this, so reboot is not a simple option :)

**Comment by olivierlambert** [comment]
Hi,

1. XCP-ng 7.6 isn't supported since a while now. You should consider to upgrade first.
2. I think the forum would be a better place to report your problem, since it will be impossible to reproduce on our side (nobody will reinstall an old unsupported XCP-ng version to check if a potentially fixed bug was fixed since)
