### ISSUE TITLE
Can't change interface for XOA

### ISSUE THREAD

**Issue by mik0s** [xcp-ng/xcp#587]
I'm trying to change the network interface on a running XOA instance, but the VM hangs. After turning off and on the VM - the interface remains the old one.

I assume that this is due to the fact that I make changes from the XO interface.

Can you please tell me how to do it from cli?

**Comment by olivierlambert** [comment]
Hi,

I don't see how it's related to this repository. Please either:
* open [a support ticket](https://help.vates.fr/kb/en-us/8-technical-support/15-open-a-support-ticket) if you are using XOA
* ask on the community forums in the [Xen Orchestra section](https://xcp-ng.org/forum/category/12/xen-orchestra)
