### ISSUE TITLE
SW RAID install fails if /dev/md127 already exists

### ISSUE THREAD

**Issue by pebenito** [xcp-ng/xcp#588]
I tried to do a new install on both 8.2.1 and 8.3-alpha. My goal was to use `/dev/sda` and `/dev/sdb` as a new RAID array for the installation target. The installer proceeded as expected, and I could select `sda` and `sdb` as the software RAID devices. However, at that point, the installer went back to the previous install location menu instead of going forward to the next install step (can't remember what that is).

In my setup, I already had a RAID array with VM images that I wanted to migrate from Fedora. During the install, the array was reassembled (correctly) as /dev/md127, which is what it was on the Fedora system. Once I did a `mdadm -S /dev/md127`, the install could proceed as normal, and my install was successful on 8.3-alpha (I didn't retry 8.2.1).

**Comment by stormi** [comment]
Thanks for your feedback. @ydirson is working on improvements in this area. There also is #543 and #107. I'm closing your report as a duplicate.
