### ISSUE TITLE
XCP ISO upgrade on existing XS

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#6]
That would be interesting to get to keep XAPI settings/VM/SR from a previous XS install, and install XCP "on top".

This would smooth transition from XS to XCP.

**Comment by fetzerms** [comment]
With meltdown not getting fixed in XS v6.x and Citrix changing stuff again, people might want to move/migrate from v6.x to XCP-ng - the ability to upgrade from previous versions of XS to XCP-ng would be great.

**Comment by olivierlambert** [comment]
That's completely my opinion too. I'm not really concerned: if we managed to upgrade 7x to XCP-ng, it should be relatively similar from 6.x

The only extra-stuff is the partition scheme, but we'll use probably the same mechanism that XS itself to recreate it.

**Comment by dominictayloruk** [comment]
The partition stays the same as 6.x when upgraded to 7.x and it stays the same smaller size throughout all 7.x patches, maybe this should also be factored in.

**Comment by olivierlambert** [comment]
It doesn't stay the same if you decide to. See my blog post: https://xen-orchestra.com/blog/upgrade-to-xenserver-7/#usingthenewpartitions

The only thing to consider: it removes your local SR to make room.

**Comment by olivierlambert** [comment]
This is in fact working perfectly!
