### ISSUE TITLE
Does XCP/XOA monitor drives?

### ISSUE THREAD

**Issue by michaelr0** [xcp-ng/xcp#600]
Hi There,

I'm just curious if there is anything in place for XCP/XOA to monitor drive health, including mdadm status.
Does anything alert you in the event of a failing drive/raid array?

Cheers.

**Comment by michaelr0** [comment]
These seem close to this question https://github.com/vatesfr/xen-orchestra/issues/4458 https://github.com/xcp-ng/xcp/issues/263 any updates to those?

It would be great to hard SMART status etc, but also mdadm status when viewing a drive that is detected as being an /dev/md* device

**Comment by olivierlambert** [comment]
It's a work in progress :)

**Comment by michaelr0** [comment]
Awesome thanks @olivierlambert
