### ISSUE TITLE
Creating a Private Network seems to fail with an error, but it actually creates the network.

### ISSUE THREAD

**Issue by jbmorgado** [xcp-ng/xcp#602]
When trying to create a Private Network (either VxLAN or GRE) and error pops up and the interface is marked as in an error state. But it actually created the private tunnel.

The logs show that the error is due to an Unknown CA.

1. There's no documentation or any message explaining the steps needed to create the Private Network and the need and how to set the CA.
2. Also, the process fails, so:
  2.1: This should actually be a warning, not an error.
  2.2: The interface should reflect a success with a warning and exit the process.
3. Consider adding documentation on how to properly create a Private LAN (tunnel) without this error. 

```
sdnController.createPrivateNetwork
{
  "poolIds": [
    "2f79a604-f8c4-1dd1-f905-d7d61a6c2bbc"
  ],
  "pifIds": [
    "4fa5e17d-be66-9bdb-77ed-5a0ab3dd7f18"
  ],
  "name": "teste",
  "description": "",
  "encapsulation": "vxlan",
  "encrypted": false
}
{
  "library": "SSL routines",
  "reason": "tlsv1 alert unknown ca",
  "code": "ERR_SSL_TLSV1_ALERT_UNKNOWN_CA",
  "message": "C0674865C77F0000:error:0A000418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 48
",
  "name": "Error",
  "stack": "Error: C0674865C77F0000:error:0A000418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 48
"
} 
```

**Comment by UAnton** [comment]
@jbmorgado How you resolve this error?
