### ISSUE TITLE
XO Lite does not login on 8.3 alpha 2

### ISSUE THREAD

**Issue by konsultaner** [xcp-ng/xcp#605]
@olivierlambert I finally got to install alpha 2 with IOMMU disabled, but when I try to login to `XO lite` nothing happens:

![Screenshot 2023-05-04 110741](https://user-images.githubusercontent.com/2699538/236160606-91d3c9e4-6a1d-4732-b800-b2d349bb013e.png)

I found out that the first `jsonrpc` request actually worked (the login process) but the second one listing the methods stays pending. any idea?

![image](https://user-images.githubusercontent.com/2699538/236161297-152653ca-7ba0-46b5-96c6-41cb088198cf.png)

**Comment by konsultaner** [comment]
Also if I try to create a reverse ssh tunnel to show the login screen, something goes wrong:

```bash
ssh -L 127.0.0.1:443:192.xxx.xxx.xxx:443 root@xxx.xxx.xxx.xxx
```

![image](https://user-images.githubusercontent.com/2699538/236162610-8d0dbfe5-8b60-49b2-863b-8822efdafeb8.png)

**Comment by olivierlambert** [comment]
For now, it's not yet integrated as a package inside XCP-ng, it's fetching the JS from our server. This will change when XCP-ng will be officially released. In the meantime, it allows us to develop and update at a faster pace :)
