### ISSUE TITLE
Live Telemetry not working

### ISSUE THREAD

**Issue by basher83** [xcp-ng/xcp#615]
I enabled Live Telemetry and when I click the button on my host I get: "Access to file is not permitted: /usr/share/netdata/web//index.html"

**Comment by stormi** [comment]
Hi. I think this message is not related to XCP-ng, but instead is an issue with Xen Orchestra. Possibly, if you installed from sources, from your installation (or the instructions, or a third party installation script you may have used).

The forum will be the best place to start pinpointing the exact issue: https://xcp-ng.org/forum/category/12/xen-orchestra
