### ISSUE TITLE
XO not showing Container tab in a CoreOS VM

### ISSUE THREAD

**Issue by eBeagle** [xcp-ng/xcp#62]
I did a fresh install of XCP-ng 7.5 and installed xscontainer using yum:

`yum install xscontainer`
`xe-toolstack-restart`

Installation ran successfully and didn't return any errors:

```
Command Line   : install xscontainer
Transaction performed with:
    Installed     rpm-4.11.3-17.el7.x86_64                      @install/$releasever
    Installed     yum-3.4.3-132.el7.centos.0.1.noarch           @install/$releasever
    Installed     yum-plugin-fastestmirror-1.1.31-34.el7.noarch @install/$releasever
Packages Altered:
    Dep-Install genisoimage-1.1.11-23.el7.x86_64     @xcp-ng-base
    Dep-Install libtomcrypt-1.17-25.el7.x86_64       @xcp-ng-base
    Dep-Install libtommath-0.42.0-5.el7.x86_64       @xcp-ng-base
    Dep-Install libusal-1.1.11-23.el7.x86_64         @xcp-ng-base
    Dep-Install python2-crypto-2.6.1-13.el7.x86_64   @xcp-ng-base
    Dep-Install python2-ecdsa-0.13-4.el7.noarch      @xcp-ng-base
    Dep-Install python2-paramiko-1.16.1-2.el7.noarch @xcp-ng-base
    Install     xscontainer-10.0.1-1.noarch          @xcp-ng-base
```
Downloaded the latest CoreOS iso from http://stable.release.core-os.net/amd64-usr/current/coreos_production_iso_image.iso and copied to my local ISO SR.

Created a new VM using the CoreOS template, but the Container tab is not showing on XO:

![image](https://user-images.githubusercontent.com/34895526/45504801-c09dd200-b782-11e8-8c31-3f536a555d4e.png)

![image](https://user-images.githubusercontent.com/34895526/45505105-9d275700-b783-11e8-9ca0-726e62d13fa9.png)

**Comment by jmccoy555** [comment]
Not just me then....

**Comment by stormi** [comment]
I think I remember having heard of people who succeeded in using that container plugin. I suggest to open a thread with relevant details on the forum where you are more likely to get help from the active community members, and report back here if a bug that can be fixed is found.

Forum:  https://xcp-ng.org/forum/

**Comment by jmccoy555** [comment]
Just found this thread. Not had chance to test the alterations to the cloud config yet;

https://xcp-ng.org/forum/topic/281/coreos-vm-to-run-docker-containers/15

**Comment by gt2416** [comment]
I tried that change and it still doesn't work on 7.6. 
I found that creating the coreOS from xen orchestra, it doesn't show the container tab or show that  xen tools is installed. 
However creating the same thing on xcp-ng center, the container tab shows up on xen orchestra, but it still doesn't show as a recognized docker VM nor do any running container services actually show up in the container tab. On boot coreos shows that the cloud config service failed.

**Comment by AustinSaintAubin** [comment]
@gt2416, I am having the same issue.

**Comment by dlopeza** [comment]
I had the same issue. I resolved it by installing manually the guest-tools, since I think that was the problem. Whatch this thread:

https://github.com/xcp-ng/xcp/issues/183

**Comment by stormi** [comment]
Closing as old, as this was on older releases of XCP-ng, and installation of guest tools on CoreOs has been fixed. 

Feel free to open a new issue if a similar problem is encountered again in recent XCP-ng.
