### ISSUE TITLE
Invalid attempt to start snapshots following host reboot

### ISSUE THREAD

**Issue by Danp2** [xcp-ng/xcp#625]
This is a continuation of the issue originally reported on the [forums](https://xcp-ng.org/forum/post/66447). It seems to me that [this line](https://github.com/xcp-ng/xen-api/blob/47e269cb2004e12d4d591929e6172a31559cf2ef/scripts/xapi-autostart-vms#L17) could be modified to exclude snapshots by adding  `is-a-snapshot=false` to it.

Thoughts?

**Comment by stormi** [comment]
Pinging @benjamreis and @gthvn1 for their opinion

**Comment by Danp2** [comment]
FWIW, I tried the above on my local host and it appears to work without issue AFAICS.

**Comment by benjamreis** [comment]
Thx for the report and investigation, indeed snapshots and templates should no be autostarted I opened a PR upstream to fix it. :)

Regard

**Comment by benjamreis** [comment]
Upstream PR merged. Will be released in next release.
