### ISSUE TITLE
Dell PowerEdge R350 Only UEFI Mode

### ISSUE THREAD

**Issue by clarcksp** [xcp-ng/xcp#627]
Hello, I purchased a Dell R250 and tried to install version 8.2.1, but during the installation, when copying the files, an error appears and the installation requests a reboot.
I searched the internet and came across this post on the DELL community: [Link](https://www.dell.com/community/en/conversations/rack-servers/xenserver-and-xcp-ng-on-r250/647f99d1f4ccf8a8ded49bca)

Has anyone managed to install version 8.2.1 on the Dell R250?

**Comment by olivierlambert** [comment]
Hi!

Can you try with this version of XCP-ng ISO?

https://nextcloud.vates.fr/index.php/s/5GHSMojntLKT5z5

**Comment by clarcksp** [comment]
> Hi!
> 
> Can you try with this version of XCP-ng ISO?
> 
> https://nextcloud.vates.fr/index.php/s/5GHSMojntLKT5z5
> 
> edit: and alternatively, with XCP-ng 8.3 beta 1 👍

Hi Oliver, thanks for getting back to us.
In the case of 8.3 beta, I can't use XCP Center 20.04, right?

**Comment by olivierlambert** [comment]
Sorry I don't know since we are not supporting nor using XCP-ng Center at Vates. Keep us posted :+1:

**Comment by clarcksp** [comment]
Hi Oliver.
I want to thank you immensely, it worked. I already had no expectations of what to do as the entire project is based on XCP.
I really appreciate it.

**Comment by olivierlambert** [comment]
Just to clarify: is the 8.2 nightly ISO worked or the 8.3 beta1?
