### ISSUE TITLE
Install on a partition

### ISSUE THREAD

**Issue by 0strych** [xcp-ng/xcp#628]
Is there any way of installing it inside a partition of a disk?
I've got an NVME with around 96 gB used and over 400 gB free in which I want to install xcp-ng. It is currently formatted as free under a Windows installation (Which I require to run every now and then on bare-hardware). The installer currently gave me no option to select either a partition on which to install it or a way to partition myself the disk, as a normal arch install would do.
Thanks in advanced.

**Comment by olivierlambert** [comment]
Hello,

No it's not possible. XCP-ng is meant to be an appliance, not a regular Linux distro. Tinkering with the partition layout isn't even planned.
