### ISSUE TITLE
Error "VDI_IO_ERROR(Device I/O errors)" importing via XOA

### ISSUE THREAD

**Issue by clarcksp** [xcp-ng/xcp#629]
Hey guys
I am migrating a VMware ESXI server to XCP 8.2 using the XOA import.
So far I have built several machines, all with between 40~80GB of storage.
However, when executing the migration of one of the servers that has a 240GB usable disk, problems occurred, it seems to me that it was a timeout, as the execution stopped after 4 hours of migration
This below is the end of the RAW Log that XOA generated

RAW log
`"XapiError: VDI_IO_ERROR(Device I/O errors)\n    at Function.wrap (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/_XapiError.js:16:12)\n    at _default (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/_getTaskResult.js:11:29)\n    at Xapi._addRecordToCache (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:1001:37)\n    at forEach (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:1035:14)\n    at Array.forEach (<anonymous>)\n    at Xapi._processEvents (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:1025:12)\n    at Xapi._watchEvents (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:1198:14)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at processImmediate (node:internal/timers:447:9)\n    at process.callbackTrampoline (node:internal/async_hooks:130:17)"`

**Comment by olivierlambert** [comment]
Hi!

You should create a thread on https://xcp-ng.org/forum/category/22/advanced-features it's will be the right place for this :+1: 

Thanks!
