### ISSUE TITLE
Shutdown on disruption of heartbeat

### ISSUE THREAD

**Issue by bikepope** [xcp-ng/xcp#63]
Shutdown on disruption of heartbeat. Log enclosed.
[XCP-ng Center.log](https://github.com/xcp-ng/xcp/files/2388843/XCP-ng.Center.log)

**Comment by olivierlambert** [comment]
Hi,

I'm not sure to follow. Please provide more info, your issue isn't cleat at all. Is it a XCP-ng issue or a XCP-ng Center issue?

**Comment by bikepope** [comment]
Hello.

German OK? Ich habe einen Hardware Ausfall simuliert und das Netzkabel gezogen. XCP Center offen.
Nach einiger Zeit erschien eine Meldung, dass man das Log einsenden soll. An Github? 
Der Pool ging auf rot und war nicht mehr ansprechbar. Nach Neustart des Pools war der Fehlerrechner auf rot, was OK ist. 
Verhalten ist so für mich nicht i.O. da bis anhin (7.4.1) die VM's auf einen anderen Poolmember verschoben wurden und dies ohne Absturz vonstatten ging.
Habe all Knoten (3) nochmals neu installiert. Keine Ändernung.

**Comment by olivierlambert** [comment]
Well, you can use google translate. However, that's not the main issue. It's not clear enough, also you should probably go on the forum to have more assistance, we can't say yet if it's a bug or a configuration issue: https://xcp-ng.org/forum

**Comment by bikepope** [comment]
Ok. But there is still the question, why the XCP Center is showing the host as red although is online and healthy.
![xcp](https://user-images.githubusercontent.com/40688134/45631743-dfaaa580-ba9b-11e8-880b-ddd0283a11c4.PNG)
![xcp2](https://user-images.githubusercontent.com/40688134/45631751-e20cff80-ba9b-11e8-9568-7e706ccfe63d.PNG)

**Comment by olivierlambert** [comment]
So this is a XCP-ng Center question. You aren't in the right repository then.

**Comment by borzel** [comment]
ok, das ist ein Pool mit HA... hab damit noch nix gemacht.

Laut den Logfile ist scheinbar NTP nicht konfiguriert, oder?

-------------

Ok, its a poll with HA enabled... not my field of expert :-)

The logfile says that it has a problem to resolve servertime...NTP not configured?

**Comment by stormi** [comment]
Closing since it's an XCP-ng Center question and hasn't seen activity since last comment.
