### ISSUE TITLE
xcp-ng hangs on install before splash screen

### ISSUE THREAD

**Issue by pendragonmikel** [xcp-ng/xcp#630]
Using a mini computer that I've been running ESXi on. Ryzen 5500u with 32G ram and a 512G NVMe SSD boot drive. I've tried UEFI and Legacy boot and changed the memory settings from 8G to 2G per prior posts as well as "Try to boot with the iommu=0 xen parameter."
With an unaltered install USB drive (either UEFI or Legacy) it goes through the install startup, shows "Xen is relinquishing VGA console", wipes the screen, and hangs. If I try changing the memory to 2G, (either UEFI or Legacy) it does the same thing, but then reboots itself. Google-fu has not helped me in this case. Any help would be appreciated. I don't see a path forward. 
![20231121_122434](https://github.com/xcp-ng/xcp/assets/102331382/44d2c9cb-ce68-4f35-ba13-967cafb86f8d)

**Comment by olivierlambert** [comment]
Hi,

This is something well known. It's better to ask on the forum first, and leave the GH issue repository for issues that the community can reproduce and without any workaround :)

You have 2 options:
* use a nightly 8.2.1 ISO
* use 8.3 beta 1

Some example after a quick search on the forum:
* https://xcp-ng.org/forum/topic/7934/installation-xcp-ng-8-2-1-hangs/2?_=1700588104521
* https://xcp-ng.org/forum/topic/5652/panic-on-cpu-0-xen-bug-at-iommu-init-c-1419/175?_=1700588104531 (with links toward the 8.2.1 nightly ISO)
