### ISSUE TITLE
Cannot net boot grub cfg

### ISSUE THREAD

**Issue by comsma** [xcp-ng/xcp#635]
I am following the guide for `iPXE over HTTP install` and was able to boot the grubx64.efi file on my dell poweredge r240. I am now stuck at booting the config file.
I called to these two commands in grub
```
set root=(http,10.10.0.2:8080)
configfile /EFI/xenserver/grub.cfg
```

This causes the console to refresh and do nothing.

I would also like to note that i am using the serial interface to interact with my server.

**Comment by stormi** [comment]
Hi. This is likely a configuration thing. Issues here are for bugs, so the best place to ask would be the forum: https://xcp-ng.org/forum/

Also make sure you checked the documentation: https://docs.xcp-ng.org/installation/install-xcp-ng/#-pxe-boot-install
