### ISSUE TITLE
Cloud-Init fails with "The requested plugin could not be found"

### ISSUE THREAD

**Issue by kedare** [xcp-ng/xcp#64]
When trying to create a VM with cloud-init configuration (For example coreos in my case).
The VM is created sucessfully but the cloud-init part fails with "The requested plugin could not be found" in the event logs. I could find those logs in the host : 

```
Sep 17 16:39:22 bcn-xen-3-3 xapi: [debug|bcn-xen-3-3|7182 INET :::80|host.call_plugin R:59c26c2eff57|audit] Host.call_plugin host = '1b2ee017-4e4a-4c37-8dbe-
0e6dabc718ef (bcn-xen-3-3)'; plugin = 'xscontainer'; fn = 'create_config_drive'; args = [ vmuuid: ca78526c-bf48-2c0d-6312-46a5f57810a2; sruuid: 89132e75-1f63
-9c04-03a0-be53d8563df1; configuration: <here goes my config> ]
Sep 17 16:39:22 bcn-xen-3-3 xapi: [error|bcn-xen-3-3|7182 INET :::80|dispatch:host.call_plugin D:f0781dea30e9|backtrace] host.call_plugin R:59c26c2eff57 fail
ed with exception Server_error(XENAPI_MISSING_PLUGIN, [ xscontainer ])
Sep 17 16:39:22 bcn-xen-3-3 xapi: [error|bcn-xen-3-3|7182 INET :::80|dispatch:host.call_plugin D:f0781dea30e9|backtrace] Raised Server_error(XENAPI_MISSING_PLUGIN, [ xscontainer ])
```

I think this could be related to this https://github.com/xcp-ng/xcp/issues/31 but I'm not 100%

Let me know if you need any other information.

Thanks.

**Comment by olivierlambert** [comment]
Did you installed the plugin?

**Comment by kedare** [comment]
Indeed it works better with the plugin installed :)

I thought this was included by default as the GUI gave me the option.

Thank you.
