### ISSUE TITLE
Kernel error when installing 8.2.1 version

### ISSUE THREAD

**Issue by neroxyr** [xcp-ng/xcp#640]
I'm making a fresh install with the latest xcp version but I keep getting this error and can't continue the installation

![signal-2024-02-22-152800](https://github.com/xcp-ng/xcp/assets/3222586/668f4183-13b8-43f6-938d-96cb61525660)

The server is an x86 64-bit processor

**Comment by olivierlambert** [comment]
Hi,

We tend to keep this bug tracker for confirmed issue. It's better to start a thread on our community forum: https://xcp-ng.org/forum

Also, when creating a thread there, please give more context:
* the exact hardware used
* with which kind of media you are doing the install
* any other context that could be helpful.

See you there :)
