### ISSUE TITLE
XOA quick Deploy

### ISSUE THREAD

**Issue by kkrumm1** [xcp-ng/xcp#642]
When trying to deploy XOA. I keep getting this error.

```
Importing XOA VM...
The value given is invalid
field: bridge
value: xapi1
```

xe network-list
uuid ( RO)                : 32149031-f758-6724-315b-d60a988edaa0
          name-label ( RW): Host internal management network
    name-description ( RW): Network on which guests will be assigned a private link-local IP address which can be used to talk XenAPI
              bridge ( RO): xenapi

uuid ( RO)                : 334be6f0-ceb6-f1d4-ac8f-9970bbbdb9f9
          name-label ( RW): Pool-wide network associated with eth0
    name-description ( RW): 
              bridge ( RO): xenbr0

**Comment by olivierlambert** [comment]
Thanks for the report, on it.

**Comment by kkrumm1** [comment]
Ace! Thanks!
