### ISSUE TITLE
XO with XCP-NG 8.2.1 not reporting IP addresses when VM is Ubuntu 24.04

### ISSUE THREAD

**Issue by salvador-andes** [xcp-ng/xcp#655]
Xen Orchestra not showing the IP addresses of the VM when the OS is Ubuntu 24.04. The VM is running xe-guest-utilities version 7.20.2-0ubuntu1, which is the one automatically installed when I used the command "sudo apt install xe-guest-utilities".

Versions: 
- XCP-NG 8.2.1 with all the patches at July 26th, 2024
- XO from source version: commit d4637
- xe-guest-utilities 7.20.2-0ubuntu1

![image](https://github.com/user-attachments/assets/9b3f9967-15ca-4768-b537-a5282b1cc29a)
![image](https://github.com/user-attachments/assets/25e882c5-0808-4c34-a8c2-21449db161aa)

I have another VM on the same server running Ubuntu 22.04 but in that case it shows the IP addresses

<img width="1357" alt="image" src="https://github.com/user-attachments/assets/1baf37e3-ac5e-4513-a5c0-fa347f1d41d1">

<img width="1361" alt="image" src="https://github.com/user-attachments/assets/bcc81ac4-0da6-489d-99f4-b078149ed373">

**Comment by DensonNgumo** [comment]
Same case for me. VMs that are running Ubuntu 24.04, on XCP 8.2.1, all don't show the IP information even under XCP Center.

**Comment by olivierlambert** [comment]
Hi,

Please try with the new tools we created ourselves: https://gitlab.com/xen-project/xen-guest-agent

You can find a deb here: https://gitlab.com/xen-project/xen-guest-agent/-/releases

Please report if it works, and if yes, we'll close this issue and continue to move forward to get them directly in Ubuntu.

**Comment by DensonNgumo** [comment]
Hey @olivierlambert just tested out the deb package you shared and It works for my instance. I can now see the network info. Thank you!

**Comment by olivierlambert** [comment]
Great news! Closing this as we don't want to support the XS tools anymore and use our upstream Rust ones instead :+1:

**Comment by Ringoinmel** [comment]
Can you explain more how to install it?  Thanks

**Comment by Ringoinmel** [comment]
I got dependency problem

**sudo dpkg -i xen-guest-agent-dbgsym_0.4.0_amd64.deb**
[sudo] password for ringochan: 

Selecting previously unselected package xen-guest-agent-dbgsym.
(Reading database ... 171328 files and directories currently installed.)
Preparing to unpack xen-guest-agent-dbgsym_0.4.0_amd64.deb ...
Unpacking xen-guest-agent-dbgsym (0.4.0) ...
dpkg: dependency problems prevent configuration of xen-guest-agent-dbgsym:
 xen-guest-agent-dbgsym depends on xen-guest-agent (= 0.4.0); however:
  Package xen-guest-agent is not installed.

dpkg: error processing package xen-guest-agent-dbgsym (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 xen-guest-agent-dbgsym

**Comment by Ringoinmel** [comment]
**sudo rpm -i xen-guest-agent-0.4.0-0.fc37.x86_64.rpm**

error: Failed dependencies:
	/bin/sh is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6()(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.14)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.15)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.18)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.2.5)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.25)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.28)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.3)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.3.2)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.3.4)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.4)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.7)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libc.so.6(GLIBC_2.9)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libdl.so.2()(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libdl.so.2(GLIBC_2.2.5)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libgcc_s.so.1()(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libgcc_s.so.1(GCC_3.0)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libgcc_s.so.1(GCC_3.3)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libgcc_s.so.1(GCC_4.2.0)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libm.so.6()(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libm.so.6(GLIBC_2.2.5)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libpthread.so.0()(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libpthread.so.0(GLIBC_2.12)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	libpthread.so.0(GLIBC_2.2.5)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	librt.so.1()(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	librt.so.1(GLIBC_2.2.5)(64bit) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64
	rtld(GNU_HASH) is needed by xen-guest-agent-0.4.0-0.fc37.x86_64

**Comment by Ringoinmel** [comment]
problem fixed by installing [XenServer Guest Tools v8.4.0-1](https://github.com/xenserver/xe-guest-utilities/releases/tag/v8.4.0)

**Comment by olivierlambert** [comment]
Good. However, same advice apply: you can now use the Rust tools that we made instead of XenServer ones.
