### ISSUE TITLE
yum CentOS-Base.repo invalid mirrorlist

### ISSUE THREAD

**Issue by ecoutinho** [xcp-ng/xcp#658]
After installing xcp-ng 8.3 RC1, I've tried to install nagios-plugins from CentOS-Base repo and got the following error:

> (...)
> Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=$infra error was
> 14: HTTP Error 503 - Service Unavailable
> (...)

because _mirrorlist.centos.org_ does not resolve any longer.

I had to delete mirrorlist from /etc/yum.repos.d/CentOS-Base.repo and replace each baseurl with:

```
baseurl=https://vault.centos.org/7.9.2009/os/$basearch/
baseurl=https://vault.centos.org/7.9.2009/updates/$basearch/
baseurl=https://vault.centos.org/7.9.2009/extras/$basearch/
baseurl=https://vault.centos.org/7.9.2009/centosplus/$basearch/
```

Then I was able to install the extra package. You might want to update that file.

**Comment by stormi** [comment]
Thanks for taking time to report this. It is known, and we'll update the repo files, however we'll also make it clear that anything installed from these is from an EOL repository, so may have vulnerabilities.

**Comment by ecoutinho** [comment]
That males sense. Thanks
