### ISSUE TITLE
Embed zstd support for VM export

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#66]
It seems to be possible to add `zstd` compression for VM export (XVA format). @johnelse said it was probably not that complicated, because current GZIP is just a wrapper around the binary.

So we should:

- [x] add `zstd` binary in XCP-ng (@stormi )
- [x] add an extra flag to ask for `zstd` compression during export
- [x] same flag (or autodetect?) for import
- [x] use `zstd` binary in XAPI

See https://github.com/vatesfr/xen-orchestra/issues/2523#issuecomment-350308409 for numbers regarding `zstd` speed

In a future issue, it would be also great to add `zstd` support for VHD export, but it's likely more complicated.

@johnelse I know you are already very busy with EMU-manager, but then, can you try to assist us on how to achieve that? Maybe just by pointing us into the right direction (not necessarily build the code, up to you to see what's faster)

**Comment by stormi** [comment]
EPEL has zstd 1.3.5 which seems to be the latest stable version. I'll import it.

**Comment by stormi** [comment]
zstd, libzstd and libzstd-devel added to XCP-ng 7.6

**Comment by olivierlambert** [comment]
Excellent!

**Comment by johnelse** [comment]
The existing gzip library is just a wrapper around the gzip binary:

https://github.com/xapi-project/xen-api-libs-transitional/blob/master/gzip/gzip.ml

I will try to replicate that library for zstd, hopefully reusing some of the existing code.

**Comment by olivierlambert** [comment]
@johnelse to get the best speed possible (by just losing a very small bit of compressed size), you can pass `-1` to `zstd` command. It's the lowest level of compression, but it's still enough to beat GZIP :rabbit: :turtle: 

So the command is `zstd -1 <content>`.

**Comment by stormi** [comment]
Status update: code contributed to the XAPI project (one PR accepted, one PR pending review). 

Next steps: testing and packaging.

**Comment by olivierlambert** [comment]
This has been released and now in production. See [this blog post](https://xen-orchestra.com/blog/xen-orchestra-5-31/#zstdcompressionsupportforbackup) for bench results.

![](https://xen-orchestra.com/blog/content/images/2019/01/zstd2.png)

**Comment by BoarderEB** [comment]
Really cool,

but it does contain a bug.

`xe vm-export uuid=<UUID> filename= | zstd -1 > compresszstd.xva`
`pid=$(ps ax | grep "xe vm-export vm=UUID" | grep -v "grep" | cut -d" " -f1)`
`kill $pid`
`wait $pid`
`echo $? `

= "0" 
but must something = ">0"

**Comment by nagilum99** [comment]
Should be >= "0", technically. It's one comparing operation, you can't make it on the value itself. ;P

**Comment by olivierlambert** [comment]
hmm @stormi anything we should modify on our end?

**Comment by stormi** [comment]
I'm missing the context of where the quoted commands come from

**Comment by stormi** [comment]
So if I understand correctly by inferring the context myself from the comment, `xe vm-export` wouldn't return an error return value (>0) when you kill it.

* Is it related to zstd at all?
* Does it also return 0 when a real error occurs, not a kill?

**Comment by BoarderEB** [comment]
Yes, you understand it right. But I don't now with a other error. With the kill i want to provoke the error. If a file is specified like "filename=/somthing.xva", there is an exit >0

**Comment by BoarderEB** [comment]
@nagilum99 Not realy. The code is just to describe the problem. In a script I want test if there a successfully export. With a false exit code it is not possible.

**Comment by BoarderEB** [comment]
Is there any news about the bug? 

`xe vm-export uuid=<uudi> filename= | zstd -1 > file.xva & pid=$(ps ax | grep "xe vm-export" | grep -v "grep" | cut -d" " -f1)
kill $pid
wait $pid
echo $?
`
Still returns a 

`[1]+ Done     xe vm-export uuid=<uudi> filename= | zstd -1 > file.xva
0
`
But it should be a 
`[1]+ Terminated     xe vm-export uuid=<uudi> filename= | zstd -1 > file.xva
1
`

**Comment by stormi** [comment]
As far as I can tell it's not a bug. It just looks like zstd doesn't care about the return code of the vm-export command, isn't it?

**Comment by BoarderEB** [comment]
Hi, there you are right. But that's not the bug.

I test the return code of "xe vm-export" not of zstd

This starts the export:
`xe vm-export uuid=<uudi> filename= | zstd -1 > file.xva &`

With that we get the PID from "xe vm-export", not from zstd (which is normal the vm-export-pid plus 1)
`pid=$(ps ax | grep "xe vm-export" | grep -v "grep" | cut -d" " -f1)`

No we kill "xe vm-export"
`kill $pid`

And now we get the status of "xe vm-export"
`wait $pid`

**Comment by stormi** [comment]
So, does it also return 0 when there is an actual failure of the export, not just a SIGINT signal that kills it? There are various programs that don't interpret SIGINT as an error, but simply as a "please terminate cleanly" instruction.

**Comment by BoarderEB** [comment]
Without "| zstd -1 > file.xva":

`xe vm-export uuid=<uudi> filename=file.xva `

The right status comes when it is killed. 

The bug came in by (the really nice) extension of you.

**Comment by stormi** [comment]
What if you pipe the output into something that is not zstd? gzip for example?

**Comment by BoarderEB** [comment]
I pipe in gpg there the same. And only with this really nice extension is it possible to encrypt on the fly.  That was never possible with xen.

But sorry, it is not zstd or gzip or else it is xe vm-export. They do't know if the right time has come for the end of the pipe.

**Comment by stormi** [comment]
So it's not related to the changes we made for zstd support. It's related to how the `xe vm-export` command handles being piped into another command, and is not something we at XCP-ng have changed. So I suggest to report it to the XAPI project directly, which is the upstream for `xe`: https://github.com/xapi-project/xen-api

**Comment by BoarderEB** [comment]
Oh ok, I thought the whole pipe came in through you. Then I'll report it there. Thank you for your time.

**Comment by stormi** [comment]
Now that I think of it, couldn't you simply use the `compress=zstd` parameter to vm-export and avoid the pipe altogether? That's how the feature is intended to be used.

**Comment by BoarderEB** [comment]
Yes, in that case it would be compressed. But I would like to use it to encrypt. And unfortunately that only seems to be possible with a pipe. 

```
# xe help vm-export
command name            : vm-export
        reqd params     : filename
        optional params : preserve-power-state, compress, <vm-selectors>
```

**Comment by stormi** [comment]
By the way, have you tried to pipe another command, unrelated to `xe` into gpg to check that your test procedure does yield the expected result? I'm still unsure about how the return code is defined in that situation.

**Comment by BoarderEB** [comment]
Ok, i have tried a lot but i haven't tried that yet.  A `cat file | gpg ....` brings also the wrong error code.

Together, we are smarter. Thanks a lot!

**Comment by psafont** [comment]
Have you tried using `-o pipefail` in the script?

> The return status of a pipeline is the exit status of the last command, unless the `pipefail` option is enabled. If `pipefail` is enabled, the pipeline's return status is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands exit successfully.  If the reserved  word `!` precedes  a pipeline, the exit status of that pipeline is the logical negation of the exit status as described above. The shell waits for all commands in the pipeline to terminate before returning a value.

**Comment by BoarderEB** [comment]
hi, @psafont thanks for the hint.  

But I've already solved it that way:

{
xe vm-export uuid=<uuid> filename= | zstd -1 > file.xva 
if [[ ${PIPESTATUS[0]} != 0 ]]; then
   ExportError="true"
fi
} &
echo $ExportError

And once again many thanks to @stormi  for his time and effort.
