### ISSUE TITLE
Added Memory to Host. Windows 11 VM now fails to boot and VM cannot be created

### ISSUE THREAD

**Issue by letizido** [xcp-ng/xcp#662]
I am running xcp-ng 8.3 RC2. I had one host as the master with 32G ram (xcp2) and another with 16G ram (xcp3). I created a Windows 11 VM on xcp2 and it was running perfectly. Then I installed 96G ram on xcp2 and ever since that, the Windows VM doesn't boot, and eventually I lost contact with the xcp2 server and have to reattach with Xen Orchestra. I just changed masters to xcp3, and just created a Windows 11 VM there. No problem. Is there something you can tell me about how xcp-ng behaves when memory is added? Do I have to reinstall xcp-ng?

**Comment by olivierlambert** [comment]
Hi,

1. Prioritize the forum for that kind of request (we use the bug tracker for confirmed issues): https://xcp-ng.org/forum
2. There's no reason that adding RAM will cause any problem. Check your hardware and the XCP-ng logs: https://docs.xcp-ng.org/troubleshooting/

Happy to assist you on the forum!
