### ISSUE TITLE
xolite.html Not Found on Fresh Install of XCP-ng v8.3

### ISSUE THREAD

**Issue by kismetgerald-ngc** [xcp-ng/xcp#668]
**Good Day Folks,**

I trust you're all doing well. I'm attempting to demo XCP-ng + Xen Orchestra for use in an air-gapped environment, in hopes of making a case for using this as a replacement of VMware ESXi + vCenter. I've worked with one of your sales reps to get a XOA appliance provisioned for me and I installed XCP-ng v8.3 last week. Today I attempted to access XO Lite via one of the host's IP address, and it's not working. I'm being met with the following 404 error:

`Note Found The requested URL /xolite.html was not found on this server`

Is there anything else I should be doing to access the web interface of the host, besides just punching in the IP address into the browser?

**Comment by olivierlambert** [comment]
Hi,

Thanks for your report. @stormi have we fixed it on XO Lite side but maybe not having the fix in our ISO?

**Comment by stormi** [comment]
It's fixed in the `xo-lite` package currently available in the `xcp-ng-ci` repository. We have several updates queued for 8.3 that we need to make move forward.

Once published, it won't be fixed in the ISO itself for now, so updates will have to be applied after the installation.

Right now, you can install the fixed one with:
```
yum update xo-lite --enablerepo=xcp-ng-candiates,xcp-ng-testing,xcp-ng-ci
```

**Comment by kismetgerald-ngc** [comment]
Thanks @stormi and @olivierlambert.  I've grabbed the rpm and will install it when I get to work (in about 3 hours).  Will provide an update then.

**Comment by kismetgerald-ngc** [comment]
Update - the rpm worked and XO Lite is operational on both hosts.  Now, on to figuring out how to deploy the air-gapped XOA appliance I received.

Thank you all for the assist.
