### ISSUE TITLE
Installer can't add EFI boot entry

### ISSUE THREAD

**Issue by aeonoea** [xcp-ng/xcp#670]
So with a few old Intel Mac minis lying around who make excellent servers, I thought giving xcp-ng a spin finally, but encountered an efi error.

**Hardware**

- Mac mini 2014
- SSD (orignal)
- HDD (original)

More details:
- No fusion drive, seperate drives completely wiped before
- No secure boot (introduced in 2018 model)
- Other OS like Proxmox, Win, Linux etc. can run and install just fine also via EFI boot

**Issue**

Installer won't complete fully. At around 50% of the "completing" phase, it would return an unrecoverable error:

> Failed to add new efi boot entry: Could not prepare
> Boot variable: Invalid argument.

Interestingly after confirming the error, xcp-ng would just boot up fine, but is useless as the root password is not working, as already experienced by another user [here](https://github.com/xcp-ng/xcp/issues/659#issue-2468908655).

Starting the installer with the alternative kernel didn't make a difference unfortunately.

**Traceback**

> Traceback (most recent call last):
> File "/opt/xensource/installer/install.py", line 284, in go
> backend.perfornInstallation(results, ui, interactive)
> File "/opt/xensource/installer/backend.py", line 476, in performInstallation
> executeSequence (fin_seq, "Completing installation...", answers, ui_package, True)
> File "/opt/xensource/installer/backend.py", line 283, in executeSequence
> updated_state = item.execute (answers, progressCallback)
> File "/opt/xensource/installer/backend.py", line 81, in execute
> rv = apply(self.fn, args)
> File "/opt/xensource/installer/backend.py", line 1125, in installBootLoader
> setEfiBootEntry(mounts, disk, boot_partnum, install_type, branding)
> File "/opt/xensource/installer/backend.py, line 1185, in setEfiBootEntry
> check_efibootmgr_err(rc, err, install_type, "Failed to add new efi boot entry")
> File "/opt/xensource/installer/backend.py, line 1157, in check_efibootmgr_err
> raise RuntimeError ("%s: %s" % (err_type, err))
> RuntimeError: Failed to add new efi boot entry: Could not prepare Boot variable: Invalid argument

(may contain some typos as transcribed from a photo)

**Comment by stormi** [comment]
Hi! Sorry for the late reply. This looks a lot like this other issue: #489. I'm closing this one to keep a single issue where we can discuss the topic in one place.
