### ISSUE TITLE
very outdated samba makes samba unusable from GUI

### ISSUE THREAD

**Issue by thctlo** [xcp-ng/xcp#69]
Hai, 
I notice samba is still 4.2.3  Which is EOL for some time now. 

If you want to create a CIFS SR against a new samba version, it wont work because xen is trying to mount over SMB1. 

xcp-ng should upgrade to at least, samba 4.7.10  or 4.8.5 or 4.9.2

**Comment by olivierlambert** [comment]
XenServer 7.5 Administrator guide tells that SMB 3.0 is supported by default (page 83).

**Comment by thctlo** [comment]
smbclient, 4.2.x still has the defaults set to SMB1.

**Comment by olivierlambert** [comment]
XenServer/XCP-ng is a layer on top, so we can't assume what commands are set to the SMB mount just by checking `smbclient` version. Check your mount properties.

Again, the official doc explains that's 3.0 is done by default, if it's not the case, then we should report the issue to https://bugs.xenserver.org first.

**Comment by thctlo** [comment]
From the manual, i took the command line to try it. 
xe sr-create content-type=user name-label="TEST shared SMB SR"> shared=true device-config:server=//hostname.dom.tld/share1 device-config:username='DOM\user' device-config:password='password' type=smb 
( tested with and without domainname ) 

Error code: SR_BACKEND_FAILURE_111
Error parameters: , SMB mount error [opterr=mount failed with return code 32]

**Comment by polar147** [comment]
I have the same problem on XCP-NG 7.6.0

**Comment by stormi** [comment]
You might be interested in this: https://xcp-ng.org/forum/topic/726/experimental-update-of-centos-packages

**Comment by thctlo** [comment]
My solution was upgrade my samba version to 4.8.x on all my Debian servers. 
installed XCP-NG 7.6 and now it works great.

**Comment by mondialkr** [comment]
I migrated xcp-ng 8.0RC from XenServer 7.6.  
The version of xcp-ng 8.0RC's sambaclient is 4.7.1. 

But, I can not connect Windows fileserver.
- Command : xe sr-create content-type=user name-label=SMB shared=true device-config:server=//172.17.21.165 device-config:username='mondial' device-config:password='xxxxxx' type=smb 
- Error code : SR_BACKEND_FAILURE_111 
- Error parameters :  , SMB mount error [opterr=mount failed with return code 32],
So, I checked log file and found another error message : mount error(22): Invalid argument


----------------------------------------------------------------------------------------
Jul 19 10:06:38 xen3 SM: [10552] lock: opening lock file /var/lock/sm/e39a7e38-bdcf-0cdd-5261-5d407dd06a88/sr
Jul 19 10:06:38 xen3 SM: [10552] lock: acquired /var/lock/sm/e39a7e38-bdcf-0cdd-5261-5d407dd06a88/sr
Jul 19 10:06:38 xen3 SM: [10552] sr_create {'sr_uuid': 'e39a7e38-bdcf-0cdd-5261-5d407dd06a88', 'subtask_of': 'DummyRef:|e2e0f316-8138-4a1a-abbf-16e71867b83b|SR.create', 'args': ['0'], 'host_ref': 'OpaqueRef:939eb74f-90e0-48c2-9163-0155a5f6d1b5', 'session_ref': 'OpaqueRef:ce9e818f-be91-4aba-9518-ae7543e9720f', 'device_config': {'username': 'mondial', 'password': '******', 'SRmaster': 'true', 'server': '//172.17.21.165'}, 'command': 'sr_create', 'sr_ref': 'OpaqueRef:26cd6191-5b61-4198-8b64-a7c31c2c6c05'}
Jul 19 10:06:38 xen3 SM: [10552] ['uuidgen', '-r']
Jul 19 10:06:38 xen3 SM: [10552]   pread SUCCESS
Jul 19 10:06:38 xen3 SM: [10552] ['mount.cifs', '//172.17.21.165', '/var/run/sr-mount/SMB/172.17.21.165/e39a7e38-bdcf-0cdd-5261-5d407dd06a88', '-o', 'cache=loose,vers=3.0,actimeo=0,credentials=/tmp/24b26b0f-3b73-40f6-a535-d39db0a6e472']
Jul 19 10:06:38 xen3 SM: [10552] FAILED in util.pread: (rc 32) stdout: '', stderr: 'mount error(22): Invalid argument
Jul 19 10:06:38 xen3 SM: [10552] Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
Jul 19 10:06:38 xen3 SM: [10552] '
Jul 19 10:06:39 xen3 SM: [10552] ['mount.cifs', '//172.17.21.165', '/var/run/sr-mount/SMB/172.17.21.165/e39a7e38-bdcf-0cdd-5261-5d407dd06a88', '-o', 'cache=loose,vers=3.0,actimeo=0,credentials=/tmp/24b26b0f-3b73-40f6-a535-d39db0a6e472']
Jul 19 10:06:39 xen3 SM: [10552] FAILED in util.pread: (rc 32) stdout: '', stderr: 'mount error(22): Invalid argument
Jul 19 10:06:39 xen3 SM: [10552] Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
Jul 19 10:06:39 xen3 SM: [10552] '
Jul 19 10:06:39 xen3 SM: [10552] Raising exception [111, SMB mount error [opterr=mount failed with return code 32]]
Jul 19 10:06:39 xen3 SM: [10552] lock: released /var/lock/sm/e39a7e38-bdcf-0cdd-5261-5d407dd06a88/sr
Jul 19 10:06:39 xen3 SM: [10552] ***** generic exception: sr_create: EXCEPTION <class 'SR.SROSError'>, SMB mount error [opterr=mount failed with return code 32]
Jul 19 10:06:39 xen3 SM: [10552]   File "/opt/xensource/sm/SRCommand.py", line 110, in run
Jul 19 10:06:39 xen3 SM: [10552]     return self._run_locked(sr)
Jul 19 10:06:39 xen3 SM: [10552]   File "/opt/xensource/sm/SRCommand.py", line 159, in _run_locked
Jul 19 10:06:39 xen3 SM: [10552]     rv = self._run(sr, target)
Jul 19 10:06:39 xen3 SM: [10552]   File "/opt/xensource/sm/SRCommand.py", line 323, in _run
Jul 19 10:06:39 xen3 SM: [10552]     return sr.create(self.params['sr_uuid'], long(self.params['args'][0]))
Jul 19 10:06:39 xen3 SM: [10552]   File "/opt/xensource/sm/SMBSR", line 285, in create
Jul 19 10:06:39 xen3 SM: [10552]     raise xs_errors.XenError('SMBMount', opterr=exc.errstr)
Jul 19 10:06:39 xen3 SM: [10552]
Jul 19 10:06:39 xen3 SM: [10552] ***** SMB VHD: EXCEPTION <class 'SR.SROSError'>, SMB mount error [opterr=mount failed with return code 32]
Jul 19 10:06:39 xen3 SM: [10552]   File "/opt/xensource/sm/SRCommand.py", line 372, in run
Jul 19 10:06:39 xen3 SM: [10552]     ret = cmd.run(sr)
Jul 19 10:06:39 xen3 SM: [10552]   File "/opt/xensource/sm/SRCommand.py", line 110, in run
Jul 19 10:06:39 xen3 SM: [10552]     return self._run_locked(sr)
Jul 19 10:06:39 xen3 SM: [10552]   File "/opt/xensource/sm/SRCommand.py", line 159, in _run_locked
Jul 19 10:06:39 xen3 SM: [10552]     rv = self._run(sr, target)
Jul 19 10:06:39 xen3 SM: [10552]   File "/opt/xensource/sm/SRCommand.py", line 323, in _run
Jul 19 10:06:39 xen3 SM: [10552]     return sr.create(self.params['sr_uuid'], long(self.params['args'][0]))
Jul 19 10:06:39 xen3 SM: [10552]   File "/opt/xensource/sm/SMBSR", line 285, in create
Jul 19 10:06:39 xen3 SM: [10552]     raise xs_errors.XenError('SMBMount', opterr=exc.errstr)
Jul 19 10:06:39 xen3 SM: [10552]
Jul 19 10:06:39 xen3 SM: [10552] lock: closed /var/lock/sm/e39a7e38-bdcf-0cdd-5261-5d407dd06a88/sr

**Comment by nagilum99** [comment]
I'm not super sure right now about linux, but // usually is NFS and \\ is SMB, so it should be backslash, not slash.
Also you could try XCP-ng Center via GUI to see if that one works.

**Comment by mondialkr** [comment]
I tested "\\" instead of "//".
But, the same error has been issued.

**Comment by olivierlambert** [comment]
Try without any `/` or `\`, just the IP address.

**Comment by mondialkr** [comment]
A similar error message has been issued.


--------------------------------------------------------------------------------------

[15:55 xen3 /]# xe sr-create content-type=user name-label=SMB shared=true device-config:server=172.17.21.165 device-config:username='mondial' device-config:password='ahWkfxm' type=smb
Error code: SR_BACKEND_FAILURE_111
Error parameters: , SMB mount error [opterr=mount failed with return code 1],



Jul 19 15:55:28 xen3 SM: [9970] lock: opening lock file /var/lock/sm/67b765b0-0c4c-d1db-e92f-71d44b72b3cc/sr
Jul 19 15:55:28 xen3 SM: [9970] lock: acquired /var/lock/sm/67b765b0-0c4c-d1db-e92f-71d44b72b3cc/sr
Jul 19 15:55:28 xen3 SM: [9970] sr_create {'sr_uuid': '67b765b0-0c4c-d1db-e92f-71d44b72b3cc', 'subtask_of': 'DummyRef:|815676b1-2efa-4d9e-97e3-c6963ac4b592|SR.create', 'args': ['0'], 'host_ref': 'OpaqueRef:939eb74f-90e0-48c2-9163-0155a5f6d1b5', 'session_ref': 'OpaqueRef:1132ddd9-4cbe-4b0d-910f-9a3ca4978720', 'device_config': {'username': 'mondial', 'password': '******', 'SRmaster': 'true', 'server': '172.17.21.165'}, 'command': 'sr_create', 'sr_ref': 'OpaqueRef:3ef42c47-a143-4334-891b-b83116b7d50a'}
Jul 19 15:55:28 xen3 SM: [9970] ['uuidgen', '-r']
Jul 19 15:55:28 xen3 SM: [9970]   pread SUCCESS
Jul 19 15:55:28 xen3 SM: [9970] ['mount.cifs', '172.17.21.165', '/var/run/sr-mount/SMB/2.17.21.165/67b765b0-0c4c-d1db-e92f-71d44b72b3cc', '-o', 'cache=loose,vers=3.0,actimeo=0,credentials=/tmp/657e8b3f-e10d-426d-a584-b5b7aa4389ad']
Jul 19 15:55:28 xen3 SM: [9970] FAILED in util.pread: (rc 1) stdout: '', stderr: 'mount.cifs: bad UNC (172.17.21.165)
Jul 19 15:55:28 xen3 SM: [9970] '
Jul 19 15:55:28 xen3 SM: [9970] Raising exception [111, SMB mount error [opterr=mount failed with return code 1]]
Jul 19 15:55:28 xen3 SM: [9970] lock: released /var/lock/sm/67b765b0-0c4c-d1db-e92f-71d44b72b3cc/sr
Jul 19 15:55:28 xen3 SM: [9970] ***** generic exception: sr_create: EXCEPTION <class 'SR.SROSError'>, SMB mount error [opterr=mount failed with return code 1]
Jul 19 15:55:28 xen3 SM: [9970]   File "/opt/xensource/sm/SRCommand.py", line 110, in run
Jul 19 15:55:28 xen3 SM: [9970]     return self._run_locked(sr)
Jul 19 15:55:28 xen3 SM: [9970]   File "/opt/xensource/sm/SRCommand.py", line 159, in _run_locked
Jul 19 15:55:28 xen3 SM: [9970]     rv = self._run(sr, target)
Jul 19 15:55:28 xen3 SM: [9970]   File "/opt/xensource/sm/SRCommand.py", line 323, in _run
Jul 19 15:55:28 xen3 SM: [9970]     return sr.create(self.params['sr_uuid'], long(self.params['args'][0]))
Jul 19 15:55:28 xen3 SM: [9970]   File "/opt/xensource/sm/SMBSR", line 285, in create
Jul 19 15:55:28 xen3 SM: [9970]     raise xs_errors.XenError('SMBMount', opterr=exc.errstr)
Jul 19 15:55:28 xen3 SM: [9970]
Jul 19 15:55:28 xen3 SM: [9970] ***** SMB VHD: EXCEPTION <class 'SR.SROSError'>, SMB mount error [opterr=mount failed with return code 1]
Jul 19 15:55:28 xen3 SM: [9970]   File "/opt/xensource/sm/SRCommand.py", line 372, in run
Jul 19 15:55:28 xen3 SM: [9970]     ret = cmd.run(sr)
Jul 19 15:55:28 xen3 SM: [9970]   File "/opt/xensource/sm/SRCommand.py", line 110, in run
Jul 19 15:55:28 xen3 SM: [9970]     return self._run_locked(sr)
Jul 19 15:55:28 xen3 SM: [9970]   File "/opt/xensource/sm/SRCommand.py", line 159, in _run_locked
Jul 19 15:55:28 xen3 SM: [9970]     rv = self._run(sr, target)
Jul 19 15:55:28 xen3 SM: [9970]   File "/opt/xensource/sm/SRCommand.py", line 323, in _run
Jul 19 15:55:28 xen3 SM: [9970]     return sr.create(self.params['sr_uuid'], long(self.params['args'][0]))
Jul 19 15:55:28 xen3 SM: [9970]   File "/opt/xensource/sm/SMBSR", line 285, in create
Jul 19 15:55:28 xen3 SM: [9970]     raise xs_errors.XenError('SMBMount', opterr=exc.errstr)

**Comment by olivierlambert** [comment]
The forum would be a better place for that, I think it might be an incorrect `xe` parameter (but I'm not using SMB at all so I can't spot it easily)

**Comment by mondialkr** [comment]
Thanks for you advice.
I will ask at the forum.

**Comment by stormi** [comment]
Samba was updated with XCP-ng 8.0. Closing.
