### ISSUE TITLE
Start thinking about repo requirements -- particularly building and signing

### ISSUE THREAD

**Issue by Storycrafter** [xcp-ng/xcp#7]

**Comment by olivierlambert** [comment]
Signing won't be really complicated I think (creating a PGP key, right?)

Regarding building process, yes it should be fully automated (eg fetching the sources RPMs, includes our patches, build the RPMs and send them to the repo).

**Comment by Storycrafter** [comment]
Cool. I've never done it, but I imagined it was as easy as you describe. I just wanted to capture the task for now.

**Comment by olivierlambert** [comment]
There is already a public RPM repo, cf the end of this blog post: https://xcp-ng.github.io/news/2018/01/22/xcp-ng-on-tracks.html

I made it, but for now it's not signed with a key.

**Comment by stormi** [comment]
This is now done. We're using Koji as a build system and the RPMs are signed since XCP-ng 7.6. See https://github.com/xcp-ng/xcp/wiki/Development-process-tour for more information.
