### ISSUE TITLE
Remove unsupported GFS2 license

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xcp#70]
# Issue
GFS2/Cluster/corosync is not supported in XCP-ng but it reports the license param `restrict_corosync` as **false**

# Solution
report `restrict_corosync` as **true**

# Background
https://github.com/xcp-ng/xenadmin/issues/108

**Comment by stormi** [comment]
@johnelse Something for you?

**Comment by johnelse** [comment]
Yes that'll be an easy change, I'll have a look tonight.

**Comment by johnelse** [comment]
https://github.com/xcp-ng/xcp-featured/pull/2

**Comment by stormi** [comment]
Merged, and update pushed to 7.6 repos.

**Comment by stormi** [comment]
I'll wait for tests before closing :)

**Comment by borzel** [comment]
ahh... it just came to my mind ... what if people had it activated and rely on the cluster part of it? Can this be an issue?

**Comment by stormi** [comment]
We could improve xcp-emu-manager in the future to let it detect the presence of the appropriate proprietary packages, if the need arises. If no one asks for it, then I'd rather not invest time and energy in supporting proprietary features.
