### ISSUE TITLE
add ZFS support

### ISSUE THREAD

**Issue by nraynaud** [xcp-ng/xcp#74]
A lot of the VHD code uses `O_DIRECT` which is not supported by ZFS, let's remove it.

**Comment by stormi** [comment]
What's current status on this enhancement?

**Comment by nraynaud** [comment]
It's still far from done, for now I'm on hold on this topic for immigration reasons.

**Comment by olivierlambert** [comment]
We could close this since ZoL 0.8 fixes all issues.
