### ISSUE TITLE
VSS Provider not working

### ISSUE THREAD

**Issue by borzel** [xcp-ng/xcp#87]
Not working on
* [ ] Windows 10 x64
* [ ] Windows Server 2012 R2
* [ ] Windows Server 2016 x64

**Comment by tiancu1980** [comment]
Working on 
WIN 10 Pro  x64
WIN server 2019 x64 standard

**Comment by ruskofd** [comment]
Like explained on the forum, it seems to work on : 

- [x] Windows Server 2019 Core Standard (x64) : French Locale
- [x] Windows Server 2019 Desktop Experience Standard (x64) : French Locale

https://xcp-ng.org/forum/topic/636/beta-release-xcp-ng-windows-client-tools-8-2-1-beta1/39

**Comment by stormi** [comment]
VSS support has been removed from Citrix Hypervisor and XCP-ng thus closing this issue.

We provided a new RAM-backup feature instead.
