### ISSUE TITLE
Add a [general] section to .treeinfo to make pulp happy

### ISSUE THREAD

**Issue by stormi** [xcp-ng/xcp#88]
pulp doesn't like our .treeinfo in https://updates.xcp-ng.org/netinstall/latest/ because it lacks a [general] section.

An example of such a section:

```
[general]
name = XenServer-7.2
family = XenServer
timestamp = 1449700442.21
variant =
version = 7.2
packagedir =
arch = x86_64
```

See also https://github.com/pulp/pulp_rpm/blob/2-master/plugins/pulp_rpm/plugins/importers/yum/parse/treeinfo.py#L476

We could consider adding this section when building the ISOs and the netinstall repository.

**Comment by NeilHanlon** [comment]
@stormi 

Long road back here, but this is the treeinfo file we're using that appears to work with Katello/Pulp.


[treeinfo.txt](https://github.com/xcp-ng/xcp/files/2926658/treeinfo.txt)

**Comment by stormi** [comment]
Thanks. I know nothing about those tools. Do you think it is generic enough, or are there bits that are specific to your setup?

**Comment by NeilHanlon** [comment]
Yeah I think it is generic enough.

**Comment by stormi** [comment]
I'm working on it right now for the upcoming XCP-ng 8.0 RC, but there's something that struck me:
```
[images-x86_64]
kernel = boot/pxelinux/mboot.c32
initrd = boot/vmlinuz
boot.iso = boot/xen.gz
```

How can vmlinuz, which is the kernel, fit the initrd entry? Can you also explain the other values in this section to me?

**Comment by borzel** [comment]
@stormi https://wiki.syslinux.org/wiki/index.php?title=Mboot.c32

this is a helper for PXE. /boot/vmlinuz is just a "parameter" for that mboot.c32. So from that view at this stage, the mboot.c32 is the "kernel"

**Comment by stormi** [comment]
Ok, the commits are made and the next ISO will have this enhanced .treeinfo file. Closing.

**Comment by ydirson** [comment]
@NeilHanlon @borzel could you please elaborate on what those additional sections are useful for?  Since we added those, they possibly could be useful for other users and could use some more documentation.
I'm especially interested in which tool uses which information. I located some apparently-kickstart-related code in pulp-rpm, which parses the `[images-*]` sections, but can't really deduce what it can achieve with XCP-ng.
