### ISSUE TITLE
pfSense template

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#89]
We should add another extra "empty" template by default in XCP-ng: pfSense.

This template should contains all the settings needed to work correctly (eg no hardware eth checksum etc).

@Fohdeesha can you give me all the right settings to do?

**Comment by Fohdeesha** [comment]
This is a really good idea! The only thing that needs changing on the xen side is `other-config:ethtool-tx="off"` for every interface added to the VM. Is there a way we can have the template do this for interfaces added during VM creation, but also interfaces added later? (after the VM has been created).

There's a couple commands that need to be ran in the VM afterwords to install xentools, but I don't think we can handle those with a template. My info here has everything needed (some guides say to turn off checksumming in pfsense UI, or turn off other offload settings in xen, but from testing they don't do anything at best and actually harm performance at worst) https://forum.netgate.com/topic/97553/pfsense-2-3-on-xen-server/5

**Comment by Fohdeesha** [comment]
also FYI freebsd keeps saying this will be fixed so maybe one day it won't be necessary, but after seeing it supposedly fixed and then still broken in, 10, 11, and now 12, I don't have my hopes up

**Comment by olivierlambert** [comment]
I need to check if there is a way to have a kind of "sticky" config that would disable eth-tool thing for each VIF created then. I'm not sure it exists.

You don't need to disable it for RX?

**Comment by Fohdeesha** [comment]
nope, just rx

**Comment by borzel** [comment]
Edited my wiki entry to redirect to this thread: https://github.com/xcp-ng/xcp/wiki/Guest-System-Support#pfsense

**Comment by maayant** [comment]
While on the topic, although I'm not sure if this requires a dedicated thread.
Going over 7 NICs for pfSense freezes the VM (tested on latest XCP and pfSense versions).

https://redmine.pfsense.org/issues/8207
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=183337

**Comment by stormi** [comment]
Do we still need a specific pfSense template?

**Comment by olivierlambert** [comment]
nope, also you can't really configure other config in VIF in a template.

**Comment by stormi** [comment]
If I understood the answer correctly, there is not need for this template anymore (unless we still want to provide one as a convenience). Closing, feel free to reopen.
