### ISSUE TITLE
Debian based distro support

### ISSUE THREAD

**Issue by olivierlambert** [xcp-ng/xcp#9]
Some people asked for it. Sounds hard to achieve, but we'll explore this in Phase III

**Comment by aut0exec** [comment]
This would be fantastic. Was looking into trying to build a Xen based system with Debian. If XCP is to pursue this, please let me know how I could help.

**Comment by yctn** [comment]
Debian is awesome this would be cool

**Comment by thctlo** [comment]
I'm wondering why also. 

Debian already includes Xen, im a heavy Debian user, used the xen hypervisor on Debian and im using xcp-ng.  Both are ok to me.

I.m.o.  better spend the time on improving xcp-ng as it is now, its great, but lets make it even greater.. :-)

**Comment by olivierlambert** [comment]
Why? Because XCP-ng do NOT use Xen bundled in CentOS (nor in Debian obviously), but a "vanilla" Xen + ton of patches, same for various CentOS packages that are patched to make it work.

So you'll need a vast amount of resources to apply those patches to different packages, which are not getting the same version number etc.

It's not impossible technically but require a LOT of work. Obviously, your contributions are welcome!!

**Comment by stormi** [comment]
So, as has been said earlier, re-basing XCP-ng on top of Debian would require a tremendous amount of work, and would end-up in being a totally different project. Thus I'm closing this enhancement idea, while at the same time renewing my previous statement that if anyone wants to start such a project, we'd try to offer our help (pointers, advice...).
