### ISSUE TITLE
xapi or state.db broken after XCP-NG 7.6 Upgrade from 7.5 

### ISSUE THREAD

**Issue by cocoon** [xcp-ng/xcp#94]
As discussed here: 
https://xcp-ng.org/forum/topic/575/vmware-xcp-ng-7-6-iso-upgrade-from-7-5-network-gone

After upgrading 2 VMware VMs xapi is not working anymore because it can't read the database state.db.
Upgrade was tested with ISO anmd YUM with the same problem.

**Problems that are caused by this:**

There is no network adapter shown in the console menu and it is not configurable with "Configure Management Interface" as it shows no interface to select, only "<No interfaces present>".
But on the command line there are still the interfaces and bridges and ping/ssh from/to the ip is still working.

**xe commands are not working:**
```php
xe network-list
Error: Connection refused (calling connect )`
```

**On the console the following message appears:**
```php
xapi-nbd[6121]: main: Failed to log in via xapi's Unix domain socket in 300.000000 seconds
```

The real problem:

**xapi error in /var/log/xensource.log:**

```php
Nov  1 09:25:52 xen-01 xapi: [error|xen-01|0 ||backtrace] server_init D:7b76fe698182 failed with exception Db_exn.DBCache_NotFound("missing column", "Cluster", "network")
Nov  1 09:25:52 xen-01 xapi: [error|xen-01|0 ||backtrace] Raised Db_exn.DBCache_NotFound("missing column", "Cluster", "network")
Nov  1 09:25:52 xen-01 xapi: [error|xen-01|0 ||backtrace] 1/1 xapi @ xen-01 Raised at file (Thread 0 has no backtrace table. Was with_backtraces called?, line 0
Nov  1 09:25:52 xen-01 xapi: [error|xen-01|0 ||backtrace]
Nov  1 09:25:52 xen-01 xapi: [debug|xen-01|0 ||xapi] xapi top-level caught exception: INTERNAL_ERROR: [ missing column; Cluster; network ]
Nov  1 09:25:52 xen-01 xapi: [error|xen-01|0 ||backtrace] Raised Db_exn.DBCache_NotFound("missing column", "Cluster", "network")
Nov  1 09:25:52 xen-01 xapi: [error|xen-01|0 ||backtrace] 1/1 xapi @ xen-01 Raised at file (Thread 0 has no backtrace table. Was with_backtraces called?, line 0
Nov  1 09:25:52 xen-01 xapi: [error|xen-01|0 ||backtrace]
Nov  1 09:25:53 xen-01 xapi: [ warn|xen-01|0 ||xapi] Duplicate configuration keys in Xcp_service.configure: disable-logging-for in [ use-switch; switch-path; search-path; pidfile; log; daemon; disable-logging-for; loglevel; inventory; config; config-dir; master_connection_reset_timeout; master_connection_retry_timeout; master_connection_default_timeout; qemu_dm_ready_timeout; hotplug_timeout; pif_reconfigure_ip_timeout; pool_db_sync_interval; pool_data_sync_interval; domain_shutdown_total_timeout; emergency_reboot_delay_base; emergency_reboot_delay_extra; ha_xapi_healthcheck_interval; ha_xapi_healthcheck_timeout; ha_xapi_restart_attempts; ha_xapi_restart_timeout; logrotate_check_interval; rrd_backup_interval; session_revalidation_interval; update_all_subjects_interval; wait_memory_target_timeout; snapshot_with_quiesce_timeout; host_heartbeat_interval; host_assumed_dead_interval; fuse_time; db_restore_fuse_time; inactive_session_timeout; pending_task_timeout; completed_task_timeout; minimum_time_between_bounces; minimum_time_between_reboot_with_no_added_delay; ha_monitor_interval; ha_monitor_plan_interval; ha_monitor_startup_timeout; ha_default_timeout_base; guest_liveness_timeout; permanent_master_failure_retry_interval; redo_log_max_block_time_empty; redo_log_max_block_time_read; redo_log_max_block_time_writedelta; redo_log_max_block_time_writedb; redo_log_max_startup_time; redo_log_connect_delay; default-vbd3-polling-duration; default-vbd3-polling-idle-threshold; vm_call_plugin_interval; xapi_clusterd_port; sm-plugins; hotfix-fingerprint; logconfig; writereadyfile; writeinitcomplete; nowatchdog; log-getter; onsystemboot; relax-xsm-sr-check; disable-logging-for; disable-dbsync-for; xenopsd-queues; xenopsd-default; nvidia-whitelist; igd-passthru-vendor-whitelist; gvt-g-whitelist; mxgpu-whitelist; pass-through-pif-carrier; cluster-stack-default; ciphersuites-good-outbound; ciphersuites-legacy-outbound; gpumon_stop_timeout; reboot_required_hfxs; xen_livepatch_list; kpatch_list; modprobe_path; db_idempotent_map; post-install-scripts-dir; gpg-homedir; xen-cmdline; cluster-stack-root; web-dir; tools-sr-dir; sm-dir; udhcpd-skel; db-config-file; pool_config_file; fcoe-driver; xen-cmdline-script; static-vdis; xsh; xe-toolstack-restart; xe; host-restore; host-backup; upload-wrapper; update-mh-info; logs-download; xe-syslog-reconfigure; set-hostname; host-bugreport-upload; fence; vhd-tool; sparse_dd; redo-log-block-device-io; pbis-force-domain-leave-script; busybox; xapissl; startup-script-hook; rolling-upgrade-script-hook; xapi-message-script; non-managed-pifs; update-issue; killall; nbd-firewall-config; firewall-port-config; nbd_client_manager; pool_secret_path; udhcpd-conf; remote-db-conf-file; logconfig; cpu-info-file; server-cert-path; iscsi_initiatorname; master-scripts-dir; packs-dir; xapi-hooks-root; xapi-plugins-root; xapi-extensions-root; static-vdis-root ]
```

**Details about the environment:**

- VMware ESXi v6.0.0 6921384
- 3 network adapters, 2 adapters on one network and the one in the middle on another network
- VM nic tested: Intel E1000E and also changing to E1000
- VM was I think initially installed with Citrix Xen Server 7.4 and then upgraded to XCP-NG 7.4 or directly fresh installed with XCP-NG 7.4 (can't remember), then Upgraded to 7.5 and now to 7.6
- It was a Cluster with a pool and also used with CloudStack and had multiple vlan
-OVS backend network enabled

![Image](https://img.picload.org/image/dcograag/2018-11-01_no_network-01.png)

![Image](https://img.picload.org/image/dcograar/2018-11-01_no_network-02.png)

The same problem was reportet on the forum to happen on a Cluster with Dell M600.

**Comment by cocoon** [comment]
New Test: Upgrade XCP-NG 7.5 to Citrix Xen Server 7.6
Outcome: same problem here

**Comment by tltow** [comment]
I can add a Cluster of 3 Proliant DL320e G8 to this list. Upgrading the master from XCP-NG 7.4 to XCP-NG 7.5 and later 7.6 leads to the same issue described here. Let me know if i can do something to help finding the source of the problem. I tried to upgrade the ISO way. Restoring 7.4 did solve the issue both times.

**Comment by olivierlambert** [comment]
@cocoon so it could be a XS issue in the first place? Can you try from a XS 7.5 to XS 7.6, this way we can "rule out" XCP-ng specific issue?

**Comment by cocoon** [comment]
@olivierlambert I was thinking the same, I could try to upgrade XCP-NG 7.5 to Xen Server 7.5 and then to Xen Server 7.6 (to have it a bit as a supported upgrade way).

Or upgrade XCP-NG 7.5 to XS 7.5 and restore from state.db, this should work as it should be the same version I expect?

**Comment by tltow** [comment]
This Cluster was also XS based before i upgraded it to XCP-NG 7.4. I have another Cluster of 2 similar Proliant Servers, which went the same way from XS to XCP-NG, but this Cluster did not show this behaviour. I was able to upgrade to 7.5 and today to 7.6?!

**Comment by olivierlambert** [comment]
@cocoon  For bug chasing purpose, the easiest diagnostic would be to install a fresh XS 7.5 and upgrade it to XS 7.6

**Comment by cocoon** [comment]
XS 7.5 fresh installation, only setting management ip (no Cluster, no OVS ...), then upgrading to XS 7.6: no problem

**Comment by olivierlambert** [comment]
I'm not sure to understand. So if you install XS 7.5 as you installed XCP-ng 7.5 (same choices, same IP/networks), then upgrade to XS 7.6, it works?

**Comment by cocoon** [comment]
No my first test was a stupid simple test fresh installed Xen Server 7.5 without any more complex settings even no SRs etc.

As I don't know how to get the configuration back exactly like it was before, because as I saif, I had a mor complex configuration from CloudStack, multiple networks, VLAns, SRs, NFS, Cluster, OVS backend ...

I will try to configure it manually as good as possible and build a cluster and try the upgrade again.

**Comment by olivierlambert** [comment]
Thank you, this could help to see if it comes from your "complex" setup in the meantime :+1: 
Do you have the same issue with a simple fresh XCP-ng 7.5 with a simple config, then upgraded to 7.6?

**Comment by cocoon** [comment]
@olivierlambert will try to do the check with simple XCP-NG config when I find the time.

While manually trying to readd one NFS datastore that was like this in the config:
```php
device_config="(('options'%.'')%.('server'%.'10.x.x.x')%.('serverpath'%.'/mnt/pool1/x/xx/store')%.('nfsversion'%.'4'))"
`

it failed and the interesting thing in the Xen Center GUI is, that if I scan the server it find the existing SR with its ID but it changes automatically from NFS v4 to NFS v3 and doesn't allow to check v4.

Don't know if this causes a problem, as in the state.db is nfsversion 4 what I think should be NFS v4?

I added now a new SR with a new ID on that NFS share and it worked.

**Comment by cocoon** [comment]
I think I found the "one" checkbox that caused this trouble:
You should not enable "Clustering" on the pool properties ...

**Comment by olivierlambert** [comment]
"Clustering"? what's that thing, and where you configure it?

**Comment by cocoon** [comment]
![pool-clustering](https://user-images.githubusercontent.com/1071741/48062939-d13b5900-e1c3-11e8-9bdb-a0b5bb2b3ab3.png)

**Comment by cocoon** [comment]
and the very best thing with clustering 2 Servers is that there is no quorum and the second server will restart if the first on reboots ^^

Not that I would have needed that option ... it was a "test"

**Comment by olivierlambert** [comment]
GFS2 is NOT supported on XCP-ng, this option shouldn't be available (it's not exposed in XO). @borzel we need to disable it or it will potentially have side effects like this.

**Comment by cocoon** [comment]
I created an own issue for it: https://github.com/xcp-ng/xenadmin/issues/115

**Comment by olivierlambert** [comment]
Great, thanks! :+1:

**Comment by Ehnix** [comment]
Thank you very much cocoon

I had the same problem by updating xcp 7.4 to xcp 7.5, xapi was not running:

```ruby
Nov 6 14:49:59 localhost xapi: [debug | localhost | 0 | starting up database engine D: 307281139104 | sql] attempting to restore database from /var/lib/xcp/state.db
Nov 6 14:49:59 localhost xapi: [error | localhost | 0 | server_init D: 93452b5a8d6a | backtrace] starting up database engine D: 307281139104 failed with exception Db_exn.DBCache_NotFound ("missing column", "Cluster", "network" )
Nov 6 14:49:59 localhost xapi: [error | localhost | 0 | server_init D: 93452b5a8d6a | backtrace] Raised Db_exn.DBCache_NotFound ("missing column", "Cluster", "network")
```

I disabled cluster option in xcp-ng Center but without Restart toolstack, so after upgrade i removed the cluster settings in the state.db file :

```xml
<table name="Cluster">..</table><table name="Cluster_host">..</table>
```

Now everything works fine.

Thanks again.

**Comment by cocoon** [comment]
@olivierlambert It turned out to be fixed for v7.6 here:
https://github.com/xcp-ng/xcp/issues/70
with "report restrict_corosync as true"

But the problem still exists for v7.5, so 7.5 still reports it would support Clustering/GFS2.

I thought it might be good to fix the v7.5 ISO (https://updates.xcp-ng.org/isos/7.5/) + yum updates
and maybe add a text to check Clustering option is disabled and update to latest 7.5 before upgrading to 7.6 to the Upgrade guide here:
https://xcp-ng.org/blog/2018/10/31/xcp-ng-7-6-upgrade/

What do you think?

**Comment by olivierlambert** [comment]
That's one of the reason why having a fork of XenCenter without doing very careful checks on side effects can be dangerous. I'll recommend to use xe or Xen Orchestra to avoid these issues :/

I'll see what we can do with @stormi about this on our side (XCP-ng side)

**Comment by stormi** [comment]
What would happen if 7.5 started reporting that it does not support clustering? Would it break for the same reason as it breaks after an upgrade to 7.6?

**Comment by cocoon** [comment]
But it also would happen if someone comes from Citrix Xen Server and had it enabled.

**Comment by cocoon** [comment]
@stormi: I can try it If you give me an updated daemon for 7.5?

**Comment by stormi** [comment]
@cocoon ok I'll build one

**Comment by stormi** [comment]
@cocoon here's an updated xcp-featured package built for 7.5: https://updates.xcp-ng.org/tmp/xcp-featured-1.1.1-1.el7.centos.x86_64.rpm

**Comment by stormi** [comment]
> @olivierlambert It turned out to be fixed for v7.6 here:
> #70
> with "report restrict_corosync as true"

I believe this is what caused the issue after the upgrade actually. It looks like once the option is enabled it really doesn't like that support for it is removed from what the license daemon says... And instead of failing gracefully with an error message about that, it just breaks.

If this is true, a quick fix might be to re-enable the feature in the deamon, but:
* some packages it depends on are not included anymore, so this could yield other errors
* this would make it offered again in XCP-ng Center
* this is just delaying the issue

We could also try to automatically change the setting upon upgrade, if there's a clean way to do it.

Or we can leave it as is, document the issue, how to solve it (I added a warning to the upgrade howto already), and quickly respond to anyone who gets stuck because of this enabled "clustering" option.

My preference currently balances between the second and the third solution, mostly depending on the number of affected users.

**Comment by olivierlambert** [comment]
Believe or not, I had a bad feeling when we removed this feature from the license daemon :laughing:

**Comment by cocoon** [comment]
XCP-NG 7.5 seems not to be very impressed about the changed daemon.
I can no longer disable clustering (no option in XCP-NG Center anymore) and it did not break xapi, but it seems to still enable clustering.

```php
[root@xen-01 ~]# rpm -ivh xcp-featured-1.1.1-1.el7.centos.x86_64.rpm --force
Preparing...                          ################################# [100%]
Updating / installing...
   1:xcp-featured-1.1.1-1.el7.centos  ################################# [100%]


[root@xen-01 ~]# xe-toolstack-restart
Executing xe-toolstack-restart
Warning: v6d.service changed on disk. Run 'systemctl daemon-reload' to reload units.
^C
[root@xen-01 ~]# systemctl daemon-reload
[root@xen-01 ~]# xe-toolstack-restart
Executing xe-toolstack-restart
done.


grep "Cluster" xensource.log
Nov  7 15:48:59 xen-01 xapi: [debug|xen-01|0 |wait management interface to come up D:305b8f285526|xapi_cluster_host] Cluster_host.enable was successful for cluster_host: OpaqueRef:62d691c5-ac39-4e64-aa9b-6e1e378f1b51

```

**Comment by stormi** [comment]
I did some tests myself and indeed the licensing daemon changes nothing. My new hypothesis is that when the database is updated the first time after upgrade, the fact that the proprietary `xapi-clusterd` or `xapi-storage-plugins` package are absent causes some elements not to be added to the database, and they are needed for the clustering function. Either they contain upgrade scripts, or the upgrade scripts take their absence into account.

**Comment by stormi** [comment]
New tests made:
* Enable clustering on 7.5
  ```
  xe pif-param-set disallow-unplug=true uuid=<pif_uuid>
  xe cluster-pool-create network-uuid=<network_uuid>
  ```
* yum update to 7.6 (which removes the proprietary packages and updates xcp-featured)
* `xe-toolstack-restart`
* `xe network-list` => **fails**

Second test:

* Enable clustering on 7.5
  ```
  xe pif-param-set disallow-unplug=true uuid=<pif_uuid>
  xe cluster-pool-create network-uuid=<network_uuid>
  ```
* yum update to 7.6 (which removes the proprietary packages and updates xcp-featured)
* downgrade xcp-featured to a version without restrictions
  ```
  wget https://updates.xcp-ng.org/7/7.5/base/x86_64/Packages/xcp-featured-1.1.0-2.el7.centos.x86_64.rpm 
  yum downgrade xcp-featured-1.1.0-2.el7.centos.x86_64.rpm
  ```
* `xe-toolstack-restart
* `xe network-list` => **works**
* reboot
* `xe network-list` => **still works**

Conclusion: what matters is what the license daemon says at the very moment when `xapi` is first started after the upgrade.

**Comment by stormi** [comment]
Interestingly, the version that **fails** has this in state.db:
```
<table name="Cluster">
    <row ref="OpaqueRef:be785f48-4cf0-47bd-a7b1-527a53c18ccc" __ctime="8532" __mtime="8532" _ref="OpaqueRef:be785f48-4cf0-47bd-a7b1-527a53c18ccc" allowed_operations="()" cluster_config="()" cluster_hosts="('OpaqueRef:13f9afbe-e8dc-4e33-812a-dc00fd093c2e')" cluster_stack="corosync" cluster_token="47fd446b-76a1-4b39-8e00-0d013ba59042" current_operations="()" network="OpaqueRef:1b6fe11f-f6ac-4e90-b6f7-16db83e4b79a" other_config="()" pool_auto_join="true" token_timeout="20000" token_timeout_coefficient="1000" uuid="0f28dc6e-606d-4c9a-a919-a3a05014280c"/>
</table>
<table name="Cluster_host">
...
</table>
```
... where I can see a 'network' column in the unique row, from what I understand... So why the `Raised Db_exn.DBCache_NotFound("missing column", "Cluster", "network")` error, it seems counter-intuitive... There must be a reason of course.

In the version that **works**, with the feature allowed by the license daemon (but no proprietary packages installed) I have this:
```
  <table name="Cluster"/>
  <table name="Cluster_host"/>
```
... empty tables... Why, I don't know. Well, that's a result that is good for us since we don't support that feature, but still I wonder. A few mysteries remain to uncover.

**Comment by stormi** [comment]
I've deleted my previous comments because they were wrong. I did not manage to make it not to break by keeping the previous version of the license daemon.

All I can say for sure is that after upgrading XCP-ng 7.5 with clustering enabled to XCP-ng 7.6, the xapi database is **not** upgraded (in state.db, `schema_minor_vsn` stays at 142). Probably because it fails when reading it from the file before it can perform the database upgrade. Removing the <Cluster> and <Cluster_hosts> tags and waiting a bit results in an upgraded database (`schema_minor_vsn` = 203).

The error is raised by https://github.com/xapi-project/xen-api/blob/v1.110.0/ocaml/database/schema.ml#L89. Previous item in the backtrace is https://github.com/xapi-project/xen-api/blob/v1.110.0/ocaml/database/db_xml.ml#L127.

Here are the changes in the model regarding the Cluster table between 7.5 and 7.6:
https://github.com/xapi-project/xen-api/compare/v1.90.5...v1.110.0#diff-c486a5fc675f36df8d81213187cb3278

**Comment by stormi** [comment]
If you get hit by this issue:
* If you actually relied on clustering through GFS2, there is no solution to keep using it in XCP-ng: the the `xapi-clusterd` and `xapi-storage-plugins` RPMs from Citrix are not opensource.
* If you did not rely on it, you probably accidentally enabled it in XCP-ng Center (which won't offer it anymore starting with XCP-ng 7.6, to avoid this). Two solutions:
** Cautiously edit /var/xapi/state.db (it's XAPI's database, it contains all your configuration!) and remove this from the file: `<table name="Cluster">[...]</table><table name="Cluster_host">[...]</table>`. Reboot. **Warning**: it's been reported to work and I tested it personnally, but I wouldn't go so far as guaranteeing that the state of the database will remain consistent. All I can say is that in my tests, it seems to automatically set clustering back to false and thus very much looks like the database you would have if you had never enabled the clustering feature.
** Second solution: reinstall your server. Safer if you can afford it.

If you did activate clustering, do not really rely on it and are about to upgrade, disable it first, restart the toolstack (`xe-toolstack-restart`) and check that the `<table name="Cluster"/>` tag in /var/xapi/state.db is now empty. Then upgrade.

I have added a warning in our upgrade howto https://github.com/xcp-ng/xcp/wiki/Upgrade-Howto to help people avoid this issue.

I'm closing this issue. Many thanks to @cocoon for reporting it and to @Ehnix for the workaround.

**Comment by borzel** [comment]
hmm... yes this sounds ok. Was just thinking around :-)

**Comment by olivierlambert** [comment]
https://github.com/xcp-ng/xcp/issues/94#issuecomment-437838544 saved my life today :laughing:  (well a customer life in fact :smile: )
