### ISSUE TITLE
Missing default templates after upgrade from XenServer 6.5 to XCP-ng 7.6

### ISSUE THREAD

**Issue by vegarnilsen** [xcp-ng/xcp#97]
I upgraded one of our XenServer 6.5 pools to XCP-ng 7.6.0 this weekend, and after that most of the default templates I would expect to find where missing. (E.g. CentOS 7, Ubuntu 16.04, and so on.)

When I tried to run create-guest-templates I got this error:

```bash
[root@oslo1pool1h1 ~]# create-guest-templates
Load /usr/share/xapi/vm-templates/windows-server-2012-64bit.json
[…]
Load /usr/share/xapi/vm-templates/ubuntu-12.04-64bit.json
Load /usr/share/xapi/vm-templates/base-windows-8.json
Traceback (most recent call last):
File "/usr/bin/create-guest-templates", line 16, in <module>
loader.remove_old_templates()
File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 90, in remove_old_templates
templates = self._session.xenapi.VM.get_all_records_where(query)
File "/usr/lib/python2.7/site-packages/XenAPI.py", line 264, in __call__
return self.__send(self.__name, args)
File "/usr/lib/python2.7/site-packages/XenAPI.py", line 160, in xenapi_request
result = _parse_result(getattr(self, methodname)(*full_params))
File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
return self.__send(self.__name, args)
File "/usr/lib64/python2.7/xmlrpclib.py", line 1587, in __request
verbose=self.__verbose
File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
return self.single_request(host, handler, request_body, verbose)
File "/usr/lib64/python2.7/xmlrpclib.py", line 1306, in single_request
return self.parse_response(response)
File "/usr/lib64/python2.7/xmlrpclib.py", line 1476, in parse_response
p.feed(data)
File "/usr/lib64/python2.7/xmlrpclib.py", line 558, in feed
self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 12254
```

I then tried to remove all the old standard templates, leaving only two templates I've cloned and modified for our setup, and re-ran create-guest-templates, but I got the same error message.

If I run the code in create-guest-templates manually, skipping the `loader.remove_old_templates()` step I get this error message:

```python
>>> loader.insert_templates()
Insert 11fd3dc9-96cc-49af-b091-a2ca7e94c589
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 181, in insert_templates
    self._insert_template(i)
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 168, in _insert_template
    template_ref = self._session.xenapi.VM.get_by_uuid(template.uuid)
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 264, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 160, in xenapi_request
    result = _parse_result(getattr(self, methodname)(*full_params))
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 238, in _parse_result
    raise Failure(result['ErrorDescription'])
XenAPI.Failure: ['UUID_INVALID', 'VM', '11fd3dc9-96cc-49af-b091-a2ca7e94c589']
```

**Comment by olivierlambert** [comment]
Did you changed the partition layout from 6.5?

**Comment by vegarnilsen** [comment]
> Did you changed the partition layout from 6.5?

No, we have VMs on local storage that wasn't easily relocated on this pool, so I kept the partition layout as it was from XenServer.

**Comment by olivierlambert** [comment]
So I have the feeling something went wrong on this side, eg not enough space and then some templates were lost due to that.

Try to dig on this side.

**Comment by vegarnilsen** [comment]
I cleaned out old log files from /var/log, and now I have ~800MB free space, still getting the same XML error from expat:

```
[root@oslo1pool1h1 ~]# df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       3.4G  2.5G  816M  76% /
[root@oslo1pool1h1 ~]# create-guest-templates 
Load /usr/share/xapi/vm-templates/windows-server-2012-64bit.json
Load /usr/share/xapi/vm-templates/xenapp-windows-server-2008-r2-64bit.json
Load /usr/share/xapi/vm-templates/base-windows-10.json
Load /usr/share/xapi/vm-templates/debian-9.json
Load /usr/share/xapi/vm-templates/kylin-6-64bit.json
Load /usr/share/xapi/vm-templates/xenapp-windows-server-2008-32bit.json
[…]
Load /usr/share/xapi/vm-templates/base-windows-8.json
Traceback (most recent call last):
  File "/usr/bin/create-guest-templates", line 16, in <module>
    loader.remove_old_templates()
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 90, in remove_old_templates
    templates = self._session.xenapi.VM.get_all_records_where(query)
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 264, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 160, in xenapi_request
    result = _parse_result(getattr(self, methodname)(*full_params))
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1306, in single_request
    return self.parse_response(response)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1476, in parse_response
    p.feed(data)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 12254
```

**Comment by olivierlambert** [comment]
Yep, because it's maybe already "corrupted" :/

**Comment by vegarnilsen** [comment]
> Yep, because it's maybe already "corrupted" :/

Right. Is it enough to have the templates on the pool master in order to create new VMs? I have one host in this pool without local storage that can be reinstalled with the new partition scheme and then promoted.

**Comment by olivierlambert** [comment]
I would say yes, because the master get the DB that's then synchronized on the slaves. That's the theory, but your idea is interesting.

**Comment by vegarnilsen** [comment]
> I would say yes, because the master get the DB that's then synchronized on the slaves. That's the theory, but your idea is interesting.

Ok, I will try that and see if it gets us back to a working state. Thanks.

**Comment by olivierlambert** [comment]
Frankly I don't know, I never encountered this situation before. You must use `create-guest-templates`? Otherwise you can't create VMs on the master?

**Comment by vegarnilsen** [comment]
I would like to have at least one template with our default setup so that we don't have to fill out all the fields in the new VM interface manually every time we create a new VM. It would be more than good enough if I only had the "Other install media" template active, since we boot a custom netboot ISO that installs pre-reqs for Puppet in Ubuntu, but it seems that I can't add any templates here:

[root@oslo1pool1h3 vm-templates]# ls
other-install-media.json
[root@oslo1pool1h3 vm-templates]# create-guest-templates 
Load /usr/share/xapi/vm-templates/other-install-media.json
Insert 552bce37-51b2-445d-84f2-5f33fa112d7e
Traceback (most recent call last):
  File "/usr/bin/create-guest-templates", line 17, in <module>
    loader.insert_templates()
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 181, in insert_templates
    self._insert_template(i)
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 168, in _insert_template
    template_ref = self._session.xenapi.VM.get_by_uuid(template.uuid)
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 264, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 160, in xenapi_request
    result = _parse_result(getattr(self, methodname)(*full_params))
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 238, in _parse_result
    raise Failure(result['ErrorDescription'])
XenAPI.Failure: ['UUID_INVALID', 'VM', '552bce37-51b2-445d-84f2-5f33fa112d7e']
[root@oslo1pool1h3 vm-templates]#

**Comment by olivierlambert** [comment]
I tested the `create-guest-templates` template on my side, and it works perfectly. Can you reinstall your hosts one by one (and migrate VMs to the clean hosts?)

**Comment by vegarnilsen** [comment]
> I tested the `create-guest-templates` template on my side, and it works perfectly. Can you reinstall your hosts one by one (and migrate VMs to the clean hosts?)

Sure, but it'll take a few days to finish that and know if it helps or not.

**Comment by vegarnilsen** [comment]
Reinstalled all hosts, still the same issue:

```
[…]
Load /usr/share/xapi/vm-templates/sles-11-sp4-64bit.json
Load /usr/share/xapi/vm-templates/ubuntu-12.04-64bit.json
Load /usr/share/xapi/vm-templates/base-windows-8.json
Insert 11fd3dc9-96cc-49af-b091-a2ca7e94c589
Traceback (most recent call last):
  File "/usr/bin/create-guest-templates", line 17, in <module>
    loader.insert_templates()
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 181, in insert_templates
    self._insert_template(i)
  File "/usr/lib/python2.7/site-packages/guesttemplates/loader.py", line 168, in _insert_template
    template_ref = self._session.xenapi.VM.get_by_uuid(template.uuid)
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 264, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 160, in xenapi_request
    result = _parse_result(getattr(self, methodname)(*full_params))
  File "/usr/lib/python2.7/site-packages/XenAPI.py", line 238, in _parse_result
    raise Failure(result['ErrorDescription'])
XenAPI.Failure: ['UUID_INVALID', 'VM', '11fd3dc9-96cc-49af-b091-a2ca7e94c589']
[root@oslo1pool1h3 ~]# 
```

Kind of looks like templates on this pool are perma-broken.

**Comment by vegarnilsen** [comment]
And without any templates, I can't create new VMs from either Xen Orchestra or XCP-ng Center, so that's a problem.

**Comment by olivierlambert** [comment]
Huh, very strange. When you reinstalled, which method did you used?

**Comment by vegarnilsen** [comment]
Installed from the 7.6.0 ISO, and did a clean install. Then I added the host to the existing pool and configured network and shared storage.

**Comment by vegarnilsen** [comment]
Can I migrate the VMs between pools without moving storage if all the hosts can access the same NFS shares? We have 160 VMs running on this pool.

**Comment by olivierlambert** [comment]
Hmmm… you shouldn't do that, because there is no "lock" on VM disks outside a pool. I suppose you'd like to avoid any shutdown time?

**Comment by vegarnilsen** [comment]
I would mainly like to avoid a migration that will take at least a week to complete, just to get back to being able to create new VMs.

**Comment by olivierlambert** [comment]
I understand. I'm sorry, we never met this kind of issue before :disappointed: 

Feel free to create a topic on the XCP-ng forum to see if community can help with that :smiley:  If you need dedicated pro support with XCP-ng core team to look at it, let us know.

**Comment by vegarnilsen** [comment]
I've compared two /var/xapi/state.db files now, one from this pool and one from another pool that I upgraded to XCP-ng 7.5 last week (just before 7.6 was released), and the template rows are missing entirely from the database for this pool.

I basically only need the "Other install media" template, since we have custom boot ISOs with preseed config anyway. 

So, if I reboot the pool master (without maintenance mode, so that the pool doesn't choose another master), and boot it up with a live-CD so that I get a guaranteed single-user access to the local filesystem, would it be dangerous to cut and paste the "Other install media" template row from the database that works into the one that doesn't?

**Comment by olivierlambert** [comment]
Editing XAPI DB is doable if you did a backup before. At the point where you are, it seems a decent option. You can just shutdown XAPI on the master, copy it (as a backup), modify it, then start again XAPI process

**Comment by vegarnilsen** [comment]
I'll test it out on a couple of lab servers first, just to see how it behaves. Definitely a lot easier if I can just shut down XAPI instead of the entire server. Thanks.

**Comment by olivierlambert** [comment]
XAPI DB won't be accessed if the process is down, no worries (did it for other things)

**Comment by vegarnilsen** [comment]
Ok, editing state.db and manually inserting the "Other install media" template seems to have worked.

```
[root@oslo1pool1h3 ~]# xe template-list 
uuid ( RO)                : 552bce37-51b2-445d-84f2-5f33fa112d7e
          name-label ( RW): Other install media
    name-description ( RW): Template which allows VM installation from install media
```

Both Xen Orchestra and XCP-ng Center will now let me create new VMs on this pool again.
