### ISSUE TITLE
Upgrade from 7.4 to 7.6 not working

### ISSUE THREAD

**Issue by scpcom** [xcp-ng/xcp#99]
I followed this guide here:
https://xcp-ng.org/blog/2018/10/31/xcp-ng-7-6-upgrade/

At this step:
[root@xen-host ~] # yum install xcp-ng-deps

I get this:
Transaction check error:
  file /usr/lib/python2.7/site-packages/xcp/branding.py from install of xcp-ng-release-7.6.0-3.x86_64 conflicts with file from package xcp-python-libs-2.0.3-2.noarch
  file /usr/lib/python2.7/site-packages/xcp/branding.pyc from install of xcp-ng-release-7.6.0-3.x86_64 conflicts with file from package xcp-python-libs-2.0.3-2.noarch
  file /usr/lib/python2.7/site-packages/xcp/branding.pyo from install of xcp-ng-release-7.6.0-3.x86_64 conflicts with file from package xcp-python-libs-2.0.3-2.noarch

BTW: Please re-add the "Rolling Pool Upgrade" Button. It is much easier to handle the "missing patch" instead of messing up with things like above. Personally I think it should be possible to upgrade with the static ISO content without booting from the ISO. Not every server around has iLO/iDRAC :-)

**Comment by olivierlambert** [comment]
1. @stormi will check for you first issue
2. RPU: it's XenCenter specific, note that you can upgrade without remote console anyway, please check "Alternate method: remote upgrade" in here: https://xcp-ng.org/blog/2018/06/11/migrate-from-xenserver-to-xcp-ng/

**Comment by stormi** [comment]
Thanks for reporting the issue. It turns out that this manual step is not required anymore when upgrading to 7.6, because something else automatically makes xcp-ng-deps pulled when updating the rest of the system. I updated the Upgrade Howto.

In your situation, simply continue with steps 3 to 5 at https://github.com/xcp-ng/xcp/wiki/Upgrade-Howto#3-upgrade-the-systems-packages

That is:
```
yum update
yum reinstall xcp-featured
reboot
```

**Comment by borzel** [comment]
@scpcom the RPU is a feature that XCP-ng doesn't have any more. It's the old style update from XenServer with the patch files.

If you have the ressources to integrade the yum-style update into XCP-ng Center, please go ahead: https://github.com/xcp-ng/xenadmin/issues/55
We would be proud to include the changes!

**Comment by stormi** [comment]
Closing since the upgrade instructions have been updated
